### ISSUE TITLE
[compile] DDPOptimizer + activation checkpointing not supported

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#104674]
Activation checkpointing is supported via higher order operators. However, DDP optimizer backend in Dynamo does not work with higher order operators yet. The workaround is to disable DDP optimizer using `torch._dynamo.config.optimize_ddp = False`. However, the tradeoff is bad performance because there will be just one bucket for the entire Dynamo graph.

No plan to support it yet. We will revisit if this is a common ask. 

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @soulitzer @chauhang @penguinwu @ezyang @gchanan @zou3519 @kadeng @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @XilunWu @tianyu-l @yf225 @msaroufim @bdhirsh @kiukchung @lucasllc

**Comment by pritamdamania87** [comment]
> No plan to support it yet. We will revisit if this is a common ask.

Would be great if we could support this. DDP + activation checkpointing are used together often.

**Comment by wconstab** [comment]
cc @fegin who is working on supporting 'compiled DDP'- we don't have a specific ETA yet but @fegin can share updates and link a gh issue here to track his work.  once we do that, we should also ensure activation checkpointing is working.  any reason it wouldn't work out of the box once we compile w/o graph-breaks @anijain2305 ?

**Comment by fordflip** [comment]
+1 for support here

**Comment by ezyang** [comment]
This is also affecting this Meta internal workflow: https://fb.workplace.com/groups/1075192433118967/posts/1361398451165029/

**Comment by jwohlwend** [comment]
+1 here too, would be extremely useful

**Comment by MattMcPartlon** [comment]
+1

**Comment by wconstab** [comment]
I believe @anijain2305 has declared DDPOptimizer + Activation Checkpointing as D.O.A. (or "will not support") due to the technical complexity of supporting higher-order-operators (which are the basis for our A.C. support) within graph-breaky regions.

However, we have 'compiled DDP' coming soon.  IIRC its already (mostly?) working in the landed code, so it'd be worth checking the design issue for status updates (https://github.com/pytorch/pytorch/issues/109774) CC @fegin @yf225 @anijain2305

**Comment by alexdremov** [comment]
Catch this error when using flex attention

**Comment by yf225** [comment]
We need to check whether this is fixed with @Chillee's work on https://github.com/pytorch/pytorch/pull/138787.

**Comment by Chillee** [comment]
@yf225 This should be fixed AFAIK.

**Comment by maxall41** [comment]
bump

**Comment by Mr-Blue-Sky-Candy** [comment]
I still get this error on pytorch 2.6
```
[rank1]: torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
[rank1]: NotImplementedError: DDPOptimizer backend: Found a higher order op in the graph. This is not supported. Please turn off DDP optimizer using torch._dynamo.config.optimize_ddp=False. Note that this can cause performance degradation because there will be one bucket for the entire Dynamo graph. Please refer to this issue - https://github.com/pytorch/pytorch/issues/104674.
```
I guess it has not been resolved. I am only compiling step function of the optimiser BTW as it is mentioned [here](https://pytorch.org/tutorials/recipes/compiling_optimizer.html?highlight=compile): `optimizer.step = torch.compile(optimizer.step, fullgraph=False)`

**Comment by Mr-Blue-Sky-Candy** [comment]
> [@yf225](https://github.com/yf225) This should be fixed AFAIK.

I still get this error on pytorch 2.6
```
[rank1]: torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
[rank1]: NotImplementedError: DDPOptimizer backend: Found a higher order op in the graph. This is not supported. Please turn off DDP optimizer using torch._dynamo.config.optimize_ddp=False. Note that this can cause performance degradation because there will be one bucket for the entire Dynamo graph. Please refer to this issue - https://github.com/pytorch/pytorch/issues/104674.
```
I guess it has not been resolved. I am only compiling step function of the optimiser BTW as it is mentioned [here](https://pytorch.org/tutorials/recipes/compiling_optimizer.html?highlight=compile): `optimizer.step = torch.compile(optimizer.step, fullgraph=False)`

**Comment by jialusui1102** [comment]
I get the same error again. Is there an ETA for fix?

**Comment by dandarm** [comment]
+1 here too.  Pytorch version 2.2.0a0

**Comment by bdhirsh** [comment]
This should have been fixed by https://github.com/pytorch/pytorch/pull/138787.

I also tried running a quick test that seems to work for me:
```
        class Model(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.lin1 = torch.nn.Linear(1024, 1024, device='cuda')


            def forward(self, x):
                def inner(elem):
                    for _ in range(32):
                        elem = self.lin1(elem).sin()
                    return elem
                for _ in range(32):
                    x = torch.utils.checkpoint.checkpoint(inner, x)
                return x

        model = Model()
        inp = torch.randn(8, 1024, device='cuda')
        model = DDP(model, device_ids=self.device_ids)
        model = torch.compile(model)
        model(inp)
        torch.cuda.synchronize()
```

I'm going to tentatively close this, but if anyone is still encountering issues we can re-open. @jialusui1102 are you able to upgrade to the most recent pytorch (either 2.7 or a nightly) and let me know if you're still running into problems?
