### ISSUE TITLE
Support AMD Ryzen Unified Memory Architecture (UMA)

### ISSUE THREAD

**Issue by winstonma** [pytorch/pytorch#107605]
### 🚀 The feature, motivation and pitch

**Background:**
I am using Asus Zenbook S13 OLED, which runs AMD Ryzen 6800U APU. The APU comes with 680M Graphics Card. The memory of the graphic card use the shared memory from the system and its default is 512MB (Please reference the screenshot below).
![alt text](https://p.xfastest.com/~sinchen/AMD-Zenbook-S-13-OLED/AMD-Zenbook-S-13-OLED-7.jpg)

In Windows environment the memory size would dynamically change, due to the amount of GPU memory required. But in Linux environment it shows 512MB memory (which is the result of setting Auto in BIOS) and thus when I use Stable Diffusion Pytorch would face the OOM situation. As the BIOS setting of the Notebook doesn't allow users from modifying the amount of dedicated memory so would it be possible that PyTorch could support UMA? 

Here is the quote from [AMD Ryzen UMA](https://www.amd.com/en/support/kb/faq/pa-280#faq-Recommendations)

> The UMA Frame Buffer Size when set to Auto (default setting) allows the system to manage the amount of shared memory for graphics. In this configuration, the size of the UMA frame buffer should scale depending on the amount of available system memory, enabling the system to perform in an optimal state. Therefore, it is recommended to leave the setting on Auto, which is ideal for most types of video processing workloads.

### Additional context

Another developer created [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) that uses `CUDAPluggableAllocator` to take advantage of the shared memory on PyTorch. However when I try the code snippet with Stable Diffusion I got the following error:

```
RuntimeError: CUDAPluggableAllocator does not yet support getDeviceStats. If you need it, please file an issue describing your use case.
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by winstonma** [comment]
@yiakwy-xpu-ml-framework-team but it seems that the sample in [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) could get a piece of shared memory from the system and used by PyTorch. Maybe that is just a simple demo and may not have full functionalities but it seems there is a way for PyTorch to grab a piece of memory from the system.

Compared to booting the system into BIOS, define a dedicated piece of memory for GPU, and then reboot the system. I think allocating a fixed piece of memory at the program runtime is already considered as an improvment.

**Comment by dkuku** [comment]
Llama cpp added an option to use the shared memory on amd apus and I can confirm that it works. This is the pull request:
https://github.com/ggerganov/llama.cpp/pull/4449

**Comment by winstonma** [comment]
@dkuku Thanks. From llama.cpp we know that it is do-able (on Windows we can access video memory via UMA through DirectX, that's my guess). Also [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) uses the same way to get PyTorch using the UMA.

However for using Stable Diffusion, the [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) method would not work. And it support PyTorch on using the video memory. However when Stable Diffusion uses some other PyTorch API it would fail (like the following example)

```
Warning: caught exception 'CUDAPluggableAllocator does not yet support getDeviceStats. If you need it, please file an issue describing your use case.', memory monitor disabled
```

It shows that in order to get higher level application working, the [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) is not sufficient. Getting official support from PyTorch is needed (just like llama.cpp).

**Comment by winstonma** [comment]
@jithunnair-amd Could you help? Thanks 🙏🏻

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@winstonma  as for pytorch caching algorithm, I have tried to added a external cached allocator successfully (with exactly pytorch block algorithm, -- I am familiar with Pytorch block, extended segments allocation strategy) and it works well in pytorch sample tests.

The only issue is how to dump it into pytorch newly supported memory snapshot. That needs a python frame tracer. Hence it is better to have native support from Pytorch code base.

Note the external allocator should support export memory snapshot and livenessinfo like this:

<img width="1775" alt="截屏2023-12-13 18 32 46" src="https://github.com/pytorch/pytorch/assets/89890040/c3b4d31b-e7e7-4da3-a20d-c29c6bca5eb2">

So I guess your demo doesn't work in practice.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@dkuku How did llama.cpp handles overhead of memory allocation ? Does it cached memory allocated ?

**Comment by winstonma** [comment]
> So I guess your **hipHostMalloc** demo doesn't work in practice.

I am not sure. But I think both llama.cpp and torch-apu-helper both referenced [HIP Programming Manual](https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/programming_manual.html). I think memory-allocation-wise torch-apu-helper works. But as you mentioned modifications are needed in order to get full support from PyTorch.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> > So I guess your **hipHostMalloc** demo doesn't work in practice.
> 
> I am not sure. But I think both llama.cpp and torch-apu-helper both referenced [HIP Programming Manual](https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/programming_manual.html). I think memory-allocation-wise torch-apu-helper works. But as you mentioned modifications are needed in order to get full support from PyTorch.
> 
> But I didn't know it need to modify 3k lines of codes. I just think the modification mainly perpose on "ask the ROCm driver to assign the memory". After the memory is allocated everything should work.

This is not how pytorch works:

>  I just think the modification mainly perpose on "ask the ROCm driver to assign the memory". After the memory is allocated everything should work.

The pytorch first request  an available block (which containers valid GPU address + offset point to remaining available block), then it split the block such that a memory description are exactly what you want. This will create my small memory segments, hence each time you request an allocation, pytorch will increase age of the memory and release the "oldest" one if necessary.

This algorithm can be easily supported with around 2k codes dependent on whether you want to handle multi streams : this is tricky because a memory can be used under one stream for computing and another stream for stream copy and one has to manually notifiy pytorch to increase event - streams -block references.

Native support from Pytorch must consider this for "CUDAPlugableAllocator".

Another issue one must need to support tracing, other wise pytorch will not generate memory snapshot. This needs another 1k codes : PyObject frame tracking, c++ codes tracking, etc.

**Comment by winstonma** [comment]
@yiakwy-xpu-ml-framework-team Thanks for explaining. Seems I oversimplify the whole process and think AMD could take advantage of the existing PyTorch ROCm framework and include support for UMA with some modification. Seems there is a long way to go.

**Comment by qkiel** [comment]
> @dkuku Thanks. From llama.cpp we know that it is do-able (on Windows we can access video memory via UMA through DirectX, that's my guess). Also [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) uses the same way to get PyTorch using the UMA.
> 
> However for using Stable Diffusion, the [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) method would not work. And it support PyTorch on using the video memory. However when Stable Diffusion uses some other PyTorch API it would fail (like the following example)
> 
> ```
> Warning: caught exception 'CUDAPluggableAllocator does not yet support getDeviceStats. If you need it, please file an issue describing your use case.', memory monitor disabled
> ```
> 
> It shows that in order to get higher level application working, the [torch-apu-helper](https://github.com/pomoke/torch-apu-helper) is not sufficient. Getting official support from PyTorch is needed (just like llama.cpp).
> 
> > With this I can offload a 25GB model into gpu memory (it's still copying the model) and run it using the gpu. Since that time I have the gpu memory set in bios to 512MB
> 
> Are you using AMD APU or AMD Dedicated GPU? How much memory does your system originally have? I think I am a bit confused.

If you use [force-host-alloction-APU](https://github.com/segurac/force-host-alloction-APU) instead of [torch-apu-helper](https://github.com/pomoke/torch-apu-helper), you can run Stable Diffusion on an APU.

I have a 5600G APU and I'm using [Fooocus](https://github.com/lllyasviel/Fooocus) with `force-host-alloction-APU` and only 512MiB allocated to VRAM. For ROCm version 5.7.3 I need to set up environment variable `HSA_OVERRIDE_GFX_VERSION=9.0.0` and for ROCm 6.0+ I need one more `HSA_ENABLE_SDMA=0`. Then I start Foocus like that:
```
LD_PRELOAD=~/force-host-alloction-APU/./libforcegttalloc.so python3 ~/Fooocus/entry_with_update.py --always-high-vram
```
Notice a `./` before `libforcegttalloc.so`. Model is fully loaded into memory and GPU generates an image.

Links to ROCm and PyTorch versions I used:
[https://www.amd.com/en/support/linux-drivers|https://www.amd.com/en/support/linux-drivers](url)
[https://pytorch.org/get-started/locally/|https://pytorch.org/get-started/locally/](url)

ROCm 5.7 with PyTorch for 5.7

```
https://repo.radeon.com/amdgpu-install/5.7.3/ubuntu/jammy/amdgpu-install_5.7.50703-1_all.deb
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.7
```

ROCm 6.0 with PyTorch for 6.0

```
https://repo.radeon.com/amdgpu-install/23.40.2/ubuntu/jammy/amdgpu-install_6.0.60002-1_all.deb
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.0
```

**Comment by gonwan** [comment]
I was able to run sd-webui around January on my AMD APU(7840HS, RDNA3, 4G VRAM). I used  [UMAF](https://github.com/DavidS95/Smokeless_UMAF) to adjust VRAM from 4G to 8G, and set `HSA_OVERRIDE_GFX_VERSION=11.0.0`. ROCm 6.0 with PyTorch-ROCm 5.6 works for me, but ROCm 6.0 with PyTorch-ROCm 5.7/6.0 do not.

Just leave some words, as an alternative approach.

**Comment by winstonma** [comment]
@yiakwy-xpu-ml-framework-team I tested @qkiel's [method](https://github.com/pytorch/pytorch/issues/107605#issuecomment-2013766731) and it works on my laptop.

**Comment by qkiel** [comment]
@winstonma great it worked :]

@gonwan have you tried adding one more environment variable `HSA_ENABLE_SDMA=0` for the latest PyTorch-ROCm6.0? That did the trick for me.
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.0
```

**Comment by gonwan** [comment]
@qkiel 
Just tried to set `HSA_ENABLE_SDMA=0` with both versions, no luck.
With rocm6.0+pytorch-rocm5.7, hang when generating images, no other logs.
With rocm6.0+pytorch-romc6.0, invalid ISA error reported.

Any idea?

**Comment by dkuku** [comment]
I have also a problem with my ryzen: when starting a model (I mostly saw it
with stable diffusion) sometimes my screen flashes black and it even kicks
me out of x session. Have you seen this before ?
-- 
Sincerely
Daniel Kukula

**Comment by qkiel** [comment]
@gonwan 
If `HSA_OVERRIDE_GFX_VERSION=11.0.0` + `HSA_ENABLE_SDMA=0`, maybe try lower version `HSA_OVERRIDE_GFX_VERSION=10.3.0` + `HSA_ENABLE_SDMA=0`.

You can also try setting `UMA_SPECIFIED` to 8 or more GiB of VRAM in BIOS or use [force-host-alloction-APU](https://github.com/segurac/force-host-alloction-APU) method when launching Stable Diffusion, which requires `UMA_AUTO` set in BIOS. I have a 5600G APU with `UMA_AUTO`, and I'm launching [Fooocus](https://github.com/lllyasviel/Fooocus) with `force-host-alloction-APU` like that:
```
LD_PRELOAD=~/force-host-alloction-APU/./libforcegttalloc.so python3 ~/Fooocus/entry_with_update.py --always-high-vram
```
Notice a `./` before `libforcegttalloc.so`.

@dkuku I've seen something like that when I launched Fooocus on CPU instead of GPU.

**Comment by langyuxf** [comment]
With this patch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.10-rc4&id=eb853413d02c8d9b27942429b261a9eef228f005, the default VRAM size for ROCm is 1/2 system memory now.

You can also change the default VRAM size via ttm_pages_limit. (sudo modprobe ttm pages_limit=xxx)

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@dkuku @qkiel in cuda platform using HostAllocator means memory is locked and not pagable which means the buffer size is usually small. So HostAllocator is rarely used in models with large inputs.

In Pytorch, The pluggable memory allocator means no support of caching algorithm (blocks, segments, and memory aging) and recently supported profiling toolkits (3 months ago).

This may result in degradation of performance. 

Note if Unified Memory used, that means no need copy between GPU and CPU:

```
a = torch.rand(..., device='cpu')

# memory aligns, not copy observed in intel x86 pcm(https://github.com/intel/pcm)
b = a.to('amdgpu')

```

**Comment by AGenchev** [comment]
I observe 50% degradation of performance when GTT allocator hack is applied.  I installed the https://pypi.org/project/pytorch-rocm-gtt/ . The hardware is APU 5600G's GPU (gfx 900).

**Comment by langyuxf** [comment]
@AGenchev You can try to use hipMallocHost(&ptr,size) instead of hipHostMalloc(&ptr,size,0) in
https://github.com/pomoke/torch-apu-helper/blob/main/gttalloc.c#L10C5-L10C32.

Since hipHostMalloc allocation is coherent(i.e., uncached on APU) by default, please refer to
https://rocm.docs.amd.com/projects/HIP/en/docs-5.7.0/user_guide/programming_manual.html#coherency-controls.

**Comment by AGenchev** [comment]
Yes, it has effect: now the performance degradation decreased to roughly ~30 %:
time = 6.47 (without GTT), 9.223 with  hipMallocHost(), 11.93 with hipHostMalloc(&ptr,size,0);

**Comment by langyuxf** [comment]
@AGenchev Can you build the kernel with this patch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.10-rc4&id=eb853413d02c8d9b27942429b261a9eef228f005?
Then you don't need the GTT allocator hack and it should not have ~30 % performance degradation from my observation.

**Comment by AGenchev** [comment]
time = 7.20 (probably due to differences in kernel version - I compiled the v6.10-rc6 kernel).
And yes, now it doesn't need to replace the memory allocator, works with UMA memory size=auto. 
Tested with ResNet152 to rise the memory needs above the 'auto' reserved GPU memory.

**Comment by winstonma** [comment]
I close this ticket because it was fixed in Linux Kernel 6.9.9 and Linux 6.10 onwards

**Comment by DarkCenobyte** [comment]
> With this patch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.10-rc4&id=eb853413d02c8d9b27942429b261a9eef228f005, the default VRAM size for ROCm is 1/2 system memory now.
> 
> You can also change the default VRAM size via ttm_pages_limit. (sudo modprobe ttm pages_limit=xxx)

I don't know if my machine is a very specific case (an APU Ryzen 6900HX), but with Linux Kernel 6.11, I was only able to exceed the 1/2 RAM limit, by using UMA_AUTO bios setting + adding in grub these parameters:

amd_iommu=on
amdgpu.gttsize=xxx
ttm.pages_limit=yyy
ttm.page_pool_size=yyy

amdgpu.gttsize only display the expected value as available the GTT memory in dmesg
ttm.pages_limit and page_pool_size are ignored... EXCEPT when I also set amd_iommu=on (even if dmesg AMD IOMMU without...)

I don't know why the amd_iommu parameter change this behavior... but it work only with it for me...

**Comment by hephaex** [comment]
## This issue is not fully resolved — HIP runtime still reports VRAM-only on kernel 6.12+

The kernel 6.9.9 fix (commit `8d656c`) changed the default GTT size to 50% of system RAM, which is correct. However, the **HIP runtime** still reports only the VRAM aperture (~15.49 GiB) via all memory APIs, even on kernel 6.12.74:

```
hipMemGetInfo:          total = 15.49 GiB  (should be ~88 GiB)
hipDeviceTotalMem:      15.49 GiB
hipGetDeviceProperties: totalGlobalMem = 15.49 GiB
```

While the kernel correctly shows:
```
/sys/class/drm/card1/device/mem_info_gtt_total: 103079215104  (96 GiB)
/sys/class/drm/card1/device/mem_info_vram_total: 16636528640  (15.49 GiB)
```

### Verified workaround

I developed an **LD_PRELOAD C shim** that intercepts 5 HIP APIs (hipMemGetInfo, hipDeviceTotalMem, hipGetDeviceProperties, hipGetDevicePropertiesR0600, hipGetDevicePropertiesR0000) and returns sysfs GTT values instead.

Combined with `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`:

| Test | Without shim | With shim + expandable_segments |
|------|-------------|--------------------------------|
| `torch.cuda.get_device_properties(0).total_memory` | 15.49 GiB | **88.0 GiB** |
| `torch.zeros(20 GiB, device="cuda:0")` | OOM | **SUCCESS** |
| `torch.zeros(50 GiB, device="cuda:0")` | OOM | **SUCCESS** |
| vLLM Qwen3.6-27B (51.75 GiB bf16) | OOM | **4.4 tok/s serving** |

### Key finding: expandable_segments is required

Even with the shim reporting 88 GiB total, `torch.zeros(20 GiB)` still fails without `expandable_segments:True`. PyTorch's caching allocator cannot allocate contiguous segments through GTT without this option.

**Suggestion**: PyTorch ROCm build could auto-detect APU (VRAM < GTT) and enable `expandable_segments` by default, similar to how CUDA builds handle unified memory on Jetson/Grace Hopper.

### Environment
- AMD Ryzen AI MAX+ 395 (Strix Halo, gfx1151), 128GB LPDDR5, 96GB UMA
- Debian 13, kernel 6.12.74, ROCm 7.13.0
- Docker: kyuz0/vllm-therock-gfx1151:stable

### Related
- HIP runtime bug filed: ROCm/hip#3892
- vLLM APU fix PR: vllm-project/vllm#40963
- Full shim source: https://github.com/ROCm/ROCm/issues/5444#issuecomment-4324346251
