### ISSUE TITLE
`pytest test/dynamo -v ` fails locally

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#110641]
This fails locally for me (and for @voznesenskym, so it's probably not just us). We're not sure why CI is green. The number of failures is deterministic, I get between 10-150 each time I run this.

Possibly related:
- https://github.com/pytorch/pytorch/issues/103213

Example failures:
![image](https://github.com/pytorch/pytorch/assets/5652049/c76d8566-87e8-4e3c-a6ea-5d57d4ec1bd6)

cc @ezyang @gchanan @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @wconstab

**Comment by eellison** [comment]
This has been causing failures for https://github.com/pytorch/pytorch/pull/108170

**Comment by ezyang** [comment]
This looks like someone is toggling default dtype and not seitching it back

**Comment by Fidget-Spinner** [comment]
What commit are you on? Roughly one-two weeks ago I accidentally set the default dtype without setting it back (sorry about that). 3 days ago, it was fixed in https://github.com/pytorch/pytorch/pull/110412#event-10542479970.

**Comment by eellison** [comment]
@voznesenskym or @Fidget-Spinner mind confirming if this is still an issue?

**Comment by zou3519** [comment]
<img width="1126" alt="image" src="https://github.com/pytorch/pytorch/assets/5652049/14ecd8ca-5071-426d-98ed-5976b6b3aaa4">
pytest test/dynamo -v still fails (see image). With fewer failures now.

**Comment by voznesenskym** [comment]
known, oft discussed, long running

**Comment by penguinwu** [comment]
@zou3519 Is this issue still happening?

**Comment by zou3519** [comment]
It passes for me now.
