### ISSUE TITLE
torch2.1.0 compile+amp+ddp cause NotImplementedError

### ISSUE THREAD

**Issue by sasa9451** [pytorch/pytorch#111794]
### 🐛 Describe the bug

When I try to compile the ddp + amp model using torch.compile, I get the following error：

```
NotImplementedError: argument of type: <class 'torch.amp.autocast_mode.autocast'>
```

Can you help me with this error?

### Error logs

```
eager train time 0: 2.062772216796875 loss: 12.34566593170166
eager train time 29: 0.12792012786865234 loss: 12.378190040588379
~~~~~~~~~~

[rank0]:[2023-10-20 15:17:41,173] [1/0] torch._dynamo.variables.torch: [WARNING] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
Traceback (most recent call last):
  File "elastic_ddp.py", line 347, in <module>
    demo_basic()
  File "elastic_ddp.py", line 330, in demo_basic
    loss, compile_time = timed(
  File "elastic_ddp.py", line 288, in timed
    result = fn()
  File "elastic_ddp.py", line 331, in <lambda>
    lambda: train_opt(ddp_model, inp, opt, grad_scaler))
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "elastic_ddp.py", line 267, in train
    opt.zero_grad(True)
  File "elastic_ddp.py", line 269, in <resume in train>
    predict = model(data[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 487, in catch_errors
    return hijacked_callback(frame, cache_entry, hooks, frame_state)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2162, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 833, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 957, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1024, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1009, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/backends/distributed.py", line 436, in compile_fn
    submod_compiler.run(*example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/backends/distributed.py", line 417, in run_node
    compiled_submod_real = self.compile_submod(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/backends/distributed.py", line 361, in compile_submod
    self.compiler(input_mod, args),
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/__init__.py", line 1568, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 961, in compile_fx
    return compile_fx(
  File "/opt/conda/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 1150, in compile_fx
    return aot_autograd(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 3891, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 3429, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2212, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2392, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2804, in aot_dispatch_autograd
    fx_g = aot_dispatch_autograd_graph(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2781, in aot_dispatch_autograd_graph
    fx_g = create_functionalized_graph(
  File "/opt/conda/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1420, in create_functionalized_graph
    fx_g = make_fx(helper, decomposition_table=aot_config.decompositions)(*args)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 809, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/opt/conda/lib/python3.8/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 468, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 451, in create_arg
    return super().create_arg(a)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 385, in create_arg
    return super().create_arg(a)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/proxy.py", line 255, in create_arg
    return type(a)(self.create_arg(elem) for elem in a)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/proxy.py", line 255, in <genexpr>
    return type(a)(self.create_arg(elem) for elem in a)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 451, in create_arg
    return super().create_arg(a)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 385, in create_arg
    return super().create_arg(a)
  File "/opt/conda/lib/python3.8/site-packages/torch/fx/proxy.py", line 291, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
NotImplementedError: argument of type: <class 'torch.amp.autocast_mode.autocast'>

While executing %submod_0 : [num_users=3] = call_module[target=submod_0](args = (%l_x_,), kwargs = {})
Original traceback:
None

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

233522-10ea61f2-6f10-11ee-9682-4ee5ea5d12cf-6mprp:6107:6116 [0] NCCL INFO [Service thread] Connection closed by localRank 0
233522-10ea61f2-6f10-11ee-9682-4ee5ea5d12cf-6mprp:6107:6107 [0] NCCL INFO comm 0x55b1609f2ad0 rank 0 nranks 1 cudaDev 0 busId b1000 - Abort COMPLETE

```

### Minified repro

The code for `elastic_ddp.py` is shown below.

```python
# coding=utf-8
import numpy as np
import torch
import torch._dynamo as dynamo
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel as DDP
from torchvision.models import resnet18, resnet152

using_ckpt = False


def conv3x3(in_planes, out_planes, stride=1, groups=1, dilation=1):
    """3x3 convolution with padding"""
    return nn.Conv2d(in_planes,
                     out_planes,
                     kernel_size=3,
                     stride=stride,
                     padding=dilation,
                     groups=groups,
                     bias=False,
                     dilation=dilation)


def conv1x1(in_planes, out_planes, stride=1):
    """1x1 convolution"""
    return nn.Conv2d(in_planes,
                     out_planes,
                     kernel_size=1,
                     stride=stride,
                     bias=False)


class IBasicBlock(nn.Module):
    expansion = 1

    def __init__(self,
                 inplanes,
                 planes,
                 stride=1,
                 downsample=None,
                 groups=1,
                 base_width=64,
                 dilation=1):
        super(IBasicBlock, self).__init__()
        if groups != 1 or base_width != 64:
            raise ValueError(
                'BasicBlock only supports groups=1 and base_width=64')
        if dilation > 1:
            raise NotImplementedError(
                "Dilation > 1 not supported in BasicBlock")
        self.bn1 = nn.BatchNorm2d(
            inplanes,
            eps=1e-05,
        )
        self.conv1 = conv3x3(inplanes, planes)
        self.bn2 = nn.BatchNorm2d(
            planes,
            eps=1e-05,
        )
        self.prelu = nn.PReLU(planes)
        self.conv2 = conv3x3(planes, planes, stride)
        self.bn3 = nn.BatchNorm2d(
            planes,
            eps=1e-05,
        )
        self.downsample = downsample
        self.stride = stride

    def forward_impl(self, x):
        identity = x
        out = self.bn1(x)
        out = self.conv1(out)
        out = self.bn2(out)
        out = self.prelu(out)
        out = self.conv2(out)
        out = self.bn3(out)
        if self.downsample is not None:
            identity = self.downsample(x)
        out += identity
        return out

    def forward(self, x):
        if self.training and using_ckpt:
            return checkpoint(self.forward_impl, x)
        else:
            return self.forward_impl(x)


class IResNet(nn.Module):
    fc_scale = 7 * 7

    def __init__(self,
                 block,
                 layers,
                 dropout=0,
                 num_features=512,
                 zero_init_residual=False,
                 groups=1,
                 width_per_group=64,
                 replace_stride_with_dilation=None,
                 fp16=False):
        super(IResNet, self).__init__()
        self.extra_gflops = 0.0
        self.fp16 = fp16
        self.inplanes = 64
        self.dilation = 1
        if replace_stride_with_dilation is None:
            replace_stride_with_dilation = [False, False, False]
        if len(replace_stride_with_dilation) != 3:
            raise ValueError("replace_stride_with_dilation should be None "
                             "or a 3-element tuple, got {}".format(
                                 replace_stride_with_dilation))
        self.groups = groups
        self.base_width = width_per_group
        self.conv1 = nn.Conv2d(3,
                               self.inplanes,
                               kernel_size=3,
                               stride=1,
                               padding=1,
                               bias=False)
        self.bn1 = nn.BatchNorm2d(self.inplanes, eps=1e-05)
        self.prelu = nn.PReLU(self.inplanes)
        self.layer1 = self._make_layer(block, 64, layers[0], stride=2)
        self.layer2 = self._make_layer(block,
                                       128,
                                       layers[1],
                                       stride=2,
                                       dilate=replace_stride_with_dilation[0])
        self.layer3 = self._make_layer(block,
                                       256,
                                       layers[2],
                                       stride=2,
                                       dilate=replace_stride_with_dilation[1])
        self.layer4 = self._make_layer(block,
                                       512,
                                       layers[3],
                                       stride=2,
                                       dilate=replace_stride_with_dilation[2])
        self.bn2 = nn.BatchNorm2d(
            512 * block.expansion,
            eps=1e-05,
        )
        self.dropout = nn.Dropout(p=dropout, inplace=True)
        self.fc = nn.Linear(512 * block.expansion * self.fc_scale, num_features)
        self.features = nn.BatchNorm1d(num_features, eps=1e-05)
        nn.init.constant_(self.features.weight, 1.0)
        self.features.weight.requires_grad = False

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.normal_(m.weight, 0, 0.1)
            elif isinstance(m, (nn.BatchNorm2d, nn.GroupNorm)):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

        if zero_init_residual:
            for m in self.modules():
                if isinstance(m, IBasicBlock):
                    nn.init.constant_(m.bn2.weight, 0)

    def _make_layer(self, block, planes, blocks, stride=1, dilate=False):
        downsample = None
        previous_dilation = self.dilation
        if dilate:
            self.dilation *= stride
            stride = 1
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                conv1x1(self.inplanes, planes * block.expansion, stride),
                nn.BatchNorm2d(
                    planes * block.expansion,
                    eps=1e-05,
                ),
            )
        layers = []
        layers.append(
            block(self.inplanes, planes, stride, downsample, self.groups,
                  self.base_width, previous_dilation))
        self.inplanes = planes * block.expansion
        for _ in range(1, blocks):
            layers.append(
                block(self.inplanes,
                      planes,
                      groups=self.groups,
                      base_width=self.base_width,
                      dilation=self.dilation))

        return nn.Sequential(*layers)

    def forward(self, x):
        with torch.cuda.amp.autocast(True):
            x = self.conv1(x)
            x = self.bn1(x)
            x = self.prelu(x)
            x = self.layer1(x)
            x = self.layer2(x)
            x = self.layer3(x)
            x = self.layer4(x)
            x = self.bn2(x)
            x = torch.flatten(x, 1)
            x = self.dropout(x)
        x = self.fc(x.float())
        x = self.features(x)
        return x


def _iresnet(arch, block, layers, pretrained, progress, **kwargs):
    model = IResNet(block, layers, **kwargs)
    if pretrained:
        raise ValueError()
    return model


def iresnet18(pretrained=False, progress=True, **kwargs):
    return _iresnet('iresnet18', IBasicBlock, [2, 2, 2, 2], pretrained,
                    progress, **kwargs)


def iresnet34(pretrained=False, progress=True, **kwargs):
    return _iresnet('iresnet34', IBasicBlock, [3, 4, 6, 3], pretrained,
                    progress, **kwargs)


def iresnet50(pretrained=False, progress=True, **kwargs):
    return _iresnet('iresnet50', IBasicBlock, [3, 4, 14, 3], pretrained,
                    progress, **kwargs)


def iresnet100(pretrained=False, progress=True, **kwargs):
    return _iresnet('iresnet100', IBasicBlock, [3, 13, 30, 3], pretrained,
                    progress, **kwargs)


def iresnet200(pretrained=False, progress=True, **kwargs):
    return _iresnet('iresnet200', IBasicBlock, [6, 26, 60, 6], pretrained,
                    progress, **kwargs)


def generate_data(b, device_id=0):
    channel = 3
    height = 112
    width = 112
    return (
        torch.randn(b, channel, height, width).to(torch.float32).cuda(),
        torch.randint(256, (b,)).cuda(device_id),
    )


def init_model(amp=False, device_id=0):
    # return resnet152(num_classes=256).to(torch.float32).cuda(device_id)
    return iresnet200(num_features=256).cuda(device_id)


def train(model, data, opt, grad_scaler):
    opt.zero_grad(True)
    # with torch.autocast(device_type="cuda", enabled=True):
    predict = model(data[0])
    loss = torch.nn.CrossEntropyLoss()(predict, data[1])
    loss = grad_scaler.scale(loss)
    loss.backward()
    opt.step()
    return loss


def eval(model, data):
    with torch.cuda.amp.autocast(enabled=True):
        predict = model(data[0])
        loss = torch.nn.CrossEntropyLoss()(predict, data[1])
    return loss


def timed(fn):
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    result = fn()
    end.record()
    torch.cuda.synchronize()
    return result, start.elapsed_time(end) / 1000


def demo_basic():
    N_ITERS = 30
    dist.init_process_group("nccl")
    rank = dist.get_rank()
    print(f"Start running basic DDP example on rank {rank}.")

    # create model and move it to GPU with id rank
    device_id = rank % torch.cuda.device_count()
    # model = ToyModel().to(device_id)
    dynamo.reset()
    model = init_model(device_id=device_id)
    ddp_model = DDP(model, device_ids=[device_id])

    opt = optim.SGD(ddp_model.parameters(), lr=0.001)
    # data = generate_data(16, device_id=device_id)
    grad_scaler = torch.cuda.amp.GradScaler(init_scale=2.0)
    eager_times = []
    for i in range(N_ITERS):
        inp = generate_data(16)
        loss, eager_time = timed(
            lambda: train(ddp_model, inp, opt, grad_scaler))
        eager_times.append(eager_time)
        print(f"eager train time {i}: {eager_time}", "loss:", loss.item())
    print("~" * 10)
    dynamo.reset()
    model = init_model(device_id=device_id)
    ddp_model = DDP(model, device_ids=[device_id])
    opt = optim.SGD(ddp_model.parameters(), lr=0.001)
    grad_scaler = torch.cuda.amp.GradScaler(init_scale=2.0)
    train_opt = torch.compile(train,
                              options={"triton.cudagraphs": True},
                              backend="inductor")

    compile_times = []
    for i in range(N_ITERS):
        inp = generate_data(16)
        loss, compile_time = timed(
            lambda: train_opt(ddp_model, inp, opt, grad_scaler))
        compile_times.append(compile_time)
        print(f"compile train time {i}: {compile_time}", "loss:", loss.item())
    print("~" * 10)

    eager_med = np.median(eager_times)
    compile_med = np.median(compile_times)
    speedup = eager_med / compile_med
    print(
        f"(train) eager median: {eager_med}, compile median: {compile_med}, speedup: {speedup}x"
    )
    print("~" * 10)
    dist.destroy_process_group()


if __name__ == "__main__":
    demo_basic()

```

The running commands are as follows:

```shell
torchrun --nnodes=1 --nproc_per_node=1 --node_rank=0 --master_addr=127.0.0.1 elastic_ddp.py
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1062.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz
Stepping:            7
CPU MHz:             3170.947
CPU max MHz:         4000.0000
CPU min MHz:         1000.0000
BogoMIPS:            4800.00
Virtualization:      VT-x
L1d cache:           1.5 MiB
L1i cache:           1.5 MiB
L2 cache:            48 MiB
L3 cache:            71.5 MiB
NUMA node0 CPU(s):   0-23,48-71
NUMA node1 CPU(s):   24-47,72-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchdata==0.7.0
[pip3] torchtext==0.16.0+cpu
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     2.1.0+cu118              pypi_0    pypi
[conda] torchaudio                2.1.0+cu118              pypi_0    pypi
[conda] torchdata                 0.7.0                    pypi_0    pypi
[conda] torchtext                 0.16.0+cpu               pypi_0    pypi
[conda] torchvision               0.16.0+cu118             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @aakhundov @mcarilli @ptrblck @leslie-fang-intel

**Comment by mlazos** [comment]
assigning @jansel arbitrarily

**Comment by williamwen42** [comment]
This seems to be a bad interaction between ddp, amp, and aotautograd (same failure is seen on `aot_eager` compile backend).

**Comment by williamwen42** [comment]
I believe what is happening is that ddp splits the graph that dynamo produces when it encounters autocast, resulting in a graph that returns an autocast context object, which aotautograd doesn't handle.

**Comment by williamwen42** [comment]
More context:
The GraphModule traced by dynamo is:
```python
class GraphModule(torch.nn.Module):
    def forward(self, L_x_ : torch.Tensor):
        l_x_ = L_x_
        
        # No stacktrace found for following nodes
        _enter_autocast = torch.amp.autocast_mode._enter_autocast('cuda', torch.float16, True, True)
        
        # File: /data/users/williamwen/pytorch/playground4.py:194, code: x = self.conv1(x)
        x = self.L__self___conv1(l_x_);  l_x_ = None
        
        # File: /data/users/williamwen/pytorch/playground4.py:195, code: x = self.bn1(x)
        x_1 = self.L__self___bn1(x);  x = None
...
        # File: /data/users/williamwen/pytorch/playground4.py:203, code: x = self.dropout(x)
        x_9 = self.L__self___dropout(x_8);  x_8 = None
        
        # No stacktrace found for following nodes
        _exit_autocast = torch.amp.autocast_mode._exit_autocast(_enter_autocast);  _enter_autocast = None
        
        # File: /data/users/williamwen/pytorch/playground4.py:204, code: x = self.fc(x.float())
        float_1 = x_9.float();  x_9 = None
        x_10 = self.L__self___fc(float_1);  float_1 = None
        
        # File: /data/users/williamwen/pytorch/playground4.py:205, code: x = self.features(x)
        x_11 = self.L__self___features(x_10);  x_10 = None
        return (x_11,)
```

The ddp dynamo backend transforms this graph, and aotautograd receives this graph:
```python
class GraphModule(torch.nn.Module):
    def forward(self, l_x_ : torch.Tensor):
        # No stacktrace found for following nodes
        _enter_autocast = torch.amp.autocast_mode._enter_autocast('cuda', torch.float16, True, True)
        
        # File: /data/users/williamwen/pytorch/playground4.py:194, code: x = self.conv1(x)
        l__self___conv1 = self.L__self___conv1(l_x_);  l_x_ = None
        
        # File: /data/users/williamwen/pytorch/playground4.py:195, code: x = self.bn1(x)
        l__self___bn1 = self.L__self___bn1(l__self___conv1);  l__self___conv1 = None
...
        # File: /data/users/williamwen/pytorch/playground4.py:81, code: out += identity
        getattr_l__self___layer2___1___bn3 += iadd_6;  iadd_7 = getattr_l__self___layer2___1___bn3;  getattr_l__self___layer2___1___bn3 = iadd_6 = None
        
        # File: /data/users/williamwen/pytorch/playground4.py:73, code: out = self.bn1(x)
        getattr_l__self___layer2___2___bn1 = self.getattr_L__self___layer2___2___bn1(iadd_7)
        return (getattr_l__self___layer2___2___bn1, iadd_7, _enter_autocast)
```

**Comment by zou3519** [comment]
also cc @bdhirsh and @ezyang for https://github.com/pytorch/pytorch/pull/103024

DDP splitting the graph causes `_enter_autocast` (an autocast context object) to be a return from the graph, but AOTAutograd doesn't know how to handle autocast context objects.

One potential solution is to change the traced APIs to not return and accept autocast context object (this is what we do for other context managers):
```
torch.amp.autocast_mode._set_autocast_enabled(True)
...
torch.amp.autocast_mode._set_autocast_enabled(False)
```
This is what the body of #103024 advertises, but it sounds like this was changed somewhere down the line. Was there a reason why?

Also, there is a second problem with DDP splitting the graph into 2+ pieces: in the next graph, autocast might not actually be enabled (see https://github.com/pytorch/pytorch/issues/112072). I'm not sure that graphs received from Dynamo are allowed to be split; only functional graphs are safely splittable.

**Comment by jon-chuang** [comment]
> I'm not sure that graphs received from Dynamo are allowed to be split; only functional graphs are safely splittable.

Yeah, this seems wrong. DDP should not be allowed to split dynamo graphs arbitrarily. Every new graph split / graph break needs to be aware of the context manager stack so as to be able to restore / unwind it.

I guess in this case, we just need to make the graph splitting aware of `torch.amp._set_autocast_{enabled,disabled}`? Let's see if it is also aware of `set_grad_enabled`.

**Comment by jon-chuang** [comment]
Would be great to have a simpler repro. But I guess this one is a bit non-deterministic.

**Comment by jon-chuang** [comment]
The right way to handle this _generically_ IMO is to actually ask the DDP backend to insert graph breaks into the graph modules where it needs them, and then _ask dynamo to retrace the graph_. This way, dynamo can properly do the right setup/unwind logic for the context managers. Then, the DDP backend promises not to try to insert new graph breaks.

Fixing this for `_set_grad_enabled`, `autocast` only may be simpler, however, we can just manually perform the unwind/setup by inspecting the autocast/grad mode at the time of the DDP-induced graph break.

Thoughts? @jansel @voznesenskym @ezyang

**Comment by jon-chuang** [comment]
I am able to repro.

**Comment by wconstab** [comment]
> The right way to handle this generically IMO is to actually ask the DDP backend to insert graph breaks into the fx.GraphModules where it needs them, and then ask dynamo to retrace the graph. This way, dynamo can properly do the right setup/unwind logic for the context managers. Then, the DDP backend promises not to try to insert new graph breaks / buckets.

well, we have another "right way" to handle DDP: we're compiling it without needing to insert graph breaks at all.  But that's a work in progress.  For now the graph-break thing is on life support, if there is an easy patch we might do it but otherwise we might wait.

**Comment by jon-chuang** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/112231 with this technique:

> Fixing this for _set_grad_enabled, autocast only may be simpler, however, we can just manually perform the unwind/setup by inspecting the autocast/grad mode at the time of the DDP-induced graph break, and insert the right setup/unwind manually.

```
Start running basic DDP example on rank 0.
eager train time 0: 0.45598104858398436 loss: 12.225789070129395
~~~~~~~~~~
[rank0]:[2023-10-27 00:06:19,947] [1/0] torch._dynamo.variables.torch: [WARNING] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
autocast_regions {(_enter_autocast, ('cuda', torch.float16, False, True)): [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], (_enter_autocast_1, ('cuda', torch.float16, True, True)): [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}
grad_regions {(_set_grad_enabled, (True,)): [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], (_set_grad_enabled_1, (True,)): [16]}
/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_inductor/compile_fx.py:131: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
/home/jonch/Desktop/Programming/mlsys/pytorch/torch/autograd/__init__.py:254: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [512, 256, 1, 1], strides() = [256, 1, 256, 256]
bucket_view.sizes() = [512, 256, 1, 1], strides() = [256, 1, 1, 1] (Triggered internally at /home/jonch/Desktop/Programming/mlsys/pytorch/torch/csrc/distributed/c10d/reducer.cpp:322.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
compile train time 0: 155.04621875 loss: 12.770548820495605
/home/jonch/Desktop/Programming/mlsys/pytorch/torch/autograd/__init__.py:254: UserWarning: Waiting for pending NCCL work to finish before starting graph capture. (Triggered internally at /home/jonch/Desktop/Programming/mlsys/pytorch/aten/src/ATen/cuda/CUDAGraph.cpp:145.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
compile train time 1: 23.47212109375 loss: 12.521818161010742
compile train time 2: 0.14583699035644532 loss: 11.45854377746582
compile train time 3: 0.14697984313964843 loss: 12.453595161437988
compile train time 4: 0.14625382995605468 loss: 11.855585098266602
compile train time 5: 0.16280064392089844 loss: 12.720451354980469
compile train time 6: 0.14646357727050782 loss: 12.215387344360352
compile train time 7: 0.14906367492675782 loss: 12.055177688598633
compile train time 8: 0.15279615783691405 loss: 12.267801284790039
compile train time 9: 0.1569769287109375 loss: 11.227594375610352
compile train time 10: 0.15158457946777343 loss: 11.399459838867188
compile train time 11: 0.1475962829589844 loss: 11.330711364746094
compile train time 12: 0.167048095703125 loss: 12.16124153137207
compile train time 13: 0.19255987548828124 loss: 11.893743515014648
compile train time 14: 0.19741081237792968 loss: 11.885215759277344
compile train time 15: 0.19720806884765624 loss: 12.5259370803833
compile train time 16: 0.19388211059570312 loss: 12.420429229736328
compile train time 17: 0.1589555206298828 loss: 11.20382308959961
compile train time 18: 0.14926541137695312 loss: 11.823939323425293
compile train time 19: 0.1494466552734375 loss: 11.947622299194336
compile train time 20: 0.15223202514648437 loss: 12.32269287109375
compile train time 21: 0.15297535705566406 loss: 11.983843803405762
compile train time 22: 0.15380662536621093 loss: 12.016621589660645
compile train time 23: 0.15333990478515624 loss: 13.40727424621582
compile train time 24: 0.14944358825683593 loss: 11.341147422790527
compile train time 25: 0.16411135864257811 loss: 11.352535247802734
compile train time 26: 0.19596902465820312 loss: 11.577886581420898
compile train time 27: 0.1956505584716797 loss: 11.485648155212402
compile train time 28: 0.15360000610351562 loss: 12.211712837219238
compile train time 29: 0.15046035766601562 loss: 12.0223388671875
~~~~~~~~~~
(train) eager median: 0.45598104858398436, compile median: 0.15346995544433595, speedup: 2.9711421187541176x
```

**Comment by jon-chuang** [comment]
@sasa9451 please let us know if your model runs correctly on latest main

**Comment by kleingeo** [comment]
I am still having the same issue. Currently the latest torch with a new conda environment. Same issues (ddp + amp + torch.compile)

**Comment by jon-chuang** [comment]
>  latest torch

Can you clarify if you mean torch nightly? This is not yet fixed on the stable release.

**Comment by zou3519** [comment]
Script doesn't repro anymore
