### ISSUE TITLE
[Caffe2] Blob/Tensors aliased & overwritten

### ISSUE THREAD

**Issue by steplee** [pytorch/pytorch#11317]
Using caffe2 from C++, when I had two blobs created in the workspace (on the GPU, with an init/prediction net also in the workspace), doing the workflow of `GetBlob -> GetMutable -> CopyFrom(cpu source tensor)`, the second blob would overwrite the first (and vice versa, whichever was most recently written).

The solution was to not use` GetMutable(src)`, but to use create a new `TensorCUDA` and call `blob->Reset(src)` instead.

Is the GetMutable() approach below not supposed to work? It works when only one blob needs to be set, and is used by the only C++ samples I could find.

A snippet from my old code
```
    std::vector<float> fake_data_vec(1*3*224*224);
    const TensorCUDA* fake_data_t = wrk.CreateBlob("data")->GetMutable<TensorCUDA>();
    auto fake_data_src = TensorCPU({1,3,224,224}, fake_data_vec, cctx);
    fake_data_t->CopyFrom(fake_data_src);

    referenceCodesBlob = wrk.CreateBlob("reference_codes");
    const TensorCUDA* refCodes_t = referenceCodesBlob->GetMutable<TensorCUDA>();
    auto src = TensorCPU({N,D}, refCodesVec, cctx);
    refCodes_t->CopyFrom(src);
```

I printed the pointer addresses of `GetBlob` and `GetMutable`, and they were different as expected, which leads me to believe it might have to do with `TensorImpl` or `Storage`. Also the dims of the tensors were copied as well, not just the data.

- PyTorch or Caffe2: caffe2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): `CMAKE_FLAGS=-DUSE_MPI=0 NO_MIOPEN=1 FULL_CAFFE2=1 sudo -EH python setup.py install`
- OS: Ubuntu 16.04
- PyTorch version: Commit b7cd4b692c294d93986da6565f3e0ff88ae6afae (sept. 5)
- Python version: 3.5
- CUDA/cuDNN version: 9.0 / 7
- GPU models and configuration: 1060
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.5+
- Versions of any other relevant libraries:

**Comment by ezyang** [comment]
Fixed in #11323

**Comment by rilesdg3** [comment]
I am having this issue, I cloned from Git and built from source on 10-22-2018, and this is still a problem

Everything compiles but will crash when I do it this way
auto* w2 = w.CreateBlob("w2")->GetMutable<caffe2::Tensor>();

I get the following 

*** Aborted at 1540324467 (unix time) try "date -d @1540324467" if you are using GNU date ***
PC: @           0x440e6e at::DataPtr::device()
*** SIGSEGV (@0x38) received by PID 3436 (TID 0x7ffff7f6ab80) from PID 56; stack trace: ***
    @     0x7ffff4e91390 (unknown)
    @           0x440e6e at::DataPtr::device()
    @           0x4420c8 at::StorageImpl::device()
    @           0x4423f2 at::Storage::device()
    @           0x442b92 at::TensorImpl::GetDevice()
    @           0x442d76 at::TensorImpl::CopyFrom()
    @           0x44478f caffe2::Tensor::CopyFrom()
    @           0x43edd3 main
    @     0x7ffff4ad6830 __libc_start_main
    @           0x40d9a9 _start
    @                0x0 (unknown)

and when I try it this way
auto* w1 = w.CreateBlob("w1")->GetMutable(caffe2::Tensor);

I get the following error
error: expected primary-expression before ‘)’ token

This is my first time posting on Git, so let me know if I am missing/not doing something properly

thank you

**Comment by ezyang** [comment]
@rilesdg3 Glad you figured it out. We're working on making these APIs much easier to use
