### ISSUE TITLE
Channels Last Logic in `native_group_norm_backward` errors on some edge cases on CPU

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#115940]
### 🐛 Describe the bug

```python
import torch
import torch.nn as nn
N = 2048
C = 384
H = 1
W = 1

groups = 3
input = torch.randn(H, N, C, W, requires_grad=True, device='cpu').permute(1, 2, 0, 3)
# input shape: torch.Size([2048, 384, 1, 1]), stride: (384, 1, 786432, 1)
print(f"input shape: {input.shape}, stride: {input.stride()}")
# True
print(input.is_contiguous(memory_format=torch.channels_last))

m = nn.GroupNorm(groups, C, affine=False, device='cpu')
output = m(input)
gradient = torch.randn(N, C, H, W, device='cpu').to(memory_format=torch.channels_last)
# gradient shape: torch.Size([2048, 384, 1, 1]), stride: (384, 1, 384, 384)
print(f"gradient shape: {gradient.shape}, stride: {gradient.stride()}")
output.backward(gradient) # RuntimeError: Expected memory formats of X and dY are same.
```

This is failing [this check here](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/group_norm.cpp#L122-L124) added in https://github.com/pytorch/pytorch/pull/100234

The gradient formula here has [some special casing for memory format ](https://github.com/pytorch/pytorch/blob/main/tools/autograd/derivatives.yaml#L1231) so we would expect this check should be passing(?)

### Versions

main

cc @CaoE 

cc @albanD @mruberry @jbschlosser @walterddr @jamesr66a @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by mannatsingh** [comment]
Thanks for creating the issue @mikaylagawarecki ! This issue isn't restricted to CPU devices. The exact same repro also fails when the device is changed to "cuda" as well.

**Comment by rdadan** [comment]
Hi guys, when I was doing backpropagation now, I got "RuntimeError: Expected memory formats of X and dY are same." Can I upgrade pytorch to solve this problem? My current version is 2.2.2+cu121.

![expect x and dy same](https://github.com/pytorch/pytorch/assets/36651939/1f330626-d80f-42c6-9f20-7ba3596b04d2)

**Comment by CaoE** [comment]
@rdadan This should have been fixed. You can try with latest PT. You may also check the version of PyTorch you are using.

**Comment by rdadan** [comment]
Thanks for the reply. The version I am using is 2.2.2+cu121. But the "RuntimeError: Expected memory formats of X and dY are same." problem still occurs.``....

When I calculate the loss between ori_embedding_pre and gaussion_embedding_pre, I get an error in backpropagation.
Here's the code:
`for j in range(num_inner_steps):
                self.unet.to(memory_format=torch.contiguous_format)
                with torch.no_grad():
                    noise_ddim =  self.unet(ori_embedding.contiguous(), t)["sample"]
                    ori_embedding_pre = self.prev_step2(noise_ddim.contiguous(), t, ori_embedding.contiguous()).contiguous()
                
                noise_gaus =  self.unet(gaussion_embedding.contiguous(), t)["sample"]
                noise_gaus = w_scale * noise_ddim + (1-w_scale)*noise_gaus
                gaussion_embedding_pre = self.prev_step2(noise_gaus.contiguous(), t, 
                gaussion_embedding.contiguous()).contiguous()
                ori_embedding_pre = ori_embedding_pre.to(memory_format=torch.contiguous_format)
                gaussion_embedding_pre = gaussion_embedding_pre.to(memory_format=torch.contiguous_format)
                
                loss = nnf.mse_loss(ori_embedding_pre, gaussion_embedding_pre)
                loss = loss.contiguous()
                loss.is_contiguous(memory_format=torch.contiguous_format)
                # loss = sdtw(ori_embedding.squeeze(0), gaussion_embedding_pre.squeeze(0)) # Just like any torch.nn.xyzLoss()
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()`

**Comment by rdadan** [comment]
> @rdadan This should have been fixed. You can try with latest PT. You may also check the version of PyTorch you are using.

Thanks for the reply. The version I am using is 2.2.2+cu121. But the "RuntimeError: Expected memory formats of X and dY are same." problem still occurs.``....

When I calculate the loss between ori_embedding_pre and gaussion_embedding_pre, I get an error in backpropagation.
Here's the code:

![code](https://github.com/pytorch/pytorch/assets/36651939/5842a310-4dd0-478c-aab5-6eadc9cf4a23)

PyTorch version 
![torch](https://github.com/pytorch/pytorch/assets/36651939/08548383-f87d-4d1d-be11-c4a514be9859)

**Comment by CaoE** [comment]
@rdadan You can try latest torch. pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu

**Comment by rdadan** [comment]
> @rdadan You can try latest torch. pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu If problem still occurs. You may need to make sure all inputs and model is in same layout. Also try xxx.contiguous(memory_formats=torch.contiguous)

Thanks for the reply, this version of ”pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu“is valid，but seems to be cpu version ('2.4.0.dev20240418+cpu'). 
Where can I download the latest GPU Torch to solves the problem

**Comment by rdadan** [comment]
> @rdadan You can try latest torch. pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu If problem still occurs. You may need to make sure all inputs and model is in same layout. Also try xxx.contiguous(memory_formats=torch.contiguous)

Thank you very much, it works

**Comment by NYH-Dolphin** [comment]
> @rdadan You can try latest torch. pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu If problem still occurs. You may need to make sure all inputs and model is in same layout. Also try xxx.contiguous(memory_formats=torch.contiguous)

Hi! I want to know if there is any torch Cuda version that can resolve this problem as well? I ran into the same problem, but my local computer would speed up the training process with Cuda and GPU, as I didn't want to put the whole process on the CPU.

**Comment by CaoE** [comment]
> > @rdadan You can try latest torch. pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu If problem still occurs. You may need to make sure all inputs and model is in same layout. Also try xxx.contiguous(memory_formats=torch.contiguous)
> 
> Hi! I want to know if there is any torch Cuda version that can resolve this problem as well? I ran into the same problem, but my local computer would speed up the training process with Cuda and GPU, as I didn't want to put the whole process on the CPU.

You can try `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118` or `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121`  (INSTALL PYTORCH in https://pytorch.org/).
