### ISSUE TITLE
MPS MatMul (even 2d) broken

### ISSUE THREAD

**Issue by BlackHC** [pytorch/pytorch#116769]
### 🐛 Describe the bug

Subindexing a matrix on the outer-dimensions before or after matrix multiplication should be the same: (A @ B)[:, U] === A @ B[:, U] because the results are independent. It is for CPU but not for MPS. Even for 2D matrices (so not even batched).

This makes PyTorch on MPS effectively useless. There is no point in using it if you cannot even assume that matrix multiplication is correct.

Example unit test:

```python
import torch

def test_matmul_transpose_associativity(device):
    # Create a random matrix 16384x128
    x = torch.rand(16384, 128, device=device)
    # Create a random matrix 70000x128
    y = torch.rand(128, 70000,device=device)

    # Sample 23444 random indices from 70000
    indices = torch.randperm(70000, device=device)[:23444]

    # Select 23444 random rows from y
    y_sampled = y[:, indices]

    # Multiply x by y_sampled
    z_sampled = torch.matmul(x, y_sampled)
    # Multiply x by y
    z = torch.matmul(x, y)

    # z[:, indices] should be equal to z_sampled
    assert torch.allclose(z[:, indices], z_sampled, rtol=1e-2, atol=1e-2), "Matmul associativity test failed on device {}".format(device)

test_matmul_transpose_associativity("cpu")
test_matmul_transpose_associativity("mps")
```

```
[42](file:///Users/akirsch/git/midjourney_explorations/spikes/matmul_mps?line=41) assert torch.allclose(z[:, indices], z_sampled, rtol=1e-2, atol=1e-2), "Matmul associativity test failed on device {}".format(device)

AssertionError: Matmul associativity test failed on device mps
```

### Versions

```
Collecting environment information...
PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.7 | packaged by conda-forge | (main, Dec 15 2023, 08:41:36) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] light-the-torch==0.4.2
[pip3] numpy==1.26.2
[pip3] open-clip-torch==2.23.0
[pip3] torch==2.1.2
[pip3] torch-aesthetic-redux==0.1.0
[pip3] torchaudio==2.1.2
[pip3] torchvision==0.16.2
[conda] light-the-torch           0.4.2                    pypi_0    pypi
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] open-clip-torch           2.23.0                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] torch-aesthetic-redux     0.1.0                    pypi_0    pypi
[conda] torchaudio                2.1.2                    pypi_0    pypi
[conda] torchvision               0.16.2                   pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by albanD** [comment]
cc @malfet is this fixed by your PR from last week?

**Comment by lezcano** [comment]
@BlackHC Could you post how far are the two solutions using `torch.dist` on 2-norm and the infinity norm? The matrices you are using are quite large, and this is a textbook example where mathematically equivalent computations can give different results due to numerical errors.

**Comment by BlackHC** [comment]
Totally agree, re potential numerical issues. 

Points to take into account:
* for one, the test passes on CPU with identical dtype;
* using `rtol=0.5, atol=0.5` still fails on MPS, sadly;
* the inner dimension is only 128, so we are not summing that many terms for each output.

Also, I'm not comparing across devices but on the same device, so ideally, optimizations that reorder the order of summations should be identical as the inner dimensions (128) does not change. The associativity this tests is that one row @ col is independent of other row @ cols.

This even fails on MPS when just multiplying two 2D vectors: (16k, 1) x (1, 70k). So here there shouldn't be any numerical issues really because we only multiply two numbers for each output:

```python
import torch

def test_matmul_transpose_associativity(device):
    # Create a random matrix 16384x128
    x = torch.rand(16384, 1, device=device)
    # Create a random matrix 70000x128
    y = torch.rand(1, 70000,device=device)

    # Sample 23444 random indices from 70000
    indices = torch.randperm(70000, device=device)[:23444]

    # Select 23444 random rows from y
    y_sampled = y[:, indices]

    # Multiply x by y_sampled
    z_sampled = torch.matmul(x, y_sampled)
    # Multiply x by y
    z = torch.matmul(x, y)

    # z[:, indices] should be equal to z_sampled
    assert torch.allclose(z[:, indices], z_sampled, rtol=0.5, atol=0.5), "Matmul associativity test failed on device {}".format(device)

test_matmul_transpose_associativity("cpu")
test_matmul_transpose_associativity("mps")
```

**Comment by lezcano** [comment]
Could you try this on the last nightly, see if it's already fixed on main, as @albanD hinted?

**Comment by BlackHC** [comment]
Thanks! Last nightly also fails :( If I replace 70000 with e.g. 25000, it starts passing. So must be some overflow or similar in a for loop.

collect_env.py with nightly
```
Collecting environment information...
PyTorch version: 2.3.0.dev20240104
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.7 | packaged by conda-forge | (main, Dec 15 2023, 08:41:36) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] light-the-torch==0.4.2
[pip3] numpy==1.26.2
[pip3] open-clip-torch==2.23.0
[pip3] torch==2.3.0.dev20240104
[pip3] torch-aesthetic-redux==0.1.0
[pip3] torchaudio==2.1.2
[pip3] torchvision==0.18.0.dev20240104
[conda] light-the-torch           0.4.2                    pypi_0    pypi
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] open-clip-torch           2.23.0                   pypi_0    pypi
[conda] torch                     2.3.0.dev20240104          pypi_0    pypi
[conda] torch-aesthetic-redux     0.1.0                    pypi_0    pypi
[conda] torchaudio                2.1.2                    pypi_0    pypi
[conda] torchvision               0.18.0.dev20240104          pypi_0    pypi
```

**Comment by BlackHC** [comment]
Just as FYI with some blind debugging: It starts failing at 2**15+1 but works for 2**15 (for the 70k dimension).

So looks like you might be storing your loop counters as type (signed) int16/short which overflows?

**Comment by kulinseth** [comment]
Thanks @BlackHC ,  we are actively looking into this issue . It’s indeed not related to 3D or similar correctness issue with batched matmul . It’s as you pointed out related to the indexing data type

**Comment by davidmerwin** [comment]
>### 🐛 Describe the bug ...

@BlackHC 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by malfet** [comment]
> cc @malfet is this fixed by your PR from last week?

Shouldn't be as `torch.mm` and `torch.addmm` follow a slightly different codepath, but I suspect both are affected. And I wonder if it's similar to https://github.com/pytorch/pytorch/issues/111634

**Comment by malfet** [comment]
Hmm, though it does not look like problem in the matmul, but rather in index_select, i.e. example below
```python
import torch

def test_matmul_transpose_associativity(device):
    # Create a random matrix 16384x1
    x = torch.ones(16384, 1, device=device)
    # Create a random matrix 1x70000
    y = torch.arange(0, 1.0, 1.0/70000,device=device).reshape(1, 70000)

    indices = torch.arange(0, 10, device=device)

    y_sampled = y[:, indices]

    # Multiply x by y_sampled
    z_sampled = torch.matmul(x, y_sampled)
    # Multiply x by y
    z = torch.matmul(x, y)

    # Compute the difference
    z_d = z[:, indices]-z_sampled

    # Compute the difference one by one
    for i in range(10):
        print((z[:,i]-z_sampled[:,i]).abs().max(), z_d[:,i].abs().max())

    # z[:, indices] should be equal to z_sampled
    assert torch.allclose(z[:, indices], z_sampled, rtol=0.5, atol=0.5), f"Matmul associativity test failed on device {device}"

test_matmul_transpose_associativity("cpu")
test_matmul_transpose_associativity("mps")
```
prints the following:
```
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0.) tensor(0.)
tensor(0., device='mps:0') tensor(0.7304, device='mps:0')
tensor(0., device='mps:0') tensor(0.7304, device='mps:0')
tensor(0., device='mps:0') tensor(0.7304, device='mps:0')
tensor(0., device='mps:0') tensor(0.7304, device='mps:0')
tensor(0., device='mps:0') tensor(0.7304, device='mps:0')
tensor(0., device='mps:0') tensor(0.7303, device='mps:0')
tensor(0., device='mps:0') tensor(0.7303, device='mps:0')
tensor(0., device='mps:0') tensor(0.7303, device='mps:0')
tensor(0., device='mps:0') tensor(0.7303, device='mps:0')
tensor(0., device='mps:0') tensor(0.7303, device='mps:0')
```

**Comment by malfet** [comment]
> Just as FYI with some blind debugging: It starts failing at `2**15+1` but works for `2**15` (for the 70k dimension).
> 
> So looks like you might be storing your loop counters as type (signed) int16/short which overflows?
Indeed, `uint3` is vector of 3 16-bit integers
https://github.com/pytorch/pytorch/blob/d23972df005ea811762796c5c52ea3bb1d135f7d/aten/src/ATen/mps/IndexKernels.h#L32

**Comment by malfet** [comment]
Ok, sorry I've realized there are 2 problems here:
 - matmul does not work for larger matrices
 - `index_select` does not work for 4Gb+ tensors
Will work on fixing the second, but I wonder if one should raise some sort of exception when it happens right now (to avoid silent correctness problems)
@albanD what do you think?

**Comment by ezyang** [comment]
Exceptions good :)

**Comment by albanD** [comment]
Agreed!

**Comment by john1089** [comment]
Even (1025,1)*(1,32769) is broken with mps.

**Comment by john1089** [comment]
Please fix this issue as soon as possible.

**Comment by john1089** [comment]
I have tested out that the minimum size for matmul to fail is (1025,1)*(1,32769).

**Comment by john1089** [comment]
also,matmul is broken even without subindexing.
test program:
```python
import torch.nn as nn
import torch
def print_stats(y, y_p):
    abs_diff = (y - y_p).abs()
    items_different = (abs_diff > 1e-3).int().sum()

    print(
        f"linear diff sum: {abs_diff.sum()}"
    )
    print(
        f"items different (> 1e-3): {items_different} ({100*(int(items_different) / y.numel())}%)"
        )


x_cpu = torch.rand((1025, 1), dtype=torch.float32)
linear_cpu = nn.Linear(in_features=1, out_features=32769,bias=False)
linear_cpu.eval()
y_cpu = linear_cpu(x_cpu)
print(y_cpu.shape)
print("=== CPU matmul ===")
y_matmul = torch.matmul(x_cpu,linear_cpu.weight.t())
print_stats(y_matmul, y_cpu)

x_mps = x_cpu.to("mps")
linear_mps = linear_cpu.to("mps")

print("=== MPS Linear ===")
y_mps = linear_mps(x_mps)
print_stats(y_mps.to("cpu"), y_cpu)

print("=== MPS matmul ===")
y_mps_matmul = torch.matmul(x_mps,linear_mps.weight.t())
print_stats(y_mps_matmul.to("cpu"), y_cpu)
```

**Comment by john1089** [comment]
Also,for each row,the first few 1024 columns are correct, but all columns after that are wrong. @albanD @malfet

**Comment by Muhammad-Ibrahim-Khan** [comment]
I have two tensors, xbow (derived using for loops) and xbow2 (derived using matmul or @). Code for replication.

``` torch.manual_seed(1337)
B, T, C = 4, 8, 2  # Batch, Time, Channels
x = torch.randn(B, T, C)

# Using for loop
xbow = torch.zeros((B, T, C))
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1]  # (t, C)
        xbow[b, t] = torch.mean(xprev, 0)

# Using matmul (@)
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x 

# Checking
# torch.allclose(xbow, xbow2)
torch.eq(xbow, xbow2)

Output:
tensor([[[ True,  True],
         [ True,  True],
         [ True, False],
         [ True,  True],
         [ True, False],
         [False,  True],
         [False, False],
         [ True,  True]],

First element of tensors xbow and xbow2
(tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]),
 tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]))
```
The problem persists even for very small matrices.

**Comment by Muhammad-Ibrahim-Khan** [comment]
@kulinseth, is this already underway (PR created) or is there a branch I can help contribute to?

**Comment by malfet** [comment]
Ok, I've tried to do the tiling in https://github.com/pytorch/pytorch/pull/117319 but for some weird reason I hit problems but only if one of matrix dimensions is more then 64k

**Comment by malfet** [comment]
@BlackHC can you please confirm that everything works on your end?

**Comment by john1089** [comment]
@malfet the problem still isn't fixed.when running this program :
```python
import torch.nn as nn
import torch
def print_stats(y, y_p):
    abs_diff = (y - y_p).abs()
    items_different = (abs_diff > 1e-3).int().sum()

    print(
        f"linear diff sum: {abs_diff.sum()}"
    )
    print(
        f"items different (> 1e-3): {items_different} ({100*(int(items_different) / y.numel())}%)"
        )


x_cpu = torch.rand((1025, 1), dtype=torch.float32)
linear_cpu = nn.Linear(in_features=1, out_features=32769,bias=False)
linear_cpu.eval()
y_cpu = linear_cpu(x_cpu)
print(y_cpu.shape)
print("=== CPU matmul ===")
y_matmul = torch.matmul(x_cpu,linear_cpu.weight.t())
print_stats(y_matmul, y_cpu)

x_mps = x_cpu.to("mps")
linear_mps = linear_cpu.to("mps")

print("=== MPS Linear ===")
y_mps = linear_mps(x_mps)
print_stats(y_mps.to("cpu"), y_cpu)

print("=== MPS matmul ===")
y_mps_matmul = torch.matmul(x_mps,linear_mps.weight.t())
print_stats(y_mps_matmul.to("cpu"), y_cpu)
```
the result is
torch.Size([1025, 32769])
=== CPU matmul ===
linear diff sum: 0.0
items different (> 1e-3): 0 (0.0%)
=== MPS Linear ===
linear diff sum: 9458197.0
items different (> 1e-3): 32281993 (96.1110418904244%)
=== MPS matmul ===
linear diff sum: 9458197.0
items different (> 1e-3): 32281993 (96.1110418904244%)

**Comment by john1089** [comment]
with `PYTORCH_MPS_PREFER_METAL=1`,the result is
torch.Size([1025, 32769])
=== CPU matmul ===
linear diff sum: 0.0
items different (> 1e-3): 0 (0.0%)
=== MPS Linear ===
linear diff sum: 9706167.0
items different (> 1e-3): 32277939 (96.09897218444857%)
=== MPS matmul ===
linear diff sum: 0.0
items different (> 1e-3): 0 (0.0%)

**Comment by malfet** [comment]
@john1089 do you mind creating a new issue? At least for Linear I guess I need to extend it the fix for `torch.bmm` (which linear might be using under the hood)
But I also do not understand why one needs to specify PYTORCH_MPS_PREFER_METAL when matrix is transposed or not, fix for it is coming soon

**Comment by BlackHC** [comment]
Thank you. Tested now and both snippets pass with the latest nightly version.

(Apologies for the delay!)

**Comment by Jckwind** [comment]
just for a heads uo sake, I believe this issue still exists and has not been fully batched yet.

**Comment by Muhammad-Ibrahim-Khan** [comment]
@Jckwind , I ran Torch tensors through the SHAP API for calculating SHAP values recently and unfortunately, this issue replicating in other libraries is messing up a lot of workflows that require additivity assertions.
