### ISSUE TITLE
CUDA Memory leak w/ torch.compile in both stable and trunk

### ISSUE THREAD

**Issue by xmfan** [pytorch/pytorch#119607]
### 🐛 Describe the bug

models traced with torch.compile don't seem to be freeing CUDA memory

``` python
import torch
import gc

def main():
    x = torch.randn(1000, 3000, device="cuda", requires_grad=True)
    model = torch.nn.Sequential(
        torch.nn.Linear(3000, 10000),
        torch.nn.ReLU(),
        torch.nn.Linear(10000, 50000),
        torch.nn.ReLU(),
        torch.nn.Linear(50000, 20000),
        torch.nn.ReLU(),
        torch.nn.Linear(20000, 1234),
    ).to("cuda")
    model = torch.compile(model, backend="eager")
    model(x)

if __name__ == "__main__":
    main()

    # tried clearing with a few ways
    torch.cuda.synchronize()
    torch.cuda.empty_cache()
    torch._C._cuda_clearCublasWorkspaces()
    gc.collect()

    print(f"{torch.cuda.memory_allocated()/1e9} GB!!")  # 6.219729408 GB!!
```

one high priority use case to fix this is for compiled autograd, which calls torch.compile for compiled fw and once for compiled bw, leading to 2x memory use

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @Chillee 

### Versions

2.2.0
trunk

**Comment by xmfan** [comment]
marking dynamo since it happens with backend="eager"

**Comment by anijain2305** [comment]
Cc @williamwen42

**Comment by williamwen42** [comment]
This is not intended, but I find that if I wrap the `torch.nn.Sequential` inside a custom `nn.Module`, then the memory gets freed:
```python
import gc
import torch

class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        # self.fc1 = torch.nn.Linear(3000, 50000)
        self.fc1 = torch.nn.Sequential(
            torch.nn.Linear(3000, 10000),
            torch.nn.ReLU(),
            torch.nn.Linear(10000, 50000),
            torch.nn.ReLU(),
            torch.nn.Linear(50000, 20000),
            torch.nn.ReLU(),
            torch.nn.Linear(20000, 1234),
        )

    def forward(self, out):
        out = self.fc1(out)
        return out

def run(compile):
    mod = MyModel().cuda()
    if compile:
        mod = torch.compile(mod, backend="eager")
    inp = torch.rand(10000, 3000).cuda()
    mod(inp)

def clean_and_report_memory():
    gc.collect()
    print(f"max memory: {torch.cuda.max_memory_allocated()}, curr memory: {torch.cuda.memory_allocated()}")

run(False)
clean_and_report_memory()

run(True)
clean_and_report_memory()

torch._dynamo.reset()
clean_and_report_memory()
```
I will continue to investigate why memory is not being freed in the original code snippet.

**Comment by gchanan** [comment]
is it a regression?

**Comment by atalman** [comment]
Moving to release 2.2.2. Since fix is not out yet

**Comment by williamwen42** [comment]
I've simplified the repro:
```python
import gc
import weakref
import torch

mod = torch.nn.Linear(3000, 50000).cuda()
def fn(x):
    return mod(x)

ref = weakref.ref(mod, lambda _: print("mod deleted"))
weakref.finalize(fn, lambda: print("fn deleted"))

inp = torch.rand(10000, 3000).cuda()

torch.compile(backend="eager")(fn)(inp)

del mod
del fn

gc.collect()
```

It seems that dynamo holds on to a reference to `mod` somewhere.

**Comment by lezcano** [comment]
a shot in the dark, but may this be related to the memory leak that you were once hunting @Fidget-Spinner?

**Comment by Fidget-Spinner** [comment]
The memory leak I was once hunting concerned a circular reference between the compiled code cache and the code object itself IIRC. If anyone is aware of a reference from the compiled artefact object to the symbolic evaluator, that might be a source of leaks, because the symbolic stuff definitely holds a reference onto `mod` in this case. Otherwise, it wouldn't be that.

**Comment by lezcano** [comment]
alas @IvanYashchuk patched in https://github.com/pytorch/pytorch/pull/109422 and didn't seem to help with this one, so I guess there's something else going on here.

**Comment by ezyang** [comment]
@williamwen42 any updates on this?

**Comment by williamwen42** [comment]
Still working on this - got blocked recently because https://github.com/pytorch/pytorch/issues/112090 was happening again.

**Comment by xmfan** [comment]
Given the repro was fixed for nightly in 2.3, I'm closing this issue

While debugging the issue, @williamwen42 found others related bugs and can file individual issues to track them for a future release

**Comment by huydhn** [comment]
I'm testing this with the current 2.3 RC release and still seeing the issue.  @xmfan @williamwen42 Could you help double that it's fixed with `pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/test/cu121`?

In the meantime, I will reopen this and move it to 2.3 milestone

**Comment by williamwen42** [comment]
@huydhn which python version are you using? There are memory leaks that only happen in 3.11+.

**Comment by huydhn** [comment]
Ouch, I'm using 3.11.  Let me try it out again with a different python version.

**Comment by atalman** [comment]
@williamwen42 Could you please follow up on this issue ?

**Comment by williamwen42** [comment]
I'm working on the 3.11+ fix as part of the 3.12 work - the root cause revolves around the presence of the COPY_FREE_VARS bytecode instruction in the C Dynamo shadow (created) frame.

**Comment by JerrickLiu** [comment]
@williamwen42 is there a fix for this? I am also experiencing a memroy leak with torch compile and python 3.11

**Comment by williamwen42** [comment]
Do you have a repro? The fix only recently went in so you should try the nightly binaries.

**Comment by JerrickLiu** [comment]
Not a local repro unforunately. I can try the nightly binary. How long does it take to make it into the default stable installation?

Where can I find the nightly binaries that would have your fix?

**Comment by JerrickLiu** [comment]
I'm also hitting this leak with `backend=cudagraphs`, if your fix accounts for that

**Comment by JerrickLiu** [comment]
@williamwen42 I noticed this PR got closed: https://github.com/pytorch/pytorch/pull/124238

is this because the changes are merged or there is still an issue?

**Comment by JerrickLiu** [comment]
@williamwen42 bump on the nightly binary. Can I just use the one found here: https://pytorch.org/get-started/locally/

and selecting nightly?

**Comment by williamwen42** [comment]
Yeah that's the right link. Give it another day and it should be in the nightlies. The fix will not be in the stable binaries until next release (2.4). The leak occurs at a very high level in the PT2 stack (dynamo) - it should occur even on the eager backend. Can you confirm this?

**Comment by JerrickLiu** [comment]
@williamwen42 I confirmed with a nightly build that the memory leak is fixed

**Comment by huydhn** [comment]
This issue has been fixed in the upcoming 2.3.1 release https://dev-discuss.pytorch.org/t/pytorch-release-2-3-1-final-rc-is-available/2126 on python 3.11
