### ISSUE TITLE
Building via FetchContent and exporting via install results in missing "sleef" target

### ISSUE THREAD

**Issue by anthonyalayo** [pytorch/pytorch#119952]
### 🐛 Describe the bug

Building pytorch v2.2.0 via FetchContent, and attempting to setup an export set via CMake install, results in missing target "sleef". 

Upon investigating, I can see that the version of sleef currently pinned in pytorch's submodule is slightly older than hash that contains this fix: https://github.com/shibatch/sleef/pull/412

We are currently pinned to a hash from Dec 21, 2020.
We need to update to a hash from Mar 11, 2021.

### Error logs

CMake Error: install(EXPORT "Caffe2Targets" ...) includes target "torch_cpu" which requires target "sleef" that is not in any export set.

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.1.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.0
Libc version: N/A

Python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.1.2-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.2.0a0+git7e6cf04
[conda] Could not collect

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by masnesral** [comment]
@malfet AFAICT you were the last to update the pin for this submodule. Do you know if we have a process I should follow for a request like this?

**Comment by anthonyalayo** [comment]
Thanks for moving it along @masnesral , I fixed the issues that came up in CI last night so it's good to go

**Comment by masnesral** [comment]
@anthonyalayo , cool does that mean we can close this?

**Comment by JoergAtGithub** [comment]
As the PR got reverted, this bug is not fixed. Can somebody reopen this issue. It blocks https://github.com/microsoft/vcpkg/pull/42706

**Comment by malfet** [comment]
@JoergAtGithub sleef has been updated a few times, so clearly include the fix mentioned in this issue. But if you still experience the problem with 2.5 release, please create an issue and mention this one
