### ISSUE TITLE
[inline_inbuilt_nn_modules] Long compilation time for hf_T5_generate inference cause timeout

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#121989]
### 🐛 Describe the bug

The pass status for hf_T5_generate inference has been flaky in a few settings for the past month [link](https://hud.pytorch.org/benchmark/torchbench/inductor_with_cudagraphs?startTime=Wed%2C%2014%20Feb%202024%2021%3A15%3A20%20GMT&stopTime=Fri%2C%2015%20Mar%202024%2020%3A15%3A20%20GMT&granularity=day&mode=inference&dtype=bfloat16&lBranch=main&lCommit=38d9bb5abcc31ba97927a5399b88afe2cf60bf64&rBranch=main&rCommit=ca55468416ec96d31564304efe7a63bd92892e0b&model=hf_T5_generate)

The root cause is hf_T5_generate takes too long to compile. Here summarizes it's compilation time in different settings (dashboard [link](https://hud.pytorch.org/benchmark/compilers?startTime=Fri%2C%2008%20Mar%202024%2019%3A10%3A58%20GMT&stopTime=Fri%2C%2015%20Mar%202024%2018%3A10%3A58%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&lBranch=main&lCommit=660ec3d38d9d1c8567471ae7fe5b40ae7c6d7438&rBranch=main&rCommit=96ed37ac13366cc9a7e6645b8955061d0a14f80b) ):
- default: 223s
- cudagraphs: 1669s
- inductor_max_autotune: 1845s
- cudagraphs_freezing: 549s
- inductor_with_cudagraphs_freezing_autotune: 770s

I've seen timeout in both cudagraphs and inductor_max_autotune settings. Max autotune do increase compilation time but I think the main issue is not max autotune here.

### Error logs

..

### Minified repro

..

### Versions

..

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @oulgen @jamesjwu @aorenste @laithsakka @bdhirsh

**Comment by shunting314** [comment]
cc @anijain2305

**Comment by anijain2305** [comment]
This should be fixed now. We had a recent regression fixed by this revert - https://github.com/pytorch/pytorch/pull/121864

**Comment by shunting314** [comment]
@anijain2305  a update here. The issue still exists.

In the latest dashboard run for inference [link](https://hud.pytorch.org/benchmark/compilers?startTime=Fri%2C%2022%20Mar%202024%2021%3A54%3A51%20GMT&stopTime=Fri%2C%2029%20Mar%202024%2021%3A54%3A51%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&lBranch=main&lCommit=8c8e4e31f2ddd8e59de18ac733c0c205c23d14ad&rBranch=main&rCommit=8a209344c9900678dcf55d75783338f161341ccb)

hf_T5_generate fail in cudagraphs and cudagraphs_freezing setting due to timeout.

**Comment by anijain2305** [comment]
Seems like there are recompilations. 

![image](https://github.com/pytorch/pytorch/assets/13822661/498bc410-b08f-4dae-bc7d-a908e132324f)

**Comment by anijain2305** [comment]
I am seeing excessive recompilations here. Definitely something bad. I remember seeing similar pattern in user empath day 

https://gist.github.com/anijain2305/4e2639684bbc13d28ef6de1fb5efc2b4

Turning high priority on this as this one is easier to repro then User empathy day.

**Comment by ezyang** [comment]
If someone wants to help, try running the model with TORCH_TRACE and post the tlparse

**Comment by anijain2305** [comment]
@ezyang These are the logs -  https://www.internalfb.com/intern/paste/P1452924428/

The first issue here was that we were not iniling in built nn modules. For some reason, the original nn module dies and it deletes the cache entry. compile_id keeps on moving, and we see cases like [20/17]. 

After I inline the inbuilt nn module, I am seeing 8 recompilations. And these are due to automatic dynamic shapes not kicking in. Maybe the original nn module going out of scope is causing issues there as well.

**Comment by anijain2305** [comment]
Ok, I am able to repro the failure 

~~~
import torch


@torch.compile(backend="eager")
def fn(x, y):
    return x * y


for i in range(1, 10):
    x = torch.randn(4, i)

    # create a view for i > 1
    if i == 1:
        x1 = x
    else:
        x1 = x[:, 0:1]

    y = torch.randn(4, 1)
    print(x1.shape, y.shape)
    fn(x1, y)

~~~

This recompiles always. Creating a new issue as well to track this.

**Comment by anijain2305** [comment]
With `inlining_inbuilt_nn_modules = True`, there is only 1 recompile

~~~
V0725 13:17:53.875000 3968737 torch/_dynamo/guards.py:2688] [9/1] [__recompiles] Recompiling function forward in /home/anijain/.conda/envs/pytorch-3.11/lib/python3.11/site-packages/transformers/models/t5/modeling_t5.py:1647
V0725 13:17:53.875000 3968737 torch/_dynamo/guards.py:2688] [9/1] [__recompiles]     triggered by the following guard failure(s):
V0725 13:17:53.875000 3968737 torch/_dynamo/guards.py:2688] [9/1] [__recompiles]     - 9/0: ___check_obj_id(L['past_key_values'], 8822752)
V0725 13:17:58.806000 3968737 torch/_dynamo/guards.py:2688] [9/2] [__recompiles] Recompiling function forward in /home/anijain/.conda/envs/pytorch-3.11/lib/python3.11/site-packages/transformers/models/t5/modeling_t5.py:1647
V0725 13:17:58.806000 3968737 torch/_dynamo/guards.py:2688] [9/2] [__recompiles]     triggered by the following guard failure(s):
V0725 13:17:58.806000 3968737 torch/_dynamo/guards.py:2688] [9/2] [__recompiles]     - 9/1: tensor 'L['past_key_values'][0][0]' stride mismatch at index 0. expected 512, actual 1024
V0725 13:17:58.806000 3968737 torch/_dynamo/guards.py:2688] [9/2] [__recompiles]     - 9/0: ___check_obj_id(L['past_key_values'], 8822752)
pass
~~~

So, this should be fixed by https://github.com/pytorch/pytorch/pull/131275
