### ISSUE TITLE
[torch.export] TypeError: import_nn_module_stack() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by siahuat0727** [pytorch/pytorch#126063]
### 🐛 Describe the bug

Hi,

I encountered a failure with torch.export.load (even immediately after using torch.export.save).

I am wondering if this is a bug and if there is a possible workaround for my particular case. The extracted ".pt2" model is attached.

[seg.zip](https://github.com/pytorch/pytorch/files/15293047/seg.zip)

Sorry for not providing a full reproduction of the process right now, as it's a bit complicated. (this model was exported from mmsegmentation with some workarounds to make it `torch.export`-able)
 

If the error message and the attached model do not provide enough clues, I will try to extract reproducible steps.

Thank you.

```python
patched_model = ...
ep = torch.export.export(patched_model, (args,))
torch.export.save(ep, path)  # success
torch.export.load(path)  # failed. Note that this is immediately after torch.export.save (in the same context)
```

To reproduce with the attached file
```python
import torch
torch.export.load('seg.pt2')
```

Error message
```
Traceback (most recent call last):
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1330, in deserialize_graph
    self.deserialize_node(serialized_node, target)
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1398, in deserialize_node
    fx_node.meta.update(self.deserialize_metadata(serialized_node.metadata))
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1751, in deserialize_metadata
    nn_module_stack = dict(
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1752, in <genexpr>
    import_nn_module_stack(*item.split(","))
TypeError: import_nn_module_stack() takes 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/export/__init__.py", line 299, in load
    return load(
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/__init__.py", line 304, in load
    ep = deserialize(artifact, expected_opset_version)
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1998, in deserialize
    ExportedProgramDeserializer(expected_opset_version)
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1828, in deserialize
    GraphModuleDeserializer()
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1502, in deserialize
    self.deserialize_graph(serialized_graph_module.graph)
  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/_export/serde/serialize.py", line 1333, in deserialize_graph
    raise SerializeError(f"Failed deserializing node {serialized_node}") from e
torch._export.serde.serialize.SerializeError: Failed deserializing node Node(target='torch.ops.aten.convolution.default', inputs=[NamedArgument(name='input', arg=Argument(as_tensor=TensorArgument(name='view_14'))), NamedArgument(name='weight', arg=Argument(as_tensor=TensorArgument(name='arg2_1'))), NamedArgument(name='bias', arg=Argument(as_tensor=TensorArgument(name='arg3_1'))), NamedArgument(name='stride', arg=Argument(as_ints=[1, 1])), NamedArgument(name='padding', arg=Argument(as_ints=[0, 0])), NamedArgument(name='dilation', arg=Argument(as_ints=[1, 1])), NamedArgument(name='transposed', arg=Argument(as_bool=False)), NamedArgument(name='output_padding', arg=Argument(as_ints=[0, 0])), NamedArgument(name='groups', arg=Argument(as_int=1))], outputs=[Argument(as_tensor=TensorArgument(name='convolution_2'))], metadata={'stack_trace': '  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/mmdeploy/apis/onnx/export.py", line 124, in wrapper\n    return forward(*arg, **kwargs)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/mmdeploy/codebase/mmseg/models/segmentors/base.py", line 52, in base_segmentor__forward\n    seg_logit = self.predict(inputs, data_samples)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py", line 25, in encoder_decoder__predict\n    x = self.extract_feat(inputs)\n  File "/home/chensf/git/mmdeploy_export_onnx/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 119, in extract_feat\n    x = self.backbone(inputs)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl\n    return forward_call(*args, **kwargs)\n  File "/home/chensf/git/mmdeploy_export_onnx/mmsegmentation/mmseg/models/backbones/mit.py", line 444, in forward\n    x = block(x, hw_shape)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl\n    return forward_call(*args, **kwargs)\n  File "/home/chensf/git/mmdeploy_export_onnx/mmsegmentation/mmseg/models/backbones/mit.py", line 294, in forward\n    x = _inner_forward(x)\n  File "/home/chensf/git/mmdeploy_export_onnx/mmsegmentation/mmseg/models/backbones/mit.py", line 288, in _inner_forward\n    x = self.ffn(self.norm2(x), hw_shape, identity=x)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl\n    return forward_call(*args, **kwargs)\n  File "/home/chensf/git/mmdeploy_export_onnx/mmsegmentation/mmseg/models/backbones/mit.py", line 84, in forward\n    out = self.layers(out)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl\n    return forward_call(*args, **kwargs)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/mmcv/cnn/bricks/wrappers.py", line 58, in forward\n    return super().forward(x)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward\n    return self._conv_forward(input, self.weight, self.bias)\n  File "/home/chensf/miniconda3/envs/open-mmlab-pytorch23/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward\n    return F.conv2d(input, weight, bias, self.stride,\n', 'nn_module_stack': "L__self__,,mmseg.models.segmentors.encoder_decoder.EncoderDecoder;L__forward_____self___backbone,L['forward'].__self__.backbone,mmseg.models.backbones.mit.MixVisionTransformer;L__forward_____self___backbone_layers_0_1_0,L['forward'].__self__.backbone.layers[0][1][0],mmseg.models.backbones.mit.TransformerEncoderLayer;L__forward_____self___backbone_layers_0_1_0_ffn,L['forward'].__self__.backbone.layers[0][1][0].ffn,mmseg.models.backbones.mit.MixFFN;L__forward_____self___backbone_layers_0_1_0_ffn_layers,L['forward'].__self__.backbone.layers[0][1][0].ffn.layers,mmengine.model.base_module.Sequential;L__forward_____self___backbone_layers_0_1_0_ffn_layers_0,getattr(L['forward'].__self__.backbone.layers[0][1][0].ffn.layers, '0'),mmcv.cnn.bricks.wrappers.Conv2d", 'source_fn_stack': 'conv2d_1,torch.conv2d'})
```

### Versions

```
Collecting environment information...
PyTorch version: 2.3.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.19 (default, Mar 20 2024, 19:58:24) 
```

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by siahuat0727** [comment]
[seg.zip](https://github.com/pytorch/pytorch/files/15293055/seg.zip)

**Comment by angelayi** [comment]
I can take a look at this!

**Comment by angelayi** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/122793

**Comment by psycoplankton** [comment]
Hey @siahuat0727. I case you have not resolved the error. You could try importing the APIs you used for quantization and then run the torch.export.load line. 

in my case, the imports were
`from torch.ao.quantization.quantize_pt2e import prepare_pt2e, convert_pt2e
import torch.ao.quantization.quantizer.x86_inductor_quantizer as xiq
from torch.ao.quantization.quantizer.x86_inductor_quantizer import X86InductorQuantizer`
