### ISSUE TITLE
Dynamo complains about number of arguments of autograd.Function

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#133529]
### 🐛 Describe the bug

When executing the code at the bottom, dynamo breaks with

```
torch._dynamo.exc.ArgsMismatchError: too many positional arguments.
  func = 'forward' /Users/vmoens/Library/Application Support/JetBrains/PyCharm2023.3/scratches/scratch_5.py:7, args = [<class 'torch.autograd.function.Function'>, <class 'torch.Tensor'>, <class 'float'>], kwargs = {}
```

Only the second use case fails (when only `x` is passed and eps=1.0 is constant) and only with vmap.

Code:
```python
from torch.autograd import Function
import torch

class _SafeTanh(Function):
    generate_vmap_rule = True

    @staticmethod
    def forward(input, eps):
        output = input.tanh()
        lim = 1.0 - eps
        output = output.clamp(-lim, lim)
        return output

    @staticmethod
    def setup_context(ctx, inputs, output):
        ctx.save_for_backward(output)

    @staticmethod
    def backward(ctx, *grad):
        grad = grad[0]
        (output,) = ctx.saved_tensors
        return (grad * (1 - output.pow(2)), None)

func = _SafeTanh.apply

x = torch.randn((1, 1), requires_grad=True)
eager = lambda x, y: torch.vmap(lambda x: func(x, y))
eager(x, 1.0)
c = torch.compile(eager, fullgraph=True)
y = c(x, 1.0)
eager = torch.vmap(lambda x: func(x, 1.0))
eager(x)
c = torch.compile(eager, fullgraph=True)
y = c(x)

```

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @zou3519 @ydwu4 @bdhirsh @Chillee @anijain2305 

### Versions

nightly

**Comment by zou3519** [comment]
I think this is a duplicate of https://github.com/pytorch/pytorch/issues/129845 (@yanboliang)

**Comment by vmoens** [comment]
I can't reproduce this error so I assume it is fixed, closing

**Comment by Birch-san** [comment]
@vmoens this is still a problem in torch 2.5.0.

with an autograd Function like this:

```python
class HalfRopeInPlace(torch.autograd.Function):
    @staticmethod
    def forward(t: Tensor, freqs_cis: Tensor, conj: bool):
        _halfrope_inplace(t, freqs_cis, conj)
        return t

    @staticmethod
    def setup_context(ctx, inputs, output):
        _, freqs_cis, conj = inputs
        ctx.save_for_backward(freqs_cis)
        ctx.conj = conj

    @staticmethod
    def backward(ctx, grad_output):
        (freqs_cis,) = ctx.saved_tensors
        _halfrope_inplace(grad_output, freqs_cis, not ctx.conj)
        return grad_output, None, None
```

invoked like so, in the bowels of a model which is under `torch.compile(dynamic=False, fullgraph=True)`:

```python
HalfRopeInPlace.apply(qk.unflatten(-1, ((-1, 2))), rotations, False)
```

I receive this error:

```
too many positional arguments.
  func = 'forward' rope.py:223, args = [<class 'torch.autograd.function.Function'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'bool'>], kwargs = {}

File "mycoolfile.py", line 560, in forward
    HalfRopeInPlace.apply(qk.unflatten(-1, ((-1, 2))), rotations, False)
```

probably what's happened is that my `HalfRopeInPlace.apply()` got fused into the flex_attention that occurs after it, and hence got caught in its vmap. there's no explicit vmaps in my own code.

I was able to make the error go away by making my `forward` function stupider:

```python
class HalfRopeInPlace(torch.autograd.Function):
    @staticmethod
    def forward(*args):
        *_, t, freqs_cis, conj = args
        _halfrope_inplace(t, freqs_cis, conj)
        return t
```

but basically _something_ is invoking `HalfRopeInPlace::forward` as though it's a class method, binding an unwanted first arg `<class 'torch.autograd.function.Function'>`. despite the function's actually being static.

**Comment by vmoens** [comment]
Can you try with the nightlies perhaps (v2.6 onward)?
I tried to rewrite your example and it runs ok with PT built from source, but breaks with 2.5.1

```python
import torch
from torch import Tensor

def _halfrope_inplace(*args):
    ...

class HalfRopeInPlace(torch.autograd.Function):
    @staticmethod
    def forward(t: Tensor, freqs_cis: Tensor, conj: bool):
        _halfrope_inplace(t, freqs_cis, conj)
        return t

    @staticmethod
    def setup_context(ctx, inputs, output):
        _, freqs_cis, conj = inputs
        ctx.save_for_backward(freqs_cis)
        ctx.conj = conj

    @staticmethod
    def backward(ctx, grad_output):
        (freqs_cis,) = ctx.saved_tensors
        _halfrope_inplace(grad_output, freqs_cis, not ctx.conj)
        return grad_output, None, None

t = torch.randn(3, 4)
rotations = torch.randn(())

@torch.compile(fullgraph=True)
def func(t, rotations):
    return HalfRopeInPlace.apply(t, rotations, False)

func(t, rotations)
```
