### ISSUE TITLE
Inline of strided conv cause continuous recompilations with torch 2.4

### ISSUE THREAD

**Issue by Giuseppe5** [pytorch/pytorch#135636]
### 🐛 Describe the bug

When trying to compile a strided convolution with torch 2.4+, if the forward pass of the NN module is inlined, every forward pass will cause recompilation and consequently terrible performance. This happens when compiling with `dynamic=True`.

Although the default behaviour is not to inline forward pass of NN module, using a class that inherits from Conv2d seems to supersede that behaviour (check repro below).

This problem doesn't show with torch 2.3, or when `dynamic` is not set, or when executing on cpu, or with a non-strided convolution.

### Error logs
```bash
V0911 00:22:37.633000 139825679033536 torch/_dynamo/guards.py:2611] [0/1] [__recompiles] Recompiling function forward in repro.py:13
V0911 00:22:37.633000 139825679033536 torch/_dynamo/guards.py:2611] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0911 00:22:37.633000 139825679033536 torch/_dynamo/guards.py:2611] [0/1] [__recompiles]     - name 'FloatTrueDiv' is not defined
```

### Minified repro

Run as:
```bash
TORCH_LOGS="recompiles" python repro.py"
```

repro.py:

```python
import torch

class NewConv2d(torch.nn.Conv2d):
    def forward(self, x):
        # This would be more complicated than this
        return super().forward(x)

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = NewConv2d(3, 16, 1, stride=2)

    def forward(self, x):
        return self.conv(x)


inp = torch.randn(1, 3, 224, 224, device='cuda')
model = Model()

model.eval()
model.cuda()
compiled_model = torch.compile(model, fullgraph=True, dynamic=True)
with torch.no_grad():
    compiled_model(torch.randn(1, 3, 224, 224, device='cuda'))
    compiled_model(torch.randn(1, 3, 224, 224, device='cuda'))


```

### Versions

Relevant packages:

torch==2.4.0+cu124

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

**Comment by xmfan** [comment]
This is fixed on nightly already, it might be also be in latest stable 2.4.1.
On 2.4.0, could you try `torch._dynamo.inline_inbuilt_nn_modules = True`?

**Comment by Giuseppe5** [comment]
Thanks for letting me know, I thought I had tried already on 2.4.1 and it was still failing but I will double check. 

Adding 'torch._dynamo.inline_inbuilt_nn_modules = True' makes everything fail even without creating a new Conv2d class unfortunately.

I'll try again on 2.4.1 but if it is going to be fixed on the next release, I am happy for this issue to be closed.

**Comment by xmfan** [comment]
`torch._dynamo.inline_inbuilt_nn_modules` might still be default off in 2.4.1. The repro worked for me on the nightly, if you'd like to verify: https://pytorch.org/get-started/locally/
<img width="865" alt="image" src="https://github.com/user-attachments/assets/f6208ad5-b5e6-45ae-9904-98e956f241f0">

Feel free to reopen if nightly/2.5. don't work
