### ISSUE TITLE
compilation of rrelu_with_noise with bfloat16 input does not capture noise mutation

### ISSUE THREAD

**Issue by IvanKobzarev** [pytorch/pytorch#136784]
### 🐛 Describe the bug

compilation of rrelu_with_noise with bfloat16 input does not capture noise mutation

### Minified repro

```
    def test_rrelu_noise_mutation(self):
        def fn(x):
            noise = torch.ones_like(x)
            result = torch._C._nn.rrelu_with_noise(x, noise, 0.2, 0.8, True)
            return result, noise

        x = -torch.abs(torch.randn(4, 4, dtype=torch.bfloat16, requires_grad=True))

        ref_y, ref_noise = fn(x)
        self.assertTrue(torch.all(ref_noise < torch.ones_like(ref_noise)).item())

        comp_y, comp_noise = torch.compile(fn, backend="inductor", fullgraph=True)(x)
        self.assertTrue(torch.all(comp_noise < torch.ones_like(comp_noise)).item())
```

### Versions

main Sep 26 2024

cc @ezyang @chauhang @penguinwu @zou3519 @bdhirsh @yf225

**Comment by zou3519** [comment]
@IvanKobzarev is this fixed now?

**Comment by IvanKobzarev** [comment]
> @IvanKobzarev is this fixed now?

No, this is not fixed. I do not know if changing the schema of rrelu_with_noise fixes it(adding noise(!))

I tried to do it, but there were many torchgen failures to fix.

**Comment by bdhirsh** [comment]
If we really want to fix `rrelu_with_noise`, we'll need to either:

(1) create two new ops, similar to the batch_norm fix that @janeyx99 and @andrewor14, to handle the two cases where `rrelu_with_noise` does or not mutate the noise argument. We'd probably have to deal with the same FC/BC issues

(1) just mark the noise argument mutable, like Ivan said - and don't make any new ops, avoiding the FC/BC issues. The downside is that this would cause compile/export to pessimistically think that `rrelu_with_noise` always mutates its noise argument, which could result in extra `copy_()` nodes in the graph (seems bad).

**Comment by bdhirsh** [comment]
Comments from meeting:

`rrelu_with_noise` is a private API. `torch.rrelu(x, ..)` is public though, and calls `rrelu_with_noise(x, noise=torch.empty_like(x), ...).

Given that, we can still be silently wrong on call to `torch.rrelu()` under compile/export.

But `noise` can never be a graph input. Maybe it's more ok to treat `rrelu_with_noise` as "always mutating", given that? (backend can optimize away the extra clone).

**Comment by intellinjun** [comment]
@bdhirsh  @IvanKobzarev Do we have a solution for that yet?

**Comment by bdhirsh** [comment]
@IvanKobzarev is workign on it here https://github.com/pytorch/pytorch/pull/136629

**Comment by IvanKobzarev** [comment]
Hi @intellinjun , if you desperately need the fix for compilation, you can try the patch and it should fix the compilation and capture noise mutation, technically it should work for you. CI has some failures:
 https://github.com/pytorch/pytorch/pull/136629

Though this fix is hacky, introducing another op with different schema.

The proper fix will be without introducing another op, but it needs some changes in autogen. I am working on it.

**Comment by intellinjun** [comment]
> Hi @intellinjun , if you desperately need the fix for compilation, you can try the patch and it should fix the compilation and capture noise mutation. Technically it should work for you (cI has some guard failures): #136629
> 
> Though this fix is hacky, introducing another op with different schema.
> 
> The proper fix will be without introducing another op, but it needs some changes in autogen. I am working on it.

Ok, I will try it later, thanks for your help!

**Comment by IvanKobzarev** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/141867

@intellinjun
