### ISSUE TITLE
conda 3.6 installation currently broken due to 3.6.1 ABI breakage

### ISSUE THREAD

**Issue by alexjc** [pytorch/pytorch#1383]
I'm posting here so others with this problem find it. But as I mentioned on Twitter, I don't think this is your bug to fix. Likely 3.6.2 must be pushed out or 3.6.1 marked invalid in conda.

Following these minimal install instructions:
```
conda create -p pyvenv python=3.6
conda activate ./pyvenv
conda install pytorch torchvision -c soumith
```

Conda downgrades 3.6.1 to 3.6.0 but it still fails. Then just trying to import torchvision gives this callstack:

```
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/pyvenv/lib/python3.6/site-packages/torchvision-0.1.8-py3.6.egg/torchvision/__init__.py", line 2, in <module>
  File "/tmp/pyvenv/lib/python3.6/site-packages/torchvision-0.1.8-py3.6.egg/torchvision/datasets/__init__.py", line 1, in <module>
  File "/tmp/pyvenv/lib/python3.6/site-packages/torchvision-0.1.8-py3.6.egg/torchvision/datasets/lsun.py", line 2, in <module>
  File "/tmp/pyvenv/lib/python3.6/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: /tmp/pyvenv/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PySlice_Unpack
>>> quit()
```

UPDATE: maybe the problem is occurring now because they did mark 3.6.1 as incompatible in conda and you're building against it?

**Comment by AjayTalati** [comment]
Same problem here :-1:

**Comment by AjayTalati** [comment]
Definitely a conda 3.6 thing, fresh install into a 3.5 environment works perfectly :+1:

**Comment by soumith** [comment]
new binaries on the way. building for 3.6, and then 3.6.0 and 3.6.1 separately.
will finish building in a few hours.

**Comment by AjayTalati** [comment]
Thank you :+1:

**Comment by soumith** [comment]
this is now fixed. Latest 0.1.12 binaries will not have this downgrade issue. They're available on conda now.

**Comment by davidenitti** [comment]
still having this issue with:
pytorch:     0.1.12-py360_2cu75 soumith
torchvision: 0.1.8-py36_2       soumith

**Comment by soumith** [comment]
@davidenitti is your issue coming from pytorch, or Pillow (as others reported). Try doing: `conda uninstall -y pillow; conda install -y pillow`

**Comment by soumith** [comment]
the pillow version to be installed should be atleast 4.1.1 according to the pillow devs, who fixed the issue in their release.

**Comment by davidenitti** [comment]
thank you for the fast reply.
uninstall/install of pillow does not work
"coda install pillow" installs the version 4.1.0-py36_0
is there a way to install 4.1.1 with conda?

**Comment by soumith** [comment]
does this work: `pip install pillow==4.1.1`

**Comment by davidenitti** [comment]
it works, but it does not solve the problem.
the issue is that removing pillow ("conda uninstall -y pillow") removes also torchvision.
If I install torchvision again it will install and use pillow 4.1.0 even if I installed pillow==4.1.1 with pip

**Comment by soumith** [comment]
```
conda uninstall -y torchvision pillow
pip install pillow=4.1.1 torchvision
```

**Comment by davidenitti** [comment]
solved! thanks
