### ISSUE TITLE
torch.onnx.export with torchaudio Spectrogram doesn't support dynamic batch size

### ISSUE THREAD

**Issue by sammlapp** [pytorch/pytorch#148687]
### 🐛 Describe the bug

It is now possible to include torchaudio.transforms.Spectrogram in a model and successfully export the model to an onnx program. However, when loading the model I cannot use a batch size besides the one used in the saved model. I've tried several approaches. Here is an example based on https://github.com/pytorch/pytorch/issues/113067#issuecomment-2702153314 

### create and save onnx model
```python
import torchvision
import torchaudio
import torch

# define a pytorch model
class SpecMaker(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.transforms = torchvision.transforms.Compose(
            [
                torchaudio.transforms.Spectrogram(
                    n_fft=512,
                    win_length=512,
                    hop_length=256,
                ),
                torchaudio.transforms.AmplitudeToDB(top_db=100),
            ]
        )

    def forward(self, x):
        return self.transforms(x)


specmodel = SpecMaker()
input = torch.rand(32000 * 10)
spec = specmodel(input)
input_batch = torch.stack([input, input])
spec_batch = specmodel(input_batch) # just testing pytorch model works as expected

assert spec_batch.shape== torch.Size([2, 257, 1251])

onnx_program = torch.onnx.export(
    specmodel,
    (input_batch,),
    dynamic_shapes=[{0: "dim_x"}],
    report=True,
    dynamo=True,
)

onnx_program.save("specmodel2.onnx")
```

### load onnx model and attempt to run with different batch size
```python
import onnx, onnxruntime
import torch

onnx_model = onnx.load("specmodel2.onnx")
onnx.checker.check_model(onnx_model)
input = torch.rand(32000 * 10)
input = torch.tensor((opso.birds).trim(0, 10).samples)

# what if its batched?
input_batched = torch.stack([input, input, input]) #works if batch has 2 samples, fails with 3 samples

EP_list = ["CUDAExecutionProvider", "CPUExecutionProvider"]

ort_session = onnxruntime.InferenceSession("specmodel2.onnx", providers=EP_list)


def to_numpy(tensor):
    return (
        tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
    )


# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input_batched)}
ort_outs = ort_session.run(None, ort_inputs)
```

Error:
```
---------------------------------------------------------------------------
RuntimeException                          Traceback (most recent call last)
Cell In[8], [line 14](vscode-notebook-cell:?execution_count=8&line=14)
     [12](vscode-notebook-cell:?execution_count=8&line=12) # compute ONNX Runtime output prediction
     [13](vscode-notebook-cell:?execution_count=8&line=13) ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input_batched)}
---> [14](vscode-notebook-cell:?execution_count=8&line=14) ort_outs = ort_session.run(None, ort_inputs)

File ~/miniconda3/envs/bmz_dev/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:266, in Session.run(self, output_names, input_feed, run_options)
    [264](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/bmz_dev/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:264)     output_names = [output.name for output in self._outputs_meta]
    [265](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/bmz_dev/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:265) try:
--> [266](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/bmz_dev/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:266)     return self._sess.run(output_names, input_feed, run_options)
    [267](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/bmz_dev/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:267) except C.EPFail as err:
    [268](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/bmz_dev/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:268)     if self._enable_fallback:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'node_Reshape_5' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:47 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, onnxruntime::TensorShapeVector &, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{3,320000}, requested shape:{1,2,320000}
```

Am I loading and using the onnx model incorrectly, or is this an issue with dynamic shape exporting when the model contains stft? (There are several related issues including https://github.com/pytorch/pytorch/issues/113067, https://github.com/pytorch/pytorch/issues/139246, and this PR https://github.com/pytorch/pytorch/pull/145080) 

### Versions

collect_env.py.1                                         100%[================================================================================================================================>]  23.78K  --.-KB/s    in 0.004s  

2025-03-06 12:54:42 (6.31 MB/s) - ‘collect_env.py.1’ saved [24353/24353]

zsh: command not found: #
Collecting environment information...
PyTorch version: 2.7.0.dev20250301
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.14 (main, May  6 2024, 14:42:37) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-15.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.17.0
[pip3] onnxruntime==1.20.1
[pip3] onnxscript==0.2.1
[pip3] optree==0.14.0
[pip3] pytorch-lightning==2.4.0
[pip3] torch==2.7.0.dev20250301
[pip3] torch-audiomentations==0.11.0
[pip3] torch_pitch_shift==1.2.5
[pip3] torchaudio==2.6.0.dev20250301
[pip3] torchmetrics==1.2.0
[pip3] torchview==0.2.6
[pip3] torchvision==0.22.0.dev20250301
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.14.0                   pypi_0    pypi
[conda] pytorch-lightning         2.4.0                    pypi_0    pypi
[conda] torch                     2.7.0.dev20250301          pypi_0    pypi
[conda] torch-audiomentations     0.11.0                   pypi_0    pypi
[conda] torch-pitch-shift         1.2.5                    pypi_0    pypi
[conda] torchaudio                2.6.0.dev20250301          pypi_0    pypi
[conda] torchmetrics              1.2.0                    pypi_0    pypi
[conda] torchview                 0.2.6                    pypi_0    pypi
[conda] torchvision               0.22.0.dev20250301          pypi_0    pypi

**Comment by titaiwangms** [comment]
Seems like a bug in torch.export: https://github.com/pytorch/pytorch/issues/148702

**Comment by titaiwangms** [comment]
@sammlapp This should be fixed. Can you try it again?

**Comment by sammlapp** [comment]
@titaiwangms I installed the nightly pytorch build, ran the same code as above, and still get an error (again, only if the batch size changes)


```
RuntimeException                          Traceback (most recent call last)
Cell In[11], [line 25](vscode-notebook-cell:?execution_count=11&line=25)
     [23](vscode-notebook-cell:?execution_count=11&line=23) # compute ONNX Runtime output prediction
     [24](vscode-notebook-cell:?execution_count=11&line=24) ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input_batched)}
---> [25](vscode-notebook-cell:?execution_count=11&line=25) ort_outs = ort_session.run(None, ort_inputs)

File ~/miniconda3/envs/opso_dev/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:220, in Session.run(self, output_names, input_feed, run_options)
    [218](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/opso_dev/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:218)     output_names = [output.name for output in self._outputs_meta]
    [219](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/opso_dev/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:219) try:
--> [220](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/opso_dev/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:220)     return self._sess.run(output_names, input_feed, run_options)
    [221](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/opso_dev/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:221) except C.EPFail as err:
    [222](https://file+.vscode-resource.vscode-cdn.net/Users/SML161/nb_opso/ml/save_model/~/miniconda3/envs/opso_dev/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:222)     if self._enable_fallback:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'node_Reshape_5' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:47 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, onnxruntime::TensorShapeVector &, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{3,320000}, requested shape:{1,2,320000}
```

**Comment by titaiwangms** [comment]
From my computer, I can't repro anymore (build from source). Maybe try it again tomorrow. Note that your inference inputs and tracing/exporting are slightly different:
```python
input = torch.tensor((opso.birds).trim(0, 10).samples)

```

**Comment by sammlapp** [comment]
Excellent, it's working! I think I just tried the nightly build too soon. 

I can use different batch sizes with the saved onnx model. 

I do get a warning, not sure if this is worth worrying about:

```
.../lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69): UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CoreMLExecutionProvider, AzureExecutionProvider, CPUExecutionProvider'
```

I think you can close this issue, thanks for the assistance!

**Comment by vadimkantorov** [comment]
@justinchuby Has this shipped in 2.7.0? :)

**Comment by justinchuby** [comment]
It should, can you try the latest onnxscript?

**Comment by justinchuby** [comment]
Sorry I thought it was about stft. No the dynamic batch size was fixed in torch 2.7.

**Comment by vadimkantorov** [comment]
> No the dynamic batch size was fixed in torch 2.7.

Hope it means a "yes, it was fixed" :)

**Comment by sammlapp** [comment]
@titaiwangms should this also work with dynamic "length", eg size of input to stft or dimension `1`, as well as dynamic batch size? see https://github.com/pytorch/pytorch/issues/112844#issuecomment-2883900227

**Comment by titaiwangms** [comment]
Yes, it should. The issue from the comment is just like what @justinchuby suggested that the symbolic function (aten.unfold's ONNX translation) does not currently support dynamism.

**Comment by sammlapp** [comment]
Is there an open issue for that?

**Comment by justinchuby** [comment]
- https://github.com/microsoft/onnxscript/issues/2309

**Comment by justinchuby** [comment]
I see. The solution then is to set opset to be 18 for now. @sammlapp
