### ISSUE TITLE
Activation Checkpointing dtype Mismatch in Recomputed Activations Due to Skipped Type Casting in FSDPv2 _pre_forward

### ISSUE THREAD

**Issue by KimbingNg** [pytorch/pytorch#159359]
### Description:​​
When using gradient checkpointing (torch.utils.checkpoint.checkpoint) with FSDPv2, the re-computation of activations during backward pass may produce tensors with mismatched dtypes compared to the original forward pass. 
```
29.162.224.92: [rank30]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
29.162.224.92: [rank30]: tensor at position 9:
29.162.224.92: [rank30]: saved metadata: {'shape': torch.Size([2, 1, 4127, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=6)}
29.162.224.92: [rank30]: recomputed metadata: {'shape': torch.Size([2, 1, 4127, 128]), 'dtype': torch.float32, 'device': device(type='cuda', index=6)}
29.162.224.92: [rank30]: tensor at position 10:
29.162.224.92: [rank30]: saved metadata: {'shape': torch.Size([2, 1, 4127, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=6)}
29.162.224.92: [rank30]: recomputed metadata: {'shape': torch.Size([2, 1, 4127, 128]), 'dtype': torch.float32, 'device': device(type='cuda', index=6)}
29.162.224.92: [rank30]: tensor at position 11:
29.162.224.92: [rank30]: saved metadata: {'shape': torch.Size([2, 1, 4127, 128]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=6)}
29.162.224.92: [rank30]: recomputed metadata: {'shape': torch.Size([2, 1, 4127, 128]), 'dtype': torch.float32, 'device': device(type='cuda', index=6)}
```

This occurs because the _pre_forward method ([code](https://github.com/pytorch/pytorch/blob/9d32aa9789fc0ef0cad01a788157ecc2121db810/torch/distributed/fsdp/_fully_shard/_fsdp_state.py#L235)) skips type casting logic when the module’s _training_state is set to TrainingState.PRE_BACKWARD, which is active during backward pass re-computation triggered by gradient checkpointing.

```python
    def _pre_forward(
        self, module: nn.Module, args: Tuple[Any, ...], kwargs: Dict[str, Any]
    ) -> Tuple[Tuple[Any, ...], Dict[str, Any]]:
        # When composing with module-hook-based activation checkpointing, the
        # the pre-backward hook is responsible for the unshard
        if self._training_state == TrainingState.PRE_BACKWARD:
            return args, kwargs
        self._training_state = TrainingState.FORWARD
        args, kwargs = self._root_pre_forward(module, args, kwargs)
        if self._mp_policy.cast_forward_inputs and self._mp_policy.param_dtype:
            with torch.profiler.record_function("FSDP::cast_forward_inputs"):
                cast_fn = functools.partial(
                    _cast_fp_tensor, self._mp_policy.param_dtype
                )
                args, kwargs = tree_map(cast_fn, args), tree_map(cast_fn, kwargs)
        if self._fsdp_param_group:
            args, kwargs = self._fsdp_param_group.pre_forward(module, args, kwargs)
        for fsdp_state in self._states_to_forward_prefetch:
            if (target_param_group := fsdp_state._fsdp_param_group) is not None:
                FSDPParamGroup._prefetch_unshard(target_param_group, "forward")
        return args, kwargs
```

### Versions

pytorch 2.6

cc @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @pragupta @soulitzer

**Comment by KimbingNg** [comment]
@weifengpy Here is the minimal reproducible script: 
```python
# torchrun --nproc_per_node=8 ac_bug.py
import loguru
import torch
from torch import distributed as dist
from torch import nn
from torch.distributed.fsdp import MixedPrecisionPolicy
from torch.distributed.fsdp._fully_shard import fully_shard
from torch.utils.checkpoint import checkpoint
dist.init_process_group()
torch.cuda.set_device(dist.get_node_local_rank())


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear1 = nn.Linear(1, 1)
        self.linear2 = nn.Linear(1, 1)

    def forward(self, x):
        x = x.float()
        return self.linear2(checkpoint(self.linear1, x, use_reentrant=False)).sum()  # x should be automatically cast to bf16 in linear1 recomutation since linear1 is an FSDP module

fsdp_kwargs = {'param_dtype': torch.bfloat16, 'reduce_dtype': torch.bfloat16}
model = Model()
fully_shard(model.linear1, mp_policy=MixedPrecisionPolicy(**fsdp_kwargs))
fully_shard(model.linear2, mp_policy=MixedPrecisionPolicy(**fsdp_kwargs))
fully_shard(model, mp_policy=MixedPrecisionPolicy(**fsdp_kwargs))

inp = torch.randn(8, 1).cuda()
model(inp).backward()

```
cc @soulitzer

**Comment by ShaoDingBao** [comment]
Is there a solution to this problem? I'm having a similar issue.

**Comment by KimbingNg** [comment]
@ShaoDingBao This issue is fixed in the latest PyTorch

**Comment by ShaoDingBao** [comment]
> [@ShaoDingBao](https://github.com/ShaoDingBao) This issue is fixed in the latest PyTorch

Which Torch version should I use? I tried running the demo you provided with the 'latest' version 2.11, but I'm still getting an error.

**Comment by thereAreDemonsNearby** [comment]
@ShaoDingBao can you share the way in which you fixed it?

**Comment by ShaoDingBao** [comment]
> [@ShaoDingBao](https://github.com/ShaoDingBao) can you share the way in which you fixed it?

The issue occurs when FSDP and activation checkpointing are used together, because the backward phase triggers forward recomputation. As a temporary workaround, I patched the `_fsdp_state.py` file in my local PyTorch installation, located at `.../torch/distributed/fsdp/_fully_shard/_fsdp_state.py`.

In the original implementation, `_pre_forward()` and `_post_forward()` return early when `self._training_state == TrainingState.PRE_BACKWARD`. Because of that early return, the mixed precision policy logic for `cast_forward_inputs` and `output_dtype` is skipped during activation-checkpointing recomputation.

The fix is to apply the same dtype casting logic in the `PRE_BACKWARD` recomputation path as in the normal forward path:

- In `_pre_forward()`, before returning from the `PRE_BACKWARD` branch, cast input tensors to `param_dtype` when `cast_forward_inputs` and `param_dtype` are configured.
- In `_post_forward()`, before returning from the `PRE_BACKWARD` branch, cast output tensors to `output_dtype` when `output_dtype` is configured.

This makes the dtype behavior during activation-checkpointing forward recomputation consistent with the normal forward pass, and avoids the input/output dtype mismatch I encountered in mixed precision training.

I have not confirmed whether this has already been fixed in the latest PyTorch release, but this local patch resolves my issue.

[_fsdp_state_old.py](https://github.com/user-attachments/files/27201598/_fsdp_state_old.py)
[_fsdp_state.py](https://github.com/user-attachments/files/27201599/_fsdp_state.py)

**Comment by weifengpy** [comment]
hi @ShaoDingBao , thanks for sharing your solution. I added you as co-author in https://github.com/pytorch/pytorch/pull/182580 

Are you interested in sign easyCLA https://github.com/pytorch/pytorch/pull/182580#issuecomment-4385241040 to I can land the PR?

**Comment by ShaoDingBao** [comment]
> hi [@ShaoDingBao](https://github.com/ShaoDingBao) , thanks for sharing your solution. I added you as co-author in [#182580](https://github.com/pytorch/pytorch/pull/182580)
> 
> Are you interested in sign easyCLA [#182580 (comment)](https://github.com/pytorch/pytorch/pull/182580#issuecomment-4385241040) to I can land the PR?

Done, CLA signed. Thanks for adding me as co-author!
