### ISSUE TITLE
F.conv2d throws C++ side error when shape of weights and input mismatch

### ISSUE THREAD

**Issue by FanShupei** [pytorch/pytorch#16035]
## 🐛 Bug

When the shape of weights is bigger than the shape of input, calling `F.conv2d` throws an error in ATen. 

## To Reproduce

Install pytorch and run the following code

```
>>> import torch
>>> import torch.nn.functional as F
>>> F.conv2d(torch.ones((1,1,3,3)), torch.ones((1,1,5,3)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at /opt/conda/conda-bld/pytorch-cpu_1544218667092/work/aten/src/TH/THGeneral.cpp:188
>>> F.conv2d(torch.ones((1,1,3,3)), torch.ones((1,1,5,5)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std::exception

```

## Expected behavior

A error indicates that the shapes mismatch. Definitely not "invalid memory size".

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Fedora 29 (Workstation Edition)
GCC version: (GCC) 8.2.1 20181011 (Red Hat 8.2.1-4)
CMake version: version 3.12.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 410.78
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2019.1                      144    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.0.10           py37ha843d7b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.0.2            py37hd81dba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch-cpu               1.0.0               py3.7_cpu_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision-cpu           0.2.1                      py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

**Comment by soumith** [comment]
this is fixed on master, and will be part of the next release.

The cause of this issue is a libmkldnn.so on your machine that is of a different version than what PyTorch expects.

**Comment by slbinilkumar** [comment]
I tried with the master same issue is still there .Can you please give the correct branch ,that i can try with

**Comment by FanShupei** [comment]
I haven't tested the master so I don't know whether it's fixed there.
I guess the reason is that the shape of result tensor may be negative and PyTorch fails to check it.

In case 1, input size is `(3, 3)` and kernel size is `(5, 3)`, the calculated result's size is `(-1, 1)`. The element number is `-1` so the allocator complains invalid size.

In case 2, input size is `(3, 3)` and kernel size is `(5, 5)`, the result's size is `(-1, -1)`. The element number is `1` so the allocator is happy, the error is from other part.

This explains why the error message in two cases are so different. This seems nothing related to mkldnn. Maybe reopen?

**Comment by VinACE** [comment]
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 410.48
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] torch==1.0.0
[pip] torchaudio==0.2
[pip] torchfile==0.1.0
[pip] torchvision==0.2.1
[pip] warpctc-pytorch==0.1
[conda] blas                      1.0                         mkl  
[conda] cuda100                   1.0                           0    pytorch
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.0.0           py3.6_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch
[conda] torchaudio                0.2                      pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.2.1                    py36_1    pytorch
[conda] warpctc-pytorch           0.1                      pypi_0    pypi

**Comment by VinACE** [comment]
# python transcribe.py --model-path librispeech_pretrained.pth --audio-path OSR_
us_000_0010_8k.wav --cuda
Traceback (most recent call last):
  File "transcribe.py", line 88, in <module>
    out = model(Variable(spect, volatile=True))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/deepspeech.pytorch-1.2/model.py", line 172, in forward
    x = self.conv(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
root@dl-tf-gpu:/workspace/deepspeech.pytorch-1.2#

Passed the --cuda options and getting the above error.
