### ISSUE TITLE
Multi-GPU K80s

### ISSUE THREAD

**Issue by davidmascharka** [pytorch/pytorch#1637]
I'm having trouble getting multi-gpu via `DataParallel` across two Tesla K80 GPUs. The code I'm using is a modification of the MNIST example:

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
from data_parallel import DataParallel

train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=256, shuffle=True, num_workers=2, pin_memory=True)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2(x), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x)

model = DataParallel(Net())
model.cuda()

optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
criterion = nn.NLLLoss().cuda()

model.train()
for batch_idx, (data, target) in enumerate(train_loader):
    input_var = Variable(data.cuda())
    target_var = Variable(target.cuda())

    print('Getting model output')
    output = model(input_var)
    print('Got model output')

    loss = criterion(output, target_var)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print('Finished')
```

This doesn't throw an error, but hangs after it prints "Getting model output" and never returns. I traced this down to the `parallel_apply` spawning threads that then never finish. The line that hangs is [here](https://github.com/pytorch/pytorch/blob/e50a1f19b3dc735f0710929b97b0af384aafe09b/torch/nn/parallel/parallel_apply.py#L25) where the threads are spawned using both GPU 0 and GPU 1, but never finish.

This is only a problem when `CUDA_VISIBLE_DEVICES=0,1` as both GPU0 and GPU1 work perfectly well individually.

Before running this, `nvidia-smi` shows

```
+------------------------------------------------------+
| NVIDIA-SMI 352.68     Driver Version: 352.68         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:06:00.0     Off |                    0 |
| N/A   40C    P0    57W / 149W |     55MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:07:00.0     Off |                    0 |
| N/A   35C    P0    76W / 149W |     55MiB / 11519MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

after running (while it hangs), `nvidia-smi` gives

```
+------------------------------------------------------+
| NVIDIA-SMI 352.68     Driver Version: 352.68         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:06:00.0     Off |                    0 |
| N/A   42C    P0    69W / 149W |    251MiB / 11519MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:07:00.0     Off |                    0 |
| N/A   36C    P0    90W / 149W |    249MiB / 11519MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      4785    C   python                                         194MiB |
|    1      4785    C   python                                         192MiB |
+-----------------------------------------------------------------------------+
```

and `top` shows the main python process and the two python subprocesses. Wondering if this could be something similar to #554.

Using [this](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py) TensorFlow example, I get linear speedup using multiple GPUs as I change `CUDA_VISIBLE_DEVICES` so multiple K80s should certainly be viable.

**Comment by apaszke** [comment]
It seems that you have a fully utilized GPU even before you run the script? I suspect it might be a NCCL problem. Can you try to kill all Python processes, make sure that you have 0% GPU utilization, and run the script again?

**Comment by davidmascharka** [comment]
It was my understanding that running `nvidia-smi` could cause the volatile usage to be nonzero. Anyway, I was able to get it to zero and run again.

Before:
```
Mon Jun  5 08:44:00 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
| N/A   41C    P0    57W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:07:00.0     Off |                    0 |
| N/A   36C    P0    85W / 149W |      0MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

It hangs on the same line, then `nvidia-smi` shows:

```
Mon Jun  5 08:45:01 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
| N/A   41C    P0    69W / 149W |    195MiB / 11439MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:07:00.0     Off |                    0 |
| N/A   36C    P0    90W / 149W |    195MiB / 11439MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0    107462    C   python3                                        193MiB |
|    1    107462    C   python3                                        193MiB |
+-----------------------------------------------------------------------------+
```

**Comment by zhanghang1989** [comment]
Do you have memory usage issue on K80? It seems allocating twice the gpu memory on K80 than regular gpu like Titan X.

**Comment by davidmascharka** [comment]
@zhanghang1989 I haven't noticed anything but I haven't worked with very large models or minibatch sizes in Pytorch. Most of what I've been doing has been below 4-6 GB of GPU memory, so it hasn't been anywhere close to being a problem even when training multiple models on the same GPU.

**Comment by cheekala** [comment]
@davidmascharka were you able to find a solution?? I'm facing the same issue too.

**Comment by davidmascharka** [comment]
@cheekala I've not found a solution yet. I've been using just the one GPU. Certainly not ideal but it's tolerable for now.

**Comment by dominic-rossi** [comment]
@davidmascharka I was able to get your code to run on a machine with multiple GPUs simply by changing:
```
from data_parallel import DataParallel
...
model = DataParallel(Net())
```
to:
`model = nn.DataParallel(Net())`

All of the following configurations ran to completion:
CUDA_VISIBLE_DEVICES unset (defaults to discovering 4 GPUs on the machine I used)
CUDA_VISIBLE_DEVICES=0,1
CUDA_VISIBLE_DEVICES=0

Perhaps DataParallel has been updated/fixed since this issue was reported?

**Comment by davidmascharka** [comment]
@dominic-rossi the `data_parallel` I import from is the exact file that houses `nn.DataParallel`. I just pulled the 0.2.0 changes and the issue remains.

I'm going to assume your machine does not have 4 K80 GPUs. As far as I can tell, this is specific to either the Tesla architectures as a whole or the K80 GPU specifically, since other people have reportedly been running multi-gpu on GTX cards.

**Comment by dominic-rossi** [comment]
@davidmascharka Correct. I tried the code on a machine with Maxwell Titan X's as well as a machine with a 1070.

**Comment by EgorLakomkin** [comment]
Is there any progress or workaround here? My code hangs and cannot parallelize to 2 K80 :(

**Comment by CraveInfinity** [comment]
I have the same issue here. It hangs when DataParallel is used but each individual K80 GPU work just fine.

**Comment by jgoldfa** [comment]
I have the same issue with two 1080Tis. Also, the same issue with the imagenet example.
Is this an Ubuntu Nvidia driver problem?

**Comment by davidmascharka** [comment]
@jgoldfa I'm not running Ubuntu, so my bet is it's not that particular driver. I'll get access to a machine with multiple 1080Tis in the next few days and I'll try this example there and report whether it works for me.

**Comment by soumith** [comment]
hey everyone. I suggest testing against pytorch-master. I just committed https://github.com/pytorch/pytorch/pull/3028 which may have worked around a deadlock issue with the previous NCCL PyTorch bindings.

**Comment by davidmascharka** [comment]
@soumith as of Commit 403a53382754bcb17e6b818c4eb4272f4a263355 I'm still having this issue on K80s. Sending a kill signal to the script also doesn't actually kill my processes and running `nvidia-smi` shows me `Unknown Error` on the processes on GPU0 and GPU1. I have to go and kill the processes manually to get them to actually die.

**Comment by Mctigger** [comment]
I just want to add that me and SamTse still have a similar problem with 1080TIs: https://discuss.pytorch.org/t/nn-dataparallel-model-cuda-stuck/8085

**Comment by davidmascharka** [comment]
@Mctigger I just ran my program above on a machine with Ubuntu 16.04, CUDA 9, cuDNN 7, and PyTorch 9ef39a50ee16d4944240ac5cfa6489e3dd294c5f on 2 1080Ti GPUs and it worked. Went from about 36 seconds to 17.5 seconds for 10 epochs of MNIST.

**Comment by Mctigger** [comment]
@davidmascharka From source without "conda install -c soumith magma-cuda80 # or magma-cuda75 if CUDA 7.5"?

**Comment by jgoldfa** [comment]
I have two novice questions.
#1 Can the driver be a factor? Should we be stating which driver is used?
#2 Does multi-gpu need to be turned on? ie. sudo nvidia-xconfig --multi-gpu="On"

**Comment by Mctigger** [comment]
@soumith I would like to help fix this, but I do not have any experience with any Pytorch internals. Can you give me instructions how to help/diagnose the problem?

**Comment by soumith** [comment]
@zou3519 can you work with @Mctigger and isolate the issue?
I suspect either a deadlock or that something is being jitted from ptx -> sass.
`perf top -p [pid of the pytorch process]` will give hints on why the thing is just spinning if its a ptx->sass issue.

If it's a deadlock issue, compiling pytorch with `DEBUG=1 python setup.py build develop` and getting gdb stack traces for all threads will help. A nicer way to figure out the deadlock is https://en.wikibooks.org/wiki/Linux_Applications_Debugging_Techniques/Deadlocks

It could also be botched CUDA install where some libraries are from CUDA8 and other libraries are from CUDA7.5 or CUDA9. To debug this, you can enter gdb with the process and run `gdb info shared` which will give the list of loaded shared libs. If some of them have 7.5 and some of them have 8, for example in their version number, that's suspect.

I will be sparsely available for a week. @zou3519 can you co-ordinate with and help @Mctigger isolate the issue?

**Comment by Mctigger** [comment]
So I just tried another clean installation with the current master. 
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64
libcudnn7_7.0.3.11-1+cuda9.0_amd64
Anaconda3-5.0.0.1-Linux-x86_64
```
I installed from source exactly like [here](https://github.com/pytorch/pytorch#from-source), but I skipped this 
```
# Add LAPACK support for the GPU
conda install -c soumith magma-cuda80 # or magma-cuda75 if CUDA 7.5
```
as written here #3040 and #3018.

When using `nn.DataParallel` I still get the same behavior, meaning 100% load, but the program is stuck.
When I try running on a single GPU it works, but calculations are significantly slower (training a network takes double the time).

After I ran `pip uninstall torch` and installed the pytorch binaries with `pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl `.
`nn.DataParallel` still does not work, but now my network trains at the 100% of the expected speed.

**Comment by zou3519** [comment]
@Mctigger I'm working on getting a machine with multiple K80s to replicate the problem (I have a machine with 4 K40s and it isn't running into any problems). Have you tried soumith's debugging suggestions / have you found anything interesting?

**Comment by Mctigger** [comment]
@zou3519 I looked into it, but did not have the time to dive in deeper and since I have zero experience with anything more "low-level" than Java it is hard to see what's important an what not.
If you want I can give you remote access to my machine so you do not have set up one yourself.

**Comment by awaelchli** [comment]
@zou3519 @Mctigger I have the same issue but with the 1080ti. I have four of them in my system. Same behaviour using DataParallel as described above. I think it is not directly related to the K80 card.

**Comment by ngimel** [comment]
@davidmascharka I've ran your script in the beginning of this issues in a docker image built from current upstream with the current dockerfile (cuda 8, cudnn 6.0.21, nccl 2.0.5) on 2 GPUs (1 K80 card) and on 8 GPUs (4 K80 cards), and I did not have any hangs.

**Comment by zou3519** [comment]
I ran the mnist example script on a machine with 2 K80 gpus on pytorch master (with cuda 8, python 3.5, gcc 5.4 on Ubuntu 14.04) and it did not hang. I'll try installing cuda 9 and seeing if that changes anything

**Comment by Mctigger** [comment]
I can still let you remote in my machine, so you can either find out what I did wrong or whether there is a bug. To me it seems like most people so far have issues with 1080TIs. Tell me whether you have time/when so I can provide a fresh install.

**Comment by zou3519** [comment]
@Mctigger that would be great if you don't mind me poking around. Please feel free to direct message me on the pytorch forums https://discuss.pytorch.org/u/richard/ so we can figure out details

**Comment by zou3519** [comment]
Debugging on @Mctigger's machine with 2 1080s, I found the following:

1) `python test/test-nccl.py` fails.
2) Calling ncclBcast in the backend causes a GPU to go into 100% and hang. It returns immediately, though, so DataParallel eventually calls it again on another GPU, causing that GPU to hang as well. The end result is that both GPUs are at 100% utilization after DataParallel calls code to split the input over multiple gpus. 
3) I wondered if this was a problem with the NCCL version. The one that is used by default seems to be 1.3.5. I built pytorch using the system nccl (2.0.5) and re-ran. Now, when ncclBcast is called, GPU usage is at 0% but the entire program hangs (and ncclBcast doesn't return).

Any ideas?

**Comment by ngimel** [comment]
Is CUDA_LAUNCH_BLOCKING set by any chance? It is incompatible with nccl. What's happening in 2 is expected (except the hang part) - nccl kernels have to be submitted to all the devices, so kernel is submitted to the first device, it goes into 100% utilization, then kernel is submitted to the 2nd device, then nccl has to realize that the full grid is launched, run reduction and exit. 
Try ```export NCCL_DEBUG=INFO``` and may be you'll see something?

**Comment by ngimel** [comment]
@zou3519, is it possible to install nvidia-docker on that machine and try with pytorch docker image? I'm grasping at straws, with a fresh install there should not be problems.

**Comment by thatguymike** [comment]
Can we see the output of "lspci -t -vv"  And what is the CPU type and configuration in your system?

**Comment by zou3519** [comment]
@ngimel Good idea, I'll try that and see what happens.

@thatguymike CPU type is AMD Ryzen 7 1700 Eight-Core Processor. 16 gb of ram, 2x GTX 1080TI
```
(root) pytorch@pytorch-desktop:~/multigpu-test$ lspci -t -vv
-[0000:00]-+-00.0  Advanced Micro Devices, Inc. [AMD] Device 1450
           +-00.2  Advanced Micro Devices, Inc. [AMD] Device 1451
           +-01.0  Advanced Micro Devices, Inc. [AMD] Device 1452
           +-01.3-[03-0b]--+-00.0  Advanced Micro Devices, Inc. [AMD] Device 43b9
           |               +-00.1  Advanced Micro Devices, Inc. [AMD] Device 43b5
           |               \-00.2-[04-0b]--+-00.0-[05]--
           |                               +-01.0-[06]----00.0  Intel Corporation I211 Gigabit Network Connection
           |                               +-02.0-[07]--
           |                               +-03.0-[08]--
           |                               +-04.0-[09]--
           |                               +-06.0-[0a]--
           |                               \-07.0-[0b]--
           +-02.0  Advanced Micro Devices, Inc. [AMD] Device 1452
           +-03.0  Advanced Micro Devices, Inc. [AMD] Device 1452
           +-03.1-[0c]--+-00.0  NVIDIA Corporation Device 1b06
           |            \-00.1  NVIDIA Corporation Device 10ef
           +-03.2-[0d]--+-00.0  NVIDIA Corporation Device 1b06
           |            \-00.1  NVIDIA Corporation Device 10ef
           +-04.0  Advanced Micro Devices, Inc. [AMD] Device 1452
           +-07.0  Advanced Micro Devices, Inc. [AMD] Device 1452
           +-07.1-[11]--+-00.0  Advanced Micro Devices, Inc. [AMD] Device 145a
           |            +-00.2  Advanced Micro Devices, Inc. [AMD] Device 1456
           |            \-00.3  Advanced Micro Devices, Inc. [AMD] Device 145c
           +-08.0  Advanced Micro Devices, Inc. [AMD] Device 1452
           +-08.1-[12]--+-00.0  Advanced Micro Devices, Inc. [AMD] Device 1455
           |            +-00.2  Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode]
           |            \-00.3  Advanced Micro Devices, Inc. [AMD] Device 1457
           +-14.0  Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller
           +-14.3  Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge
           +-18.0  Advanced Micro Devices, Inc. [AMD] Device 1460
           +-18.1  Advanced Micro Devices, Inc. [AMD] Device 1461
           +-18.2  Advanced Micro Devices, Inc. [AMD] Device 1462
           +-18.3  Advanced Micro Devices, Inc. [AMD] Device 1463
           +-18.4  Advanced Micro Devices, Inc. [AMD] Device 1464
           +-18.5  Advanced Micro Devices, Inc. [AMD] Device 1465
           +-18.6  Advanced Micro Devices, Inc. [AMD] Device 1466
           \-18.7  Advanced Micro Devices, Inc. [AMD] Device 1467
```

**Comment by zou3519** [comment]
@ngimel I installed pytorch using nvidia-docker and ran a basic script that used DataParallel. The script still hangs at the same point. Looking at nvidia-smi outside the docker shows both GPUs at 100% utilization, so it looks like the same symptoms as before.

**Comment by awaelchli** [comment]
I also have an AMD processor (Ryzen Threadripper 1920X). Is it a coincidence or could the problem be related to Ryzen?

**Comment by Mctigger** [comment]
SamTsu also uses and AMD processor. (Ryzen Threadripper 19**5**0X).
https://discuss.pytorch.org/t/nn-dataparallel-model-cuda-stuck/8085/11

**Comment by EgorLakomkin** [comment]
I have  Intel processor+K80 and also have this problem.

**Comment by awaelchli** [comment]
@EgorLakomkin Good to know. Then I am glad that this is not the problem :)

**Comment by thatguymike** [comment]
Can you try building and running the CUDA sample 1_Utilities/p2pBandwidthLatencyTest?  What CUDA driver?

**Comment by awaelchli** [comment]
@thatguymike I did that with cuda 9.0.176. _p2pBandwithLatencyTest_ gives me the following output and then hangs. At the same time, GPU utilization is at 100% on the first GPU until I kill the process.

`[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, GeForce GTX 1080 Ti, pciBusID: 9, pciDeviceID: 0, pciDomainID:0
Device: 1, GeForce GTX 1080 Ti, pciBusID: a, pciDeviceID: 0, pciDomainID:0
Device: 2, GeForce GTX 1080 Ti, pciBusID: 42, pciDeviceID: 0, pciDomainID:0
Device: 3, GeForce GTX 1080 Ti, pciBusID: 43, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=0 CAN Access Peer Device=2
Device=0 CAN Access Peer Device=3
Device=1 CAN Access Peer Device=0
Device=1 CAN Access Peer Device=2
Device=1 CAN Access Peer Device=3
Device=2 CAN Access Peer Device=0
Device=2 CAN Access Peer Device=1
Device=2 CAN Access Peer Device=3
Device=3 CAN Access Peer Device=0
Device=3 CAN Access Peer Device=1
Device=3 CAN Access Peer Device=2

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) in those cases.

P2P Connectivity Matrix
     D\D     0     1     2     3
     0	     1     1     1     1
     1	     1     1     1     1
     2	     1     1     1     1
     3	     1     1     1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1      2      3 
     0 350.37   3.17   3.17   3.17 
     1   3.34 352.77   4.60   4.58 
     2   3.31   4.57 351.91   4.50 
     3   3.34   4.62   4.16 352.17 
Unidirectional P2P=Enabled Bandwidth Matrix (GB/s)
`

**Comment by Mctigger** [comment]
Same result here, also with cuda 9.0.176.
```
[P2P (Peer-to-Peer) GPU Bandwidth Latency Test]
Device: 0, GeForce GTX 1080 Ti, pciBusID: c, pciDeviceID: 0, pciDomainID:0
Device: 1, GeForce GTX 1080 Ti, pciBusID: d, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Access Peer Device=1
Device=1 CAN Access Peer Device=0

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure.
So you can see lesser Bandwidth (GB/s) in those cases.

P2P Connectivity Matrix
     D\D     0     1
     0	     1     1
     1	     1     1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
   D\D     0      1 
     0 345.38   6.20 
     1   6.21 352.54 
Unidirectional P2P=Enabled Bandwidth Matrix (GB/s)
Cuda failure p2pBandwidthLatencyTest.cu:105: 'the launch timed out and was terminated'

```

**Comment by thatguymike** [comment]
Okay, more fundamental problem.   We'll have to get a Ryzen system up to debug.

**Comment by jgoldfa** [comment]
I just want to make everyone aware that there is another issue with the nvidia ubuntu driver and 1080 Ti SLI.
I'm not sure if they could be related.

https://devtalk.nvidia.com/default/topic/1000833/linux/unity-doesn-t-start-on-ubuntu-16-04-when-sli-on/post/5213941/#5213941

**Comment by awaelchli** [comment]
@jgoldfa This seems to be about SLI, but as I understand SLI is not required for multi gpu training with torch, or am I missing something here?

**Comment by lvpengyuan** [comment]
I have the same issue but with the Titan X

**Comment by ngimel** [comment]
To everyone facing hangs:
1) Please make sure you can run p2pBandwithLatencyTest from cuda samples without errors, hangs, and timeouts. If you cannot, then the hangs you are facing are not a pytorch problem
2) If p2pBandwidthLatencyTest fails, please check dmesg for IOMMU-related messages after reboot. If you see something like 
```
[    1.217752] iommu: Adding device 0000:44:00.0 to group 18
[    1.217762] iommu: Adding device 0000:44:00.2 to group 18
[    1.217980] AMD-Vi: Found IOMMU at 0000:00:00.2 cap 0x40
[    1.217984] AMD-Vi: Found IOMMU at 0000:40:00.2 cap 0x40
[    1.220552] perf: amd_iommu: Detected. (0 banks, 0 counters/bank)
``` 
iommu is being enabled. P2P GPU traffic fails with enabled IOMMU, unless the cards are behind PLX switch.
3. Try disabling iommu via grub:
```
sudo vim /etc/default/grub
```
Make below changes in the file:
```
#GRUB_CMDLINE_LINUX=""                           <----- Original commented
GRUB_CMDLINE_LINUX="iommu=soft"           <------ Change
```
```
sudo update-grub
```
Reboot to see the change.

4. Could also be an ACS-related issue https://devtalk.nvidia.com/default/topic/883054/multi-gpu-peer-to-peer-access-failing-on-tesla-k80-/?offset=26, https://www.supermicro.com/support/faqs/faq.cfm?faq=20732

**Comment by awaelchli** [comment]
@ngimel **Your solution worked for me**! Now the dcgan example is running on all GPUs! Thank you very much. I don't understand why this is with pytorch, because multi-gpu with tensorflow was working fine.

**Comment by ngimel** [comment]
Apparently TensorFlow is not using nccl, and is not using p2p memcopies.

**Comment by Mctigger** [comment]
Can confirm, also worked for me!

**Comment by apaszke** [comment]
Thanks Natalia! This seems resolved, so I'm closing the issue.

**Comment by drhey** [comment]
@ngimel I tried setting `iommu=soft` to no avail. I also tried `iommu=off` along with `intel_iommu=off` also to no avail. Would you happen to have any other suggestions for Intel machines? Thanks for the assistance!

**Comment by lukas** [comment]
I'm also seeing my pytorch hang when turning on more than one GPU.
I'm on an ec2 p2 (K80) machine with the ubuntu deep learning AMI.
The p2pBandwidthLatencyTest seems to run fine, with all the GPUs able to communicate with each other.

**Comment by lukas** [comment]
In case anyone else lands here with the same issue, I was able to fix it by installing pytorch from source.

**Comment by ozancaglayan** [comment]
If you can't fix it with the iommu=off, check if ACS is enabled as suggested in https://github.com/pytorch/pytorch/issues/1637#issuecomment-338268158 . We are hitting the same problem on one of our servers and it does not seem to be related to iommu.

**Comment by nbansal90** [comment]
@ozancaglayan @ngimel I am running in to this issue for Ti 1080. I am running python on Conda environment, And I tried  immu=soft, But that did not work out. My ACS command is not giving the expected output,SO I am not able to check if ACS is enabled or not. Still stuck

**Comment by dmitry-xnor** [comment]
On a Threadripper quad-GPU box with 1080ti's turning off IOMMU replaces a hang with a particularly brutal and immediate crash, and GPU fans spin up to 100% and stay there. That's progress, but not quite all the way to where I need to be.

**Comment by dmitry-xnor** [comment]
In case this helps anybody else: our crashing issue seems to have been power-related. NVIDIA GPUs will actually happily "overshoot" their claimed power limit, sometimes by a lot, and when they do that simultaneously against a power supply that's too close to its specified max, a brownout can occur and the system can crash. 

The "temporary" fix (or a hypothesis test, at least) for this is to add:
```
nvidia-smi -pm 1
nvidia-smi -pl 200
```
to `rc.local`. This will reduce P~max~ of 1080ti's by about 20%. Moral of the story: get a 1500-1600W power supply for your quad-GPU box, 1300W is not enough.

**Comment by yubeic** [comment]
@dmitry-xnor 
I'm planning about a new quad GPU build around a 1950x platform. Does your threadripper server have any significant issues with PyTorch? Thanks a lot!

**Comment by dmitry-xnor** [comment]
@yubeic no issues at all once you disable IOMMU. But there was much trial and error before we got to a working config that doesn't die and doesn't thermal throttle.

1. **Power**: Be aware that, as it turns out, power supply manufacturers routinely overstate the current capabilities of their power supplies (we've had bad luck with Rosewill in particular), and NVIDIA understates the peak power draw. We've had good results with EVGA SuperNova 1600, everything less than that resulted in sudden shutdowns, usually in the first few batches of a 4-GPU job. With 1600W PSU everything is rock solid. The issue with this is $#@ miners are willing to pay twice as much for this power supply, so it's $500+, which is way too much.

2. **Heat**: A potential issue with consumer cards in a 4GPU box is that they are, well, consumer cards, and they are optimized for low noise. They would rather thermal throttle to 160W than ramp up the fan. The workaround is you force X to run on all GPUs, even if monitors aren't connected, and force the fans to 100% through coolbits. There are numerous examples of that on the internet.

3. **Fans**: Not all fans are made equal. GIGABYTE 1080ti cards have pretty weak fans. PNY 1080ti's have pretty good ones. So we mix them, Gigabyte cards in slots 1 and 4 ("outside") and PNY in slots 2 and 3 ("inside"). Works pretty well.

Once you take care of all this, you get a pretty solid box with 4C/8T to feed each GPU. In fact, I'm thinking of building one for myself right now, it's a sweet rig.

**Comment by yubeic** [comment]
@dmitry-xnor Great! Our tool chains are mainly around PyTorch and our models work very efficiently with data-parallelism training. So if threadripper works, it should be an ideal platform for Quad GPU PyTorch learning box. Based on your suggestion, I got Supernova 1600. The GPUs are all 1080Ti FE cards. I will update my experience once I got my PyTorch working on this box. Or if I got issues, I may come back to ask for further suggestions.

**Comment by awaelchli** [comment]
@yubeic I can confirm that PyTorch is working fine with 4 GPUs on 1950x/1920x when setting iommu=soft (or off). However, we were unable to install Ubuntu 16.04 LTS due to unknown kernel issues; only 17.10 is working :( Hopefully 18.04 will install without problems. I have the 1700 W power supply from Enermax, but the PCI-E cables are a bit short. 
I use the Asus ROG Zenith mainboard (can recommend), which has 2x EPS 12V power delivery for the CPU. Look for a  power supply that has two of these CPU cables in case you also have a board with two connectors (I think all threadripper boards have two).

I would be interested with what build you come up with in the end.

**Comment by dmitry-xnor** [comment]
We are running 16.04.4 **Desktop** with HWE kernel quite successfully. Desktop because X is needed for fan control.

**Comment by yubeic** [comment]
@awaelchli @dmitry-xnor An update on the trheadripper 1950x build. The recently released linux 16.04.4 LTS works with 1950x smoothly. I did have to turn off an energy saving feature in the kernel, but that's actually good for a server. The whole build works well with PyTorch and I was glad that I used 1950x rather than 1920 since Pytorch uses MAGMA library to handle some of the linalg functions like symeig and svd. MAGMA uses CPU heavily for these functions and a fast CPU is very necessary. However, even I use 1950x, the CPU is still a bottleneck if I run several such processes independently. I hope in the future PyTorch can provide an option run svd and symeig on GPUs only. I think the whole system is working quite stably now and Further I suggest to add two additional fans to cool the GPUs properly.

**Comment by 1e100** [comment]
Why do you use CPU for linear algebra in the first place? It should be used for JPEG decoding and data augmentation, and loss function (although some loss functions can be accelerated as well). If you’re doing linear algebra on the CPU you’re doing it wrong. For JPEG and data augmentation Threadripper is sufficient, especially if you replace Pillow with PillowSIMD

**Comment by yubeic** [comment]
@1e100 PyTorch uses MAGMA for some processing, e.g. SVD. MAGMA is uses both CPU and GPU, now the CPU becomes a bottleneck easily since MAGMA also runs slower (with all cores ..) on Threadripper. For research, sometimes a quick prototyping is good if the performance is not too bad. But anyway, it's too bad that linear algebra is this slow on Threadripper 1950x. We were thinking about building many more servers with this CPU.

**Comment by 1e100** [comment]
If you need linear algebra on the CPU, AMD is not the best choice, I agree. Recent Intel CPUs are twice as wide per core. Even with fewer cores and thermal throttling they are going to outperform AMD. Our workload, however, does not, and will not require much from the CPU aside from data augmentation (which is quite elaborate) and JPEG decoding, so for us Threadripper is a good choice.

**Comment by yubeic** [comment]
@1e100, that's very unfortunate. We are glad that we didn't start to build more servers with 1950x. I probably will switch to an i9-7960x now. A lot of extra work, that's the risk and fun trying something new.

**Comment by gwern** [comment]
Just leaving another comment about the workaround: I built a Threadripper/2x1080ti workstation and began the Fast.ai course. Training on a single GPU worked fine, so I thought I'd try both, using `DataParallel`. The Python process would spin at 100% unkillably, with small GPU utilization, requiring a reboot. The p2p CUDA sample would likewise hang at the first benchmark. Adding the IOMMU line in Grub and rebooting fixed both problems (could get the P2P benchmark within seconds, and dual-GPU training overnight ran without a hitch) and doesn't thus far appear to have caused any side-effects.

**Comment by gabsens** [comment]
@yubeic Any update on the slow performance of the 1950x ?

**Comment by yubeic** [comment]
@gabsens I switched to 7960x to save some time. For more details, I have put my benchmarks under the github discusson under openBLAS project if you google "1950x openBLAS". My conclusion is that the software is not there.

**Comment by awaelchli** [comment]
Recently I had a segfault when training, shortly after that the system would freeze. This happened a few times in the past but very rare (once every month). A kernel update did not fix the problem, it seems. The log files say something about a locked page or a removed page. 

[syslog-jul-25.txt](https://github.com/pytorch/pytorch/files/2228267/syslog-jul-25.txt)

Did anyone with threadripper have the same issue? 
I know I will have to post somewhere else it is probably not pytorch issue but was just wondering since some here have similar hardware and use case.

**Comment by winnechan** [comment]
if my test info are as follows, does it mean i can just use 0 and 1 or 2 and 3 dual GPUs to train my model instead of all 4 GPUs ?

Device=0 CAN Access Peer Device=1
Device=0 CANNOT Access Peer Device=2
Device=0 CANNOT Access Peer Device=3
Device=1 CAN Access Peer Device=0
Device=1 CANNOT Access Peer Device=2
Device=1 CANNOT Access Peer Device=3
Device=2 CANNOT Access Peer Device=0
Device=2 CANNOT Access Peer Device=1
Device=2 CAN Access Peer Device=3
Device=3 CANNOT Access Peer Device=0
Device=3 CANNOT Access Peer Device=1
Device=3 CAN Access Peer Device=2

**Comment by Swarchal** [comment]
I'm having the same problem with `nn.DataParallel()` locking up the entire computer despite disabling iommu in the kernel and in the BIOS.

Running `p2pBandWidthLatencyTest` returns the following before completely locking up the computer in the same way:

```
Device: 0, Geforce GTX 1060 6GB, pciBusID: 1c, pciDeviceID: 0, pciDomainID:0
Device: 1, Geforce GTX 1060 6GB, pciBusID: 1d, pciDeviceID: 0, pciDomainID:0
Device=0 CAN Acess Peer Device=1
Device=1 CAN Acess Peer Device=0

***NOTE: In case a device doesn't have P2P access to other one, it falls back to normal memcopy procedure. So you can see lesser Bandwidth (GB/s) and unstable Latency (us) in those cases.

P2P Connectivity Matrix
    D/D    1    0
    0      1    1
    1      1    1
Unidirectional P2P=Disabled Bandwidth Matrix (GB/s)
```

`nvidia-smi` returns:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:1C:00.0  On |                  N/A |
| 24%   42C    P8     6W / 120W |    235MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 00000000:1D:00.0 Off |                  N/A |
| 27%   34C    P8     5W / 120W |      2MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
...
```

I'm running os:Ubuntu 19.04 x86_64 kernel: 5.0.0-20-generic . 

Any one have more ideas how to fix? I'm completely stumped and it's a bit of a show-stopper.

**Comment by 1e100** [comment]
@Swarchal: I'm not an expert, but the output would suggest that cards still think there's peer-to-peer access, which won't work without a PCIe switch. Double check that IOMMU is disabled in the BIOS perhaps?

@awaelchli Regarding segfaults on Threadripper: it's picky wrt DRAM if you put in a lot of RAM (my machines have 128GB). There's a setting buried in the BIOS called "gear down mode". It needs to be enabled. I will improve stability if your RAM situation is not ideal. I didn't see any perf impact on my DL workloads and stability issues were resolved completely after enabling the setting. I'm not sure why motherboard manufacturers don't enable it by default.

A telltale sign of unstable RAM is lots of "EXIF" errors when training on ImageNet or sharp random spikes in your training loss. There are a couple of busted files in ImageNet, but the number of EXIF errors should be consistent run-to-run.

**Comment by SungYK** [comment]
@Swarchal I have the same issue. Did you found the solution?

**Comment by Swarchal** [comment]
@SungYK 

I no longer have the problem but I'm not sure what solved it.

Same cards and BIOS version/settings but I'm now running later nvidia drivers and linux kernel.
- NVIDIA driver version 450.80.02
- CUDA Version: 11.0
- Ubuntu 20.04 LTS
- Kernel 5.4.0-52-generic

Hope this helps

**Comment by SungYK** [comment]
@Swarchal Thanks a lot for your reply. I solved it partially.
The p2pBandWidthLatencyTest result shows that all my GPUs can access each other. But in fact, I found that the program works when the allocated GPU serial number is all even/odd like CUDA_VISIBLE_DEVICES= 0,2 or CUDA_VISIBLE_DEVICES = 1,3.` 
It may cause by the NVIDIA driver, not sure. Thanks anyway. It helps.

**Comment by kecsap** [comment]
I experience freezes with a GTX 1080 and a GTX 1070 in the same machine (old AMD FX platform). I spent a half-day today to try the newest kernel and other software fix, but:
1. With enabled IOMMU, a get a soft freeze. GPUs stuck and I have to reboot the computer.
2. With disabled IOMMU, it is a hard freeze, only the power button helps.

Fix (workaround): Use NCCL_P2P_DISABLE=1 before the pytorch command or directly export as a command-line variable. Problem solved and I don't see any degradation in performance.

**Comment by preethamam** [comment]
> I experience freezes with a GTX 1080 and a GTX 1070 in the same machine (old AMD FX platform). I spent a half-day today to try the newest kernel and other software fix, but:
> 
> 1. With enabled IOMMU, a get a soft freeze. GPUs stuck and I have to reboot the computer.
> 2. With disabled IOMMU, it is a hard freeze, only the power button helps.
> 
> Fix (workaround): Completely disable p2p communication. Use NCCL_P2P_DISABLE=1 before the pytorch command or directly export as an environmental variable. Problem solved and I don't see any degradation in performance. I love NVidia solving these generic runtime configs with environmental variables.

I do have the same issue. I have 4 Nvidia RTX 2080Ti GPUs and whenever I use `nn.DataParallel` the Linux and Windows 11 systems crash after a few seconds when the data is pushed to the GPUs. In addition, I tried `NCCL_P2P_DISABLE=1` but none of the solutions helped me. Including the `iommu=soft` or `iommu=off`. I went through the comments and their suggestions none worked for me.

I have AMD Threadripper 2950X
RAM: 128 GB
4 Nvidia RTX 2080Ti GPUs
PyTorch: 1.12.1

Any help is much appreciated!

**Comment by preethamam** [comment]
> To everyone facing hangs:
> 
> 1. Please make sure you can run p2pBandwithLatencyTest from cuda samples without errors, hangs, and timeouts. If you cannot, then the hangs you are facing are not a pytorch problem
> 2. If p2pBandwidthLatencyTest fails, please check dmesg for IOMMU-related messages after reboot. If you see something like
> 
> ```
> [    1.217752] iommu: Adding device 0000:44:00.0 to group 18
> [    1.217762] iommu: Adding device 0000:44:00.2 to group 18
> [    1.217980] AMD-Vi: Found IOMMU at 0000:00:00.2 cap 0x40
> [    1.217984] AMD-Vi: Found IOMMU at 0000:40:00.2 cap 0x40
> [    1.220552] perf: amd_iommu: Detected. (0 banks, 0 counters/bank)
> ```
> 
> iommu is being enabled. P2P GPU traffic fails with enabled IOMMU, unless the cards are behind PLX switch. 3. Try disabling iommu via grub:
> 
> ```
> sudo vim /etc/default/grub
> ```
> 
> Make below changes in the file:
> 
> ```
> #GRUB_CMDLINE_LINUX=""                           <----- Original commented
> GRUB_CMDLINE_LINUX="iommu=soft"           <------ Change
> ```
> 
> ```
> sudo update-grub
> ```
> 
> Reboot to see the change.
> 
> 4. Could also be an ACS-related issue https://devtalk.nvidia.com/default/topic/883054/multi-gpu-peer-to-peer-access-failing-on-tesla-k80-/?offset=26, https://www.supermicro.com/support/faqs/faq.cfm?faq=20732

I do have the same issue. I have 4 Nvidia RTX 2080Ti GPUs and whenever I use `nn.DataParallel` the Linux and Windows 11 systems crash after a few seconds when the data is pushed to the GPUs. In addition, I tried `NCCL_P2P_DISABLE=1` but none of the solutions helped me. Including the `iommu=soft` or `iommu=off`. I went through the comments and their suggestions none worked for me.

I have AMD Threadripper 2950X
RAM: 128 GB
4 Nvidia RTX 2080Ti GPUs
PyTorch 1.12.1
Ubuntu 22.04.1 and Windows 11

Any help is much appreciated!

**Comment by Borodin** [comment]
I faced the same problem, all the solutions described here are not suitable for me.

I have AMD FX(tm)-4100 Quad-Core Processor 
RAM: 8 GB
2x NVIDIA GeForce GTX 1060 6GB
PyTorch 1.13.1
Ubuntu 22.04.1 LTS

Any help is much appreciated!

**Comment by Borodin** [comment]
None of the above solutions worked for me.
I found a solution for myself.

In my case, my motherboard couldn't allow two PCIex16s to run at the same time in @16 mode.

I changed the motherboard
with 2 x PCI Express 2.0 x16 (PCIE2: in mode x16; PCIE3: in mode x4)
on 2 x PCI Express 2.0 x16 (PCIE2: in mode x16; PCIE4: in mode x16)
