### ISSUE TITLE
Installing pytorch via pip wheel crashes on import (no module named numpy)

### ISSUE THREAD

**Issue by y0ast** [pytorch/pytorch#1755]
I think the pip wheels are built with numpy support, however numpy is not explicitly listed as a dependency.

When trying to import torch an import error occurs:
```
>>> import torch
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/private/var/folders/b5/hgpy98310bg_g3hfqngl759m0000gn/T/tmpCRcqEy/.deps/torch-0.1.12.post2-cp27-none-macosx_10_7_x86_64.whl/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
```

Installing numpy and then importing torch does work.

**Comment by fmassa** [comment]
Hmm, so there's two possible wheel configurations: one compiled with numpy support (and numpy listed as dependency), and another one without numpy.

It seems that our conda builds list [numpy as a runtime dependency](https://github.com/pytorch/builder/blob/master/conda/pytorch-cuda80-0.1.12/meta.yaml#L21), so we should probably do the same thing for the wheels?

**Comment by soumith** [comment]
fixed in master, will be present in next release.

**Comment by gautam1858** [comment]
not fixed getting the same error for me though I installed from the master

**Comment by soumith** [comment]
we've added numpy as a dependency, in master: https://github.com/pytorch/pytorch/blob/master/setup.py#L491

**Comment by gautam1858** [comment]
hmmm but getting this error 

`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import torch
  File "/Users/neutrino/anaconda/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import`

**Comment by gautam1858** [comment]
The error is coming for macOS
