### ISSUE TITLE
[jit] incompleteInferType failed to handle type Tuple[GenericList]

### ISSUE THREAD

**Issue by yelu** [pytorch/pytorch#17650]
## 🐛 Bug

When passing a Tuple[GenericList] to jit script module in C++, it goes to line 145 in [incompleteInferType](https://github.com/pytorch/pytorch/blob/06c8aa7a3bbd91cda2fd6255ec82aad21fa1c0d5/aten/src/ATen/core/type.cpp#L145).

Then in fmap function call, incompleteInferType(GenericeList) is called recursively, then an `AT_ERROR("Type cannot be accurately recovered from this IValue.")` is thrown because GenericList is not handled directly in this function.

## To Reproduce

1. create a jit function in python
```py
@torch.jit.script
def MyScriptFun1(input1:Tuple[List[int]]) -> Tuple[List[int]]:
    return input1
```
2. load and call the function in C++ api.
```c
    auto generic_list = torch::jit::GenericList::create({1});
    auto tuple_generic_list = torch::jit::Tuple::create({ generic_list });

    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(tuple_generic_list);
    // Execute the model and turn its output into a tensor.
    try {
        auto outputs = m->forward(inputs);
    }
    catch (std::exception& e)
    {
        std::string msg(e.what());
    } 
```

## Environment

 - PyTorch Version (e.g., 1.0): latest master
 - OS (e.g., Linux): Windows 10

**Comment by eellison** [comment]
Hi - this has been fixed in #17687 so I'm closing. There is a separate issue which is that we need better Documentation / API for converting c++ vectors -> ivalue -> back again. Note in my PR we use std::vector<int64_t> instead of generic list for int lists. You can follow that issue here https://github.com/pytorch/pytorch/issues/17165

**Comment by yelu** [comment]
> Hi - this has been fixed in #17687 so I'm closing. There is a separate issue which is that we need better Documentation / API for converting c++ vectors -> ivalue -> back again. Note in my PR we use std::vector<int64_t> instead of generic list for int lists. You can follow that issue here #17165

Based on my test, this doesn't fix the issue. vector<int64_t> is a special type define, thus different from a  vector<non POD type>. So,
1. Tuple[List[int]] works
2. Tuple[GenericeList] doesn't work

**Comment by eellison** [comment]
Hi, the following code works

```
  auto module = torch::jit::compile(R"JIT(
      def tuple_op(a: Tuple[List[Optional[int]]]):
        return a
    )JIT");

   std::vector<at::IValue> generic_list = {};
  auto tuple_generic_list = torch::jit::Tuple::create({ generic_list });
   // doesn't fail on arg matching
  module->run_method("tuple_op", tuple_generic_list);
```
What is the error you are seeing?  It is difficult to understand how to construct various data types, which is I opened #17165, but this issue should remain closed I believe.

**Comment by yelu** [comment]
> Hi, the following code works
> 
> ```
>   auto module = torch::jit::compile(R"JIT(
>       def tuple_op(a: Tuple[List[Optional[int]]]):
>         return a
>     )JIT");
> 
>    std::vector<at::IValue> generic_list = {};
>   auto tuple_generic_list = torch::jit::Tuple::create({ generic_list });
>    // doesn't fail on arg matching
>   module->run_method("tuple_op", tuple_generic_list);
> ```
> What is the error you are seeing? It is difficult to understand how to construct various data types, which is I opened #17165, but this issue should remain closed I believe.

Thanks, I confirm it works with latest nightly build.
