### ISSUE TITLE
Call backward of function in backpropagation

### ISSUE THREAD

**Issue by magzHL** [pytorch/pytorch#1776]
Unfortunately the following code snippet leads to an endless loop.
Is there a way to do backward computations on functions inside a backpropagation step? 
It would be nice to have to implement quantized convolutions (e.g. like in https://arxiv.org/pdf/1612.01064.pdf)
```
import torch

class exampleFct(torch.autograd.Function):
    def forward(self, dataIn):
        self.save_for_backward(dataIn)
        print("forward...")
        return dataIn**2

    def backward(self, grad_output):
        dataIn, = self.saved_tensors
        x_in_back = torch.autograd.Variable(torch.Tensor([2]), requires_grad=True)
        y = x_in_back**2
        print("backward...")
        y.backward(torch.Tensor([1]))
        print("unreachable")
        print(x_in_back.grad.data)
        return grad_output*2*dataIn


x = torch.autograd.Variable(torch.Tensor([[3, 4]]), requires_grad=True)
m = exampleFct()
m(x).backward(torch.Tensor([1, 1]))
print(x.grad.data)
```

**Comment by albanD** [comment]
Hi,

This is a known behavior: it is not possible to call `autograd.backward` or `autograd.grad` inside the `backward` of a Function. It will hang.

I don't think there is an easy solution to fix this at the moment unfortunately @apaszke ?

**Comment by apaszke** [comment]
No, there's not. We'd have to add an option for our worker threads in the engine to suspend processing of the current function, work on `backward` called within it, and get back to it later.

**Comment by magzHL** [comment]
Are you planning to introduce this kind of behaviour? Since the easy use of gpu accelerated backward functions is one of the main reasons for me to use pytorch, switching from matconvnet to a framework that is maintained by a broader community.

**Comment by soumith** [comment]
@magzHL  
> Since the easy use of gpu accelerated backward functions is one of the main reasons for me to use pytorch

This is still totally fine with pytorch. The issue here is that inside the backward function, another autograd forward/backward is done, which is not supported at the moment. It's a fairly big change, but it seems reasonable to do. We wont be working on it in the next 2 months or so.

**Comment by magzHL** [comment]
In the mean time I found a workaround for my needs:
https://discuss.pytorch.org/t/call-backward-on-function-inside-a-backpropagation-step/3793/6?u=magz

It consists of two steps: Breaking the function call into two pieces, where the first function is used to manipulate the data in a way that suits the desired behaviour (e.g. just passing it unchanged in the forward step, in case only backward gradients should be changed), afterwards use the implemented standard function (like Conv2d). When it then comes to the backward step, "catch" the gradient from the standard function, and manipulate it again in the first, user-defined function. 
In the end just wrap these two functions inside a module to have a nice looking interface to the outside world ;)

However, this workaround still appears to be clumsy. compared to a "backward in backward" approach. So I'm looking forward to it. Thanks!

**Comment by soumith** [comment]
this should now be fixed after adding re-entrant autograd.

**Comment by magzHL** [comment]
Unfortunatly, running the script here with Python 3.5, PyTorch 0.2 and CUDA 8.0 still shows the same endless loop behaviour @soumith

**Comment by fmassa** [comment]
@magzHL there is currently no release with this fix, so you need to install pytorch from source in order to get backward inside backward to work.

**Comment by magzHL** [comment]
@fmassa Okay, thank you! :)

**Comment by LMescheder** [comment]
What is the status of this issue? Is it supposed to work under PyTorch 0.3? I have a similar use case and in the beginning, it seems to work fine using `autograd.grad` inside `backward`, but after a while I get various C++ errors, e.g.
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
```
or just `Segmentation Fault`.
As far as I can tell, this only happens in cuda-mode, cpu-mode appear to be fine.  Also, the time until these errors occur appears to be completely random.

**Comment by apaszke** [comment]
@LMescheder I'm not sure about 0.3, but this should definitely work in master

**Comment by LMescheder** [comment]
@apaszke Thanks for your answer. However, when I try @magzHL's  code snippet using the master branch  I get
```
RuntimeError: element 0 of variables does not require grad and does not have a grad_fn
```
It seems that the `grad_fn` attribute is not set when calling functions inside `.backward()`?
As I said, it works for me under 0.3.1 using CPU mode, but not when using CUDA.

**Comment by apaszke** [comment]
@LMescheder sorry for a late reply. This is because the snippet uses a number of older APIs that are not compatible with `master`. There have been a number of changes. I'm attaching a script that showcases how this can be done (and works for me locally):
```python
import torch                                                    
                                                                
class exampleFct(torch.autograd.Function):                      
    @staticmethod                                               
    def forward(self, x):                                       
        self.save_for_backward(x)                               
        return x ** 2                                           
                                                                
    @staticmethod                                               
    def backward(self, dy):                                     
        x, = self.saved_variables                               
        with torch.enable_grad():                               
            y = x ** 2                                          
            return torch.autograd.grad(y, x, torch.ones_like(y))
                                                                
                                                                
x = torch.tensor([[3, 4]], requires_grad=True)                  
m = exampleFct.apply(x).sum().backward()                        
print(x.grad.data)                                              
```

**Comment by LMescheder** [comment]
@apaszke Thanks, works like a charm now. And thanks in general for all the hard work you put into creating PyTorch. It's an amazing framework (and gets better every day).

**Comment by kurthaha** [comment]
@apaszke I found this thread while working on something similar in c++. Could you share how to call backward method within a backward wrapper?

**Comment by jimmysue** [comment]
> ```python
> enable_grad
> ```

Is there a way to avoid the forward computation in backward call ?

**Comment by jimmysue** [comment]
> @LMescheder sorry for a late reply. This is because the snippet uses a number of older APIs that are not compatible with `master`. There have been a number of changes. I'm attaching a script that showcases how this can be done (and works for me locally):
> 
> ```python
> import torch                                                    
>                                                                 
> class exampleFct(torch.autograd.Function):                      
>     @staticmethod                                               
>     def forward(self, x):                                       
>         self.save_for_backward(x)                               
>         return x ** 2                                           
>                                                                 
>     @staticmethod                                               
>     def backward(self, dy):                                     
>         x, = self.saved_variables                               
>         with torch.enable_grad():                               
>             y = x ** 2                                          
>             return torch.autograd.grad(y, x, dy)
>                                                                 
>                                                                 
> x = torch.tensor([[3, 4]], requires_grad=True)                  
> m = exampleFct.apply(x).sum().backward()                        
> print(x.grad.data)                                              
> ```

**Comment by albanD** [comment]
Hi,

You don't have to do the second forward inside the first backward call.
This is just an example that shows that you can call autograd.grad within a Function's backward.

**Comment by jimmysue** [comment]
> Hi,
> 
> You don't have to do the second forward inside the first backward call.
> This is just an example that shows that you can call autograd.grad within a Function's backward.

Hi, 

I change the code as below, which lead to endless loop, what's wrong with that ?

```python

import torch                                                    
                                                                
class exampleFct(torch.autograd.Function):                      
    @staticmethod                                               
    def forward(self, x):                                       
        y = x ** 2  
        self.save_for_backward(x, y)  
        return y                             
                                         
                                                                
    @staticmethod                                               
    def backward(self, dy):                                     
        x, y = self.saved_tensors                               
        with torch.enable_grad():                               
            return torch.autograd.grad(y, x, dy)
                                                                
                                                                
x = torch.tensor([[3, 4]], dtype=torch.float, requires_grad=True)                  
m = exampleFct.apply(x).sum().backward()                        
print(x.grad.data) 
```

**Comment by albanD** [comment]
You're calling `grad(y, x)` where the backward of this function is the `exampleFct.backward()`. Which then calls grad again, calling into `exampleFct.backward()`. etc...

If you have further question, I would encourage you to open a new topic on the forum (https://discuss.pytorch.org/) so that we can discuss it there without making too much noise on the github issues which are reserved for bug and feature requests.
