### ISSUE TITLE
matmul uses too much memory in some batched cases

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#18862]
## 🐛 Bug

PyTorch `1.1.0a0+c3e3c5c`. The GPU times reported are on a P100.

In this case matmul uses about 12 GB of memory when it shouldn't use more than ~3 MB. (i.e. it's using 4096x more memory than necessary)

#### A
```python
x = torch.randn(4096, 4096)
y = torch.randn(192, 4096, 1)
z = torch.matmul(x, y)
```

Note that this is equivalent to the following memory efficient operation:

#### B
```
x = torch.randn(4096, 4096)
y = torch.randn(192, 4096, 1)
z = torch.bmm(x.unsqueeze(0).expand(192, *x.shape), y)
```

It's also equivalent to the following which is memory efficient and faster, but may require a copy of y and the output may be batched-column-major without some extra work:

#### C
```
x = torch.randn(4096, 4096)
y = torch.randn(192, 4096, 1)
z = torch.matmul(y.permute(0, 2, 1), x.t()).permute(0, 2, 1)
```

On GPU, **A** takes ~125 ms and uses 12 GB of memory, **B** takes ~22 ms, and **C** takes ~1 ms.

Originally https://discuss.pytorch.org/t/unexpected-huge-memory-cost-of-matmul/41642/4

See also https://github.com/pytorch/pytorch/issues/13222 which may be related

----

I believe the problem is the unnecessary contiguous call here:

https://github.com/pytorch/pytorch/blob/15b318de840de61e2e789c013e34d23819715090/aten/src/ATen/native/LinearAlgebra.cpp#L460-L461

Instead of using `contiguous()` and `view()` it may be possible to use `reshape()`. That might achieve performance of **B**.

**Comment by skrah** [comment]
I can confirm that `.contiguous()` allocates `12GB`, which is `192 * 4096 * 4096 * sizeof(float)`.

I wonder though why the inner matrix dimension from `192 * 4096 * 1` is broadcasted to `4096`. The comment at the top of the function in `LinearAlgebra.cpp` says:

```
The non-matrix (i.e. batch) dimensions are broadcasted (and thus
  must be broadcastable).
```

So shouldn't the matrix dimensions be left untouched?

**Comment by skrah** [comment]
Probably I'm using `NumPy` terminology here (there is an explicit outer loop).  In this case the "broadcasting" just seems to happen internally before the operation, but the comment at the top of the function refers to the result dimensions. I have to take a closer look.

**Comment by skrah** [comment]
Done in #20448.

**Comment by liangbright** [comment]
The bug is still there for A.ndim >=3 && B.ndim >= 3
please run the code below with version 1.8.1
```
x = torch.randn(1, 4096, 4096)
y = torch.randn(192, 4096, 1)
z1 = torch.bmm(x.expand(192, 4096, 4096), y) # it works
z2 = torch.matmul(x, y) # out of memory

**Comment by nlgranger** [comment]
In terms of use-case, this happens if you try to implement grouped matrix product, where:
input.shape = (n, g, i)  -> expanded to (n, g, 1, i)
weight.shape = (g, i, o) -> expanded to (1, g, i, o)
In that case one cannot simply expand the weights into shape (n * g, i, o), a reshape is necessary to use bmm which causes an allocation of memory.
