### ISSUE TITLE
optim.lr_scheduler.CyclicLR (master only: not released) is buggy when not using momentum

### ISSUE THREAD

**Issue by Youssefares** [pytorch/pytorch#19003]
## Issue description

If I use an optimizer like adam with no momentum and follow the message of line 578 below here, passing `cycle_momentum=False`, line 584 throws a KeyError because key 'momentum' is not set. 

https://github.com/pytorch/pytorch/blob/173f224570017b4b1a3a1a13d0bff280a54d9cd9/torch/optim/lr_scheduler.py#L576-L585

1. I believe the last two lines should be indented under the if-condition as well.
2. I also think the expected behavior is that cycle_momentum is set to False by default when the passed in optimizer doesn't support momentum, instead of throwing an error.

## Code example

```
optimizer = optim.Adam(params_to_update, lr=5e-4)
scheduler = CyclicLR(optimizer, base_lr=5e-6, max_lr=5e-2, cycle_momentum=False, step_size_up=2500)
```

## System Info
In my setup, I am using the stable version of pytorch, but I copied over CyclicLR and relative imports from master and I am using it in my project. 
```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Debian GNU/Linux 9.8 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla P4
Nvidia driver version: 410.72
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] intel-numpy==1.15.1
[pip3] numpy==1.15.1
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.6            py37hd81dba3_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.0.1           py3.7_cuda10.0.130_cudnn7.4.2_2    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch
```

**Comment by Youssefares** [comment]
Let me know if you'd like me to work on this :man_technologist:

**Comment by soumith** [comment]
@Youssefares sure thing, go for it. Thank you!

**Comment by trias702** [comment]
This bug is still present in the official PyTorch 1.1.0 which was released Apr 30, 2019. It's a really bad bug since CyclicLR is a big feature of the new pytorch and this bug causes CyclicLR to fail on any optimizer which doesn't support momentum. It's a fairly easy fix too, just indent two lines of code.

**Comment by BorisMarjanovic** [comment]
When will this bug be fixed?

**Comment by memahesh** [comment]
This bug is still present. Is anyone working to fix this ? If not, maybe I can work on it.

**Comment by memahesh** [comment]
@soumith and @Youssefares 
Can any of you tell me if its fixed or not ?

**Comment by Youssefares** [comment]
@memahesh 
I haven't had time to fix this I am afraid.
Sorry for any delay I might have caused. I think a pull request is already open for it though. So you can follow the progress there.

**Comment by jeroenvuurens** [comment]
I think you are correct, if you indent the second and third to last lines in the __init__ it works.

**Comment by gchanan** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/20401.

**Comment by meghbhalerao** [comment]
Hmm. Is anyone getting this error in `pytorch 1.6.0`?

**Comment by ishedesy** [comment]
I use PyTorch 1.4, but I still get the following error when using Adam without momentum: 
`ValueError: optimizer must support momentum with `cycle_momentum` option enabled`

**Comment by meghbhalerao** [comment]
Oh, okay. So basically there are some compatibility issues with the `optimizer` and `lr scheduler` for certain combinations of the two?

**Comment by ishedesy** [comment]
Exactly. At least it seems so.

**Comment by kaushal-py** [comment]
The bug exists in pytorch 1.6 as well.

**Comment by snk4tr** [comment]
The bug exists in PyTorch 1.7.0 😞

**Comment by Jungjee** [comment]
Is there anyone who knows why this issue is closed although this bug exists in the latest stable release(1.7.0)??

Or is there a solution for this phenomenon except for setting ```cycle_momentum=False```

**Comment by Moldoteck** [comment]
Any updates for this?

**Comment by thomashirtz** [comment]
Is someone currently working on this ?

**Comment by patricio-astudillo** [comment]
The bug exists in PyTorch 1.9.0

**Comment by cowwoc** [comment]
@gchanan Please reopen this issue. It is not fixed.

**Comment by thomashirtz** [comment]
Does someone know/can explain me how to fix it ? I can try to make a PR

**Comment by gonzrubio** [comment]
The bug exists in PyTorch 2.0.0
