### ISSUE TITLE
BCEWithLogitsLoss TypeError

### ISSUE THREAD

**Issue by Timonzimm** [pytorch/pytorch#2272]
Hi,
When trying to use the new `BCEWithLogitsLoss` (pytorch version `0.2.0+7be5452`), I get the following error:
```TypeError: is_same_size received an invalid combination of arguments - got (torch.cuda.FloatTensor), but expected (torch.cuda.LongTensor other)```

And indeed, my input of the loss (output of the model forward pass) is a float, and the target is a long (1 or 0), which looks like appropriate types to me so I might have misunderstood something, or the error comes from somewhere else.

I have not used a SoftMax on the output of the last layer so the output of the forward pass is simply the output of my `Linear` layer.

**Comment by soumith** [comment]
thanks for reporting. fixed via https://github.com/pytorch/pytorch/commit/b3ca3da4b6540f38289a8dc664a36ac30b349e76

**Comment by Timonzimm** [comment]
Actually you forgot to change this line also: https://github.com/pytorch/pytorch/blob/b3ca3da4b6540f38289a8dc664a36ac30b349e76/torch/nn/functional.py#L799

I can make a PR but I think it would be quicker if you directly pushed the change @soumith.

**Comment by fmassa** [comment]
We currently don't support automatic type casting in pytorch, and while I agree allowing long types for the target would make it more similar to `nll_loss`, we would then have incompatibilities with `mse_loss` and others (which only accepts the same type as the input for the target). Also note that the target in `bce_with_logits` is not restricted to `{0,1}`, but instead `[0,1]`.
Not sure what is the best to do here (leave as is, or change all losses where it makes sense to accept `long` as well for the target).
