### ISSUE TITLE
*** Error in `/usr/bin/python2.7': free(): invalid pointer: 0x00007f801fcdbb80 ***

### ISSUE THREAD

**Issue by eric4note** [pytorch/pytorch#2542]
After updating to Pytorch 0.2, I ran into this error. I am on Ubuntu 16.04.

The suggestion at https://github.com/tensorflow/tensorflow/issues/6968 doesn't work for me.
sudo apt-get install libtcmalloc-minimal4
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"

More details are as follows:

*** Error in `/usr/bin/python2.7': free(): invalid pointer: 0x00007f801fcdbb80 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f80a2e637e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f80a2e6c37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f80a2e7053c]
/usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so(_ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE+0x142)[0x7f801fa75802]
/usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so(_ZNSt6locale5_ImplC2Em+0x1e3)[0x7f801fa77953]
/usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so(_ZNSt6locale18_S_initialize_onceEv+0x15)[0x7f801fa788c5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xea99)[0x7f80a31c4a99]
/usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so(_ZNSt6locale13_S_initializeEv+0x21)[0x7f801fa78911]
/usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so(_ZNSt6localeC1Ev+0x13)[0x7f801fa78953]
/usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so(_ZNSt8ios_base4InitC1Ev+0xb4)[0x7f801fa4a1b4]
/usr/local/lib/python2.7/dist-packages/torch/lib/libcusparse-94011b8d.so.8.0.61(+0x2f85b4)[0x7f7ff013a5b4]
/usr/local/lib/python2.7/dist-packages/torch/lib/libcusparse-94011b8d.so.8.0.61(+0x2f8703)[0x7f7ff013a703]
/usr/local/lib/python2.7/dist-packages/torch/lib/libcusparse-94011b8d.so.8.0.61(+0x393cc6)[0x7f7ff01d5cc6]
======= Memory map: ========
00400000-006ea000 r-xp 00000000 08:05 2548                               /usr/bin/python2.7
008e9000-008eb000 r--p 002e9000 08:05 2548                               /usr/bin/python2.7
008eb000-00962000 rw-p 002eb000 08:05 2548                               /usr/bin/python2.7
00962000-00985000 rw-p 00000000 00:00 0 
01bff000-0302a000 rw-p 00000000 00:00 0                                  [heap]
........
........
........
7f80a35fa000-7f80a35fb000 rw-p 00000000 00:00 0 
7ffdfdee5000-7ffdfdf04000 rwxp 00000000 00:00 0                          [stack]
7ffdfdf04000-7ffdfdf06000 rw-p 00000000 00:00 0 
7ffdfdf22000-7ffdfdf24000 r--p 00000000 00:00 0                          [vvar]
7ffdfdf24000-7ffdfdf26000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by laftworld** [comment]
In most cases SIGABRT comes out when libc tries to call free() on a non-initialized/corrupted pointer. So it could be a bug from v0.2 update, but as well as from OS, or wherever. Could you point out what exactly were you doing? is it happened when you were updating?

**Comment by soumith** [comment]
this issue should be fixed shortly once I upload new binaries.

**Comment by eric4note** [comment]
soumith, thanks!
But I re-installed pytorch with the latest source and the problem persists. Hope your binaries address it.

**Comment by soumith** [comment]
installing the latest binaries now should fix this for you.
