### ISSUE TITLE
test_cuda_kernel_loop_overflow_large fails on current build

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#26838]
## 🐛 Bug

`test_cuda_kernel_loop_overflow_large` from `TestCuda`: fails with `RuntimeError: avg_pool2d_out_cuda_frame failed with error code 0` using the current PyTorch master and nightly binaries tested on:
* TitanV, CUDA10.0
* P100, CUDA10.1
* V100, CUDA10.1

Related PR: [link](https://github.com/pytorch/pytorch/pull/24818)
CC @skrah, @ezyang 
Is this test being skipped due to:
`@unittest.skipIf(not TEST_LARGE_TENSOR, "not enough memory")`?

## To Reproduce

```python
import torch

x = torch.randn(1, 1, 1, 2**31 - 1, dtype=torch.float16, device="cuda")
expected = x[0, 0, 0, 2**31 - 2]
y = torch.nn.functional.avg_pool2d(x, kernel_size=1)
torch.cuda.synchronize()

> RuntimeError: avg_pool2d_out_cuda_frame failed with error code 0
```

## Expected behavior

Test should pass.

## Environment

Failing on `3f72bcfc`, `24ae9b5`, `1.3.0.dev20190923`, and `1.3.0.dev20190925`.

CC @ngimel

cc @ezyang @gchanan @zou3519

**Comment by zasdfgbnm** [comment]
I guess because
```python
TEST_LARGE_TENSOR = torch.cuda.get_device_properties(0).total_memory >= 12e9
```
Circle CI seems don't have a single GPU that has as large as 12G RAM. What they have could be seen from the `nvidia-smi` during build. For example in https://circleci.com/gh/pytorch/pytorch/2516062?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
+ nvidia-smi
Tue Aug 20 15:31:06 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   38C    P0    46W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   40C    P0    41W / 150W |      0MiB /  7618MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by ezyang** [comment]
@yf225 Reclassifying as CUDA: there is a CI problem which prevents us from observing the problem, but there's another bug as well on the issue.

**Comment by peterjc123** [comment]
We could reproduce it on CircleCI with the windows images:
https://app.circleci.com/jobs/github/pytorch/pytorch/3524284
Could you please skip it for now?

**Comment by ezyang** [comment]
I've reproduced this locally on two different configurations too.

**Comment by skrah** [comment]
The CI situation is strange.  I'm pretty sure that I didn't see a skip on some CIs when I wrote that test, so I assumed it was OK.

Perhaps 12GB is just too little, the 6GB limit for the other test also required some experiments because the exact amount of memory is hard to tell.

**Comment by skrah** [comment]
I only have a 6GB card here, so I cannot test.

**Comment by ezyang** [comment]
@skrah I think this is a regression of some sort, because I definitely recall that `test_cuda.py` was working in the past. :/

**Comment by ptrblck** [comment]
@ezyang Could it be that the test was skipped in CI (comment 2: https://github.com/pytorch/pytorch/issues/26838#issuecomment-535198937) due to the GPU memory limitation or was it executed on another machine?
We've seen the failure right after the initial commit.

**Comment by ezyang** [comment]
The test was always skipped in CI. I guess if you saw it after the initial commit the test never actually worked :(

**Comment by ptrblck** [comment]
@ezyang If you need to run some tests on bigger GPUs (for a PR with a fix), feel free to ping me, so that I could run it before merging.
Once a possible fix is merged, we'll put it in our CI anyway.

**Comment by skrah** [comment]
Perhaps I had only seen the ROCm test on the CI and concluded that it was the only CI machine with sufficient memory:

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/8848/consoleFull

"""
11:48:39 test_cuda_kernel_loop_overflow (__main__.TestCuda) ... ok
11:48:39 test_cuda_kernel_loop_overflow_large (__main__.TestCuda) ... ok
"""

Or ROCm uses less memory.

**Comment by skrah** [comment]
On CUDA, does the test fail only with 12GB or also with 24GB cards?

**Comment by ptrblck** [comment]
I tested it on P100 (16GB) and V100 (32GB) and the code snippet fails on both cards.

**Comment by ngimel** [comment]
Hm, do we understand why it's taking so much memory?

**Comment by ptrblck** [comment]
It's failing with the same error message as mentioned in the initial post:
```python
RuntimeError: avg_pool2d_out_cuda_frame failed with error code 0
```

I'm not sure, if we have seen an OOM issue here.
If I understand the problem correctly, the test was never executed in the CI due to 
```
@unittest.skipIf(not TEST_LARGE_TENSOR, "not enough memory")
```
and
```python
TEST_LARGE_TENSOR = torch.cuda.get_device_properties(0).total_memory >= 12e9
```
, while apparently CI uses `M60` GPUs, which will skip this test.

**Comment by ngimel** [comment]
There was a hot fix for 1.3 that apparently never got merged to master https://github.com/pytorch/pytorch/commit/024fa347003e39d616aa0d1c8e8bb5be2d8a0ec4 - can you guys please check if it fixes the issue?
If it does, @ptrblck can you please make sure that large memory tests are run in your CI and not disabled?

**Comment by skrah** [comment]
I can't check (6GB card), but  024fa34 should fix the issue.

It looks like ATenCeilDiv() can overflow, perhaps it's worth fixing that function directly.

**Comment by ptrblck** [comment]
@ngimel I cherry-picked the commit on top of current master and the provided repro code as well as `python test/test_cuda.py TestCuda.test_cuda_kernel_loop_overflow_large` now run successfully.

Please ping me once this PR is merged to master and we will execute the test in our CI.

**Comment by ngimel** [comment]
The fix #30771 has landed, @ptrblck please re-enable the tests in your CI. I'll send a PR to re-enable the test on master, but it still won't be run in the regular CI because of memory limitation, will likely be run in windows CI only.
