### ISSUE TITLE
ONNX export failed on ATen operator mv 

### ISSUE THREAD

**Issue by ozgurshn** [pytorch/pytorch#27723]
## 🐛 Bug
I run this code on [Colab](https://colab.research.google.com/drive/1zRUeHSid0PEbZULODFowxOqxc5R6dvja) 
Running torch.onnx.export gives this error.

> /content/DeOldify/deoldify/unet.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if ssh != up_out.shape[-2:]:
> /usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:562: UserWarning: ONNX export failed on ATen operator mv because torch.onnx.symbolic_opset9.mv does not exist
>   .format(op_name, opset_version, op_name))
> 
> 
> KeyError                                  Traceback (most recent call last)
> <ipython-input-11-6588fcd71ffa> in <module>()
>       1 dummy_input = torch.randn(1, 3, 224, 224)
>       2 
> ----> 3 torch.onnx.export(learn.model.cpu(), dummy_input, "colorizer.onnx")
> 
> 7 frames
> /usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
>      89         warnings.warn("ONNX export failed. The ONNX domain and/or version are None.")
>      90     global _registry
> ---> 91     return _registry[(domain, version)][opname]
> 
> KeyError: 'mv'

## To Reproduce

1.
Running this code

```
!git clone https://github.com/jantic/DeOldify.git DeOldify 

cd DeOldify

!pip install -r requirements.txt

import fastai
from deoldify.visualize import *

torch.backends.cudnn.benchmark = True
!mkdir 'models'
!wget https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0 -O ./models/ColorizeArtistic_gen.pth

from deoldify.generators import gen_inference_deep, gen_inference_wide

root_folder:Path=Path('./')
weights_name:str='ColorizeArtistic_gen'

learn = gen_inference_deep(root_folder=root_folder, weights_name=weights_name)

dummy_input = torch.randn(1, 3, 224, 224)

torch.onnx.export(learn.model.cpu(), dummy_input, "colorizer.onnx")

```

## Expected behavior

I expect the conversion to Onnx.

## Environment

 - PyTorch Version:  1.2.0
 - OS : Linux
 - How you installed PyTorch:pip
 - Python version:3.6

**Comment by Sxela** [comment]
Looks like it's because of the Spectral normalization. Works fine with Weight normalization.

**Comment by jantic** [comment]
You can simply strip Spectral Normalization from a fully trained model just before exporting to Onnx to get rid of this error. I just ran my model through this code I hacked together:

```
def remove_all_spectral_norm(item):
    if isinstance(item, nn.Module):
        try:
            nn.utils.remove_spectral_norm(item)
        except Exception:
            pass
        
        for child in item.children():  
            remove_all_spectral_norm(child)

    if isinstance(item, nn.ModuleList):
        for module in item:
            remove_all_spectral_norm(module)

    if isinstance(item, nn.Sequential):
        modules = item.children()
        for module in modules:
            remove_all_spectral_norm(module)
```

**Comment by jantic** [comment]
@jcowles  I agree that the exporter failing in the way it does isn't great, at all. You really have to dig just to figure out what's going on.

You don't need spectral_norm added back in as long as you're done training the model and are just going to use it for inference after that point (which I'm assuming is why you'd be exporting to ONNX in the first place).  The weight calculations done by spectral_norm get baked in as final weights by the removal code itself.

To clarify on this:

> Side note: the code above exists in PyTorch officially as torch.nn.utils.remove_spectral_norm

I just made the code so that it's fully recursive on any model you throw into it- you don't get that out of the box. So it's not the same and I want people to know that.

**Comment by jcowles** [comment]
Makes sense.

In our case, we export ONNX files periodically along with checkpoints, so a one-way conversion is not ideal.

**Comment by jcowles** [comment]
BTW, your code above could be simplified to just this, correct?

```
for layer in model.modules():
  torch.nn.utils.remove_spectral_norm(layer)
```

**Comment by jantic** [comment]
@jcowles If I remember correctly (can't test today)- this part of the torch removal code was problematic:

**Comment by Mut1nyJD** [comment]
Hmm I'll get a similar message but it says not ATen operator mv but just mv in Torch1.6 trying to export a model to ONNX, but it says RuntimeError:Exporting the operator mv to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for this missing operator. I tried the spectral norm removal trick but that did not make it work unfortunately

**Comment by jantic** [comment]
@Mut1nyJD You say similar but from the sounds of it the export could just as well be complaining about any number of operators.  Spectral norm is just one of many it can have a problem with. It'll have the same basic message structure for any operator that's not supported as far as I've seen.  For example, I haven't been able to export BiTM-based models because of this bug:  https://github.com/pytorch/pytorch/issues/39349 .

**Comment by Mut1nyJD** [comment]
@jantic 
Well yes that's true. What I am seeing is that the error message is instead of failed on "ATen operator mv" 

it says for me

"failed on operator mv"

So that might be the same operator and the naming has changed between PyTorch 1.3/1.4 when this bug was originally filed and the current 1.6 release or it is a different one.

But I thought before opening another issue pointing to the same problem I look first what has already been filed and I came across this one so I just want to check if this is the same problem, a related problem or a completely unrelated issue.

**Comment by tmachnitzki** [comment]
I get the exact same error as @Mut1nyJD when using spectral norm. Without spectral norm I can export the model as expected. Someone already tried approaching this issue from the ONNX site, but was redirected to the pytorch-repo: https://github.com/onnx/onnx/issues/3006

**Comment by BowenBao** [comment]
Should be resolved by #55470, will soon reflect on master.

**Comment by BowenBao** [comment]
To fully support `spectral_norm` (which seems to be the actual underlying op needed), export for `dot` is also needed. That will be added soon as well.

**Comment by rushirajsherlocked** [comment]
> To fully support `spectral_norm` (which seems to be the actual underlying op needed), export for `dot` is also needed. That will be added soon as well.

I think The `dot` operation is still not added. I just encountered this issue today again. Any guess when will this be added??

**Comment by BowenBao** [comment]
@rushirajsherlocked Thanks for spotting. Adding PR #62596. The change is simple, feel free to apply locally and give it a try, while it is being merged.
