### ISSUE TITLE
Module 'torch.nn' has no attribute 'backends' 

### ISSUE THREAD

**Issue by YuryBolkonsky** [pytorch/pytorch#28277]
Pytorch 1.3, Windows10, apex 0.1

in 
10 opt_level = 'O1'
11 model.cuda()
---> 12 model, optimizer = amp.initialize(model, optimizer, opt_level=opt_level)
13 scheduler = ReduceLROnPlateau(optimizer, factor=0.5, patience=2)

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\frontend.py in initialize(models, optimizers, enabled, opt_level, cast_model_type, patch_torch_functions, keep_batchnorm_fp32, master_weights, loss_scale, cast_model_outputs, num_losses, verbosity, min_loss_scale, max_loss_scale)
355 maybe_print("{:22} : {}".format(k, v), True)
356
--> 357 return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
358
359

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp_initialize.py in _initialize(models, optimizers, properties, num_losses, cast_model_outputs)
239 if properties.patch_torch_functions:
240 # handle is unused here. It's accessible later through a global value anyway.
--> 241 handle = amp_init(loss_scale=properties.loss_scale, verbose=(_amp_state.verbosity == 2))
242 for optimizer in optimizers:
243 # Disable Amp casting for the optimizer step, because it should only be

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\amp.py in init(enabled, loss_scale, enable_caching, verbose, allow_banned)
99 try_caching = (cast_fn == utils.maybe_half)
100 wrap.cached_cast(module.MODULE, fn, cast_fn, handle,
--> 101 try_caching, verbose)
102
103 # 1.5) Pre-0.4, put the blacklist methods on HalfTensor and whitelist

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\wrap.py in cached_cast(mod, fn, cast_fn, handle, try_caching, verbose)
31 def cached_cast(mod, fn, cast_fn, handle,
32 try_caching=False, verbose=False):
---> 33 if not utils.has_func(mod, fn):
34 return
35

c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\utils.py in has_func(mod, fn)
130
131 def has_func(mod, fn):
--> 132 if isinstance(mod, torch.nn.backends.backend.FunctionBackend):
133 return fn in mod.function_classes
134 elif isinstance(mod, dict):

AttributeError: module 'torch.nn' has no attribute 'backends'

**Comment by t-vi** [comment]
This has been fixed in apex, so you would want to upgrade:
https://github.com/NVIDIA/apex/pull/466

**Comment by YuryBolkonsky** [comment]
@t-vi it's not fixed. in NVIDIA/apex#466 there is another user who also has this problem

**Comment by t-vi** [comment]
Yeah, well, if you use apex from some discontinued branch (I don't find the branch the user mentioned on github), you would not expect it to have the latest fixes. If you use apex from the branch that got the fix, it has the fix. I would advise to move the discussion to apex.

**Comment by kamrankausar** [comment]
>>> torch.backend.cudnn.version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'backend'
>>>

**Comment by t-vi** [comment]
@kamrankausar  Try backend*s* with a s.

**Comment by STITCHESHHH** [comment]
Pytorch 1.8, Windows10, apex 0.1
File "C:\Users\Administrator\anaconda3\envs\mypytorch\lib\site-packages\apex\amp\utils.py", line 132, in has_func
    if isinstance(mod, torch.nn.backends.backend.FunctionBackends):
                  │    │     └ <module 'torch.nn' from 'C:\\Users\\Administrator\\anaconda3\\envs\\mypytorch\\lib\\site-packages\\torch\\nn\\__init__.py'>       
                  │    └ <module 'torch' from 'C:\\Users\\Administrator\\anaconda3\\envs\\mypytorch\\lib\\site-packages\\torch\\__init__.py'>
                  └ <module 'torch.nn.functional' from 'C:\\Users\\Administrator\\anaconda3\\envs\\mypytorch\\lib\\site-packages\\torch\\nn\\func...

AttributeError: module 'torch.nn' has no attribute 'backends

**Comment by STITCHESHHH** [comment]
> Pytorch 1.3, Windows10, apex 0.1
> 
> in 10 opt_level = 'O1' 11 model.cuda() ---> 12 model, optimizer = amp.initialize(model, optimizer, opt_level=opt_level) 13 scheduler = ReduceLROnPlateau(optimizer, factor=0.5, patience=2)
> 
> c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\frontend.py in initialize(models, optimizers, enabled, opt_level, cast_model_type, patch_torch_functions, keep_batchnorm_fp32, master_weights, loss_scale, cast_model_outputs, num_losses, verbosity, min_loss_scale, max_loss_scale) 355 maybe_print("{:22} : {}".format(k, v), True) 356 --> 357 return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs) 358 359
> 
> c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp_initialize.py in _initialize(models, optimizers, properties, num_losses, cast_model_outputs) 239 if properties.patch_torch_functions: 240 # handle is unused here. It's accessible later through a global value anyway. --> 241 handle = amp_init(loss_scale=properties.loss_scale, verbose=(_amp_state.verbosity == 2)) 242 for optimizer in optimizers: 243 # Disable Amp casting for the optimizer step, because it should only be
> 
> c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\amp.py in init(enabled, loss_scale, enable_caching, verbose, allow_banned) 99 try_caching = (cast_fn == utils.maybe_half) 100 wrap.cached_cast(module.MODULE, fn, cast_fn, handle, --> 101 try_caching, verbose) 102 103 # 1.5) Pre-0.4, put the blacklist methods on HalfTensor and whitelist
> 
> c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\wrap.py in cached_cast(mod, fn, cast_fn, handle, try_caching, verbose) 31 def cached_cast(mod, fn, cast_fn, handle, 32 try_caching=False, verbose=False): ---> 33 if not utils.has_func(mod, fn): 34 return 35
> 
> c:\apps\python3.7.3_64bit\lib\site-packages\apex\amp\utils.py in has_func(mod, fn) 130 131 def has_func(mod, fn): --> 132 if isinstance(mod, torch.nn.backends.backend.FunctionBackend): 133 return fn in mod.function_classes 134 elif isinstance(mod, dict):
> 
> AttributeError: module 'torch.nn' has no attribute 'backends'

friend,did you solve it

**Comment by t-vi** [comment]
you could edit the source location where it says torch.nn.backends to use torch.backends...
Note that this is in apex, not PyTorch.

**Comment by STITCHESHHH** [comment]
> you could edit the source location where it says torch.nn.backends to use torch.backends... Note that this is in apex, not PyTorch.

okey

**Comment by ShunLu91** [comment]
This problem is caused by the mismatch between the Pytorch version and the apex.
I changed the installed apex version to 22.03 for my Pytorch 1.6.0 with Cuda 10.2 from the released version and solved this problem.
