### ISSUE TITLE
Typing Error in nn.Module

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#31765]
## 🐛 Bug

[Type of `nn.Module`](https://github.com/pytorch/pytorch/blob/cb1af5f61fb338c591e6427fd274ea5b44df4f26/torch/nn/modules/module.pyi.in#L16) is 

```python
T_co = TypeVar('T_co', covariant=True)


class Module(Generic[T_co]):
    def __init__(self) -> None: ...

    def forward(self, *input: Any, **kwargs: Any) -> T_co: ...  # type: ignore

    def __call__(self, *input: Any, **kwargs: Any) -> T_co: ...  # type: ignore
```

and I expected below code does not raise any error.

```python
class SomeModel(nn.Module[torch.Tensor]):
    def forward(self, input_tensor: torch.Tensor) -> torch.Tensor:
        # some codes
```

But, in [`torch/nn/modules/modules.py`](https://github.com/pytorch/pytorch/blob/cb1af5f61fb338c591e6427fd274ea5b44df4f26/torch/nn/modules/module.py#L30), `nn.Module` does not inherit `typing.Generic`. So above code snippet raises an error.

```text
{some-path-to-python-file.py}:{some-line}: in <module>
    class SomeModel(nn.Module[torch.Tensor]):
E   TypeError: 'type' object is not subscriptable
```

## To Reproduce

1. run below code snippet

```python
import torch
from torch import nn


class SomeModel(nn.Module[torch.Tensor]):
    def __init__(self):
        super().__init__()

    def forward(self, input_tensor: torch.Tensor) -> torch.Tensor:
        return input_tensor
```

## Expected behavior

```python
class SomeModel(nn.Module[torch.Tensor]):
    def forward(self, input_tensor: torch.Tensor) -> torch.Tensor:
        # some codes
```

Above code snippet should not raise errors.

## Environment

```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.2
GCC version: Could not collect
CMake version: version 3.16.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] torch==1.3.1
[conda] Could not collect
```

cc @ezyang

**Comment by ezyang** [comment]
I'm not too familiar with the interaction of pyi files and generics, but I do find it mildly surprising that you have to modify the py file to make generics work. (This might be mooted when we move to py3 and move all the annotations inline). In any case, this seems like a legitimate problem with the generic annotations.

CC'ing @malmaud in case you have better ideas

**Comment by malmaud** [comment]
Hmm, what linter is reporting this error and how is it configured? My first suspicion is this is just the linter not being typestub-aware and not something wrong with the content of the typestub. mypy doesn't have a problem with that class declaration.

**Comment by jeongukjae** [comment]
@malmaud Yes. mypy and pyright doesn’t have a problem, but executing that code has a problem. I think that is because nn.Module doesn’t inherit typing.Generic in .py file. (not .pyi file)

**Comment by llchan** [comment]
This is a fairly common issue with generics defined out-of-band: https://mypy.readthedocs.io/en/stable/common_issues.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

**Comment by rgommers** [comment]
I can reproduce this with 1.4.0 and see that it's fixed in 1.5.0. The reason it works there is that in `module.pyi` `forward` is now annotated as:
```
forward: Callable[..., T_co]
```
And in master it typechecks fine as well. Running mypy over `test/test_nn.py` (not working yet) will cover this in the test suite, so there's no need to add a separate test case. So closing. Thanks for the report @jeongukjae and everyone else for feedback.

**Comment by alsrgv** [comment]
I'd like to double check statement about this working fine in 1.5.0:
```
In [1]: import torch

In [2]: import torch.nn as nn

In [3]: torch.__version__
Out[3]: '1.5.0+cu101'

In [4]: class SomeModel(nn.Module[torch.Tensor]):
   ...:     def forward(self, input_tensor: torch.Tensor) -> torch.Tensor:
   ...:         pass
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f4dfc3a19320> in <module>
----> 1 class SomeModel(nn.Module[torch.Tensor]):
      2     def forward(self, input_tensor: torch.Tensor) -> torch.Tensor:
      3         pass
      4

TypeError: 'type' object is not subscriptable
```
cc @rgommers

**Comment by jeongukjae** [comment]
I checked this issue again but the error still exists.

```python
Python 3.7.5 (default, Dec 23 2019, 12:52:20)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.5.0'
>>> class SomeModel(torch.nn.Module[torch.Tensor]):
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
>>>
```

tested on macOS, python 3.7.5, pytorch 1.5.0.

I think this issue should be reopened.

**Comment by rgommers** [comment]
Sorry, reading my comment above the `mypy` behavior changed on that code snippet, actually running it still raises that error in both 1.5.0 and master. Reopening.

**Comment by ezyang** [comment]
This will get fixed when we move the Generic include inline into module.py... assuming I can fix the JIT bugs in this PR: https://github.com/pytorch/pytorch/pull/38211

**Comment by alsrgv** [comment]
Somewhat unrelated, but similar - is there a plan to make `# type: ignore` possible for situations where mypy is unhappy on a per-function basis?  Currently JIT crashes upon seeing such annotations.

**Comment by ezyang** [comment]
cc @suo for the JIT question. However, I think the JIT relies on being able to determine accurate types since it's compilation process assumes well-typed programs.

**Comment by jeongukjae** [comment]
@ezyang 

I saw this comment(https://github.com/pytorch/pytorch/pull/38211#issuecomment-640153288), this commit message(https://github.com/pytorch/pytorch/pull/38211/commits/4f26b2bb33f43535fdd7279543e3f79ffe0f12df, https://github.com/pytorch/pytorch/commit/eace0533985641d9c2f36e43e3de694aca886bd9), and bpo issue(https://bugs.python.org/issue40897). I think this issue can be closed because it is reasonable to give up typing `nn.Module` currently.

Anyway, thanks for your works for this issue :)
