### ISSUE TITLE
[ONNX] scatter_add may result in wrong ONNX

### ISSUE THREAD

**Issue by shinh** [pytorch/pytorch#32960]
## 🐛 Bug

torch.onnx translates scatter_add to Scatter, but I think this is a wrong translation when elements in `index` are not unique. See the script in the repro.

## To Reproduce

1. Run the following script
1. ONNX runtime refuses to run the output ONNX

```
import onnx
import onnx.numpy_helper
import torch
import onnxruntime as rt


class Model(torch.nn.Module):
    def forward(self, data, indices, updates):
        return torch.scatter_add(data, 0, indices, updates)

model = Model()
data = torch.tensor([0.0])
indices = torch.tensor([0, 0, 0])
updates = torch.tensor([1.2, 2.3, 3.4])
# This works.
# indices = torch.tensor([0])
# updates = torch.tensor([1.2])
torch.onnx.export(model, (data, indices, updates), 'scatter_add.onnx')

m = onnx.load('scatter_add.onnx')
sess = rt.InferenceSession('scatter_add.onnx')
inputs = {m.graph.input[0].name: data.numpy(),
          m.graph.input[1].name: indices.numpy(),
          m.graph.input[2].name: updates.numpy()}
assert sess.run([m.graph.output[0].name], inputs)[0] == model(data, indices, updates).numpy()
```

## Expected behavior

I think ONNX currently does not have ScatterAdd. I doubt it cannot be implemented in the current ONNX and we should add a new op. That said, torch.onnx should probably show an error message when indices are not unique?

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.4.0
[pip3] torchvision==0.2.1
[pip3] warpctc-pytorch==0.1
[conda] Could not collect

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by dashesy** [comment]
You can use `torch.scatter` like [here](https://github.com/pytorch/pytorch/issues/26472)

**Comment by shinh** [comment]
Isn't https://github.com/pytorch/pytorch/issues/26472 a different issue? If I understand correctly,
```
data = torch.tensor([0.0])
indices = torch.tensor([0, 0, 0])
updates = torch.tensor([1.2, 2.3, 3.4])
print(torch.scatter_add(data, 0, indices, updates))  # [6.9]
```
cannot be implemented by `torch.scatter`. If you were talking about `w = torch.scatter(w, 0, idx, w[idx] + input_x[idx])`, I think this works only when indices are unique.

**Comment by BowenBao** [comment]
@shinh Thanks for creating this issue. Indeed the case where indices are not unique is not supported by current exporter.

**Comment by shinh** [comment]
Unfortunately, we cannot make the model open :(

**Comment by Nifury** [comment]
@BowenBao Sparse matrix multiplication is affected by this issue.

**Comment by ThorJonsson** [comment]
Is there any progress on this?

**Comment by ennauata** [comment]
Any update on this?

**Comment by spandantiwari** [comment]
We will take a look. Can anyone comfirm seeing this issue in latest PyTorch (1.8 or 1.8.1)?

**Comment by Nifury** [comment]
> We will take a look. Can anyone comfirm seeing this issue in latest PyTorch (1.8 or 1.8.1)?

Yes this issue still exists in the latest PyTorch. 
As @shinh points out, the root cause is that ONNX currently does not have ScatterAdd.

**Comment by shubhambhokare1** [comment]
Currently looking at issue. Can confirm that this issue exists in latest PyTorch

**Comment by ThorJonsson** [comment]
Since this issue has been open for a long time can anyone at PyTorch or ONNX give a breakdown of what is needed to close this issue via pull request from the community? What are the steps needed to add this op to ONNX?

**Comment by ThorJonsson** [comment]
> @shinh Thanks for creating this issue. Indeed the case where indices are not unique is not supported by current exporter.
> Is there a model that is being affected by this issue?

All models that rely on sparse matrix multiplications and sparse convolutions.

**Comment by levants** [comment]
Any update on this?

**Comment by levants** [comment]
> ONNX PR in progress [onnx/onnx#3484](https://github.com/onnx/onnx/pull/3484)

It was already merged, we have  "scatter" with reduction for ops 16 https://github.com/onnx/onnx/blob/master/docs/Operators.md#ScatterElements

**Comment by BowenBao** [comment]
Tracked internally at Microsoft https://msdata.visualstudio.com/Vienna/_workitems/edit/1542296

**Comment by EJShim** [comment]
I guess that this issue is resolved in the latest ONNX. Do I have to wait for pytorch to support onnx opset 16 ?

**Comment by barynton** [comment]
Found this https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset16.py 
Does it mean that opset 16 is supported?

**Comment by tony-laoshi** [comment]
> Found this https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset16.py Does it mean that opset 16 is supported?

It looks like it supports opset_version 16, but I downloaded the entire **onnx** file and still have problems using it. Could you tell me how you solved it? I mean do you have success with **opset_version 16**?

**Comment by tony-laoshi** [comment]
> Found this https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset16.py Does it mean that opset 16 is supported?

The stable version of **pytorch 1.11** installed via **conda** still does not seem to support **opset 16** . I tried to download the latest **pytorch 1.12dev** but it didn't install and I have no idea about it. Maybe I should wait patiently for the next release of the stable version

**Comment by barynton** [comment]
`pip install https://download.pytorch.org/whl/nightly/cu113/torch-1.12.0.dev20220516+cu113-cp38-cp38-linux_x86_64.whl`
worked well for me, additionally built latest scatter and sparse. I can run torch.onnx.export with  opset_version=16, but have a different error which is no connected to the topic:

`torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator prim::isinstance to ONNX opset version 16 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

**Comment by linccnu** [comment]
Any update on this? I met this problem also.

**Comment by EJShim** [comment]
I successfully exported my torch model including `torch.scatter_add` operations with parameter `opset_version=16`.

but I still get wrong results when I import model using `onnxruntime`

exported `torch.scatter_add` operations still work like `torch.scatter`.

There is no difference using previous `opset_version`
