### ISSUE TITLE
Conda install from pytorch-nightly channel with cpu-only option delivers 1.3.1 version

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/pytorch#33103]
## 🐛 Bug

Conda install from pytorch-nightly channel with cpu-only options delivers 1.3.1 version instead of 1.5.0 (python 3.7)

## To Reproduce

```
user:/# python --version
Python 3.7.5
user:/# conda install pytorch torchvision cpuonly -c pytorch-nightly

The following packages will be downloaded:    package                    |            build
    ---------------------------|-----------------
    _pytorch_select-0.2        |            gpu_0           2 KB
    cpuonly-1.0                |                0           2 KB  pytorch-nightly
    cudatoolkit-10.0.130       |                0       261.2 MB
    cudnn-7.6.5                |       cuda10.0_0       165.0 MB
    intel-openmp-2020.0        |              166         756 KB
    mkl-2020.0                 |              166       128.9 MB
    numpy-1.18.1               |   py37h4f9e942_0           5 KB
    numpy-base-1.18.1          |   py37hde5b4d6_1         4.2 MB
    pytorch-1.3.1              |cuda100py37h53c1284_0       169.0 MB
    six-1.14.0                 |           py37_0          27 KB
    torchvision-0.4.2          |cuda100py37hecfc37a_0         6.4 MB
    ------------------------------------------------------------
                                           Total:       735.4 MB
```

## Expected behavior

Conda should install 1.5.0 CPU-only version from pytorch-nightly channel.

## Environment

 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.
 - CUDA/cuDNN version: No
 - GPU models and configuration: No
 - Any other relevant information:

cc @ezyang @gchanan @zou3519 @seemethere 

PS: Ignite's CI relies on this. Cross-link: https://github.com/pytorch/ignite/pull/768#issuecomment-583444440

**Comment by seemethere** [comment]
Yea appears as though it's not pulling from the correct channel for the `pytorch` package:

```
  _pytorch_select    pkgs/main/linux-64::_pytorch_select-0.2-gpu_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  cffi               pkgs/main/linux-64::cffi-1.13.2-py37h2e261b9_0
  cpuonly            pytorch-nightly/noarch::cpuonly-1.0-0
  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.0.130-0
  cudnn              pkgs/main/linux-64::cudnn-7.6.5-cuda10.0_0
  freetype           pkgs/main/linux-64::freetype-2.9.1-h8a8886c_1
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.0-166
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libtiff            pkgs/main/linux-64::libtiff-4.1.0-h2733197_0
  mkl                pkgs/main/linux-64::mkl-2020.0-166
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py37he904b0f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.0.15-py37ha843d7b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.0-py37hd6b4f25_0
  ninja              pkgs/main/linux-64::ninja-1.9.0-py37hfd86e86_0
  numpy              pkgs/main/linux-64::numpy-1.18.1-py37h4f9e942_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.18.1-py37hde5b4d6_1
  olefile            pkgs/main/linux-64::olefile-0.46-py37_0
  pillow             pkgs/main/linux-64::pillow-7.0.0-py37hb39fc2d_0
  pycparser          pkgs/main/linux-64::pycparser-2.19-py37_0
  pytorch            pkgs/main/linux-64::pytorch-1.3.1-cuda100py37h53c1284_0
  six                pkgs/main/linux-64::six-1.14.0-py37_0
  torchvision        pkgs/main/linux-64::torchvision-0.4.2-cuda100py37hecfc37a_0
  zstd               pkgs/main/linux-64::zstd-1.3.7-h0b5b093_0
```

Note that it's pulling from the `pkgs/main/linux-64` for the `pytorch-1.3.1-cuda100py37h53c1284_0` package.

Interestingly enough, when I remove `torchvision` from the command it does the thing we would expect:

```
❯ conda install -c pytorch-nightly pytorch cpuonly

...

The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  cpuonly            pytorch-nightly/noarch::cpuonly-1.0-0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.0-166
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  mkl                pkgs/main/linux-64::mkl-2020.0-166
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py37he904b0f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.0.15-py37ha843d7b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.0-py37hd6b4f25_0
  ninja              pkgs/main/linux-64::ninja-1.9.0-py37hfd86e86_0
  numpy              pkgs/main/linux-64::numpy-1.18.1-py37h4f9e942_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.18.1-py37hde5b4d6_1
  pytorch            pytorch-nightly/linux-64::pytorch-1.5.0.dev20200207-py3.7_cpu_0
  six                pkgs/main/linux-64::six-1.14.0-py37_0
```

I believe this has something to do with the `nightly` versions of `torchvision` not having a version available for `linux-64/py3.7`,

**Comment by vfdev-5** [comment]
@seemethere thanks for the investigations! Hopefully this can unlock merging our PRs :)

**Comment by ptrblck** [comment]
@seemethere 
It seems as if `torchvision` was only built for Python3.5 in the `pytorch-nightly` channel:
```python
conda search torchvision -c pytorch-nightly
Loading channels: done
# Name                       Version           Build  Channel             
torchvision                    0.2.0          py27_0  pkgs/main           
torchvision                    0.2.0          py35_0  pkgs/main           
torchvision                    0.2.0          py36_0  pkgs/main           
torchvision                    0.2.1          py27_0  pkgs/main           
torchvision                    0.2.1          py35_0  pkgs/main           
torchvision                    0.2.1          py36_0  pkgs/main           
torchvision                    0.2.1          py37_0  pkgs/main           
torchvision                    0.3.0 cuda100py27h72fc40a_0  pkgs/main           
torchvision                    0.3.0 cuda100py36h72fc40a_0  pkgs/main           
torchvision                    0.3.0 cuda100py37h72fc40a_0  pkgs/main           
torchvision                    0.3.0 cuda90py27h6edc907_0  pkgs/main           
torchvision                    0.3.0 cuda90py36h6edc907_0  pkgs/main           
torchvision                    0.3.0 cuda90py37h6edc907_0  pkgs/main           
torchvision                    0.3.0 cuda92py27h0601742_0  pkgs/main           
torchvision                    0.3.0 cuda92py36h0601742_0  pkgs/main           
torchvision                    0.3.0 cuda92py37h0601742_0  pkgs/main           
torchvision                    0.4.0 cpu_py27h1e143f5_0  pkgs/main           
torchvision                    0.4.0 cpu_py36h1e143f5_0  pkgs/main           
torchvision                    0.4.0 cpu_py37h1e143f5_0  pkgs/main           
torchvision                    0.4.0 cuda100py27hecfc37a_0  pkgs/main           
torchvision                    0.4.0 cuda100py36hecfc37a_0  pkgs/main           
torchvision                    0.4.0 cuda100py37hecfc37a_0  pkgs/main           
torchvision                    0.4.0 cuda92py27h1667eeb_0  pkgs/main           
torchvision                    0.4.0 cuda92py36h1667eeb_0  pkgs/main           
torchvision                    0.4.0 cuda92py37h1667eeb_0  pkgs/main           
torchvision                    0.4.2 cpu_py27h9ec355b_0  pkgs/main           
torchvision                    0.4.2 cpu_py36h9ec355b_0  pkgs/main           
torchvision                    0.4.2 cpu_py37h9ec355b_0  pkgs/main           
torchvision                    0.4.2 cuda100py27hecfc37a_0  pkgs/main           
torchvision                    0.4.2 cuda100py36hecfc37a_0  pkgs/main           
torchvision                    0.4.2 cuda100py37hecfc37a_0  pkgs/main           
torchvision                    0.4.2 cuda92py27h1667eeb_0  pkgs/main           
torchvision                    0.4.2 cuda92py36h1667eeb_0  pkgs/main           
torchvision                    0.4.2 cuda92py37h1667eeb_0  pkgs/main           
torchvision          0.6.0.dev20200207        py35_cpu  pytorch-nightly     
torchvision          0.6.0.dev20200207      py35_cu100  pytorch-nightly     
torchvision          0.6.0.dev20200207      py35_cu101  pytorch-nightly     
torchvision          0.6.0.dev20200207       py35_cu92  pytorch-nightly     
torchvision          0.6.0.dev20200208        py35_cpu  pytorch-nightly     
torchvision          0.6.0.dev20200208      py35_cu100  pytorch-nightly     
torchvision          0.6.0.dev20200208      py35_cu101  pytorch-nightly     
torchvision          0.6.0.dev20200208       py35_cu92  pytorch-nightly     
```

**Comment by fmassa** [comment]
I suspect this might be related to https://github.com/pytorch/pytorch/issues/33091

**Comment by zou3519** [comment]
@fmassa #33091 could be related if some of the torchvision builds are failing. Do you have a link to a failing build?

**Comment by ngoldbaum** [comment]
This is fixed now:

```
The following NEW packages will be INSTALLED:

  cpuonly            pytorch-nightly/noarch::cpuonly-1.0-0
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc3755c2_3
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  olefile            conda-forge/noarch::olefile-0.46-py_0
  pillow             conda-forge/linux-64::pillow-7.0.0-py37hefe7db6_0
  pytorch            pytorch-nightly/linux-64::pytorch-1.5.0.dev20200218-py3.7_cpu_0
  torchvision        pytorch-nightly/linux-64::torchvision-0.6.0.dev20200218-py37_cpu
  zstd               conda-forge/linux-64::zstd-1.4.4-h3b9ef0a_1
```

**Comment by vfdev-5** [comment]
Hi @ngoldbaum the issue came back somehow, but now it reproduce only on some platforms (very weird).
For example, [here](https://travis-ci.org/pytorch/ignite/jobs/652835431#L473) it installs 0.4.2 cuda instead of cpu version. But [here](https://github.com/pytorch/ignite/pull/801/checks?check_run_id=456993235#step:3:1704) (it is the same CI code but on Github CI) it install the correct version. (Context : https://github.com/pytorch/ignite/pull/801).
Other devs of ignite confirm me a similar behaviour for different machines.

cc @ykumards

**Comment by ngoldbaum** [comment]
Can you come up with a `conda install` command and platform combination that triggers this? If so it may make more sense to open a new issue, unless the behavior is as described in your original report for this issue.

**Comment by vfdev-5** [comment]
@ngoldbaum ok, here is the command and configs
```
conda create -q -n test-environment pytorch cpuonly torchvision python=3.7 -c pytorch-nightly
```
as defined [here](https://github.com/pytorch/ignite/blob/master/.github/workflows/unittests.yml#L24).
Conda config:
```
     active environment : None
       user config file : /home/runner/.condarc
 populated config files : /home/runner/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.27
       base environment : /home/runner/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/runner/miniconda/pkgs
                          /home/runner/.conda/pkgs
       envs directories : /home/runner/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Linux/5.0.0-1031-azure ubuntu/18.04.4 glibc/2.27
                UID:GID : 1001:115
             netrc file : None
           offline mode : False
```
defined [here](https://github.com/pytorch/ignite/pull/801/checks?check_run_id=460260069#step:3:1624) and this installs now the following
```
 The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _pytorch_select-0.2        |            gpu_0           2 KB
    blas-1.0                   |              mkl           6 KB
    cpuonly-1.0                |                0           2 KB  pytorch-nightly
    cudatoolkit-10.0.130       |                0       261.2 MB
    cudnn-7.6.5                |       cuda10.0_0       165.0 MB
    freetype-2.9.1             |       h8a8886c_1         550 KB
    intel-openmp-2020.0        |              166         756 KB
    jpeg-9b                    |       h024ee3a_2         214 KB
    ld_impl_linux-64-2.33.1    |       h53a641e_7         568 KB
    libgfortran-ng-7.3.0       |       hdf63c60_0        1006 KB
    libpng-1.6.37              |       hbc83047_0         278 KB
    libtiff-4.1.0              |       h2733197_0         447 KB
    mkl-2020.0                 |              166       128.9 MB
    mkl-service-2.3.0          |   py37he904b0f_0         218 KB
    mkl_fft-1.0.15             |   py37ha843d7b_0         154 KB
    mkl_random-1.1.0           |   py37hd6b4f25_0         321 KB
    ninja-1.9.0                |   py37hfd86e86_0         1.2 MB
    numpy-1.18.1               |   py37h4f9e942_0           5 KB
    numpy-base-1.18.1          |   py37hde5b4d6_1         4.2 MB
    olefile-0.46               |           py37_0          50 KB
    pillow-7.0.0               |   py37hb39fc2d_0         598 KB
    python-3.7.6               |       h0371630_2        44.9 MB
    pytorch-1.3.1              |cuda100py37h53c1284_0       169.0 MB
    torchvision-0.4.2          |cuda100py37hecfc37a_0         6.4 MB
    zstd-1.3.7                 |       h0b5b093_0         401 KB
```
based on logs [here](https://github.com/pytorch/ignite/pull/801/checks?check_run_id=460260069#step:3:1680)

**Comment by ngoldbaum** [comment]
I have `channel_priority=strict` in my `.condarc`, which causes conda to detect that there are incompatible packages and then when it tries to generate a report about it, error out with an internal traceback (see https://github.com/conda/conda/issues/9681). So something is clearly broken still, going to re-open.

**Comment by ngoldbaum** [comment]
With conda 4.8.1 I got the following error with `channel_priority=strict`: https://gist.github.com/ngoldbaum/504f9751b678afc08a24120740264ca5.

Without `channel_priority=strict`, it tries to install pytorch 1.3.1 and torchvision 0.4.2: https://gist.github.com/ngoldbaum/f9a7e05957385ebd441eb84892d1abae.

So it seems to only happen intermittently, since it was working when I closed this the other day, and indeed it looks like the last several uploads of `torchvision` only had windows builds: https://anaconda.org/pytorch-nightly/torchvision/files.

That said, there should be installable packages, just from a few days ago:

```
○ conda search torchvision -c pytorch-nightly
Loading channels: done
# Name                       Version           Build  Channel
torchvision                    0.2.0          py27_0  pkgs/main
torchvision                    0.2.0          py35_0  pkgs/main
torchvision                    0.2.0          py36_0  pkgs/main
torchvision                    0.2.1          py27_0  pkgs/main
torchvision                    0.2.1          py35_0  pkgs/main
torchvision                    0.2.1          py36_0  pkgs/main
torchvision                    0.2.1          py37_0  pkgs/main
torchvision                    0.3.0 cuda100py27h72fc40a_0  pkgs/main
torchvision                    0.3.0 cuda100py36h72fc40a_0  pkgs/main
torchvision                    0.3.0 cuda100py37h72fc40a_0  pkgs/main
torchvision                    0.3.0 cuda90py27h6edc907_0  pkgs/main
torchvision                    0.3.0 cuda90py36h6edc907_0  pkgs/main
torchvision                    0.3.0 cuda90py37h6edc907_0  pkgs/main
torchvision                    0.3.0 cuda92py27h0601742_0  pkgs/main
torchvision                    0.3.0 cuda92py36h0601742_0  pkgs/main
torchvision                    0.3.0 cuda92py37h0601742_0  pkgs/main
torchvision                    0.4.0 cpu_py27h1e143f5_0  pkgs/main
torchvision                    0.4.0 cpu_py36h1e143f5_0  pkgs/main
torchvision                    0.4.0 cpu_py37h1e143f5_0  pkgs/main
torchvision                    0.4.0 cuda100py27hecfc37a_0  pkgs/main
torchvision                    0.4.0 cuda100py36hecfc37a_0  pkgs/main
torchvision                    0.4.0 cuda100py37hecfc37a_0  pkgs/main
torchvision                    0.4.0 cuda92py27h1667eeb_0  pkgs/main
torchvision                    0.4.0 cuda92py36h1667eeb_0  pkgs/main
torchvision                    0.4.0 cuda92py37h1667eeb_0  pkgs/main
torchvision                    0.4.2 cpu_py27h9ec355b_0  pkgs/main
torchvision                    0.4.2 cpu_py36h9ec355b_0  pkgs/main
torchvision                    0.4.2 cpu_py37h9ec355b_0  pkgs/main
torchvision                    0.4.2 cuda100py27hecfc37a_0  pkgs/main
torchvision                    0.4.2 cuda100py36hecfc37a_0  pkgs/main
torchvision                    0.4.2 cuda100py37hecfc37a_0  pkgs/main
torchvision                    0.4.2 cuda92py27h1667eeb_0  pkgs/main
torchvision                    0.4.2 cuda92py36h1667eeb_0  pkgs/main
torchvision                    0.4.2 cuda92py37h1667eeb_0  pkgs/main
torchvision          0.6.0.dev20200218        py35_cpu  pytorch-nightly
torchvision          0.6.0.dev20200218      py35_cu100  pytorch-nightly
torchvision          0.6.0.dev20200218      py35_cu101  pytorch-nightly
torchvision          0.6.0.dev20200218       py35_cu92  pytorch-nightly
torchvision          0.6.0.dev20200218        py36_cpu  pytorch-nightly
torchvision          0.6.0.dev20200218      py36_cu100  pytorch-nightly
torchvision          0.6.0.dev20200218      py36_cu101  pytorch-nightly
torchvision          0.6.0.dev20200218       py36_cu92  pytorch-nightly
torchvision          0.6.0.dev20200218        py37_cpu  pytorch-nightly
torchvision          0.6.0.dev20200218      py37_cu100  pytorch-nightly
torchvision          0.6.0.dev20200218      py37_cu101  pytorch-nightly
torchvision          0.6.0.dev20200218       py37_cu92  pytorch-nightly
torchvision          0.6.0.dev20200218        py38_cpu  pytorch-nightly
torchvision          0.6.0.dev20200218      py38_cu100  pytorch-nightly
torchvision          0.6.0.dev20200218      py38_cu101  pytorch-nightly
torchvision          0.6.0.dev20200218       py38_cu92  pytorch-nightly
```

**Comment by ngoldbaum** [comment]
So the issue is that the newest `torchvision` is pinned to ` pytorch 1.5.0.dev20200218`, but that package is no longer available. It looks like it was available few days ago when I tried this.

```
$ conda search --override-channels -c pytorch-nightly torchvision=*=py37* --info | grep "pytorch "
  - pytorch 1.5.0.dev20200218
  - pytorch 1.5.0.dev20200218
  - pytorch 1.5.0.dev20200218
  - pytorch 1.5.0.dev20200218
```

So the fix is to either have looser pinning for `torchvision` on nightly or to fix whatever is breaking the linux and mac package uploads for `torchvision`.

**Comment by vfdev-5** [comment]
@ngoldbaum thanks for the investigations. Hope this will be solved soon from torchvision's side. 
Another solution is to install from master (at least cpu version).

**Comment by fmassa** [comment]
I'm looking into fixing torchvision packaging

**Comment by fmassa** [comment]
This will hopefully be fixed with https://github.com/pytorch/vision/pull/1917

**Comment by fmassa** [comment]
This should be fixed in torchvision now, let us know if this isn't the case
