### ISSUE TITLE
CUDA Out of Memory when trying to allocate 16 EiB

### ISSUE THREAD

**Issue by JosephDiPalma** [pytorch/pytorch#33143]
## 🐛 Bug

When using `torch.float16` as the dtype, 16EiB of GPU memory is requested for allocation for certain tensor shapes.

## To Reproduce

```
>>> import torch
>>> import torchvision.models as models
>>> resnet = models.resnet18().half().cuda()
>>> t = torch.ones([1, 3, 10210, 8641], dtype=torch.float16, device="cuda")
>>> output = resnet(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/resnet.py", line 198, in _forward
    x = self.conv1(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 17179869183.95 GiB (GPU 0; 23.65 GiB total capacity; 3.15 GiB already allocated; 18.80 GiB free; 3.15 GiB reserved in total by PyTorch)
```

Changing the tensor `t` while keeping the rest of the code the same doesn't cause an error as shown below:
```
>>> t = torch.ones([1, 3, 10500, 9000], dtype=torch.float16, device="cuda")
>>> output = resnet(t)
>>> output.shape
torch.Size([1, 1000])
```

## Expected behavior

The correct amount of memory should be allocated.  This code works correctly for `torch.float32` dtype.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
PyTorch version: 1.4.0a0+a5b4d78
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: TITAN RTX
Nvidia driver version: 440.48.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.17.4
[pip] pytorch-transformers==1.1.0
[pip] torch==1.4.0a0+a5b4d78
[pip] torchtext==0.4.0
[pip] torchvision==0.5.0a0
[conda] magma-cuda101             2.5.2                         1    local
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] nomkl                     3.0                           0  
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.4.0a0+a5b4d78          pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0a0                  pypi_0    pypi

## Additional context

I'm using the official NVIDIA Docker build from `nvcr.io/nvidia/pytorch:20.01-py3`.

cc @ngimel @csarofeen @ptrblck

**Comment by cpuhrsch** [comment]
I also ran out of memory when running this on a GPU similar to yours, but I didn't get quite as dramatic of an error as you

```
$ python /tmp/asdf.py
Traceback (most recent call last):
  File "/tmp/asdf.py", line 5, in <module>
    output = resnet(t)
  File "/scratch/cpuhrsch/repos/pytorch/torch/nn/modules/module.py", line 540, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/cpuhrsch/repos/vision/torchvision/models/resnet.py", line 216, in forward
    return self._forward_impl(x)
  File "/scratch/cpuhrsch/repos/vision/torchvision/models/resnet.py", line 205, in _forward_impl
    x = self.layer2(x)
  File "/scratch/cpuhrsch/repos/pytorch/torch/nn/modules/module.py", line 540, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/cpuhrsch/repos/pytorch/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/scratch/cpuhrsch/repos/pytorch/torch/nn/modules/module.py", line 540, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/cpuhrsch/repos/vision/torchvision/models/resnet.py", line 64, in forward
    out = self.conv2(out)
  File "/scratch/cpuhrsch/repos/pytorch/torch/nn/modules/module.py", line 540, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/cpuhrsch/repos/pytorch/torch/nn/modules/conv.py", line 348, in forward
    return self._conv_forward(input, self.weight)
  File "/scratch/cpuhrsch/repos/pytorch/torch/nn/modules/conv.py", line 345, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 338.00 MiB (GPU 0; 15.90 GiB total capacity; 14.99 GiB already allocated; 215.56 MiB free; 14.99 GiB reserved in total by PyTorch)
$ cat /tmp/asdf.py
import torch
import torchvision.models as models
resnet = models.resnet18().half().cuda()
t = torch.ones([1, 3, 10210, 8641], dtype=torch.float16, device="cuda")
output = resnet(t)
```

Maybe this is a bug in the values that are supplied for this error messages. Can you try a smaller input and see if it succeeds? For example, for me it works if I set 
```
t = torch.ones([1, 3, 1210, 8641], dtype=torch.float16, device="cuda")
```

I imagine that the input is simply too big and that there is a bug in the calculation we use to get that error message.

**Comment by ngimel** [comment]
Can you try setting torch.backends.cudnn.benchmark=True? Since it works ok for larger tensor, and works ok for fp32, it is possible that cudnn heuristics is giving the wrong algorithms. 
This is possibly related to #31500. 
cc @ptrblck

**Comment by JosephDiPalma** [comment]
> Can you try setting torch.backends.cudnn.benchmark=True? Since it works ok for larger tensor, and works ok for fp32, it is possible that cudnn heuristics is giving the wrong algorithms.
> This is possibly related to #31500.
> cc @ptrblck

Setting `torch.backends.cudnn.benchmark = True` fixes the problem.

**Comment by JosephDiPalma** [comment]
Unfortunately setting `torch.backends.cudnn.benchmark = True` fixes the issue for this code segment, but when running it on a larger dataset, I receive the following error:
`RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR"`

**Comment by ptrblck** [comment]
@JosephDiPalma Could you post the shape which causes the second issue?

I wasn't able to run the initial code for FP32, as I was running out of memory on a 32GB GPU.

**Comment by ngimel** [comment]
@JosephDiPalma cudnn logging will be helpful in addition or instead of shapes https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#api-logging

**Comment by JosephDiPalma** [comment]
@ngimel @ptrblck 
Below is a code segment which reproduces the problem mentioned above.  I forgot to say that the new problem only occurs when using Apex.  
```
import torch
import torch.optim as optim
import torchvision.models as models
from apex import amp

torch.backends.cudnn.benchmark = True

model = models.resnet18().cuda()
t = torch.ones([1, 3, 2465, 4001]).cuda(non_blocking=True)
optimizer = optim.Adam(params=model.parameters(), lr=1e-3, weight_decay=0.1)

model, optimizer = amp.initialize(model, optimizer, opt_level="O1")

output = model(t)
```

The error is as follows:
```
Traceback (most recent call last):
  File "run.py", line 56, in <module>
    color_jitter_saturation=config.args.color_jitter_saturation)
  File "/workspace/deepslide_wsi/utils_model.py", line 585, in run_resnet
    batch_size=batch_size)
  File "/workspace/deepslide_wsi/utils_model.py", line 356, in train_eval_helper
    train_outputs = model(train_inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/resnet.py", line 205, in forward
    x = self.layer3(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/models/resnet.py", line 64, in forward
    out = self.conv2(out)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```

This error occurred on a different computer than the one I used before.  The information is below:
```
Collecting environment information...
PyTorch version: 1.3.0a0+24ae9b5
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro RTX 8000
Nvidia driver version: 430.50
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip3] intel-numpy==1.15.1
[pip3] numpy==1.18.0
[conda] magma-cuda100             2.1.0                         5    local
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] nomkl                     3.0                           0
[conda] torch                     1.3.0a0+24ae9b5          pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0a0                  pypi_0    pypi
```
[log.txt](https://github.com/pytorch/pytorch/files/4207647/log.txt)

**Comment by JosephDiPalma** [comment]
@ngimel @ptrblck Are there any updates on this issue?

**Comment by zasdfgbnm** [comment]
Hi @JosephDiPalma , I can not reproduce the error at https://github.com/pytorch/pytorch/issues/33143#issuecomment-586544313 , but https://github.com/pytorch/pytorch/pull/33073 should fix that kind of errors.

**Comment by JosephDiPalma** [comment]
@zasdfgbnm I built the latest code from source and still receive an error for the original code segment.  It is a different error that says: `Runtime Error: Trying to create tensor with negative dimension -59809105: [-59809105]`.

**Comment by ngimel** [comment]
Can you try nightly binaries? It seems like we cannot reproduce your issues, is there something special about your build?

**Comment by JosephDiPalma** [comment]
@ngimel I tried the Anaconda nightly binary and it produced the above Runtime Error.  I tried it on a system level Anaconda install and also the Anaconda install inside the NVIDIA docker container `nvcr.io/nvidia/pytorch:20.02-py3`.

**Comment by ngimel** [comment]
Yep, thanks, can repro it now, sorry about the noise.
