### ISSUE TITLE
CMakeFiles/Makefile2:923: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed

### ISSUE THREAD

**Issue by RobbyHuang** [pytorch/pytorch#36227]
## ❓ Questions and Help

When I install the pytorch 0.4.1 from source, it cause the following error.

`[ 69%] Linking CXX shared library ../lib/libcaffe2.so
[ 69%] Built target caffe2
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCReduceApplyUtils.cu.o
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCBlas.cu.o
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCSleep.cu.o
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorageCopy.cu.o
[ 69%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorage.cu.o
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensor.cu.o
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorCopy.cu.o
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMath.cu.o
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMathBlas.cu.o
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMathMagma.cu.o
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMathPairwise.cu.o
[ 70%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMathReduce.cu.o
[ 71%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMathScan.cu.o
[ 71%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorIndex.cu.o
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone

/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCAtomics.cuh(123): error: return value type does not match the function type

[ 71%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorRandom.cu.o
[ 71%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorScatterGather.cu.o
2 errors detected in the compilation of "/tmp/tmpxft_00004897_00000000-6_THCTensorIndex.cpp1.ii".
CMake Error at caffe2_gpu_generated_THCTensorIndex.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/llcrobot/Robby/pytorch0.4.1/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCTensorIndex.cu.o

caffe2/CMakeFiles/caffe2_gpu.dir/build.make:154: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorIndex.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorIndex.cu.o] Error 1
make[2]: *** 正在等待未完成的任务....
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone

/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCAtomics.cuh(123): error: return value type does not match the function type

ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhmhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhmhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhmhN6thrust8identityIhEE10LogicalAnyS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhmhN6thrust8identityIhEE10LogicalAnyS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Lin1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Li2ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Li2ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Li2ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Li2ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Li2ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Li2ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Li1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Li1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Li1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Li1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAnyS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAnyS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhmhN6thrust8identityIhEE10LogicalAllS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhmhN6thrust8identityIhEE10LogicalAllS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhmhN6thrust8identityIhEE10LogicalAllS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhmhN6thrust8identityIhEE10LogicalAllS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Lin1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Lin1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Lin1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Lin1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Lin1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Li2ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Li2ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Li2ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Li2ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Li2ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Li2ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Li1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Li1ELin1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Li1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Li1ELi2EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z31kernelReduceNoncontigDim_sharedIhjhN6thrust8identityIhEE10LogicalAllS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_PVS8_Pi is out of range. .minnctapersm will be ignored
ptxas warning : Value of threads per SM for entry _Z24kernelReduceNoncontigDimIhjhN6thrust8identityIhEE10LogicalAllS2_Li1ELi1EEv10TensorInfoIT_T0_ES7_S6_S6_S6_T1_T2_T3_T4_ is out of range. .minnctapersm will be ignored
2 errors detected in the compilation of "/tmp/tmpxft_000048f3_00000000-6_THCTensorScatterGather.cpp1.ii".
CMake Error at caffe2_gpu_generated_THCTensorScatterGather.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/llcrobot/Robby/pytorch0.4.1/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCTensorScatterGather.cu.o

caffe2/CMakeFiles/caffe2_gpu.dir/build.make:168: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorScatterGather.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorScatterGather.cu.o] Error 1
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh: In function ‘bool THC_reduceDim(THCState*, TensorType*, TensorType*, ModifyOp, ReduceOp, FinalizeOp, AccT, int, int) [with ScalarType = unsigned char; TensorType = THTensor; ModifyOp = thrust::identity<unsigned char>; ReduceOp = LogicalAll; FinalizeOp = thrust::identity<unsigned char>; AccT = unsigned char; THCState = THCState]’:
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:624:674: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:624:655: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:622:670: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:622:651: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:12679: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:12660: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:11195: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:11176: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:9714: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:9695: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:8184: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:8165: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:6703: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:6684: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:5225: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:5206: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:3698: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:3679: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:2217: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:2198: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:739: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:720: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh: In function ‘bool THC_reduceDim(THCState*, TensorType*, TensorType*, ModifyOp, ReduceOp, FinalizeOp, AccT, int, int) [with ScalarType = unsigned char; TensorType = THTensor; ModifyOp = thrust::identity<unsigned char>; ReduceOp = LogicalAny; FinalizeOp = thrust::identity<unsigned char>; AccT = unsigned char; THCState = THCState]’:
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:624:674: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:624:655: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:622:670: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:622:651: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:12679: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:12660: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:11195: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:11176: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:9714: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:9695: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:8184: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:8165: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:6703: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:6684: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:5225: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:5206: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:3698: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:3679: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:2217: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:2198: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:739: warning: ‘semaphores’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/llcrobot/Robby/pytorch0.4.1/aten/src/THC/THCReduce.cuh:602:720: warning: ‘stagingData’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CMakeFiles/Makefile2:923: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'
`

The environment is :
python 3.5.6
cuda 10.0
RTX2080
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 

Anyone Know how to deal with it ?Thanks

**Comment by gchanan** [comment]
Your version of PyTorch is very old and it looks like this issue was fixed.  I'd suggest upgrading or if you need more help, asking on https://discuss.pytorch.org/, but I'm closing this because it's not an open bug.

**Comment by mmaaz60** [comment]
Hi @RobbyHuang,

Are you able to fix this issue? I am also having this issue. Any information to fix this would be appreciated. Thanks

**Comment by RobbyHuang** [comment]
Sorry, I didn’t solve this problem, and I finally used pytorch 1.0.0
