### ISSUE TITLE
Runtime error when mixing FP32 loss functions and FP16 cnn layers

### ISSUE THREAD

**Issue by michaelhuang74** [pytorch/pytorch#3651]
I am trying to speed up the neural style transfer (https://github.com/leongatys/PytorchNeuralStyleTransfer) on Nvidia Tesla V100 by using FP16.

I modified the code to move the vgg to cuda().half(). In addition, all three images, style image, content image, and opt_img, are in FP16. I tried to keep the loss functions in FP32 because it easily can generate NaN and infinity in FP16.
The code is at https://gist.github.com/michaelhuang74/009e149a2002b84696731fb599408c90

When I ran the code, I encountered the following error.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
File "neural-style-Gatys-half.py", line 167, in 
style_targets = [GramMatrix()(A).detach().cuda() for A in vgg(style_image, style_layers)]
File "/home/mqhuang2/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 319, in call
result = self.forward(input, **kwargs)
File "neural-style-Gatys-half.py", line 86, in forward
G.div_(hw)
RuntimeError: value cannot be converted to type Half without overflow: 960000
+++++++++++++++++++++++++++++++++++++++++++++++++++++++

It seems that although I tried to keep the GramMatrix (see line 82) and loss functions (see line 155) in FP32, somehow, pytorch tried to convert FP32 to FP16 in the GramMatrix forward() method.

Any idea how to resolve this error?

**Comment by apaszke** [comment]
You probably forgot to cast something to fp32. Can you please post the code of `GramMatrix` so I can ensure that it's not a bug?

**Comment by michaelhuang74** [comment]
@apaszke The code is at https://gist.github.com/michaelhuang74/009e149a2002b84696731fb599408c90

In the code of GramMatrix, I tried to cast FP16 to FP32 at line 82. The modified code is as follows.

class GramMatrix(nn.Module):
    def forward(self, input):
        input_l = input.clone().cuda()
        b,c,h,w = input_l.size()
        F = input_l.view(b, c, h*w)
        G = torch.bmm(F, F.transpose(1,2)).cuda() 
        G.div_(h*w)
        return G

class GramMSELoss(nn.Module):
    def forward(self, input, target):
        out = nn.MSELoss()(GramMatrix()(input), target)
        return(out)

**Comment by apaszke** [comment]
The problem is exacly as I suspected - you run the `GramMatrix` code entirely in `fp16` tensors. Change
```python
style_targets = [GramMatrix()(A).detach().cuda() for A in vgg(style_image, style_layers)]
```
to
```python
style_targets = [GramMatrix()(A.float()).detach().cuda() for A in vgg(style_image, style_layers)]
```
to get rid of the error message.

**Comment by michaelhuang74** [comment]
@apaszke Thanks for the quick help! Your solution solved the problem. I have updated the code at https://gist.github.com/michaelhuang74/009e149a2002b84696731fb599408c90

However, I have another problem with the optimizer.
In FP32 mode, I can use both LBFGS and Adam as the optimizer. In the FP16/FP32 mixing mode, only Adam works. 
If I use LBFGS, it has the following error:
++++++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "neural-style-Gatys-half.py", line 194, in <module>
    optimizer.step(closure)
  File "/home/mqhuang2/anaconda2/lib/python2.7/site-packages/torch/optim/lbfgs.py", line 197, in step
    gtd = flat_grad.dot(d)  # g * d
RuntimeError: cublas runtime error : unknown error at /home/mqhuang2/pytorch/aten/src/THC/THCBlas.cu:67
++++++++++++++++++++++++++++++++++++++++++++++++++++++

The error message says it is a cublas runtime error. Does this mean I simply cannot use LBFGS in FP16? Thanks.

**Comment by apaszke** [comment]
That's a bug. I'll send a PR soon

**Comment by apaszke** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/3660.

**Comment by borisfom** [comment]
@apaszke , @michaelhuang74 : even though the cublas error is gone, the LBFGS optimizer is still not usable in FP16 mode - I am getting all black images when trying to use it in a similar script. Adam optimizer, on the other hand, works in FP16 but produces uninteresting images.  Any ideas if LBFGS can be fixed (or Adam  tweaked to produce output similar to LBFGSP) ?
