### ISSUE TITLE
undefined reference to pthreadpool_compute*

### ISSUE THREAD

**Issue by cloudhan** [pytorch/pytorch#37488]
## 🐛 Bug

When building with current master 07bb442b240edc8bdc944fb466b1fb56c84fa4ee
with following script
```bash
#!/bin/bash

export REL_WITH_DEB_INFO=1
export USE_CUDA=1

export BUILD_TEST=0
export BUILD_BINARY=0
export BUILD_CAFFE2_OPS=0
export USE_MKLDNN=0
export USE_FBGEMM=0
export USE_NNPACK=0
export USE_QNNPACK=0
export USE_XNNPACK=0

pip install -e . -v

```

```none
    /home/cloudhan/workspaces/pytorch/build/lib/libtorch_cpu.so: undefined reference to `pthreadpool_compute_1d_tiled'
    /home/cloudhan/workspaces/pytorch/build/lib/libtorch_cpu.so: undefined reference to `pthreadpool_compute_3d_tiled'
    /home/cloudhan/workspaces/pytorch/build/lib/libtorch_cpu.so: undefined reference to `caffe2::mobile_pthreadpool()'
    /home/cloudhan/workspaces/pytorch/build/lib/libtorch_cpu.so: undefined reference to `pthreadpool_compute_1d'
    /home/cloudhan/workspaces/pytorch/build/lib/libtorch_cpu.so: undefined reference to `pthreadpool_compute_2d'
    /home/cloudhan/workspaces/pytorch/build/lib/libtorch_cpu.so: undefined reference to `pthreadpool_compute_4d_tiled'
```

similar issue mentioned in https://github.com/pytorch/pytorch/issues/34606#issuecomment-619635665

## To Reproduce

1. build the code

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.17.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 418.87.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip3] numpy==1.16.4
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] msgpack-numpy             0.4.4.3                  pypi_0    pypi
[conda] numpy                     1.18.3                   pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torch2trt                 0.0.0                     dev_0    <develop>

**Comment by cloudhan** [comment]
```bash
for o in $(cat build.ninja | grep '^build lib/libtorch_cpu.so' | grep -E '\.(o|a)$' ); do echo $o && nm $o | grep pthreadpool_compute ; done
```


show target `lib/libtorch_cpu.so` links to following target, which causes the undefined symbols
```
...
lib/libpytorch_qnnpack.a
                 U pthreadpool_compute_2d
                 U pthreadpool_compute_3d_tiled
                 U pthreadpool_compute_4d_tiled
                 U pthreadpool_compute_4d_tiled
                 U pthreadpool_compute_4d_tiled
                 U pthreadpool_compute_1d
                 U pthreadpool_compute_1d_tiled
                 U pthreadpool_compute_2d
                 U pthreadpool_compute_3d_tiled
                 U pthreadpool_compute_4d_tiled
...
```

**Comment by cloudhan** [comment]
Dig through the cmake jungle

https://github.com/pytorch/pytorch/blob/4bfa51d40595d41d6bec6d4a9b1ade72adde4ebc/aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt#L344-L350

and XNNPACK will provide the implementation.

However, in
https://github.com/pytorch/pytorch/blob/a55d80e1c5b553bee1d7f60655911ce851c2b2f1/cmake/Dependencies.cmake#L398
blindly enable `PYTORCH_QNNPACK_CUSTOM_THREADPOOL` without checking XNNPACK,
which in turn caused this issue.

**Comment by eellison** [comment]
related: https://github.com/pytorch/pytorch/issues/34606

**Comment by pbelevich** [comment]
Maybe duplicate of #34606

**Comment by xuhdev** [comment]
I believe this is relatively new. I bisected and 93cd05b0f4ebb82a0f075f05d284efae1ec9e538 seems to be the culprit.

**Comment by rjknight** [comment]
I added another PR which should resolve the issues with https://github.com/pytorch/pytorch/commit/93cd05b0f4ebb82a0f075f05d284efae1ec9e538   See: https://github.com/pytorch/pytorch/pull/37865

**Comment by bmanga** [comment]
It still happens for me when `Linking CXX executable ../bin/utility_ops_gpu_test`

**Comment by adamjstewart** [comment]
Just encountered this with PyTorch 1.9.0.

**Comment by adamjstewart** [comment]
Also encountered with PyTorch 2.0.1, 2.1.1, and 2.2.2. This only occurs when building with external XNNPACK. Wondering if XNNPACK is being built with a different version of pthreadpool than PyTorch is. Or if I'm linking dynamically when I should be linking statically (or vice versa).
