### ISSUE TITLE
freeze_module does not preserve methods besides forward

### ISSUE THREAD

**Issue by kimishpatel** [pytorch/pytorch#37945]
## 🐛 Bug

freeze_module JIT pass does not preserve any other method besides forward at the moment.

As mentioned.

## To Reproduce
```
import torch
import torch.utils.mobile_optimizer
from torch.jit._recursive import wrap_cpp_module

class MyMod(torch.nn.Module):
    def forward(self, arg):
        return arg
    @torch.jit.export
    def version(self):
        return 1

sm = torch.jit.script(MyMod())
sm.eval()
print("Original")
sm._c.dump(True, True, False)
print("==========")
frozen = wrap_cpp_module(torch._C._freeze_module(sm_1._c))
print("POST FREEZING")
frozen._c.dump(True, True, False)
print("==========")
```

## Expected behavior

version method in the above code snippet preserved.

cc @suo

**Comment by eellison** [comment]
This was fixed via API, closing.

**Comment by xuzhuang1996** [comment]
> This was fixed via API, closing.

But I found that this phenomenon still exists in 1.10.0+CPU. which version you fixed it in API. Thanks
