### ISSUE TITLE
libtorch 1.5.0 libiomp5.dylib contains erroneous link to /DLC/torch/libiomp5.dylib instead of using @rpath

### ISSUE THREAD

**Issue by marpaia** [pytorch/pytorch#38607]
## 🐛 Bug

In the mac libtorch bundle for 1.5.0, the `libiomp5.dylib` shared object file contains a hard-coded link to a path which seems incorrect. I assume that the link for `/DLC/torch/libiomp5.dylib` should be `@rpath/libiomp5.dylib` like it is for all of the other links in provided dylibs.

## To Reproduce

```
wget https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.5.0.zip
unzip libtorch-macos-1.5.0.zip
otool -L libtorch/lib/libiomp5.dylib
```

<img width="808" alt="Screen Shot 2020-05-16 at 1 03 14 PM" src="https://user-images.githubusercontent.com/927168/82128126-00963300-9776-11ea-98b4-2e62c0522e4c.png">

cc @ezyang @seemethere

**Comment by ezyang** [comment]
This is probably the same thing as #36941

**Comment by marpaia** [comment]
@ezyang I think this is a little different. That looks like the user doesn't have a local installation of libc++ (a local configuration issue) whereas this is an issue with the artifact itself in my opinion.

**Comment by malfet** [comment]
Same `DLC` path is present in https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.4.0.zip

**Comment by co42** [comment]
I had the same issue and fixed it with:

```shell
install_name_tool -id @rpath/libiomp5.dylib libiomp5.dylib
```

**Comment by Sanghoon94** [comment]
Hope this issue gets fixed soon!

Is there any workaround besides @co42 's solution?
It's kind of frustrating to execute the command every time.

**Comment by ezyang** [comment]
@malfet do you know if we fixed this in 1.7?

**Comment by malfet** [comment]
@ezyang No, it isn't fixed yet.
@Sanghoon94 can you please share exact steps how you reproduce this issue (and your OSX version)?

**Comment by Sanghoon94** [comment]
@malfet Sure.
I am using macOS 10.15.7 with Xcode 12.1 (12A7403), but I have seen the identical problem on previous versions, too.
Also, I have faced this issue using both 1.6.0 & 1.7.0 release for macOS.

I have configured the dependency settings on Xcode like the following.
1. Header search paths: ${LIB_ROOT}/include
2. Library search paths: ${LIB_ROOT}/lib
3. Other linker flags: -lc10 -lcaffe2_detection_ops -lcaffe2_module_test_dynamic -lcaffe2_observers -lfbjni -lfmt -liomp5 -lpytorch_jni -lshm -ltensorpipe -ltorch_cpu -ltorch_global_deps -ltorch
4. Runpath search paths: ${LIB_ROOT}/lib

After finishing the basic settings, the error pops up whatever code I write.
(For example, code from the tutorial https://pytorch.org/tutorials/advanced/cpp_export.html)

**Comment by malfet** [comment]
`DLC` path is set by delocate script here: https://github.com/matthew-brett/delocate/blob/44373c16b4abfe9ff29369096055b8ffefd5619c/delocate/delocating.py#L401

**Comment by adampauls** [comment]
It appears to have (re)appeared in 1.11.0. 

For 1.10.2 (from https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.10.2.zip)

```
adpauls$ otool -L libtorch/lib/libiomp5.dylib
libtorch/lib/libiomp5.dylib:
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

For 1.11.0 (from https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.11.0.zip)

```
adpauls$ otool -L libtorch/lib/libiomp5.dylib
libtorch/lib/libiomp5.dylib:
	/DLC/torch/.dylibs/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```
