### ISSUE TITLE
list of numpy -> tensor is much slower than list of numpy -> np.stack -> tensor

### ISSUE THREAD

**Issue by songtaoshi** [pytorch/pytorch#39842]
## 🐛 Bug

Hi, I may encounter a bug. The procedure " list of numpy array -> tensor" is much slower than the procedure "first stack of list to full numpy array then to tensor".

![image](https://user-images.githubusercontent.com/20240391/84340923-6db1b280-abd4-11ea-923e-853e85a89337.png)

## To Reproduce

```python
import torch
import numpy as np

temp_np = np.random.randn(10000)

list_temp_np = [temp_np for _ in range(1000)]

%timeit torch.Tensor(list_temp_np)

%timeit torch.Tensor(np.stack(list_temp_np))

torch.Tensor(list_temp_np).shape

torch.Tensor(np.stack(list_temp_np)).shape

torch.sum(torch.Tensor(list_temp_np)-torch.Tensor(np.stack(list_temp_np)))

```

## Expected behavior

we expect the torch.Tensor(list_of_numpy) is at least as fast as torch.Tensor(np.stack(list_of_numpy))  since they both make the same result!

## Environment
 - PyTorch Version : 1.3.1
 - Numpy Version : 1.17.3
 - How you installed PyTorch (`conda`, `pip`, source): pytorch                   1.3.1           py3.7_cuda10.0.130_cudnn7.6.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
 - Python version: 3.7.3

cc @mruberry @rgommers @heitorschueroff @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
Thanks for reporting. Yes, looks like constructing a tensor from a list of ndarrays is not optimized.

**Comment by mruberry** [comment]
We would take a PR fixing this.

**Comment by robin5540** [comment]
I can take stab at this. I'm guessing a naive solution here is just to stack first then construct tensor in the python frontend.

**Comment by touqir14** [comment]
@robin5540 , I have already implemented a solution for this and a PR will soon be posted.

**Comment by robin5540** [comment]
> @robin5540 , I have already implemented a solution for this and a PR will soon be posted.

I'll leave it to you then.

**Comment by mruberry** [comment]
We should verify this is still happening on more recent builds and when using the typical `torch.tensor()` tensor factory. I'm not sure how much faster we can make torch.tensor() in this case, but one option would be to throw a warning that users should stack their NumPy tensors before the call for better performance.

**Comment by mruberry** [comment]
Actually, duping this in favor of the older https://github.com/pytorch/pytorch/issues/13918.

**Comment by touqir14** [comment]
@mruberry , this indeed happens in the latest builds. With the optimization (it does not involve stacking using numpy c api), I am getting about ~3.5x speedup over using numpy.stack in the example below:
```
temp_np = np.random.randn(10000)
list_temp_np = [temp_np for _ in range(10000)]

%timeit torch.tensor(list_temp_np)
333 ms ± 7.45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit torch.tensor(np.stack(list_temp_np))
1.17 s ± 82.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```
Moreover, the optimization carries over to the more general case of arbitrarily stacking arrays recursively, eg: [[[x1, x2], [x3, x4]], [[x5, x6], [x7, x8]]]

**Comment by mruberry** [comment]
Interesting -- looking forward to seeing it!

**Comment by touqir14** [comment]
@mruberry , I just pushed the PR.
