### ISSUE TITLE
ONNX export does not support distributions.uniform

### ISSUE THREAD

**Issue by sidkashyap-at-Intel** [pytorch/pytorch#42230]
## 🐛 Bug

The operator torch.distributions.uniform is not supported by torch.onnx.export. It fails with the below message when a model with the uniform operation is exported: 

"RuntimeError: Exporting the operator uniform to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator."

ONNX supports RandomUniform from opset 1, it looks to be a case of exporting the uniform operation to that. 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@sidkashyap-at-Intel - yes, torch.distributions APIs are not supported in the exporter. Please consider contributing a PR for that.

**Comment by garymm** [comment]
Pretty sure this works in the latest PyTorch nightly:

```python
!pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html -U
import torch
print("torch version:", torch.__version__)

class M(torch.nn.Module):
    def forward(self, x, y):
        return torch.distributions.Uniform(x, y).sample().size(0), x , y

m = M()
inp = (torch.tensor([[0.0], [6.0]]), torch.tensor([[1.0], [7.0]]))
torch.onnx.export(
    m, inp,
    "/dev/null", verbose=True, opset_version=9)
```

Produces output:
```
torch version: 1.11.0.dev20211102+cpu
graph(%0 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu),
      %1 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu)):
  %2 : Long(2, strides=[1], device=cpu) = onnx::Shape(%0) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %3 : Float(2, 1, device=cpu) = onnx::ConstantOfShape[value={0}](%2) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %4 : Float(2, 1, strides=[1, 1], device=cpu) = onnx::Add(%3, %0) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %5 : Float(2, 1, strides=[1, 1], device=cpu) = onnx::Add(%4, %1) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %6 : Long(2, strides=[1], device=cpu) = onnx::Shape(%5) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %7 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu) = onnx::Expand(%0, %6) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %8 : Long(2, strides=[1], device=cpu) = onnx::Shape(%5) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %9 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cpu) = onnx::Expand(%1, %8) # /usr/local/lib/python3.7/dist-packages/torch/functional.py:75:0
  %10 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={2}]() # <ipython-input-5-6eed90abf6ca>:3:0
  return (%10, %7, %9)
```

So I guess this got fixed at some point.

Closing. If you have code that reproduces the issue on the latest PyTorch nightly, please post it here and I'll gladly re-open the issue, or open a new issue.

**Comment by Bresenham** [comment]
This is still an issue on my side, however, not with the minimal example @garymm provided.
Instead, I am trying to build ResNet with torch-layers.

Even after installing the nightly build of `torch` via:

`pip3 install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html -U`

I struggle with the very same error:

```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 301, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 728, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 358, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1054, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1008, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/symbolic_registry.py", line 129, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator uniform to ONNX opset version 10 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

with

```
torch.onnx.export(m,
      x,
      fn,
      export_params=True,
      opset_version=10,
      do_constant_folding=True,
      input_names = ['input'],
      output_names = ['output'],
      dynamic_axes={'input' : {0 : 'batch_size'},
                    'output' : {0 : 'batch_size'}})
```

where `m` is my ResNet model and `x = t.randn(1, 3, 300, 300, requires_grad=True)`

I am not familiar with where `torch.distributions.Uniform` is used internally.

**Comment by garymm** [comment]
@Bresenham 
Could you please provide the model? Or any model that reproduces the problem.
Without that it's not really feasible for me to debug.
