### ISSUE TITLE
unclear behavior of the torch.cummax function on CUDA

### ISSUE THREAD

**Issue by MrNeither** [pytorch/pytorch#42363]
Hello. I encountered a problem with the torch.cummax function working on tensors in cuda. I would appreciate any information to understand what the problem might be.
## To Reproduce

```
import torch

P = torch.rand(10, 10)
C_distrib = torch.distributions.categorical.Categorical(probs=P)  # 10 numbers from 0 to 10
X = C_distrib.sample((4,))
print(X)
print(torch.cummax(X, dim=1))
print(torch.cummax(X.cuda(), dim=1))
```

Output:
```
tensor([[3, 4, 8, 9, 8, 1, 5, 3, 2, 2],
        [7, 9, 1, 6, 1, 4, 5, 1, 1, 3],
        [6, 4, 4, 2, 1, 4, 5, 5, 3, 4],
        [4, 2, 2, 5, 4, 7, 0, 0, 1, 7]])
torch.return_types.cummax(
values=tensor([[3, 4, 8, 9, 9, 9, 9, 9, 9, 9],
        [7, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [4, 4, 4, 5, 5, 7, 7, 7, 7, 7]]),
indices=tensor([[0, 1, 2, 3, 3, 3, 3, 3, 3, 3],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 3, 3, 5, 5, 5, 5, 9]]))
torch.return_types.cummax(
values=tensor([[3, 7, 7, 7, 7, 9, 9, 9, 9, 9],
        [4, 4, 9, 9, 9, 9, 9, 9, 9, 9],
        [1, 4, 4, 7, 7, 7, 7, 7, 7, 7],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 7]], device='cuda:0'),
indices=tensor([[0, 1, 1, 1, 1, 5, 5, 5, 5, 5],
        [0, 0, 2, 2, 2, 2, 2, 2, 2, 2],
        [0, 1, 2, 3, 3, 3, 3, 3, 3, 3],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]], device='cuda:0'))
```
## Expected behavior

At first glance, it seems that cummax used transpose, flatten, and reshape, If you look at the column values.

## Environment

PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.14.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti

Nvidia driver version: 440.100
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.5.1.10
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.5.1
[pip3] torchaudio==0.4.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.6.1
[pip3] torchviz==0.0.1
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by kshitij12345** [comment]
Looks like the issue is fixed on master (not sure about 1.6)
```python
>>> torch.__version__
'1.7.0a0+e5445d2'
>>> X = torch.tensor([[3, 4, 8, 9, 8, 1, 5, 3, 2, 2],
...         [7, 9, 1, 6, 1, 4, 5, 1, 1, 3],
...         [6, 4, 4, 2, 1, 4, 5, 5, 3, 4],
...         [4, 2, 2, 5, 4, 7, 0, 0, 1, 7]])
>>> torch.cummax(X, dim=1)
torch.return_types.cummax(
values=tensor([[3, 4, 8, 9, 9, 9, 9, 9, 9, 9],
        [7, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [4, 4, 4, 5, 5, 7, 7, 7, 7, 7]]),
indices=tensor([[0, 1, 2, 3, 3, 3, 3, 3, 3, 3],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 3, 3, 5, 5, 5, 5, 9]]))
>>> torch.cummax(X.cuda(), dim=1)
torch.return_types.cummax(
values=tensor([[3, 4, 8, 9, 9, 9, 9, 9, 9, 9],
        [7, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [4, 4, 4, 5, 5, 7, 7, 7, 7, 7]], device='cuda:0'),
indices=tensor([[0, 1, 2, 3, 3, 3, 3, 3, 3, 3],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 3, 3, 5, 5, 5, 5, 9]], device='cuda:0'))
```

**Comment by MrNeither** [comment]
So I need to update the version?

**Comment by kshitij12345** [comment]
You can try that or maybe you can wait for more details from maintainers.

**Comment by mruberry** [comment]
I also see this issue is fixed on nightlies. Looks like you'll need to update. Sorry you hit this issue, @MrNeither, but good news that it's already been fixed.

**Comment by MrNeither** [comment]
@mruberry @kshitij12345  I updated the pytorch version. I still have a problem. I installed the latest version initially (1.6.0), and then using the command
```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
```
However the behavior of the cummax method is still erroneous.

And how can I install a version of 1.7.0? Sorry if the question is stupid, I'm pretty bad at installing packages

**Comment by mruberry** [comment]
Hm, that's odd. I always build from source so wouldn't be the best person to ask. 

```
pip install numpy
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
```

Should be the correct commands. When you launch PyTorch, can you check the version and see if you still get this behavior? You're using CUDA 10.2, right?

**Comment by MrNeither** [comment]
```
 P = torch.rand(10, 10)
    C_distrib = torch.distributions.categorical.Categorical(probs=P)  # 10 numbers from 0 to 10
    X = C_distrib.sample((4,))
    print(torch.__version__)
    print(X)
    print(torch.cummax(X, dim=1))
    print(torch.cummax(X.cuda(), dim=1))
```

Output
```
1.6.0
tensor([[3, 2, 2, 2, 6, 4, 7, 6, 1, 3],
        [2, 8, 2, 6, 3, 9, 3, 3, 5, 6],
        [0, 3, 6, 2, 7, 2, 5, 0, 5, 1],
        [9, 3, 0, 2, 2, 8, 7, 9, 1, 3]])
torch.return_types.cummax(
values=tensor([[3, 3, 3, 3, 6, 6, 7, 7, 7, 7],
        [2, 8, 8, 8, 8, 9, 9, 9, 9, 9],
        [0, 3, 6, 6, 7, 7, 7, 7, 7, 7],
        [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]]),
indices=tensor([[0, 0, 0, 0, 4, 4, 6, 6, 6, 6],
        [0, 1, 1, 1, 1, 5, 5, 5, 5, 5],
        [0, 1, 2, 2, 4, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 7, 7, 7]]))
torch.return_types.cummax(
values=tensor([[3, 3, 3, 9, 9, 9, 9, 9, 9, 9],
        [6, 6, 6, 6, 6, 6, 6, 6, 7, 7],
        [4, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [0, 9, 9, 9, 9, 9, 9, 9, 9, 9]], device='cuda:0'),
indices=tensor([[0, 0, 0, 3, 3, 3, 3, 3, 3, 3],
        [0, 0, 0, 3, 3, 3, 6, 6, 8, 8],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0'))

Process finished with exit code 0
```

I executed the same command as You. I have version 1.6.0 and I don't know if 'nighly'should be displayed somehow
Yes, I'm use CUDA 10.2.

**Comment by MrNeither** [comment]
I figured out how to install the night version.I deleted the normal version, and then use the command above.
But the problem persists
```
1.7.0.dev20200802
tensor([[1, 9, 5, 4, 8, 7, 9, 1, 2, 0],
        [5, 4, 6, 2, 6, 4, 0, 2, 8, 0],
        [9, 7, 6, 6, 7, 6, 8, 5, 5, 1],
        [3, 9, 7, 7, 8, 0, 0, 5, 7, 8]])
torch.return_types.cummax(
values=tensor([[1, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [5, 5, 6, 6, 6, 6, 6, 6, 8, 8],
        [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [3, 9, 9, 9, 9, 9, 9, 9, 9, 9]]),
indices=tensor([[0, 1, 1, 1, 1, 1, 6, 6, 6, 6],
        [0, 0, 2, 2, 4, 4, 4, 4, 8, 8],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))
torch.return_types.cummax(
values=tensor([[1, 5, 9, 9, 9, 9, 9, 9, 9, 9],
        [6, 7, 7, 7, 7, 7, 8, 8, 8, 8],
        [7, 7, 7, 7, 9, 9, 9, 9, 9, 9],
        [5, 5, 5, 8, 8, 8, 8, 8, 8, 8]], device='cuda:0'),
indices=tensor([[0, 1, 2, 2, 4, 4, 4, 7, 7, 7],
        [0, 1, 1, 1, 1, 5, 6, 6, 6, 9],
        [0, 0, 0, 0, 4, 4, 4, 4, 4, 4],
        [0, 1, 1, 3, 3, 3, 3, 3, 3, 9]], device='cuda:0'))
```

**Comment by mruberry** [comment]
Interesting. Reopening this issue until we get to the bottom of this discrepancy.

**Comment by MrNeither** [comment]
I found that torch.cummin works correctly on my example
```
 P = torch.rand(10, 10)
C_distrib = torch.distributions.categorical.Categorical(probs=P)  # 10 numbers from 0 to 10
X = C_distrib.sample((4,))
print(torch.__version__)
print(X, end='\n\n')
X_maxv, X_maxind = torch.cummax(X, dim=1)
X_cuda_maxv, X_cuda_maxind = torch.cummax(X.cuda(), dim=1)
X_minv, X_minind = torch.cummin(-X, dim=1)
X_cuda_minv, X_cuda_minind = torch.cummin(-X.cuda(), dim=1)
print(X_maxv)
print(X_cuda_maxv)
print(-X_minv)
print(-X_cuda_minv)
```

Output:
```
1.7.0.dev20200803
tensor([[9, 0, 1, 0, 7, 2, 1, 7, 1, 8],
        [7, 6, 1, 4, 2, 4, 6, 4, 2, 2],
        [2, 0, 6, 0, 6, 4, 8, 4, 1, 3],
        [2, 7, 4, 7, 9, 4, 6, 1, 5, 5]])

tensor([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [2, 2, 6, 6, 6, 6, 8, 8, 8, 8],
        [2, 7, 7, 7, 9, 9, 9, 9, 9, 9]])
tensor([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [6, 6, 6, 6, 6, 7, 7, 7, 7, 9],
        [2, 4, 4, 4, 4, 6, 8, 8, 8, 8],
        [4, 4, 4, 4, 4, 5, 8, 8, 8, 8]], device='cuda:0')
tensor([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [2, 2, 6, 6, 6, 6, 8, 8, 8, 8],
        [2, 7, 7, 7, 9, 9, 9, 9, 9, 9]])
tensor([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [2, 2, 6, 6, 6, 6, 8, 8, 8, 8],
        [2, 7, 7, 7, 9, 9, 9, 9, 9, 9]], device='cuda:0')
```

**Comment by ngimel** [comment]
The issue (with original snippet) is not fixed on nightlies. The input to cumsum is not contiguous in the original snippet. cc @anjali411
