### ISSUE TITLE
Undefined reference to fbgemm.

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#42415]
## 🐛 Bug

This is a build regression within last few days.
We got undefined reference `void fbgemm::CodeGenBase<unsigned char, signed char, int, int>::storeCRegs<asmjit::x86::Zmm, 64>(asmjit::x86::Emitter*, int, int, asmjit::x86::Gp, asmjit::x86::Gp, bool)`

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/5203025/89109182-7a82b200-d471-11ea-90e8-66d0adb25120.png">

Since there's an fbgemm update 2 days ago, that could be the reason.
https://github.com/pytorch/pytorch/pull/42302

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+gcc-8
 - CUDA/cuDNN version: 11/8

cc @ezyang @gchanan @zou3519 @malfet

**Comment by mruberry** [comment]
Did you update your submodules, clean, and then try building?

**Comment by xkszltl** [comment]
It is a fresh clone, no reused repo.

**Comment by xkszltl** [comment]
I tried the commit before https://github.com/pytorch/pytorch/pull/42302, and that works.

**Comment by z-a-f** [comment]
I have the same issue: https://gist.github.com/z-a-f/41ea79225bff7f6fde96832ea96d9984

**Comment by malfet** [comment]
Can you please share a full build log that leads to the failure? Symbol in question should be  defined in `GenerateKernelU8S8S32ACC32.cc`, as following command shows:
```
$ nm third_party/fbgemm/CMakeFiles/fbgemm_generic.dir/src/GenerateKernelU8S8S32ACC32.cc.o|c++filt |grep CodeGenBase|grep storeCRegs
0000000000000000 W void fbgemm::CodeGenBase<unsigned char, signed char, int, int>::storeCRegs<asmjit::x86::Ymm, 32>(asmjit::x86::Emitter*, int, int, asmjit::x86::Gp, asmjit::x86::Gp, bool)
0000000000000000 W void fbgemm::CodeGenBase<unsigned char, signed char, int, int>::storeCRegs<asmjit::x86::Zmm, 64>(asmjit::x86::Emitter*, int, int, asmjit::x86::Gp, asmjit::x86::Gp, bool)
```
And mangled version of the same symbol is: `_ZN6fbgemm11CodeGenBaseIhaiiE10storeCRegsIN6asmjit3x863ZmmELi64EEEvPNS4_7EmitterEiiNS4_2GpES8_b`

**Comment by z-a-f** [comment]
> Can you please share a full build log that leads to the failure? Symbol in question should be defined in `GenerateKernelU8S8S32ACC32.cc`, as following command shows:
> 
> ```
> $ nm third_party/fbgemm/CMakeFiles/fbgemm_generic.dir/src/GenerateKernelU8S8S32ACC32.cc.o|c++filt |grep CodeGenBase|grep storeCRegs
> 0000000000000000 W void fbgemm::CodeGenBase<unsigned char, signed char, int, int>::storeCRegs<asmjit::x86::Ymm, 32>(asmjit::x86::Emitter*, int, int, asmjit::x86::Gp, asmjit::x86::Gp, bool)
> 0000000000000000 W void fbgemm::CodeGenBase<unsigned char, signed char, int, int>::storeCRegs<asmjit::x86::Zmm, 64>(asmjit::x86::Emitter*, int, int, asmjit::x86::Gp, asmjit::x86::Gp, bool)
> ```
> 
> And mangled version of the same symbol is: `_ZN6fbgemm11CodeGenBaseIhaiiE10storeCRegsIN6asmjit3x863ZmmELi64EEEvPNS4_7EmitterEiiNS4_2GpES8_b`

This is the full log: https://gist.github.com/z-a-f/41ea79225bff7f6fde96832ea96d9984

**Comment by z-a-f** [comment]
Also, the third_party/fbgemm/CMakeFiles/ is not generated. Maybe the error thrown before it is?

**Comment by supriyar** [comment]
+1, seeing the same error.

**Comment by ezyang** [comment]
@dskhudia

**Comment by dskhudia** [comment]
I am taking a look at it.

**Comment by malfet** [comment]
This most likely should fix the issue:
```
diff --git a/src/GenerateKernelU8S8S32ACC32.cc b/src/GenerateKernelU8S8S32ACC32.cc
index 8b6f3c8..30fbda4 100644
--- a/src/GenerateKernelU8S8S32ACC32.cc
+++ b/src/GenerateKernelU8S8S32ACC32.cc
@@ -373,7 +373,7 @@ CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::getOrCreate(
 }
 
 /**
- * Instatiate the AVX512 instructions for 32-bit Accumulation macro-kernel.
+ * Instantiate the AVX512 instructions for 32-bit Accumulation macro-kernel.
  *
  */
 template
@@ -382,7 +382,7 @@ CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::
 getOrCreate<inst_set_t::avx512>(bool accum, int32_t mc, int32_t nc, int32_t kc);
 
 /**
- * Instatiate the AVX2 instructions for 32-bit Accumulation macro-kernel.
+ * Instantiate the AVX2 instructions for 32-bit Accumulation macro-kernel.
  *
  */
 template
@@ -390,4 +390,17 @@ CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::jit_micro_kernel_fp
 CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::
 getOrCreate<inst_set_t::avx2>(bool accum, int32_t mc, int32_t nc, int32_t kc);
 
+/**
+ * Instantiate the ZMM instructions for store kernel.
+ *
+ */
+template
+void CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::storeCRegs<x86::Zmm, 64>(
+    x86::Emitter* a,
+    int rowRegs,
+    int colRegs,
+    x86::Gp C_Offset,
+    x86::Gp ldcReg,
+    bool accum);
+
 } // namespace fbgemm
```

**Comment by supriyar** [comment]
> This most likely should fix the issue:
> 
> ```
> diff --git a/src/GenerateKernelU8S8S32ACC32.cc b/src/GenerateKernelU8S8S32ACC32.cc
> index 8b6f3c8..30fbda4 100644
> --- a/src/GenerateKernelU8S8S32ACC32.cc
> +++ b/src/GenerateKernelU8S8S32ACC32.cc
> @@ -373,7 +373,7 @@ CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::getOrCreate(
>  }
>  
>  /**
> - * Instatiate the AVX512 instructions for 32-bit Accumulation macro-kernel.
> + * Instantiate the AVX512 instructions for 32-bit Accumulation macro-kernel.
>   *
>   */
>  template
> @@ -382,7 +382,7 @@ CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::
>  getOrCreate<inst_set_t::avx512>(bool accum, int32_t mc, int32_t nc, int32_t kc);
>  
>  /**
> - * Instatiate the AVX2 instructions for 32-bit Accumulation macro-kernel.
> + * Instantiate the AVX2 instructions for 32-bit Accumulation macro-kernel.
>   *
>   */
>  template
> @@ -390,4 +390,17 @@ CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::jit_micro_kernel_fp
>  CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::
>  getOrCreate<inst_set_t::avx2>(bool accum, int32_t mc, int32_t nc, int32_t kc);
>  
> +/**
> + * Instantiate the ZMM instructions for store kernel.
> + *
> + */
> +template
> +void CodeGenBase<uint8_t, int8_t, int32_t, int32_t>::storeCRegs<x86::Zmm, 64>(
> +    x86::Emitter* a,
> +    int rowRegs,
> +    int colRegs,
> +    x86::Gp C_Offset,
> +    x86::Gp ldcReg,
> +    bool accum);
> +
>  } // namespace fbgemm
> ```

Thanks! Confirming that this fixes the issue for me.

**Comment by z-a-f** [comment]
This is not fixed, as the submodule reference is not updated

**Comment by z-a-f** [comment]
@dskhudia Does FBGEMM automatically sync? If yes, how often?

**Comment by dskhudia** [comment]
It does not automatically sync. It used to instantaneously but not anymore. Commits to fbgemm create a submodule PR such as https://github.com/pytorch/pytorch/pull/42496 and then we manually merge the PR if the pytorch CI tests look ok.

**Comment by dskhudia** [comment]
@z-a-f: I just landed the PR

**Comment by xkszltl** [comment]
Confirmed it's fixed.
