### ISSUE TITLE
Autograd not working for torch.exp(1j * phase)

### ISSUE THREAD

**Issue by jonashaag** [pytorch/pytorch#43349]
## 🐛 Bug

Complex tensor construction from magnitude and phase does not seem to support autograd when using `mag * torch.exp(1j * phase)` notation:

```py
import torch
mag, phase = torch.tensor(5., requires_grad=True), torch.tensor(3., requires_grad=True)

complex_good = torch.view_as_complex(torch.stack([mag * torch.cos(phase), mag * torch.sin(phase)], dim=-1))
complex_good.backward()  # works

complex_bad = mag * torch.exp(1j * phase)
complex_bad.backward()
```

=>

```
.../torch/autograd/__init__.py:125: UserWarning: Complex backward is not fully supported yet and could lead to wrong gradients for functions we have not fixed yet (Triggered internally at  /opt/conda/conda-bld/pytorch_1597820903894/work/torch/csrc/autograd/python_engine.cpp:172.)
  Variable._execution_engine.run_backward(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../torch/tensor.py", line 214, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File ".../torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Expected isFloatingType(grad.scalar_type()) || (input_is_complex == grad_is_complex) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
...
```

Torch version: 1.7.0.dev20200819

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @anjali411 @dylanbespalko

**Comment by anjali411** [comment]
@jonashaag thanks for reporting the issue! It's because the `MulBackward`'s behavior for complex is problematic:
```
>>> import torch
x=t>>> x=torch.randn(4, dtype=torch.cdouble)
>>> x=torch.randn(4, dtype=torch.cdouble, requires_grad=True)
>>> x=torch.randn(4, requires_grad=True)
>>> y=x*1j
>>> y
tensor([-0.-1.1449j, 0.+0.5593j, 0.+1.7524j, 0.+0.1101j],
       grad_fn=<MulBackward0>)
>>> y.sum().backward()
/home/chourdiaanjali/pytorch2/torch/autograd/__init__.py:127: UserWarning: Complex backward is not fully supported yet and could lead to wrong gradients for functions we have not fixed yet (Triggered internally at  ../torch/csrc/autograd/python_engine.cpp:172.)
  allow_unreachable=True)  # allow_unreachable flag
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chourdiaanjali/pytorch2/torch/tensor.py", line 214, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/chourdiaanjali/pytorch2/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected isFloatingType(grad.scalar_type()) || (input_is_complex == grad_is_complex) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```
As Alban mentioned, complex backward is not fully supported yet but many of these functions will be fixed soon.

> @anjali411 you might want to open a single umbrella issue that tracks these as I expect there will be more...
I have been adding these issues in the `Autograd Tasks` subsection in #33152

**Comment by cshewmake2** [comment]
Having the same issue as above. How's this going? Any way I can help?

**Comment by mountain** [comment]
same issue +1

**Comment by IvanYashchuk** [comment]
This was fixed in #43208.

**Comment by rjkilpatrick** [comment]
This is still an issue on nightly
``` python
>>> import torch
>>> print(torch.__version__)
>>> mag = torch.tensor(5., requires_grad=True, dtype=torch.complex128)
>>> phase = torch.tensor(3., requires_grad=True, dtype=torch.complex128)
>>>
>>> complex_good = mag * (torch.cos(phase) + 1.j * torch.sin(phase))
>>> complex_good.backward() # works
>>>
>>> complex_bad = mag * torch.exp(1j * phase)
>>> complex_bad.backward()

1.8.0.dev20201101
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-98d908b62931> in <module>
      8 complex_good.backward()  # works
      9 
---> 10 complex_bad = mag * torch.exp(1j * phase)
     11 complex_bad.backward()

RuntimeError: exp does not support automatic differentiation for outputs with complex dtype.
```

https://github.com/pytorch/pytorch/blob/1cc1da541158b53c24a579fd316d190d5c27bfd1/test/test_autograd.py#L4935-L4941
`torch.exp` is not being tested for autograd backwards on master

**Comment by anjali411** [comment]
fixed in #47194
