### ISSUE TITLE
Too few arguments to vulkanOptimizeForMobile()

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#45062]
## 🐛 Bug

Build failed.
This is a recent regression in the past few days.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/5203025/93755672-48eac380-fc36-11ea-8783-1df8dc415ec3.png">

This PR may be the reason: https://github.com/pytorch/pytorch/pull/44903

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): CentOS 7
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja

**Comment by malfet** [comment]
Thank you for reporting the issue. 
CC: @IvanKobzarev

**Comment by IvanKobzarev** [comment]
I think this issue was fixed in https://github.com/pytorch/pytorch/pull/45052

**Comment by malfet** [comment]
@xkszltl can you please check if issue is still reproducible with #45052 fix applied and reopen issue if this is the case.
