### ISSUE TITLE
INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/passes/onnx/unpack_quantized_weights.cpp":92

### ISSUE THREAD

**Issue by srohit0** [pytorch/pytorch#47204]
## 🐛 Bug

INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/passes/onnx/unpack_quantized_weights.cpp":92

## To Reproduce

```
import io
import torch
class aslTinyModel(nn.Module):
    def __init__(self):
        super(aslTinyModel, self).__init__()
        self.quant = torch.quantization.QuantStub()
        self.fc1 = nn.Linear(INPUT_LEN, 8)
        self.fc2 = nn.Linear(8, 4)
        self.fc3 = nn.Linear(4, NUM_GESTURES)
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):
        x = self.quant(x)
        x = x.view((-1, INPUT_LEN))
        h = F.relu(self.fc1(x))
        h = F.relu(self.fc2(h))
        h = F.relu(self.fc3(h))
        h = self.dequant(h)
        return h
model = aslTinyModel()
### TRAIN THE MODEL ###

###  QUANTIZE MODEL ###
import torch.quantization
num_calibration_batches = 10
model.eval()

# Specify quantization configuration
# Start with simple min/max range estimation and per-tensor quantization of weights
model.qconfig = torch.quantization.default_qconfig
qconfig = torch.quantization.get_default_qconfig('qnnpack')
print(model.qconfig)
torch.quantization.prepare(model, inplace=True)

### EXPORT TO ONNX ###
dummy_input = torch.randn(INPUT_LEN)
input_names = ["x"]
outputs = model(dummy_input)

traced = torch.jit.trace(model, dummy_input)
buf = io.BytesIO()
torch.jit.save(traced, buf)
buf.seek(0)

model = torch.jit.load(buf)
f = io.BytesIO()
torch.onnx.export(model, dummy_input, f, input_names=input_names, example_outputs=outputs,
                  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
f.seek(0)
```

## Error Message

/opt/tljh/user/lib/python3.7/site-packages/torch/onnx/utils.py:258: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/opt/tljh/user/lib/python3.7/site-packages/torch/onnx/utils.py:258: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)
<ipython-input-27-739d8081d6b8> in <module>
     13 f = io.BytesIO()
     14 torch.onnx.export(model, dummy_input, f, input_names=input_names, example_outputs=outputs,
---> 15                   operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
     16 f.seek(0)

/opt/tljh/user/lib/python3.7/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
    228                         do_constant_folding, example_outputs,
    229                         strip_doc_string, dynamic_axes, keep_initializers_as_inputs,
--> 230                         custom_opsets, enable_onnx_checker, use_external_data_format)
    231 
    232 

/opt/tljh/user/lib/python3.7/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
     89             dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs,
     90             custom_opsets=custom_opsets, enable_onnx_checker=enable_onnx_checker,
---> 91             use_external_data_format=use_external_data_format)
     92 
     93 

/opt/tljh/user/lib/python3.7/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, enable_onnx_checker, use_external_data_format, onnx_shape_inference, use_new_jit_passes)
    637                                 training=training,
    638                                 use_new_jit_passes=use_new_jit_passes,
--> 639                                 dynamic_axes=dynamic_axes)
    640 
    641             # TODO: Don't allocate a in-memory string for the protobuf

/opt/tljh/user/lib/python3.7/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, input_names, output_names, operator_export_type, example_outputs, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size, training, use_new_jit_passes, dynamic_axes)
    419                             fixed_batch_size=fixed_batch_size, params_dict=params_dict,
    420                             use_new_jit_passes=use_new_jit_passes,
--> 421                             dynamic_axes=dynamic_axes, input_names=input_names)
    422     from torch.onnx.symbolic_helper import _onnx_shape_inference
    423     if isinstance(model, torch.jit.ScriptModule) or isinstance(model, torch.jit.ScriptFunction):

/opt/tljh/user/lib/python3.7/site-packages/torch/onnx/utils.py in _optimize_graph(graph, operator_export_type, _disable_torch_constant_prop, fixed_batch_size, params_dict, use_new_jit_passes, dynamic_axes, input_names)
    180             torch.onnx.symbolic_helper._quantized_ops.clear()
    181             # Unpack quantized weights for conv and linear ops and insert into graph.
--> 182             torch._C._jit_pass_onnx_unpack_quantized_weights(graph, params_dict)
    183             # Insert permutes before and after each conv op to ensure correct order.
    184             torch._C._jit_pass_onnx_quantization_insert_permutes(graph, params_dict)

RuntimeError: false INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/passes/onnx/unpack_quantized_weights.cpp":92, please report a bug to PyTorch. Unrecognized quantized operator while trying to compute q_scale for operator aten::view

## Expected behavior

Not crash

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
~/ASL$ python3 collect_env.py
Collecting environment information...
/opt/tljh/user/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 5.0.0 (http://root.cern.ch/git/clang.git c698bd59e299f9418c416a08f8ec3bf4c24a314b) (http://root.cern.ch/git/llvm.git e0b472e46eb5861570497c2b9efabf96f2d4a485)
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0
[pip3] torchvision==0.8.1
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.7.0                    pypi_0    pypi
[conda] torchvision               0.8.1                    pypi_0    pypi

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @gmagogsfm

**Comment by mruberry** [comment]
cc @bzinodev as well

**Comment by jiafatom** [comment]
I cannot reproduce your issue on my local box. See my script which is more or less same as yours:
```python
#!/usr/bin/env python
import os
import torch
import onnxruntime
import numpy as np

def main():
    import io
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    INPUT_LEN = 12
    NUM_GESTURES = 6
    class aslTinyModel(nn.Module):
        def __init__(self):
            super(aslTinyModel, self).__init__()
            self.quant = torch.quantization.QuantStub()
            self.fc1 = nn.Linear(INPUT_LEN, 8)
            self.fc2 = nn.Linear(8, 4)
            self.fc3 = nn.Linear(4, NUM_GESTURES)
            self.dequant = torch.quantization.DeQuantStub()

        def forward(self, x):
            x = self.quant(x)
            x = x.view((-1, INPUT_LEN))
            h = F.relu(self.fc1(x))
            h = F.relu(self.fc2(h))
            h = F.relu(self.fc3(h))
            h = self.dequant(h)
            return h
    model = aslTinyModel()
    ### TRAIN THE MODEL ###

    ###  QUANTIZE MODEL ###
    import torch.quantization
    num_calibration_batches = 10
    model.eval()

    # Specify quantization configuration
    # Start with simple min/max range estimation and per-tensor quantization of weights
    model.qconfig = torch.quantization.default_qconfig
    qconfig = torch.quantization.get_default_qconfig('qnnpack')
    print(model.qconfig)
    torch.quantization.prepare(model, inplace=True)

    ### EXPORT TO ONNX ###
    dummy_input = torch.randn(INPUT_LEN)
    input_names = ["x"]
    outputs = model(dummy_input)

    traced = torch.jit.trace(model, dummy_input)
    buf = io.BytesIO()
    torch.jit.save(traced, buf)
    buf.seek(0)

    model = torch.jit.load(buf)
    f = io.BytesIO()
    torch.onnx.export(model, dummy_input, f, input_names=input_names, example_outputs=outputs,
                    operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
    f.seek(0)

if __name__ == "__main__":
    main()
```

And my env is almost same as yours, `mkl` does not make difference, see
```python
Collecting environment information...
/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0
[pip3] torchvision==0.8.1
[conda] mkl                       2019.0                   pypi_0    pypi
[conda] mkl-include               2019.0                   pypi_0    pypi
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.7.0                    pypi_0    pypi
[conda] torchvision               0.8.1                    pypi_0    pypi
```
It works smoothly, there is some warnings but it is fine and unrelated to your issue:
```
QConfig(activation=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, reduce_range=True), weight=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_tensor_symmetric))
/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch/quantization/observer.py:121: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  reduce_range will be deprecated in a future release of PyTorch."
/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch/onnx/utils.py:258: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch/onnx/utils.py:258: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
```

**Comment by srohit0** [comment]
@jiafatom - that's likely because you've not trained the model. 

Unfortunately, I can't give you proprietary customer data. I'll help as much as I can.

You must add the missing piece, if you're interested in reproducing the issue.

**Comment by spandantiwari** [comment]
@srohit0  - I am wondering if there's a change in topology of the model when it is trained? 
Also, I see that you are using `torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK`, which means that this is not ONNX export. 
Can you try with torch.onnx.OperatorExportTypes.ONNX and see if you get any issues. If you do, it will be great if you can provide a repro so that we can investigate. 
If this is blocking you, I would also suggest trying to send in nn.Module model as input instead of ScriptModule, as that may help with ONNX export.

**Comment by AllenTiTaiWang** [comment]
We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team

**Comment by srohit0** [comment]
The has become stale has become stale because it was not addressed in the
past 3 years.

Please open it, make sure the issue is addressed fixed and resolved before
you close it again.

Closing it would not help the pyTorch software heal itself.

🙏

**Comment by justinchuby** [comment]
Does the issue go away when you set operator_export_type to ONNX? Could you verify that the issue still exists with the latest pytorch nightly build?

**Comment by thiagocrepaldi** [comment]
This is working on pytorch master

```
import io
import torch
from torch import nn
import torch.nn.functional as F

INPUT_LEN = 12
NUM_GESTURES = 6


class aslTinyModel(nn.Module):
    def __init__(self):
        super(aslTinyModel, self).__init__()
        self.quant = torch.quantization.QuantStub()
        self.fc1 = nn.Linear(INPUT_LEN, 8)
        self.fc2 = nn.Linear(8, 4)
        self.fc3 = nn.Linear(4, NUM_GESTURES)
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):
        x = self.quant(x)
        x = x.view((-1, INPUT_LEN))
        h = F.relu(self.fc1(x))
        h = F.relu(self.fc2(h))
        h = F.relu(self.fc3(h))
        h = self.dequant(h)
        return h


model = aslTinyModel()
### TRAIN THE MODEL ###

###  QUANTIZE MODEL ###
import torch.quantization

num_calibration_batches = 10
model.eval()

# Specify quantization configuration
# Start with simple min/max range estimation and per-tensor quantization of weights
model.qconfig = torch.quantization.default_qconfig
qconfig = torch.quantization.get_default_qconfig("qnnpack")
print(model.qconfig)
torch.quantization.prepare(model, inplace=True)

### EXPORT TO ONNX ###
dummy_input = torch.randn(INPUT_LEN)
input_names = ["x"]
outputs = model(dummy_input)

traced = torch.jit.trace(model, dummy_input)
buf = io.BytesIO()
torch.jit.save(traced, buf)
buf.seek(0)

model = torch.jit.load(buf)
f = io.BytesIO()
torch.onnx.export(
    model,
    dummy_input,
    f,
    input_names=input_names,
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
    verbose=True
)
f.seek(0)
```

The only change from the original repro was deleting the `example_outputs` argument for `torch.onnx.export`, which is deprecated for a long time

the resulting onnx graph is

```bash
Exported graph: graph(%x : Float(12, strides=[1], requires_grad=0, device=cpu),
      %fc1.bias : Float(8, strides=[1], requires_grad=0, device=cpu),
      %fc1.weight : Float(8, 12, strides=[12, 1], requires_grad=0, device=cpu),
      %fc2.bias : Float(4, strides=[1], requires_grad=0, device=cpu),
      %fc2.weight : Float(4, 8, strides=[8, 1], requires_grad=0, device=cpu),
      %fc3.bias : Float(6, strides=[1], requires_grad=0, device=cpu),
      %fc3.weight : Float(6, 4, strides=[4, 1], requires_grad=0, device=cpu)):
  %aten::ATen_15 : Long(2, strides=[1], device=cpu) = onnx::Constant[value= -1  12 [ CPULongType{2} ]]()
  %/ATen_output_0 : Tensor = aten::ATen[operator="view", overload_name="", onnx_name="/ATen"](%x, %aten::ATen_15), scope: aslTinyModel:: # /home/thiagofc/dev/pytorch_repros/onnx_fallback_assert.py:21:0
  %/fc1/ATen_output_0 : Tensor = aten::ATen[operator="linear", overload_name="", onnx_name="/fc1/ATen"](%/ATen_output_0, %fc1.weight, %fc1.bias), scope: aslTinyModel::/torch.nn.modules.linear.Linear::fc1 # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/modules/linear.py:114:0
  %/ATen_1_output_0 : Tensor = aten::ATen[operator="relu", overload_name="", onnx_name="/ATen_1"](%/fc1/ATen_output_0), scope: aslTinyModel:: # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/functional.py:1457:0
  %/fc2/ATen_output_0 : Tensor = aten::ATen[operator="linear", overload_name="", onnx_name="/fc2/ATen"](%/ATen_1_output_0, %fc2.weight, %fc2.bias), scope: aslTinyModel::/torch.nn.modules.linear.Linear::fc2 # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/modules/linear.py:114:0
  %/ATen_2_output_0 : Tensor = aten::ATen[operator="relu", overload_name="", onnx_name="/ATen_2"](%/fc2/ATen_output_0), scope: aslTinyModel:: # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/functional.py:1457:0
  %/fc3/ATen_output_0 : Tensor = aten::ATen[operator="linear", overload_name="", onnx_name="/fc3/ATen"](%/ATen_2_output_0, %fc3.weight, %fc3.bias), scope: aslTinyModel::/torch.nn.modules.linear.Linear::fc3 # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/modules/linear.py:114:0
  %22 : Float(*, *, strides=[6, 1], requires_grad=1, device=cpu) = aten::ATen[operator="relu", overload_name="", onnx_name="/ATen_3"](%/fc3/ATen_output_0), scope: aslTinyModel:: # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/functional.py:1457:0
  return (%22)
```

or in Netron...


![Image](https://user-images.githubusercontent.com/5469809/199804214-c5abcca5-1285-4d53-bcbb-29fecef700e7.png)

If you use the `operator_export_type=ONNX`, the ONNX graph becomes

```bash
Exported graph: graph(%x : Float(12, strides=[1], requires_grad=0, device=cpu),
      %fc1.bias : Float(8, strides=[1], requires_grad=0, device=cpu),
      %fc1.weight : Float(8, 12, strides=[12, 1], requires_grad=0, device=cpu),
      %fc2.bias : Float(4, strides=[1], requires_grad=0, device=cpu),
      %fc2.weight : Float(4, 8, strides=[8, 1], requires_grad=0, device=cpu),
      %fc3.bias : Float(6, strides=[1], requires_grad=0, device=cpu),
      %fc3.weight : Float(6, 4, strides=[4, 1], requires_grad=0, device=cpu)):
  %/Constant_output_0 : Long(2, strides=[1], device=cpu) = onnx::Constant[value= -1  12 [ CPULongType{2} ], onnx_name="/Constant"](), scope: aslTinyModel:: # /home/thiagofc/dev/pytorch_repros/onnx_fallback_assert.py:21:0
  %/Reshape_output_0 : Float(1, 12, strides=[12, 1], device=cpu) = onnx::Reshape[allowzero=0, onnx_name="/Reshape"](%x, %/Constant_output_0), scope: aslTinyModel:: # /home/thiagofc/dev/pytorch_repros/onnx_fallback_assert.py:21:0
  %/fc1/Gemm_output_0 : Float(1, 8, strides=[8, 1], device=cpu) = onnx::Gemm[alpha=1., beta=1., transB=1, onnx_name="/fc1/Gemm"](%/Reshape_output_0, %fc1.weight, %fc1.bias), scope: aslTinyModel::/torch.nn.modules.linear.Linear::fc1 # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/modules/linear.py:114:0
  %/Relu_output_0 : Float(1, 8, strides=[8, 1], device=cpu) = onnx::Relu[onnx_name="/Relu"](%/fc1/Gemm_output_0), scope: aslTinyModel:: # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/functional.py:1457:0
  %/fc2/Gemm_output_0 : Float(1, 4, strides=[4, 1], device=cpu) = onnx::Gemm[alpha=1., beta=1., transB=1, onnx_name="/fc2/Gemm"](%/Relu_output_0, %fc2.weight, %fc2.bias), scope: aslTinyModel::/torch.nn.modules.linear.Linear::fc2 # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/modules/linear.py:114:0
  %/Relu_1_output_0 : Float(1, 4, strides=[4, 1], device=cpu) = onnx::Relu[onnx_name="/Relu_1"](%/fc2/Gemm_output_0), scope: aslTinyModel:: # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/functional.py:1457:0
  %/fc3/Gemm_output_0 : Float(1, 6, strides=[6, 1], device=cpu) = onnx::Gemm[alpha=1., beta=1., transB=1, onnx_name="/fc3/Gemm"](%/Relu_1_output_0, %fc3.weight, %fc3.bias), scope: aslTinyModel::/torch.nn.modules.linear.Linear::fc3 # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/modules/linear.py:114:0
  %22 : Float(1, 6, strides=[6, 1], requires_grad=1, device=cpu) = onnx::Relu[onnx_name="/Relu_2"](%/fc3/Gemm_output_0), scope: aslTinyModel:: # /home/thiagofc/dev/github/pytorch-dev1/torch/nn/functional.py:1457:0
  return (%22)
```

or



![Image](https://user-images.githubusercontent.com/5469809/199804424-4ccf4803-b9eb-41a3-b542-6215eefac23b.png)

**Comment by thiagocrepaldi** [comment]
Please reopen if you have a valid repro.
