### ISSUE TITLE
nn.Embedding broken for half

### ISSUE THREAD

**Issue by csarofeen** [pytorch/pytorch#4752]
```.py
import torch
import torch.nn as nn
from torch.autograd import Variable

encoder = nn.Embedding(10, 100)
encoder = encoder.cuda().half()
inp = Variable(torch.arange(10).cuda().long())

out = encoder(inp)
loss = out.sum()
loss.backward()
```
produces the error:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    loss.backward()
  File "/opt/pytorch/pytorch/torch/autograd/variable.py", line 127, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/pytorch/pytorch/torch/autograd/__init__.py", line 83, in backward
    variables, grad_variables, retain_graph, create_graph)
RuntimeError: data() cast to unexpected type.
```

**Comment by csarofeen** [comment]
Maybe from... https://github.com/pytorch/pytorch/pull/4322 @colesbury thoughts?

**Comment by soumith** [comment]
fixed via #4760

**Comment by ailzhang** [comment]
This is still broken for me while working on testcases. Minimal repro with 
```
import torch
import torch.nn as nn
from torch.autograd import Variable

encoder = nn.Embedding(10, 100, max_norm=1.0)
encoder = encoder.cuda().half()
inp = Variable(torch.arange(10).cuda().long())

out = encoder(inp)
```

**Comment by ngimel** [comment]
This was broken (again) by #4892. @csarofeen can you please reopen the issue?
