### ISSUE TITLE
Warning thrown when instantiating ParameterList

### ISSUE THREAD

**Issue by adrianjav** [pytorch/pytorch#49285]
## 🐛 Bug

Not something too concerning, but I found that, when I create a ParameterList object a warning is thrown regarding an asignment on the ParameterList object.

## To Reproduce

Running the following code:

```python
import torch
params = torch.nn.ParameterList([torch.nn.Parameter(torch.ones([1])) for _ in range(2)])
```

produces: 

`[...]/torch/nn/modules/container.py:434: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")`'.

Debugging I found that the origin of the warning is line 229 of `module.py`: 
```python
self.training = True
```

Basically, the reason of the warning is that ParameterList is a subclass of `Module`.

## Expected behavior

A warning should not be thrown.

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] geotorch==0.1.0
[pip3] numpy==1.19.2
[pip3] pytorch-ignite==0.4.2
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.7.0
[pip3] torch-optimizer==0.0.1a17
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] geotorch                  0.1.0                    pypi_0    pypi
[conda] ignite                    0.4.2                    py38_0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.7.0           py3.8_cuda11.0.221_cudnn8.0.3_0    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.0.1a17                 pypi_0    pypi
[conda] torchaudio                0.7.0                      py38    pytorch
[conda] torchvision               0.8.1                py38_cu110    pytorch

## Additional context

cc @albanD @mruberry @jbschlosser

**Comment by mariosasko** [comment]
This is fixed in PyTorch 1.7.1.

**Comment by segalinc** [comment]
I have PyTorch 1.7.1 and checked all the other packages version but still happening

**Comment by iFe1er** [comment]
Have PyTorch 1.7.1 ,but this warning is still happening @mariokostelac

**Comment by mariosasko** [comment]
It should be fixed in the nighlty build. Let me know if that's not the case.

**Comment by LinXueyuanStdio** [comment]
temporary solution

```python
import warnings
warnings.filterwarnings("ignore", message="Setting attributes on ParameterList is not supported.")```

**Comment by albanD** [comment]
Fixed now
