### ISSUE TITLE
RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 11)

### ISSUE THREAD

**Issue by Naagar** [pytorch/pytorch#50095]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: cudnn/7-cuda-10.0
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by ezyang** [comment]
cc @vishwakftw but you might just be out of luck, sounds like something ill-conditioned going on here

**Comment by Naagar** [comment]
how can I resolve this any suggestions?

**Comment by vishwakftw** [comment]
Can you extract the matrix that you are performing SVD over?

**Comment by Naagar** [comment]
code was working fine, I did update something, and this error starts showing.

**Comment by renyiryry** [comment]
Hi,

I'm experiencing similar issues. In particular, the error would occur if the data is held on GPU. However, if the data is held on CPU, SVD works fine. 

I was wondering if there is a way to bridge the gap between GPU and CPU.

The code is
`import pickle
import torch

with open('gpu_svd.pkl', 'rb') as fp:
    A = pickle.load(fp)

print('A.shape')
print(A.shape)

torch.svd(torch.from_numpy(A))

torch.svd(torch.from_numpy(A).cuda())`

The output is attached. 
<img width="775" alt="Screen Shot 2021-03-04 at 10 11 56 AM" src="https://user-images.githubusercontent.com/49887303/109984797-1efff780-7cd2-11eb-8ce7-7102fc242a1e.png">

The data (gpu_svd.pkl) can be found at https://github.com/renyiryry/gpu_svd/blob/main/gpu_svd.pkl.

Thanks a lot!

**Comment by zwzhang121** [comment]
so, what is the solution?

**Comment by Lezcano** [comment]
This is solved in master. When the algorithm does not converge now we fallback to an implementation that always converges.

**Comment by realsarm** [comment]
I still face this when using https://github.com/jettify/pytorch-optimizer#shampoo which uses `torch.svd` @Lezcano 

RuntimeError: svd_cpu: the updating process of SBDSDC did not converge (error: 1)

**Comment by Lezcano** [comment]
`torch.svd` is in the process of being deprecated. I suggest you submit an issue / PR to that repo updating the use of `torch.svd` by `linalg.svd`.
