### ISSUE TITLE
nn.function.interpolate with bi/trilinear or bicubic is VERY slow when using AMP

### ISSUE THREAD

**Issue by FabianIsensee** [pytorch/pytorch#51206]
Using nn.functional.interpolate is very slow when using mixed precision training. This seems to have already been an issue in the past (#12409) and should be fixed, but I am still seeing a performance regression of up to 5x (yes, that is 5x the runtime of fp32) depending on the network an GPU.

To demonstrate the issue I have created a small script that reproduces it. I am mostly interested in 3D images which is why that example uses 3D convs, but the same issue appears also with 2D inputs (see below, I will add a separate section for that).

What my script does is the following:
It builds a very simple convolutional encoder network (VGG style) that downsamples the input 1x64x64x64 to 512x4x4x4. It then blows up the small representation back to 512x64x64x64 using interpolate. The loss is then simple the MSE between input and upsampled output. 
This workflow does not represent a useful application, it is just there to put some load on the GPU and isolate the issue.

I run 100 iterations with this setup in three settings
1) regular fp32
2) regular AMP
3) AMP but with a hack: the encoding (512x4x4x4 tensor) is cast to float, then upsampled and then cast to half.

**Expected behavior:**
2. should be much faster than 1. due to tensor core acceleration of the convolutions, 3. should be slower than 2. due to additional overhead (casting)

**Actual behavior:**
2. is slower than 1.. 3. is faster than 2.

**Environment:**
I am using pytorch 1.7.0 compiled with cuDNN 8.0.5.39. OS is Ubuntu 18.04 (RTX 3090) and centOS (RTX 2080ti, V100).

I am also showing results for 1.7.1 with cuDNN 7.6.5 (installed with pip today) to demonstrate that is not related to my build.

**Details and standalone script**

```python
from time import time

from torch import nn
import torch
from torch.cuda.amp import GradScaler, autocast
from torch.nn import functional
from torch.optim import SGD


class Network(nn.Module):
    def __init__(self, cast_for_upsample=False):
        super().__init__()
        self.cast_for_upsample = cast_for_upsample

        self.layers = nn.Sequential(
            nn.Conv3d(1, 32, 3, 1, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),
            nn.Conv3d(32, 32, 3, 1, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),

            nn.Conv3d(32, 64, 3, 2, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),
            nn.Conv3d(64, 64, 3, 1, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),

            nn.Conv3d(64, 128, 3, 2, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),
            nn.Conv3d(128, 128, 3, 1, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),

            nn.Conv3d(128, 256, 3, 2, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),
            nn.Conv3d(256, 256, 3, 1, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),

            nn.Conv3d(256, 512, 3, 2, 1, 1, 1, False),
            nn.LeakyReLU(1e-2, True),
            nn.Conv3d(512, 512, 3, 1, 1, 1, 1, False),
        )

    def forward(self, x):
        down = self.layers(x)
        if self.cast_for_upsample:
            up = nn.functional.interpolate(down.float(), x.shape[2:], None, 'trilinear').half()
        else:
            up = nn.functional.interpolate(down, x.shape[2:], None, 'trilinear')
        return up


if __name__ == "__main__":
    inp = torch.rand((2, 1, 64, 64, 64)).cuda()

    net = Network(cast_for_upsample=False).cuda()
    optimizer = SGD(net.parameters(), 0.001)

    torch.cuda.empty_cache()

    # warmup
    for _ in range(10):
        optimizer.zero_grad()
        out = net(inp)
        l = torch.square(inp - out).mean() # just the MSE between input and output as a dummy loss function
        l.backward()
        optimizer.step()

    # fp32 measurement
    st = time()
    for _ in range(100):
        optimizer.zero_grad()
        out = net(inp)
        l = torch.square(inp - out).mean() # just the MSE between input and output as a dummy loss function
        l.backward()
        optimizer.step()
    print('fp32:', time() - st)

    ####################################################
    # now AMP
    net = Network(cast_for_upsample=False).cuda()
    optimizer = SGD(net.parameters(), 0.001)
    scaler = GradScaler()

    torch.cuda.empty_cache()

    # warmup
    for _ in range(10):
        optimizer.zero_grad()

        with autocast():
            out = net(inp)
            l = torch.square(inp - out).mean()  # just the MSE between input and output as a dummy loss function

        scaler.scale(l).backward()
        scaler.step(optimizer)
        scaler.update()

    # amp measurement
    st = time()
    for _ in range(100):
        optimizer.zero_grad()

        with autocast():
            out = net(inp)
            l = torch.square(inp - out).mean()  # just the MSE between input and output as a dummy loss function

        scaler.scale(l).backward()
        scaler.step(optimizer)
        scaler.update()
    print('amp:', time() - st)

    ####################################################
    # now AMP with hacking interpolate so that is runs in fp32
    net = Network(cast_for_upsample=True).cuda()
    optimizer = SGD(net.parameters(), 0.001)
    scaler = GradScaler()

    torch.cuda.empty_cache()

    # warmup
    for _ in range(10):
        optimizer.zero_grad()

        with autocast():
            out = net(inp)
            l = torch.square(inp - out).mean()  # just the MSE between input and output as a dummy loss function

        scaler.scale(l).backward()
        scaler.step(optimizer)
        scaler.update()

    # amp measurement
    st = time()
    for _ in range(100):
        optimizer.zero_grad()

        with autocast():
            out = net(inp)
            l = torch.square(inp - out).mean()  # just the MSE between input and output as a dummy loss function

        scaler.scale(l).backward()
        scaler.step(optimizer)
        scaler.update()
    print('amp cast to float:', time() - st)
```

I ran this on multiple types of GPUs. Numbers represent time for 100 iterations in seconds.
RTX 3090 (Ampere), 3D:

> fp32: 11.094072580337524
> amp: 55.94109606742859
> amp cast to float: 9.90783166885376

V100 (Volta), 3D:

> fp32: 11.654786348342896
> amp: 62.763665199279785
> amp cast to float: 10.015439987182617

RTX 2080ti (Turing), 3D:

> fp32: 13.840788841247559
> amp: 65.24087715148926
> amp cast to float: 12.579991817474365

As you can see, all architectures run significantly slower with amp. If I enable the casting hack the runtime is reduced substantially, which tells me that the issue is related to upsampling fp16 inputs (or distributing the gradiants through this operation in the backwards pass). 

To verify that this is not related to 3D inputs I also ran it in 2d (just replace all Conv3d with Conv2d and use `inp = torch.rand((2, 1, 512, 512)).cuda()`). Same story (showing RTX3090 only):

RTX 3090 (Ampere), 2D:

> fp32: 18.6866774559021
> amp: 32.80347037315369
> amp cast to float: 18.29295825958252

(same story with 'bicubic', data not shown)

To ensure this is related to bi/trilinear and bicubic interpolation I changed the interpolation to 'nearest', 2D:
> fp32: 4.452304124832153
> amp: 3.830399990081787
> amp cast to float: 4.455098628997803

'nearest' is working fine.

To ensure this is not related to my pytorch build I also ran it with pytorch 1.7.1 (installed today with pip). This is a 2D run on a RTX 2080 ti because 1) RTX 3090 is not supported with cuDNN 7.6.5 so I cannot run it on this GPU and 2) 1.7.1 still comes with cuDNN 7.6.5 which does not support tensor core acceleration for 3D convs on Turing, so 3D will be extra slow.

RTX 2080 ti, torch 1.7.1, cuDNN 7.6.5, 2D:
> fp32: 21.80005693435669
> amp: 35.320844650268555
> amp cast to float: 22.71259832382202

still there :-)

Would be great if someone could look into this! If there is anything else you need please let me know. 

Best,

Fabian

cc @mcarilli @ptrblck

**Comment by FabianIsensee** [comment]
Update: the issue is related to the backwards pass. If I comment out the following lines for the AMP parts:
```python
        scaler.scale(l).backward()
        scaler.step(optimizer)
        scaler.update()
```

and the following lines for the non-amp part:
```python
        l.backward()
        optimizer.step()
```

Then the behavior is as expected:

RTX 3090 (Ampere), 3D, only forward pass:
> fp32: 1.6627814769744873
> amp: 1.5250365734100342
> amp cast to float: 1.8649287223815918

Best,
Fabian

**Comment by xwang233** [comment]
Thanks for the report. This should've been fixed in https://github.com/pytorch/pytorch/pull/48675 and https://github.com/pytorch/pytorch/pull/50084. Please try a nightly build.

**Comment by FabianIsensee** [comment]
Hi,
unfortunately the nightly build is much, much worse:

RTX 2080ti, 3D:
> fp32: 138.59609055519104
> amp: 267.24780797958374
> amp cast to float: 148.06238794326782

It's like 10x slower in all experiments. Same story with RTX 3090

Build: 
```
In [5]: torch.__version__                                                       
Out[5]: '1.8.0.dev20210127+cu110'
In [6]: torch.backends.cudnn.version()                                          
Out[6]: 8005
```

Best,
Fabian

**Comment by FabianIsensee** [comment]
In order to double and triple check I also created a fresh conda environment and built pytorch from scratch:

```
In [2]: torch.__version__
Out[2]: '1.8.0a0+00adc7b'

In [3]: torch.backends.cudnn.version()
Out[3]: 8005

```

same story. Issue persists in 2D and 3D is much much slower than it was before (and also has the same issue)

**Comment by xwang233** [comment]
I wrote a script to profile the time cost of `interpolate` only, with your tensor shapes `(2, 512, 4, 4, 4) -> (*, 64, 64, 64)`, and here are my results. Tested at d3ec204

<details>
<summary> code </summary>
<p>

```python
import torch
import time

niter = 1000
# mode = 'trilinear'
mode = 'bilinear'

print(f'{mode=}')

# x = torch.randn((2, 512, 4, 4, 4), dtype=torch.float, device='cuda')
# upshape = (64, 64, 64)
x = torch.randn((2, 512, 4, 4), dtype=torch.float, device='cuda')
upshape = (64, 64)

# warmup
for _ in range(niter):
    y = torch.nn.functional.interpolate(x, upshape, None, mode)


# float
torch.cuda.synchronize()
start = time.time()

for _ in range(niter):
    y = torch.nn.functional.interpolate(x, upshape, None, mode)

torch.cuda.synchronize()
end = time.time()
print(f'float {(end - start) / niter : .4e}')


# half
xh = x.half()

torch.cuda.synchronize()
start = time.time()

for _ in range(niter):
    y = torch.nn.functional.interpolate(xh, upshape, None, mode)

torch.cuda.synchronize()
end = time.time()
print(f'half {(end - start) / niter : .4e}')


```

</p>
</details>


<details>
<summary> environment </summary>
<p>

```
PyTorch version: 1.8.0a0+d3ec204
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2070 SUPER
GPU 1: GeForce GTX 1070 Ti

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0a0+unknown
[conda] Could not collect
```

</p>
</details>

```
mode='trilinear'
(warning messages omitted)
float  3.6291e-03
half  3.4767e-03
```

```
mode='bilinear'
(warning messages omitted)
float  2.7261e-04
half  2.5113e-04
```

This shows that `interpolate` performance in half is no slower than float. The slower performance you saw with AMP could be real, but comes from another operator, e.g. `Conv3d`, `LeakyReLU`, or the optimizer. 

FYI, convolutions with tensor core acceleration requires using `channels_last` format, which is only supported for `Conv2d` at this moment. `Conv3d` with `channels_last_3d` is not supported now. Convolutions with `contiguous` format (default) may not see the acceleration effects from tensor core. 

If you find which operator executes slower in half than float dtype, please feel free to update this issue or open a new one.

**Comment by FabianIsensee** [comment]
HI, thank you for putting in the time to try and reproduce the issue. However, like I mentioned in my [previous post](https://github.com/pytorch/pytorch/issues/51206#issuecomment-768246763), the problem is related to back-propagating gradients through the interpolation operation. I have already demonstrated that the forward pass is not affected.

I am working with 3D convolutions and amp for a long time now (1.5 years?) and it works like a charm as long as I am not trying to interpolate. Volta, Turing (only with cuDNN 8.0.2 or newer) and Ampere all get a nice ~2x speed boost with amp and 3d convs, even though I am using the default layout. I am not knowledgeable about what happens in the background, but I would assume that cudnn will transpose the tensors to the format it needs (at a small overhead, of course). I therefore thank you for the pointer to the channels_last format (I will experiment with it in the hope of further improving training times), but it is unfortunately not related to the issue.

Since I saw the issue both with 2D and 3D convolutions this is another pointer that the channel layout is not the cause of the problem.

What worries me is the strong drop in performance of 3D interpolation (I verified that it is just the interpolation, other (3D) networks arenot affected) with the nightly build. Why is it 10 times slower than my 1.7.0 build with cuDNN 8.0.5.38? I verified that with two independent systems and GPUs (Ubuntu 18 & 20, RTX 2080ti and RTX 3090). 

Best,

Fabian

**Comment by xwang233** [comment]
The following code will not run because input data `x` does not require grad. The backward process in your script doesn't go through "backward of interpolate". 

```python
import torch

x = torch.randn(2, 512, 4, 4, 4, device='cuda')

y = torch.nn.functional.interpolate(x, (64, 64, 64), None, 'trilinear')

y.backward(torch.randn_like(y))
```

If the regression you saw is because of and only because of this extra interpolation forward, we may have big problem in the autograd or AMP engine.

Interpolation doesn't use cudnn. Convolution uses. The performance differences you saw in cudnn 8.0.5 could be reasonable, because cudnn changed some of the conv3d logics and algorithms in their backend.

cc @ptrblck @ngimel

**Comment by FabianIsensee** [comment]
Hi, since the conv layers in my script require gradients from the loss, and the loss was computed after nn.functional.interpolate was applied to the data - how else would the gradients get to the convs if not through the backwards of this function?

I see you need some more convincing that something is very off, so I reworked my script. The 'network' now does the following:
- apply one conv (2d or 3d) to the input so that the output tensor requires a gradient
- blow up the output of that conv with nn.functional.interpolate
- compute the mean of that just so that I have a scalar I can use as a dummy loss

<details>
  <summary>Code</summary>
  
```pyhton
from time import time

import torch
from torch import nn
from torch.cuda.amp import GradScaler, autocast
from torch.nn import functional
from torch.optim import SGD


class Network(nn.Module):
    def __init__(self, cast_for_upsample=False, conv_op=nn.Conv3d, stride=10, skip_upsample=False):
        """
        :param cast_for_upsample: if True, tensor will be cast to float before applying nn.functional.interpolate and
        then cast to half after that
        :param conv_op: nn.Conv3d or nn.Conv2d
        :param stride: stride of conv, just to make sure the output is smaller than the input
        :param skip_upsample: if True, the output will not be upsampled prior to pooling -> the problematic
        operation is skipped
        """
        super().__init__()
        self.skip_upsample = skip_upsample
        self.cast_for_upsample = cast_for_upsample

        self.layers = conv_op(1, 32, 3, stride, 1, 1, 1, False)

        if conv_op == nn.Conv2d:
            self.interp_mode = 'bilinear'
        else:
            self.interp_mode = 'trilinear'

    def forward(self, x):
        conv_output = self.layers(x)

        if not self.skip_upsample:
            if self.cast_for_upsample:
                conv_output = conv_output.float()

            # setting align_corners=False to suppress the warning. This has no effect
            conv_output = nn.functional.interpolate(conv_output, x.shape[2:], None, self.interp_mode, align_corners=False)

            if self.cast_for_upsample:
                conv_output = conv_output.half()

        pooled = conv_output.mean()
        return pooled


def run(inp, conv_op, skip_upsample=False):
    """
    runs 10 warmup iterations followed by 250 timed iterations
    uses float
    loss is just the mean of all outputs. It doesn't do anything useful. All we need is gradients
    """
    torch.cuda.empty_cache()

    net = Network(cast_for_upsample=False, conv_op=conv_op, skip_upsample=skip_upsample).cuda()
    optimizer = SGD(net.parameters(), 0.001)

    # warmup
    for _ in range(10):
        optimizer.zero_grad()
        out = net(inp)
        out.backward()
        optimizer.step()

    # fp32 measurement
    st = time()
    for _ in range(250):
        optimizer.zero_grad()
        out = net(inp)
        out.backward()
        optimizer.step()
    print('fp32:', time() - st)


def run_amp(inp, conv_op, cast_to_float_for_upsample, skip_upsample=False):
    """
    runs 10 warmup iterations followed by 250 timed iterations
    uses autocast
    loss is just the mean of all outputs. It doesn't do anything useful. All we need is gradients
    """
    torch.cuda.empty_cache()

    net = Network(cast_for_upsample=cast_to_float_for_upsample, conv_op=conv_op, skip_upsample=skip_upsample).cuda()
    optimizer = SGD(net.parameters(), 0.001)
    scaler = GradScaler()

    torch.cuda.empty_cache()

    # warmup
    for _ in range(10):
        optimizer.zero_grad()

        with autocast():
            out = net(inp)

        scaler.scale(out).backward()
        scaler.step(optimizer)
        scaler.update()

    # amp measurement
    st = time()
    for _ in range(250):
        optimizer.zero_grad()

        with autocast():
            out = net(inp)

        scaler.scale(out).backward()
        scaler.step(optimizer)
        scaler.update()
    print('amp, cast_to_float_for_upsample %s:' % cast_to_float_for_upsample, time() - st)


if __name__ == "__main__":
    ####### 2D ###########
    print('##### 2D #####')
    inp = torch.rand((1, 1, 512, 512)).cuda()
    conv_op = nn.Conv2d

    run(inp, conv_op)
    run_amp(inp, conv_op, False)
    run_amp(inp, conv_op, True)

    ####### 2D ###########
    print('##### 3D #####')
    inp = torch.rand((1, 1, 64, 64, 64)).cuda()
    conv_op = nn.Conv3d

    run(inp, conv_op)
    run_amp(inp, conv_op, False)
    run_amp(inp, conv_op, True)

    # now we skip the nn.functional.interpolate operation to demonstrate that this is not related to any other
    # component in the network
    ####### 2D ###########
    print('##### 2D, skipped nn.functional.interpolate #####')
    inp = torch.rand((1, 1, 512, 512)).cuda()
    conv_op = nn.Conv2d

    run(inp, conv_op, skip_upsample=True)
    run_amp(inp, conv_op, False, skip_upsample=True)

    ####### 2D ###########
    print('##### 3D, skipped nn.functional.interpolate no upsampling #####')
    inp = torch.rand((1, 1, 64, 64, 64)).cuda()
    conv_op = nn.Conv3d

    run(inp, conv_op, skip_upsample=True)
    run_amp(inp, conv_op, False, skip_upsample=True)
```
</details>

pytorch 1.7.0, cuDNN 8.0.5. Built myself a while ago because I needed the newer cuDNN.

<details>
  <summary>environment</summary>
Collecting environment information...
PyTorch version: 1.7.0a0+e85d494
Is debug build: True
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0a0
[conda] blas                      1.0                         mkl  
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] torch                     1.7.0a0                  pypi_0    pypi

</details>

> ##### 2D #####
> fp32: 0.3951711654663086
> amp, cast_to_float_for_upsample False: 1.2462618350982666
> amp, cast_to_float_for_upsample True: 0.6320717334747314
> ##### 3D #####
> fp32: 0.42516326904296875
> amp, cast_to_float_for_upsample False: 37.353150367736816
> amp, cast_to_float_for_upsample True: 0.714409351348877

> ##### 2D, skipped nn.functional.interpolate #####
> fp32: 0.08720135688781738
> amp, cast_to_float_for_upsample False: 0.20691871643066406
> ##### 3D, skipped nn.functional.interpolate no upsampling #####
> fp32: 0.10375046730041504
> amp, cast_to_float_for_upsample False: 0.21683597564697266

Observations: 
The network is so small that the additional overhead of autocast increases the computation time rather than providing a benefit. So we can no longer expect the amp run to be faster. *However* the amp run that casts the tensor to float, then runs interpolate and then casts back to half should be slower because of the additional casting operations. Yet it is 2x faster in 2D and a whopping >40x faster in 3D. That should not be the case.
The runs where I skipped nn.functional.interpolate are there to underline that the 37s seen with 3D conv are indeed not caused by the convolution. Both 2D and 3D see the same performance regression which is likely due to amp overhead with that single conv operation.

pytorch 1.8.0, cuDNN 8.0.5. Built yesterday from master

<details>
  <summary>environment</summary>
Collecting environment information...
PyTorch version: 1.8.0a0+00adc7b
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0a0+unknown
[conda] blas                      1.0                         mkl  
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] torch                     1.8.0a0+unknown          pypi_0    pypi

</details>

> ##### 2D #####
> fp32: 0.41517066955566406
> amp, cast_to_float_for_upsample False: 1.277278184890747
> amp, cast_to_float_for_upsample True: 0.6261446475982666
> ##### 3D #####
> fp32: 2.675328254699707
> amp, cast_to_float_for_upsample False: 7.534709930419922
> amp, cast_to_float_for_upsample True: 3.6167726516723633

> ##### 2D, skipped nn.functional.interpolate #####
> fp32: 0.08946037292480469
> amp, cast_to_float_for_upsample False: 0.19239377975463867
> ##### 3D, skipped nn.functional.interpolate no upsampling #####
> fp32: 0.10310506820678711
> amp, cast_to_float_for_upsample False: 0.19246387481689453

Vey strange things happening. The 3D amp run with interpolate is now not as bad as it was before (7.5s vs 37) but the 3D interpolate is MUCH slower than before (see 3D numbers fp32 went from 0.42 to 2.67s (6x slower!) and amp with cast went from 0.71 to 3.6s (5x slower!!))
Plain 2D and 3D conv speeds (skipped interpolate) are unchanged between the two pytorch versions. 2D with interpolate is also unchanged between the pytorch versions, but still has the issue that amp interpolate is slower without the cast.

Best,
Fabian

**Comment by ngimel** [comment]
@FabianIsensee thank you for the updates and the simplified script. 
@xwang233 in both original and simplified scripts the backward for interpolation is run (it is at the end of the network, not the beginning), and it should be run, so in that sense there's no problem with amp. 
For the sizes in the simplified script (and most likely in the original, but I didn't double-check) the backward interpolate kernel time is much slower in master than it was in 1.7, both for fp32 and fp16. 
Simplified script, 3D: 1,32,7,7,7 -> 1,32,64,64,64, P100, interpolation backward kernel time according to nvprof 
fp32 master ~32 ms
fp16 master ~39 ms
fp32 1.7.       ~4.7 ms
fp16 1.7        ~8.3 ms

@FabianIsensee is such a large interpolation (7->64 or 4->64) a typical usecase? I suspect the kernels are optimized for interpolation by a factor of 2 give or take, so 7->14, or 4->8, and if this big blow-up case is common, a different approach might be needed.

**Comment by FabianIsensee** [comment]
Hi there, thank you for looking into this and confirming the issue! I stumbled upon this issue when training a segmentation network with deep supervision. It is a U-Net type architecture where there are segmentation heads at each stage of the decoder pathway. There is some evidence in the literature that upscaling the logits to the full resolution may be superior to downsampling the segmentations.

From Deeplab V3 paper (https://arxiv.org/pdf/1706.05587.pdf):
> Upsampling logits: In our previous works [10, 11], the target groundtruths are downsampled by 8 during training when output stride = 8. We find it important to keep the groundtruths intact and instead upsample the final logits, since downsampling the groundtruths removes the fine annotations resulting in no back-propagation of details.

I wanted to try that myself. When I did that (note that this is on pytorch 1.7 with cudnn 8.0.5 and amp enabled) I noticed that my epoch time went up from 95s to over 300s. After some searching I found the trick of casting feature maps to float prior to applying interpolation and that cut down my epoch time to ~140s. So yeah - for me it's a real use case and a real problem but I don't know how many people could be (unknowingly) affected. 

Just to give some more details: In the network I was using the following tensor sizes were upscaled to the original image resolution:
(2, 3, 8, 8, 8), (2, 3, 16, 16, 16), (2, 3, 32, 32, 32), (2, 3, 64,64,64)

The original resolution was (2, 3, 128, 128, 128).

The code I was using is nnU-Net, a segmentation method for biomedical images that I developed. It has a fairly large userbase (https://github.com/MIC-DKFZ/nnUNet, 1.3k stars) and if upscaling the logits provides a benefit to segmentation accuracy I would like to make this feature available. This will however require the performance of interpolate to be good enough. Even a regression of 95->140s per epoch (with the hack) is too much given that training times are rather long already. 

Finally, I would like to recap the two problems that were uncovered as part of this issue. They are not necessarily related:
1. In 1.7, the upsampling is 2x (or more) slower with amp enabled than it is with fp32. This should not be the case. I would expect it to be equally fast with amp enabled (as far as I know this operation does not benefit from tensor cores). Note that this issue is, like you confirmed, related to the backwards pass.
2. In master, upsampling is much slower than in 1.7. Such a performance regression is certainly not intended. Also, again, fp16 is a bit slower than fp32 which is not what I would expect.

Best,

Fabian

**Comment by ngimel** [comment]
@xwang233 please benchmark #48675 on a wider range of input sizes, and at the very least switch to the old implementation for cases that regress.

**Comment by xwang233** [comment]
Thanks @FabianIsensee for discovering the issue. @ngimel , I'll check the benchmark for the interpolation backward.

**Comment by FabianIsensee** [comment]
Hi there, are there any updates on this?

**Comment by MagicFrogSJTU** [comment]
Any updates?
