### ISSUE TITLE
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 6021 but linked against 5110

### ISSUE THREAD

**Issue by ztwe** [pytorch/pytorch#5369]
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import model
  File "/home/abc/github/chinese-ocr/model.py", line 5, in <module>
    from crnn.crnn import crnnOcr
  File "/home/abc/github/chinese-ocr/crnn/crnn.py", line 72, in <module>
    model,converter = crnnSource()
  File "/home/abc/github/chinese-ocr/crnn/crnn.py", line 64, in crnnSource
    model = crnn.CRNN(32, 1, len(alphabet)+1, 256, 1).cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 65, in flatten_parameters
    if not any_param.is_cuda or not torch.backends.cudnn.is_acceptable(any_param):
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/__init__.py", line 82, in is_acceptable
    if _libcudnn() is None:
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/__init__.py", line 58, in _libcudnn
    'but linked against {}'.format(compile_version, __cudnn_version))
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 6021 but linked against 5110

How to solve the problem?

**Comment by soumith** [comment]
could you pull the latest master branch and recompile. I pushed a change yesterday that fixes this: https://github.com/pytorch/pytorch/pull/5345

**Comment by ztwe** [comment]
@soumith  It still fails.

/usr/local/lib/python2.7/dist-packages/keras/models.py:251: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import model
  File "/home/qianbb/github/chinese-ocr/model.py", line 5, in <module>
    from crnn.crnn import crnnOcr
  File "/home/qianbb/github/chinese-ocr/crnn/crnn.py", line 72, in <module>
    model,converter = crnnSource()
  File "/home/qianbb/github/chinese-ocr/crnn/crnn.py", line 64, in crnnSource
    model = crnn.CRNN(32, 1, len(alphabet)+1, 256, 1).cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 100, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 66, in flatten_parameters
    if not any_param.is_cuda or not torch.backends.cudnn.is_acceptable(any_param):
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/__init__.py", line 87, in is_acceptable
    if _libcudnn() is None:
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/__init__.py", line 58, in _libcudnn
    'but linked against {}'.format(compile_version, __cudnn_version))
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 6021 but linked against 5110


The library of cuda is shown as following screenshot.
![2018-02-24 15-40-50](https://user-images.githubusercontent.com/7899459/36627130-4b2d7fae-1979-11e8-9007-e4c459b57505.png)

**Comment by soumith** [comment]
@ztwe I found the issue, I fixed it in https://github.com/pytorch/pytorch/pull/5399 which we will merge shortly.

**Comment by ztwe** [comment]
@soumith Thanks！Does it have been merged?

**Comment by ztwe** [comment]
@soumith 
It seems the fix doesn't work. The log is shown as following

Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import model
  File "/home/qianbb/github/chinese-ocr/model.py", line 5, in <module>
    from crnn.crnn import crnnOcr
  File "/home/qianbb/github/chinese-ocr/crnn/crnn.py", line 72, in <module>
    model,converter = crnnSource()
  File "/home/qianbb/github/chinese-ocr/crnn/crnn.py", line 64, in crnnSource
    model = crnn.CRNN(32, 1, len(alphabet)+1, 256, 1).cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 222, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 100, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py", line 66, in flatten_parameters
    if not any_param.is_cuda or not torch.backends.cudnn.is_acceptable(any_param):
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/__init__.py", line 87, in is_acceptable
    if _libcudnn() is None:
  File "/usr/local/lib/python2.7/dist-packages/torch/backends/cudnn/__init__.py", line 58, in _libcudnn
    'but linked against {}'.format(compile_version, __cudnn_version))
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 6021 but linked against 5110

**Comment by soumith** [comment]
@ztwe that is weird. Can I see the full log of `python setup.py install` in pytorch directory. Can you make sure you have latest commits with `git pull`.

**Comment by ztwe** [comment]
@soumith 

I am sure the code is up-to-date.
First I uninstall the code using the command pip unisntall torch.
Then I remove the old code using the command rm -r pytorch and git clone again.
 
The log of install is 

[pytorch-install-log.txt](https://github.com/pytorch/pytorch/files/1779720/pytorch-install-log.txt)

**Comment by ztwe** [comment]
@soumith 
Sorry to trouble you. Is there any new information on this issue?

**Comment by TomLaMantia** [comment]
@ztwe I spent some time resolving this issue and I don't see too much about it online.

While I had the correct version of Pytorch, I resolved the issue by installing a different build of the same version. The build I installed is `py35_cuda8.0.61_cudnn7.0.5_2`.

For example you can install this using conda: 
`conda install pytorch==0.3.1= py35_cuda8.0.61_cudnn7.0.5_2`

Here are the list of versions and builds: https://anaconda.org/pytorch/pytorch/files?page=1

Try ensuring that your Pytorch build is correct for your specific versions of Cuda and Cudnn.

**Comment by forheroes1994** [comment]
> @ztwe I spent some time resolving this issue and I don't see too much about it online.
> 
> While I had the correct version of Pytorch, I resolved the issue by installing a different build of the same version. The build I installed is `py35_cuda8.0.61_cudnn7.0.5_2`.
> 
> For example you can install this using conda:
> `conda install pytorch==0.3.1=py35_cuda8.0.61_cudnn7.0.5_2`
> 
> Here are the list of versions and builds: https://anaconda.org/pytorch/pytorch/files?page=1
> 
> Try ensuring that your Pytorch build is correct for your specific versions of Cuda and Cudnn.
feedback from this code ： PackagesNotFoundError

**Comment by TomLaMantia** [comment]
@forheroes1994 thank you - I have edited my comment to reflect that I installed from a local zip.

**Comment by forheroes1994** [comment]
@TomLaMantia 
I want to know how you only install the zip？
conda install xxxx.tar.gz2 ?
or tar -jcv xxxxxx.tar.gz2 -c ... then move lib file to anaconda3 file ?
thank you!
