### ISSUE TITLE
Pytorch install via Pip Error

### ISSUE THREAD

**Issue by whiskeyboy9** [pytorch/pytorch#53709]
## ❓ Questions and Help

Using https://pytorch.org/get-started/locally/ for Pip gives me: 

- pip install torch==1.8.0+cu102 torchvision==0.9.0+cu102 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

and results in this error:
ERROR: Could not find a version that satisfies the requirement torch==1.8.0+cu102
ERROR: No matching distribution found for torch==1.8.0+cu102

![image](https://user-images.githubusercontent.com/7745474/110636265-5c6df480-81ac-11eb-99ad-86c28c8ed94c.png)

**I am using anaconda virtual environment and then install pip.**
I have cuda 10.2 installed
I have python x64 bit installed 

`(test) C:\Users\xxx\test>python
Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)] :: Anaconda, Inc. on win32`

```
(test) C:\Users\xxx\test>conda info

     active environment : test
    active env location : C:\Users\xxx\Anaconda3\envs\test
            shell level : 2
       user config file : C:\Users\xxx\.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\xxx\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\xxx\Anaconda3\pkgs
                          C:\Users\xxx\.conda\pkgs
                          C:\Users\xxx\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\xxx\Anaconda3\envs
                          C:\Users\xxx\.conda\envs
                          C:\Users\xxx\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by malfet** [comment]
@whiskeyboy9 what is your pip version?  And would `pip install https://download.pytorch.org/whl/cu102/torch-1.8.0-cp38-cp38-win_amd64.whl` work for you?
@seemethere I've noticed that all CUDA-accelerated wheels in that folder have +cu suffixes except for 10.2.

**Comment by whiskeyboy9** [comment]
@malfet thanks for your request i will try this tomorow

**Comment by seemethere** [comment]
Resolved by #53133

**Comment by wwdok** [comment]
Hi, just now this issue still exist
![image](https://user-images.githubusercontent.com/43233772/110760080-48e48b80-8289-11eb-820b-b0b854d3d519.png)
When will it be ok to install ?

**Comment by whiskeyboy9** [comment]
@malfet 
Hi i can verify that your solution works.

```
conda create --name test python=3.8
conda activate test
conda install pip
pip --version
# > pip 21.0.1 from C:\Users\freller.ralf\Anaconda3\lib\site-packages\pip (python 3.8)
```
currently behind a proxy so i have to use --trusted-host but you can leave it out
`pip install --trusted-host download.pytorch.org https://download.pytorch.org/whl/cu102/torch-1.8.0-cp38-cp38-win_amd64.whl`
Test in Python:
```
# test
python -c "import torch; print(torch.__version__)"
# 1.8.0
python -c "import torch;x = torch.rand(5, 3);print(x)"
# tensor(...)
python -c "import torch;print(torch.cuda.is_available())"
# True
```
Test with Jupyter. Hotfix for jupyter requires pywin32==225 :(
```
# test with jupyter notebook to verify
pip install notebook
pip install pywin32==225
# cd to a working directory
# jupyter notebook 
```

**Comment by mszhanyi** [comment]
@malfet , the link format isn't correct, It should be
cu102/torchvision-0.9.0<strong>+cu102</strong>-cp36-cp36m-linux_x86_64.whl
<strong>+cu102</strong> missing

![image](https://user-images.githubusercontent.com/16190118/110906025-59a70700-8346-11eb-94b4-9012e393c6aa.png)

**Comment by mszhanyi** [comment]
I think seemethere's PR should fix it. But the page isn't updated. maybe it needs a little more time

**Comment by walterddr** [comment]
hmm. I dont think this is fixed. seems like cu102 is still having no suffix. @seemethere @malfet was the intention to reupload/rename the cu102 whl files or to alter the command on quickstart?

**Comment by seemethere** [comment]
Suffixes will not be updated retroactively. The CUDA 10.2 binaries will have a suffix starting with the 1.8.1 release

**Comment by mszhanyi** [comment]
Is there a way to apply a hotfix?

**Comment by whiskeyboy9** [comment]
> Is there a way to apply a hotfix?

@mszhanyi if you need to install pytorch try the above mentioned hotfix ;) 
`pip install --trusted-host download.pytorch.org https://download.pytorch.org/whl/cu102/torch-1.8.0-cp38-cp38-win_amd64.whl`

**Comment by nbcsm** [comment]
verified this is fixed in 1.8.1
`pip install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`

![image](https://user-images.githubusercontent.com/32868157/112998017-367eb300-91a0-11eb-9ce4-b1aa031e6bcc.png)

close the issue.
