### ISSUE TITLE
scatter_add_ doesn't support scalar source

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5405]
I was looking to use `scatter_add_` to do `bincount`.
```python
import torch
a = torch.LongTensor([2, 0, 3, 3])
r = torch.LongTensor(5)

# works
r.zero_().scatter_(0, a, 1)
# 1
# 0
# 1
# 1
# 0
# [torch.LongTensor of size 5]

# scalar source doesn't work
r.zero_().scatter_add_(0, a, 1)
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#TypeError: scatter_add_ received an invalid combination of arguments - got (int, torch.LongTensor, int), #but expected (int dim, torch.LongTensor index, torch.LongTensor src)

# no broadcasting? but no checking for memory bounds either?
r.zero_().scatter_add_(0, a, torch.LongTensor([1]))
#1.4033e+14
# 0.0000e+00
# 1.0000e+00
# 5.4931e+18
# 0.0000e+00
# [torch.LongTensor of size 5]

# works ok
r.zero_().scatter_add_(0, a, torch.LongTensor([1]).expand_as(a))
# 1
# 0
# 1
# 2
# 0
# [torch.LongTensor of size 5]

```
at `0.4.0a0+1fdb392`

**Comment by vadimkantorov** [comment]
`index_add_` also doesn't currently support scalar source, also doesn't broadcast (but at least produces an error).

**Comment by zou3519** [comment]
Thanks for the report, I'm taking a look

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/5659

**Comment by zou3519** [comment]
Sorry I don't think #5659 Is a complete fix for this: it does better dimension checking than before (thanks @Officium!) but we still don't support scalar source in scatter_add_

**Comment by vadimkantorov** [comment]
> but we still don't support scalar source in scatter_add_

@zou3519 let's reopen this issue?

**Comment by vadimkantorov** [comment]
This is still true. Strangely, `scatter_` with `reduce=True` support scalar src. cc @ezyang

**Comment by vadimkantorov** [comment]
Same problem for `scatter_reduce_` :(

**Comment by mikaylagawarecki** [comment]
Assigning to myself to send a PR that fixes this
