### ISSUE TITLE
index_select doesnt return errors when out of bounds (GPU only)

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#571]
It would be great if it does. Lost lot of time because of this :(

**Comment by glample** [comment]
Actually this is not the first time I observed this bug. I believe I had the same issue on Embedding module once. Problem is always when it's on Cuda, it returns some arbitrary values when out of bounds.

**Comment by soumith** [comment]
thanks for the bug report. I looked into this, and I think we can add some device side assertions to trigger this. Will fix.

**Comment by predict-r** [comment]
Not sure if related, but my model works fine on the cpu but when switching the model to cuda there is an index_select error:

`Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "<stdin>", line 14, in forward
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 210, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/sparse.py", line 92, in forward
    )(input, self.weight)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/_functions/thnn/sparse.py", line 62, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.LongTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)
`

Other toy examples work fine on cuda here. The the code that worked fine on the cpu is attached, and breaks after model.cuda() to produce the error above.
[embedding.txt](https://github.com/pytorch/pytorch/files/737820/embedding.txt)

**Comment by apaszke** [comment]
@predict-r That's not related and it's expected. Sparse functions are CPU only for the moment, we didn't have time to implement their GPU counterparts yet.

**Comment by apaszke** [comment]
Fixed in #650.

**Comment by achernodub** [comment]
@apaszke Got the same error today while tried to run your standard NLP POS tagger example on GPU. 

http://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html#sphx-glr-beginner-nlp-sequence-models-tutorial-py

`TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, !torch.LongTensor!), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)`

Are you sure that it was fixed? 

Thank you.

**Comment by albanD** [comment]
@achernodub you error is unrelated, as you can see in the error message, the problem is that some of your elements are `torch.LongTensor` and should be `torch.cuda.LongTensor`. I guess you forgot to send some tensors to the GPU.

**Comment by achernodub** [comment]
@albanD yes, I've re-checked it - it was my fault, thank you! @apaszke my apologies!

**Comment by XuefeiW** [comment]
Hi, I am using Pytorch 0.4, python 2.7, cuda 8.0 version. I still have this index out of boundary without any error message bug on both GPU and CPU.

Code example:
b = torch.Tensor(3,4,5)
b[1:2,10:100]

**Comment by fmassa** [comment]
@XuefeiW this is different and follows the behavior of numpy and python lists
```python
In [3]: np.random.rand(5)[10:100]
Out[3]: array([], dtype=float64)
```

**Comment by XuefeiW** [comment]
numpy will return an empty array, so it's relatively easy to tell something is wrong. Also in numpy you cannot assign any value to this returned array.

But in PyTorch, because it returns a tensor with one value, if the original intention is fetching one value then it's very difficult to find this error when debugging. Also you can assign tensor to this value and use it later:
b = torch.Tensor(3,4,5)
print b[1:2,4:5]
b[1:2,4:5] = 3
print b[1:2,4:5]

**Comment by fmassa** [comment]
oh, this is fixed in master

```python
In [5]: a = torch.rand(5, 5)

In [6]: a[:2, 10:100]
Out[6]: tensor([])

In [7]: torch.__version__
Out[7]: '0.5.0a0+0515664'
```

**Comment by JamieCT** [comment]
I experience the same issue as @XuefeiW , however I also occasionally (and inconsistently) experience an error message @fmassa , I assume neither of these are the intended behavior?
so running:

a = torch.Tensor(2,3)
print(a[1:2,3:4])

returns either 
tensor([ 0.])
or 
if value != math.ceil(value.item()):
RuntimeError: Overflow when unpacking long

I am using python 3.6.4, IPython 6.2.1, pytorch 0.4.0

Thanks

**Comment by fmassa** [comment]
@JamieCT the `Overflow when unpacking long` was fixed in master in https://github.com/pytorch/pytorch/pull/6876

**Comment by Atcold** [comment]
Still broken on 1.5.0, py3.8_cuda10.2.89_cudnn7.6.5_0.

```python
In [20]: q = torch.rand(2, 128).cuda()                           

In [21]: q[[2]].size()          
Out[21]: torch.Size([1, 128])
```

**Comment by albanD** [comment]
The API is asynchronous, so only the next GPU op will be able to see the error after it happened.
If you run another GPU op after (waiting for some time) or running with `CUDA_LAUNCH_BLOCKING=1`, do you see the error?
