### ISSUE TITLE
[docs] symeig: unclear format of eigenvectors

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#59718]
https://pytorch.org/docs/1.8.1/generated/torch.symeig.html?highlight=symeig#torch.symeig:

It's unclear if eigenvectors are stacked as columns or as rows
```
eigenvectors (Tensor): Shape (*, m, m)(∗,m,m) . If eigenvectors=False, it’s an empty tensor. Otherwise, this tensor contains the orthonormal eigenvectors of the input.
```

Also the docs use two separate notations: `V`/`e` and `eigenvectors`/`eigenvalues`

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
This is corrected in master. This function has been superseded by `torch.linalg.eigh` which handles properly the return. The docs were also updated.

https://pytorch.org/docs/master/generated/torch.linalg.eigh.html?highlight=eigh#torch.linalg.eigh

**Comment by vadimkantorov** [comment]
There is still mismatch in notation. The above uses \Lambda and Q, and the return arguments use \Lambda and V

**Comment by vadimkantorov** [comment]
And it still does not specify explicitly if eigenvectors are stored as columns or as rows. One can deduce it from the formula, but it'd be better and more user-friendly to say it directly

**Comment by Lezcano** [comment]
It can indeed be deduced from the formula, and it is standard in maths to represent these vectors as columns (this is just a change of basis after all). As such, I think it is not needed to repeat ourselves in the documentation.

And thank you for reporting the mismatch. I will correct that just now.

**Comment by vadimkantorov** [comment]
Well, the formula is also not batched, so there is no direct correspondence anyway - maybe you'd want to mention that explicitly as well

**Comment by vadimkantorov** [comment]
Maybe having some relevant code example there would be helpful, there you may demonstrate that eigenvectors are stored as columns

**Comment by vadimkantorov** [comment]
E.g. make a laplacian of image based on w_ij = exp(||RGB_i - RGB_j||^2/sigma^2), then take symmetric laplacian and plot its top eigenvector - a very useful example

**Comment by Lezcano** [comment]
In the end I added the extra information (https://github.com/pytorch/pytorch/pull/59784).

About the formula being non-batched, we went that way because it's just easier to write in mathematical notation. We note however after the mathematical explanation that:
> Supports input of float, double, cfloat and cdouble dtypes. Also supports batches of matrices, and if A is a batch of matrices then the output has the same batch dimensions.
