### ISSUE TITLE
RuntimeError: Jacobian mismatch for output 0 with respect to input 0

### ISSUE THREAD

**Issue by beew** [pytorch/pytorch#62674]
pytorch 1.8.1
System is Ubuntu 20.04
python 3.8.10
CUDA 11.0
cudnn 8
GPU Nvidia GTX1070

I built pytorch from source with
```
export BUILD_ONNX_PYTHON=1 USE_CUDA=1 USE_CUDNN=1 USE_MKL=1 USE_MKLDNN=1 USE_OPENCV=1 USE_FFMPEG=1 GPU_ARCH=sm_61

```
running tests with  python test/run_test.py in pytorch's build directory produces these errors

```
ERROR: test_lu_square_batch_no_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 874, in wrapper
    method(*args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 295, in instantiated_test
    raise rte
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 290, in instantiated_test
    result = test_fn(self, *args)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 5176, in do_test
    check(name)
  File "test_autograd.py", line 5082, in check
    run_grad_and_gradgrad_checks(self, name, test_name, fn,
  File "test_autograd.py", line 4947, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION,
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1911, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 468, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 449, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 367, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.1295,  0.2564],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3685, -0.8116],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.3453]],
       device='cuda:0')
analytical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.1295,  0.2564],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.3685, -0.8116],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.3453]],
       device='cuda:0')


======================================================================
ERROR: test_lu_square_batch_with_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 874, in wrapper
    method(*args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 295, in instantiated_test
    raise rte
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 290, in instantiated_test
    result = test_fn(self, *args)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 5176, in do_test
    check(name)
  File "test_autograd.py", line 5082, in check
    run_grad_and_gradgrad_checks(self, name, test_name, fn,
  File "test_autograd.py", line 4959, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradgradcheck(apply_method, input_variables,
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1925, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 674, in gradgradcheck
    return gradcheck(
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 468, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 449, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 367, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 3.6142e+00,  7.0091e+00,  5.3443e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 7.0091e+00,  1.1945e+01,  9.4077e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 5.3443e+00,  9.4077e+00,  7.4169e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.0573e-01,
         -9.1116e-01, -1.7285e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.1116e-01,
          2.7100e+00,  4.9196e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.7285e-01,
          4.9196e-01, -4.1633e-11]], device='cuda:0')
analytical:tensor([[ 3.6142e+00,  7.0091e+00,  5.3443e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 7.0091e+00,  1.1945e+01,  9.4077e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 5.3443e+00,  9.4077e+00,  7.4169e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.0573e-01,
         -9.1116e-01, -1.7285e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -9.1116e-01,
          2.7100e+00,  4.9196e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.7285e-01,
          4.9196e-01,  3.8340e-17]], device='cuda:0')


======================================================================
ERROR: test_lu_square_many_batches_no_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 874, in wrapper
    method(*args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 295, in instantiated_test
    raise rte
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 290, in instantiated_test
    result = test_fn(self, *args)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 5176, in do_test
    check(name)
  File "test_autograd.py", line 5082, in check
    run_grad_and_gradgrad_checks(self, name, test_name, fn,
  File "test_autograd.py", line 4947, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION,
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1911, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 468, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 449, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 367, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4702, -0.3404],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4336, -0.2948],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.3413]],
       device='cuda:0')
analytical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4702, -0.3404],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4336, -0.2948],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.3413]],
       device='cuda:0')


======================================================================
ERROR: test_lu_square_many_batches_with_info_cuda (__main__.TestAutogradDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 874, in wrapper
    method(*args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 295, in instantiated_test
    raise rte
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 290, in instantiated_test
    result = test_fn(self, *args)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 581, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_autograd.py", line 5176, in do_test
    check(name)
  File "test_autograd.py", line 5082, in check
    run_grad_and_gradgrad_checks(self, name, test_name, fn,
  File "test_autograd.py", line 4947, in run_grad_and_gradgrad_checks
    test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION,
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1911, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 468, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 449, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "/home/bernard/opt/python38/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 367, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4702, -0.3404],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4336, -0.2948],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.3413]],
       device='cuda:0')
analytical:tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4702, -0.3404],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, -0.4336, -0.2948],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.3413]],
       device='cuda:0')


----------------------------------------------------------------------
Ran 2715 tests in 1313.439s

FAILED (errors=4, skipped=23, expected failures=1)
Traceback (most recent call last):
  File "test/run_test.py", line 926, in <module>
    main()
  File "test/run_test.py", line 905, in main
    raise RuntimeError(err_message)
RuntimeError: test_autograd failed!
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jianyuh @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233

**Comment by Lezcano** [comment]
Do you get these errors when using PyTorch compiled from master (or using the nightly)?

**Comment by nikitaved** [comment]
Looks like a dtype issues? It seems like `float` tensors are being tested, hence the issue.

**Comment by beew** [comment]
@Lezcano 

It is v1.8.1, got from git and checkout v1.8.1

**Comment by Lezcano** [comment]
The fixes to previous versions are rolled out in newer versions. I think it is likely that this issue is fixed in `master`. If that's the case, you can solve it by updating your PyTorch copy to master.

**Comment by mruberry** [comment]
Closing this since it is likely fixed in the newest PyTorch release. @beew, if you're still seeing this issue with the latest version of PyTorch would you please file a new issue?

**Comment by beew** [comment]
@mruberry 

> Closing this since it is likely fixed in the newest PyTorch release. @beew, if you're still seeing this issue with the latest version of PyTorch would you please file a new issue?

Which latest release is that? I looked at the release tags and it still shows 1.8.2rc1

**Comment by mruberry** [comment]
> @mruberry
> 
> > Closing this since it is likely fixed in the newest PyTorch release. @beew, if you're still seeing this issue with the latest version of PyTorch would you please file a new issue?
> 
> Which latest release is that? I looked at the release tags and it still shows 1.8.2rc1

The most recent release is 1.9, which is on Colab and available at https://pytorch.org/get-started/locally/. Or if you build from source, of course.

**Comment by mruberry** [comment]
> But 1.9 has been out since June and before I filed the bug. Also, I think 1.9 is backward incompatible with 1.8.x, right? If so it may break things that are currently working with 1.8.1

There may be some deprecations which occurred in 1.9 but generally it should be compatible with 1.8.

> Will this problem be fixed in 1.8.2? Maybe I should wait for that.

Unfortunately we are not planning a 1.8.2 release.


You are correct, however, that this issue may be fixed only in source and not available in 1.9. In that case this fix would first appear in 1.9.1 (no guarantee there will be a 1.9.1 release) or the 1.10 release.

**Comment by beew** [comment]
So you have a 1.8.2-rc1 release but no 1.8.2? That is very strange.

**Comment by mruberry** [comment]
> So you have a 1.8.2-rc1 release but no 1.8.2? That is very strange.

Possibly just an internal artifact, I don't think we've ever publicly announced a 1.8.2 release.

**Comment by beew** [comment]
> Possibly just an internal artifact, I don't think we've ever publicly announced a 1.8.2 release.

The link is here https://github.com/pytorch/pytorch/tags

So if I want to checkout the 1.9 branch where this is fixed, what should I do?

git checkout v.1.9.0 would give me the version released in June, correct?

**Comment by mruberry** [comment]
> > Possibly just an internal artifact, I don't think we've ever publicly announced a 1.8.2 release.
> 
> The link is here https://github.com/pytorch/pytorch/tags

Sure; I don't know if that's public-facing as much as developer-facing is my point. 

> 
> So if I want to checkout the 1.9 branch where this is fixed, what should I do?
> 
> git checkout v.1.9.0 would give me the version released in June, correct?

I think so, but it'd be more helpful if you checked out the latest commit to look at whether this issue is fixed or not.

**Comment by beew** [comment]
@mruberry 

Hi, it looks like v1.8.2 has just been released.

**Comment by mruberry** [comment]
> @mruberry
> 
> Hi, it looks like v1.8.2 has just been released.

Neat! I wonder what it contains. Maybe we are doing a series of 1.8.X releases.
