### ISSUE TITLE
[PyTorch] Error when printing tensors containing large values

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#6339]
On master:
```python
>>> x.max()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssnl/sftp/pytorch/torch/tensor.py", line 53, in __repr__
    return torch._tensor_str._str(self)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 302, in _str
    strt = _vector_str(self.unsqueeze(0))
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 270, in _vector_str
    fmt, scale, sz = _number_format(self)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 95, in _number_format
    if value != math.ceil(value.item()):
RuntimeError: Overflow when unpacking long
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssnl/sftp/pytorch/torch/tensor.py", line 53, in __repr__
    return torch._tensor_str._str(self)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 306, in _str
    strt = _matrix_str(self)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 215, in _matrix_str
    min_sz=5 if not print_full_mat else 0)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 95, in _number_format
    if value != math.ceil(value.item()):
RuntimeError: Overflow when unpacking long
>>> x.max().item()
1.8446744073709552e+19
>>> x.dtype
torch.float32
```

This is a regression as printing this tensor works in 0.3.1. Assigning to @li-roy as you are taking care of the printing issue. Reported in #6136

**Comment by SsnL** [comment]
@NoahDragon Because `torch.empty` gives uninitialized memory, so you may or may not get a large value from it.

**Comment by AveryLiu** [comment]
I had the same issue on MacOS high Sierra with the 0.4.0 torch binary install.
```python
import torch
x = torch.empty(5,3) # This line is ok 
print(x) # Raise a runtime error when printing
```
The traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/_tensor_str.py", line 218, in _str
    fmt, scale, sz = _number_format(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/_tensor_str.py", line 96, in _number_format
    if value != math.ceil(value.item()):
RuntimeError: Overflow when unpacking long
```
Unlike described by @NoahDragon, the problem persists across different runs.

**Comment by li-roy** [comment]
I think this was fixed as a side effect of #6876. Can't repro on master.

**Comment by SsnL** [comment]
Fixed in #6876

**Comment by Chasearmer** [comment]
I have received this same error `RuntimeError: Overflow when unpacking long` 
as well when using `torch.empty(5, 3)`, as seen in the Blitz 60 minute tutorial. Has this not been fixed or is this to be expected?

**Comment by li-roy** [comment]
Are you running the latest master or one of the released binaries?

**Comment by Chasearmer** [comment]
@li-roy I ran `conda install pytorch-cpu torchvision-cpu -c pytorch`

**Comment by li-roy** [comment]
Then I think it's same issue, it's fixed in master but not in the release yet. Thanks for the report, though!

**Comment by cslxiao** [comment]
Creating Tensor without initialization sometimes lead to this error. So you can avoid the error by always initialization when creating.

**Comment by johntiger1** [comment]
Has this been fixed in Pytorch 0.4?

**Comment by soumith** [comment]
this is fixed in 0.4.1 which just released.

**Comment by MayorPain** [comment]
On windows, following the install instructions, this error still appears
