### ISSUE TITLE
RuntimeError: derivative for to_sparse is not implemented

### ISSUE THREAD

**Issue by peddivarunkumar99** [pytorch/pytorch#66928]
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main(config)
  File "main.py", line 73, in main
    solver.train()
  File "/home/snap_user/Image_Segmentation/solver1.py", line 162, in train
    loss.backward()
  File "/home/snap_user/anaconda3/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/snap_user/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: derivative for to_sparse is not implemented

The autograd library does not have derivative for to_sparse() please help me with the issue.

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk @ezyang @albanD @zou3519 @gqchen @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
This was fixed last year following this issue: https://github.com/pytorch/pytorch/issues/46720
You can upgrade your version of pytorch to get the fix.

**Comment by peddivarunkumar99** [comment]
I am on the latest version of PyTorch and this still appears.
