### ISSUE TITLE
'NAN' in model features

### ISSUE THREAD

**Issue by ZakharovDenis** [pytorch/pytorch#69449]
## 🐛 Bug
When I try to get features from cuted (amp or fp16) mobilenetv2 model (from torchvision) it returns tensor full of 'nan's.
I decided to open bug here, not in torchvision repo, because:

1. I have a server with 2 gpus. One is GTX 1650, other is Quadro P2000 and i tried 2 enviroments (python 3.9.9, win10)
* torch             1.10.0+cu113                   torchvision          0.11.1+cu113   - bug on gtx, NO bug on quadro
* torch             1.10.0+cu102                   torchvision       0.11.1+cu102   - NO bug on both

2. On my own pc a have a GTX 1660 super and i tried 3 enviroments  (python 3.8.5, win10)
* torch             1.10.0+cu102                   torchvision       0.11.1+cu102   - no bug
* torch             1.10.0+cu113                   torchvision       0.11.1+cu113   - bug
* torch             1.8.0+cu111                     torchvision       0.9.0+cu111     - bug

So it seems like problem with cuda 11

## To Reproduce
Here is a code to reproduce
```python
import torch
import numpy as np
from torch.cuda.amp.autocast_mode import autocast
from torchvision.models.mobilenetv2 import MobileNetV2, mobilenet_v2

GPU_ID = 0

model = MobileNetV2().cuda(GPU_ID)
# model = mobilenet_v2(pretrained=True).cuda(GPU_ID)

## Does not matter is model pretrained or not. Half precision returns nan.


img = np.random.rand(1, 3, 224, 224)

### Full FP32 precision
img32 = torch.from_numpy(img).float().cuda(GPU_ID)
test32 = model(img32)
featured_test32 = model.features[:7](img32)
print(
    f"FP32 full model: {torch.sum(test32).item()} \t model features: {torch.sum(featured_test32).item()}"
)


### Auto Mixed precision
with autocast():
    testmp = model(img32)
    featured_testmp = model.features[:7](img32)
    print(
        f"AMP full model: {torch.sum(testmp).item()} \t model features: {torch.sum(featured_testmp).item()}"
    )


### Half FP16 precision
img16 = torch.from_numpy(img).half().cuda(GPU_ID)
model.half()
test16 = model(img16)
featured_test16 = model.features[:7](img16)
print(
    f"FP16 full model: {torch.sum(test16).item()} \t model features: {torch.sum(featured_test16).item()}"
)
```

Outputs are
* For cuda 11
```
FP32 full model: -0.2556326389312744     model features: 0.0004119873046875        
AMP full model: 0.0      model features: nan
FP16 full model: 0.0     model features: nan
```
* for cuda 10
```
FP32 full model: -4.238442420959473      model features: 9.1552734375e-05 
AMP full model: -3.986173629760742       model features: 0.09039306640625
FP16 full model: -4.0234375      model features: 0.1673583984375
```

## Expected behavior

No 'nan's in output rensor

cc @mcarilli @ptrblck

**Comment by ptrblck** [comment]
Based on the bug description, it looks like the same cuDNN issue encountered [here](https://github.com/pytorch/pytorch/issues/58123#issuecomment-864336857), which was fixed in cuDNN8.2.2. You could build PyTorch from source following [these instructions](https://github.com/pytorch/pytorch#from-source) with cuDNN>=8.2.2 or wait for a nightly build once we update cuDNN to the current release.

**Comment by ZakharovDenis** [comment]
@ptrblck, you are right. It seems like these two bugs are identical. My apologies for creating duplicate. Thank you for support!

I think I'll close this bug for now. May be reopen later if bug will reproduce again on new build

**Comment by monsieurpooh** [comment]
The bug still exists: 
https://github.com/pytorch/pytorch/issues/58123#issuecomment-839579861
https://github.com/nerdyrodent/VQGAN-CLIP/issues/151

**Comment by uesrs** [comment]
> cuDNN8
我使用的cuda11.7,
我更换为cudnn8.2.2后依然没有解决
