### ISSUE TITLE
undefined symbol curandCreateGenerator for torch extensions

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#69666]
## 🐛 Bug

With **nightly pip package** 

```
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html -U
```

I get:

```
 ImportError: ~/.cache/torch_extensions/py38_cu111/cpu_adam/cpu_adam.so: undefined symbol: curandCreateGenerator
```

when trying to use deepspeed's cuda extension.

**all works fine if I use the same version of the conda package**:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch-nightly
```

The extension builds just fine.

You can read the full detailed report with traces and ninja output here: https://github.com/microsoft/DeepSpeed/issues/1625

## To Reproduce

```
git clone https://github.com/huggingface/transformers/
cd transformers
pip install deepspeed
pip install -e .[dev]
RUN_SLOW=1 pytest tests/deepspeed/test_deepspeed.py -k test_can_resume_training_normal_0_zero2
```

the symbol is undefined with either build version, but I think it should get resolved at loading time with linked cuda libraries.
```
$ nm ~/.cache/torch_extensions/py38_cu113/cpu_adam/cpu_adam.so | grep curandCreateGenerator
                 U curandCreateGenerator
```
so this tells me some cuda library is missing. 

`ldd` output is the same with either package.

```
$ ldd ~/.cache/torch_extensions/py38_cu113/cpu_adam/cpu_adam.so
        linux-vdso.so.1 (0x00007ffe328dd000)
        libgtk3-nocsd.so.0 => /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 (0x00007f4cb1daf000)
        libc10.so => not found
        libc10_cuda.so => not found
        libtorch_cpu.so => not found
        libtorch_python.so => not found
        libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007f4cb1b0d000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4cb1929000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4cb17da000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4cb17bf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4cb15cd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4cb15c7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4cb15a4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4cb211e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4cb1597000)
```

## Expected behavior

pip and conda packages should produce the same env.

## Environment

```
Collecting environment information...
PyTorch version: 1.11.0.dev20211208
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070 Ti
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.11.0.dev20211208+cu113
[pip3] torchaudio==0.11.0.dev20211208+cu113
[pip3] torchvision==0.12.0.dev20211208+cu113
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] numpy-base                1.21.2           py38h79a1101_0
[conda] pytorch                   1.11.0.dev20211208 py3.8_cuda11.3_cudnn8.2.0_0    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torch                     1.11.0.dev20211208+cu113          pypi_0    pypi
[conda] torchaudio                0.11.0.dev20211208+cu113          pypi_0    pypi
[conda] torchvision               0.12.0.dev20211208+cu113          pypi_0    pypi
```

Thank you!

cc @ezyang @seemethere @malfet @zou3519 @brianjo @mruberry @ngimel

**Comment by malfet** [comment]
Hmm, this behavior is sort of expected in the pip world, as all cuda libraries are linked statically with `-fvisibility=hidden` in order not to pollute global address space with symbols which are not part of Pytorch API (which prevents collisions when say protobuf package is installed with version  different than one used internally by Pytorch)

I.e. if DeepSpeed depends on cuRand it should link against it explicitly rather than depend on PyTorch to export that symbol

**Comment by seemethere** [comment]
> Hmm, this behavior is sort of expected in the pip world, as all cuda libraries are linked statically with `-fvisibility=hidden` in order not to pollute global address space with symbols which are not part of Pytorch API (which prevents collisions when say protobuf package is installed with version different than one used internally by Pytorch)
> 
> I.e. if DeepSpeed depends on cuRand it should link against it explicitly rather than depend on PyTorch to export that symbol

Going to mark this as `has workaround` since linking explicitly against `cuRand` should resolve this issue as @malfet has pointed out

**Comment by stas00** [comment]
Awesome, thank you so much for this advise. I will take this back to the deepspeed Issue then.

**Comment by malfet** [comment]
If DeepSpeed is compiled using `torch.utils.cpp_extension` this should already be the case (i.e. it should be link with cuRand if any of the curand symbols are used). If it is indeed the case, then bug is on PyTorch side, but if custom build system is used, then build rules must be updated with explicit dependency.

Why it works in conda environment - cuRand is dynamic dependency part of cuda-toolkit package and as pytorch depends on it, that symbols is available in global namespace when extension is loaded.

**Comment by stas00** [comment]
have I closed this prematurely then? DS is compiled with `torch.utils.cpp_extension`

**Comment by stas00** [comment]
OK, so I found the breaking date:

Results:
```
V Oct-22 - 1826MB
X Oct-23 - 1717MB
```

Note how on Oct-23 the size of pytorch shrunk by 109MB, so this is almost certain some change in pytorch. 

I was testing with direct install, e.g.:
```
pip install https://download.pytorch.org/whl/nightly/cu113/torch-1.11.0.dev20211025%2Bcu113-cp38-cp38-linux_x86_64.whl;
```

**Comment by malfet** [comment]
@stas00 most likely it is. The only place in PyTorch codebase when `curandCreateGenerator` is used is
https://github.com/pytorch/pytorch/blob/9aa1b3e396c1fe9dadecaee04c9321f659d863ac/caffe2/core/context_gpu.h#L230
which obviously would not be compiled into binary build without caffe2 support.

**Comment by stas00** [comment]
Glad we found the culprit! Thank you for confirming it, @malfet  

OK, so cuda extensions just happened to work while `caffe2` was included.

So what needs to be done now by `torch.utils.cpp_extension` to adapt for this change? Shouldn't `torch.utils.cpp_extension` do the right linking to overcome this change?

**Comment by ngimel** [comment]
That, or deepSpeed could pass extra linking argument to link with curand

**Comment by stas00** [comment]
but won't now many CUDA extensions be impacted by this change?

This is currently a backward compatibility breaking, even though it was never by design. i.e. someone switching from pt-1.10 to pt-1.11 will have their code broken w/o a deprecation cycle. Not sure how one could deprecate such situation though.

I tried to check if Megatron got impacted since it has a bunch of cuda extensions, but it won't even build - pt-nightly has more issues. missing `THC/THCDeviceUtils.cuh` - will file another issue.

**Comment by stas00** [comment]
@jeffra, I think I will step aside since Deepspeed is your project and perhaps it'd be the easiest for you guys to figure out the best way to proceed and me not be the middle man.  

I'd be happy to test when you have something to test.

Thank you!

**Comment by malfet** [comment]
Adding needs design flag, as I'm not sure, whether `torch.utils.cpp_extension` should implicitly link every extension with the same set of libraries as original code or not. I remember behavior was changed around 1.8 timeframe, as end users of  libtorch++ api complained that cuda runtime and cudnn are mandatory dependencies to use the API (which they are not) I solved it by moving cuda library dependencies to be private of `torch_cuda` library. Perhaps the right approach would be to add extra optional argument to cpp_extensions or may be make it a soft failure

**Comment by stas00** [comment]
So @jeffra and I were trying to fix this on the "client" side and here is the status of things:

Adding 

```
def extra_ldflags(self):
    return ['-lcurand']
```
Solves the problem for JIT (ninja build)

However if it's a prebuilding and not JIT, `extra_ldflags` is getting ignored.

Here is the g++ command line:

```
    g++ -pthread -shared -B /home/stas/anaconda3/envs/py38-pt111/compiler_compat -L/home/stas/anaconda3/envs/py38-pt111/lib -Wl,-rpath=/home/stas/anaconda3/envs/py38-pt111/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/csrc/adam/cpu_adam.o build/temp.linux-x86_64-3.8/csrc/common/custom_cuda_kernel.o -L/home/stas/anaconda3/envs/py38-pt111/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-11.5/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.8/deepspeed/ops/adam/cpu_adam_op.cpython-38-x86_64-linux-gnu.so
```

If I manually added `-lcurand` to it, then all gets resolved. but this has to happen automatically of course.

So we need help on your side.

Jeff was able to hack it in by doing:

this for-loop seems to go over all the extensions h

ttps://github.com/pytorch/pytorch/blob/8dfdc3df82ee34a83c1a0a9c59de8db195591a6b/torch/utils/cpp_extension.py#L412-L432

at the end of the loop i force added `extension.extra_link_args.append('-lcurand')`

There is also `extra_link_args` that is not documented and I don't think it works anyway, as I tried it.

Thank you!

**Comment by stas00** [comment]
If you'd like to reproduce the issue:

```
git clone https://github.com/microsoft/DeepSpeed
cd DeepSpeed
rm -rf build; DS_BUILD_CPU_ADAM=1 pip install -e . --global-option="build_ext" --global-option="-j8" --no-cache -v --disable-pip-version-check --no-clean
```

and then:

```
nm build/lib.linux-x86_64-3.8/deepspeed/ops/adam/cpu_adam_op.cpython-38-x86_64-linux-gnu.so | grep curandCreateGenerator
                 U curandCreateGenerator 
```

but it needs to be:
```
                 U curandCreateGenerator@@libcurand.so.10
```
which happens if I manually re-run the linker command with `-lcurand` added.

**Comment by jeffra** [comment]
Thanks @stas00, one more piece of context I can add here. DeepSpeed's builder is just a lightweight wrapper around `torch.utils.cpp_extension`

I think the core of our question can be boiled down to, how can we add extra linker args to a `CppExtension`? This seems to work in older versions of torch.

```python
# option-1: pre-compile extension
from torch.utils.cpp_extension import CppExtension
CppExtension(name=name
             sources=sources
             include_dirs=include_dirs,
             extra_compile_args={'cxx': cxx_args},
             extra_link_args=extra_ldflags)
```

```python
# option-2: JIT compiled extension
from torch.utils.cpp_extension import load
load(name=name,
     sources=sources,
     extra_include_paths=extra_include_paths,
     extra_cflags=cxx_args,
     extra_cuda_cflags=nvcc_args,
     extra_ldflags=extra_ldflags,
     verbose=verbose)
```

**Comment by jeffra** [comment]
Here's maybe another way to rephrase our issue outside of the DeepSpeed environment all together. If someone wants to compile a `CppExtension` from `torch.utils.cpp_extension` how can they link a library like `curand`? We are unable to figure out what needs to be passed into `CppExtension` to do this since it appears `extra_link_args` is not used at build time.

**Comment by stas00** [comment]
it'd be great to have this resolved before 1.11 since we have a CI running on pt-nightly and all deepspeed tests currently fail because of this issue, so we can't detect potential other issues because of that. Thanks.

**Comment by ngimel** [comment]
As a workaround, can you run tests with conda install? We are discussing dynamically linking cuda runtime libraries even for pip installs, which would incidentally fix this issue (but would still be fragile, as we could stop linking libtorch with curand, and things would break again), and longer term ways to specify libraries to link with to `cpp_extension`.

**Comment by stas00** [comment]
Actually, since we have a working workaround for JIT-mode - I will ask @jeffra to apply that fix and use that for the CI in the meanwhile.

**Comment by stas00** [comment]
I've just re-tested building deepspeed w/ the latest nightly:
1. manual pre-build
2. JIT build

both work just fine. So I assume that somehow this Issue got resolved in pytorch, I just don't know where.

**Comment by dvolgyes** [comment]
What is the status? As I see this is the last open issue in the 1.11.0 milestone, 
it would be nice to resolve it.
https://github.com/pytorch/pytorch/milestone/26

**Comment by stas00** [comment]
Have you tried with the 1.11-rc? It should work again, try: 

```
pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cu115/torch_test.html -U
# may have to first
pip uninstall -y torch torchvision torchaudio
```

**Comment by dvolgyes** [comment]
I haven't, since I never had this issue. But this issue seems to be on the milestone list, actually the last one, and it is not clear if this could be closed, or there is remaining work, does it block v.1.11 release, or 1.11 will be just released with this open? And I haven't seen any update in 2.5 weeks. So it was just a friendly question / reminder.

**Comment by stas00** [comment]
I can't answer for the general case. I can only tell what I shared here: https://github.com/pytorch/pytorch/issues/69666#issuecomment-1040706609 - i.e. my original bug report has been addressed.

And as I stated I don't know how and where it has been resolved, it just started working when I tried again 3 weeks ago.

**Comment by maxmaier59** [comment]
> Have you tried with the 1.11-rc? It should work again, try:
> 
> ```
> pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cu115/torch_test.html -U
> # may have to first
> pip uninstall -y torch torchvision torchaudio
> ```

I have verified the proposed solution but I am still getting the same error message:

Traceback (most recent call last):
  File "/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 97, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

**Comment by stas00** [comment]
Have you tried rebuilding deepspeed?

in particular pre-building it like so:

```
git clone https://github.com/microsoft/DeepSpeed
cd DeepSpeed
DS_BUILD_CPU_ADAM=1 DS_BUILD_AIO=1  DS_BUILD_UTILS=1 pip install -e . --global-option="build_ext" --global-option="-j8" --no-cache -v --disable-pip-version-check
```

instead of using JIT when it builds on the first time it's used.

**Comment by maxmaier59** [comment]
Hello stas00,
Many thanks for looking into this!

I've just re-built deepseed. 
Unfortunately I still get the error.

Here is the output from the build:

/media/max/Volume/GPT/finetune/DeepSpeed
Using pip 21.2.4 from /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/pip (python 3.8)
Obtaining file:///media/max/Volume/GPT/finetune/DeepSpeed
/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/pip/_internal/commands/install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
    Running command python setup.py egg_info
    DS_BUILD_OPS=0
    Installed CUDA version 11.4 does not match the version torch was compiled with 11.5 but since the APIs are compatible, accepting this combination
    Install Ops={'cpu_adam': 1, 'cpu_adagrad': False, 'fused_adam': False, 'fused_lamb': False, 'sparse_attn': False, 'transformer': False, 'stochastic_transformer': False, 'async_io': 1, 'utils': 1, 'quantizer': False, 'transformer_inference': False}
    version=0.6.0+a32e9b33, git_hash=a32e9b33, git_branch=HEAD
    install_requires=['hjson', 'ninja', 'numpy', 'packaging', 'psutil', 'py-cpuinfo', 'torch', 'tqdm', 'triton==1.0.0']
    compatible_ops={'cpu_adam': True, 'cpu_adagrad': True, 'fused_adam': True, 'fused_lamb': True, 'sparse_attn': True, 'transformer': True, 'stochastic_transformer': True, 'async_io': True, 'utils': True, 'quantizer': True, 'transformer_inference': True}
    ext_modules=[<setuptools.extension.Extension('deepspeed.ops.adam.cpu_adam_op') at 0x7f2b7bd0e820>, <setuptools.extension.Extension('deepspeed.ops.aio.async_io_op') at 0x7f2b7bbdd790>, <setuptools.extension.Extension('deepspeed.ops.utils_op') at 0x7f2b7bb5ff70>]
    running egg_info
    creating /tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info
    writing /tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/entry_points.txt
    writing requirements to /tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.hip' under directory 'deepspeed'
    warning: no files found matching '*.cc' under directory 'deepspeed'
    warning: no files found matching '*.tr' under directory 'csrc'
    warning: no files found matching '*.cc' under directory 'csrc'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-vqyrd9dj/deepspeed.egg-info/SOURCES.txt'
    deepspeed build time = 0.36443185806274414 secs
Requirement already satisfied: hjson in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (3.0.2)
Requirement already satisfied: ninja in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (1.10.2.3)
Requirement already satisfied: numpy in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (1.22.3)
Requirement already satisfied: packaging in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (21.3)
Requirement already satisfied: psutil in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (5.9.0)
Requirement already satisfied: py-cpuinfo in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (8.0.0)
Requirement already satisfied: torch in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (1.11.0+cu115)
Requirement already satisfied: tqdm in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (4.63.0)
Requirement already satisfied: triton==1.0.0 in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from deepspeed==0.6.0+a32e9b33) (1.0.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from packaging->deepspeed==0.6.0+a32e9b33) (3.0.4)
Requirement already satisfied: typing-extensions in /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages (from torch->deepspeed==0.6.0+a32e9b33) (3.10.0.2)
Installing collected packages: deepspeed
  Attempting uninstall: deepspeed
    Found existing installation: deepspeed 0.5.9+d0ab7224
    Uninstalling deepspeed-0.5.9+d0ab7224:
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/bin/deepspeed
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/bin/deepspeed.pt
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/bin/ds
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/bin/ds_elastic
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/bin/ds_report
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/bin/ds_ssh
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/deepspeed-0.5.9+d0ab7224-py3.8.egg-info
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/deepspeed/
      Removing file or directory /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/op_builder/
      Successfully uninstalled deepspeed-0.5.9+d0ab7224
  Running setup.py develop for deepspeed
    Running command /home/max/anaconda3/envs/gptneo_finetuned/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/media/max/Volume/GPT/finetune/DeepSpeed/setup.py'"'"'; __file__='"'"'/media/max/Volume/GPT/finetune/DeepSpeed/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext -j8 develop --no-deps
    DS_BUILD_OPS=0
    Installed CUDA version 11.4 does not match the version torch was compiled with 11.5 but since the APIs are compatible, accepting this combination
    Install Ops={'cpu_adam': 1, 'cpu_adagrad': False, 'fused_adam': False, 'fused_lamb': False, 'sparse_attn': False, 'transformer': False, 'stochastic_transformer': False, 'async_io': 1, 'utils': 1, 'quantizer': False, 'transformer_inference': False}
    version=0.6.0+a32e9b33, git_hash=a32e9b33, git_branch=HEAD
    install_requires=['hjson', 'ninja', 'numpy', 'packaging', 'psutil', 'py-cpuinfo', 'torch', 'tqdm', 'triton==1.0.0']
    compatible_ops={'cpu_adam': True, 'cpu_adagrad': True, 'fused_adam': True, 'fused_lamb': True, 'sparse_attn': True, 'transformer': True, 'stochastic_transformer': True, 'async_io': True, 'utils': True, 'quantizer': True, 'transformer_inference': True}
    ext_modules=[<setuptools.extension.Extension('deepspeed.ops.adam.cpu_adam_op') at 0x7f41e6e48f10>, <setuptools.extension.Extension('deepspeed.ops.aio.async_io_op') at 0x7f41e6214790>, <setuptools.extension.Extension('deepspeed.ops.utils_op') at 0x7f41e6193f40>]
    running build_ext
    building 'deepspeed.ops.adam.cpu_adam_op' extension
    building 'deepspeed.ops.aio.async_io_op' extension
    creating build
    creating build/temp.linux-x86_64-3.8
    building 'deepspeed.ops.utils_op' extension
    creating build/temp.linux-x86_64-3.8/csrc
    creating build/temp.linux-x86_64-3.8/csrc
    creating build/temp.linux-x86_64-3.8/csrc/adam
    creating build/temp.linux-x86_64-3.8/csrc/utils
    creating build/temp.linux-x86_64-3.8/csrc/aio
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/utils/flatten_unflatten.cpp -o build/temp.linux-x86_64-3.8/csrc/utils/flatten_unflatten.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=utils_op -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    creating build/temp.linux-x86_64-3.8/csrc/aio/py_lib
    creating build/temp.linux-x86_64-3.8/csrc/common
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/includes -I/home/max/anaconda3/envs/gptneo_finetuned/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/adam/cpu_adam.cpp -o build/temp.linux-x86_64-3.8/csrc/adam/cpu_adam.o -O3 -std=c++14 -g -Wno-reorder -L/home/max/anaconda3/envs/gptneo_finetuned/lib64 -lcudart -lcublas -g -march=native -fopenmp -D__AVX256__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=cpu_adam_op -D_GLIBCXX_USE_CXX11_ABI=0
    creating build/temp.linux-x86_64-3.8/csrc/aio/common
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/py_lib/deepspeed_py_copy.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_py_copy.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

    In file included from csrc/includes/cpu_adam.h:12,
                     from csrc/adam/cpu_adam.cpp:1:
    csrc/includes/simd.h:63: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
       63 | #pragma unroll
          |
    csrc/includes/simd.h:71: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
       71 | #pragma unroll
          |
    csrc/includes/simd.h:79: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
       79 | #pragma unroll
          |
    csrc/includes/simd.h:87: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
       87 | #pragma unroll
          |
    csrc/includes/simd.h:95: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
       95 | #pragma unroll
          |
    csrc/includes/simd.h:103: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
      103 | #pragma unroll
          |
    csrc/includes/simd.h:109: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
      109 | #pragma unroll
          |
    csrc/includes/simd.h:115: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
      115 | #pragma unroll
          |
    csrc/includes/simd.h:121: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
      121 | #pragma unroll
          |
    csrc/includes/simd.h:127: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
      127 | #pragma unroll
          |
    csrc/includes/simd.h:133: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
      133 | #pragma unroll
          |
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/py_lib/py_ds_aio.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/py_ds_aio.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/deepspeed
    creating build/lib.linux-x86_64-3.8/deepspeed/ops
    g++ -pthread -shared -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -L/home/max/anaconda3/envs/gptneo_finetuned/lib -Wl,-rpath=/home/max/anaconda3/envs/gptneo_finetuned/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/csrc/utils/flatten_unflatten.o -L/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.8/deepspeed/ops/utils_op.cpython-38-x86_64-linux-gnu.so
    csrc/adam/cpu_adam.cpp: In member function ‘void Adam_Optimizer::Step_1(float*, float*, float*, float*, size_t, __half*, bool)’:
    csrc/adam/cpu_adam.cpp:45:17: warning: ‘params_cast_h’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       45 |         __half* params_cast_h;
          |                 ^~~~~~~~~~~~~
    csrc/adam/cpu_adam.cpp:44:17: warning: ‘grads_cast_h’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       44 |         __half* grads_cast_h;
          |                 ^~~~~~~~~~~~
    /home/max/anaconda3/envs/gptneo_finetuned/bin/nvcc -Icsrc/includes -I/home/max/anaconda3/envs/gptneo_finetuned/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/common/custom_cuda_kernel.cu -o build/temp.linux-x86_64-3.8/csrc/common/custom_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 --use_fast_math -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=cpu_adam_op -D_GLIBCXX_USE_CXX11_ABI=0
    creating build/lib.linux-x86_64-3.8/deepspeed/ops/adam
    g++ -pthread -shared -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -L/home/max/anaconda3/envs/gptneo_finetuned/lib -Wl,-rpath=/home/max/anaconda3/envs/gptneo_finetuned/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/csrc/adam/cpu_adam.o build/temp.linux-x86_64-3.8/csrc/common/custom_cuda_kernel.o -L/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/lib -L/home/max/anaconda3/envs/gptneo_finetuned/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.8/deepspeed/ops/adam/cpu_adam_op.cpython-38-x86_64-linux-gnu.so
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/py_lib/deepspeed_py_aio.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_py_aio.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/py_lib/deepspeed_py_aio_handle.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_py_aio_handle.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/py_lib/deepspeed_aio_thread.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_aio_thread.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/common/deepspeed_aio_utils.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/common/deepspeed_aio_utils.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/common/deepspeed_aio_common.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/common/deepspeed_aio_common.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    csrc/aio/common/deepspeed_aio_common.cpp: In function ‘void _do_io_submit_singles(long long int, long long int, std::unique_ptr<aio_context>&, std::vector<std::chrono::duration<double> >&)’:
    csrc/aio/common/deepspeed_aio_common.cpp:76:20: warning: unused variable ‘submit_ret’ [-Wunused-variable]
       76 |         const auto submit_ret = io_submit(aio_ctxt->_io_ctxt, 1, aio_ctxt->_iocbs.data() + i);
          |                    ^~~~~~~~~~
    csrc/aio/common/deepspeed_aio_common.cpp: In function ‘void _do_io_submit_block(long long int, long long int, std::unique_ptr<aio_context>&, std::vector<std::chrono::duration<double> >&)’:
    csrc/aio/common/deepspeed_aio_common.cpp:96:16: warning: unused variable ‘submit_ret’ [-Wunused-variable]
       96 |     const auto submit_ret = io_submit(aio_ctxt->_io_ctxt, n_iocbs, aio_ctxt->_iocbs.data());
          |                ^~~~~~~~~~
    csrc/aio/common/deepspeed_aio_common.cpp: In function ‘int regular_read(const char*, std::vector<char>&)’:
    csrc/aio/common/deepspeed_aio_common.cpp:280:16: warning: unused variable ‘f_size’ [-Wunused-variable]
      280 |     const auto f_size = get_file_size(filename, num_bytes);
          |                ^~~~~~
    csrc/aio/common/deepspeed_aio_common.cpp: In function ‘bool _validate_buffer(const char*, void*, long long int)’:
    csrc/aio/common/deepspeed_aio_common.cpp:307:16: warning: unused variable ‘reg_ret’ [-Wunused-variable]
      307 |     const auto reg_ret = regular_read(filename, regular_buffer);
          |                ^~~~~~~
    gcc -pthread -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc/aio/py_lib -Icsrc/aio/common -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/gptneo_finetuned/include/python3.8 -c csrc/aio/common/deepspeed_aio_types.cpp -o build/temp.linux-x86_64-3.8/csrc/aio/common/deepspeed_aio_types.o -g -Wall -O0 -std=c++14 -shared -fPIC -Wno-reorder -march=native -fopenmp -D__AVX256__ -laio -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=async_io_op -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    creating build/lib.linux-x86_64-3.8/deepspeed/ops/aio
    g++ -pthread -shared -B /home/max/anaconda3/envs/gptneo_finetuned/compiler_compat -L/home/max/anaconda3/envs/gptneo_finetuned/lib -Wl,-rpath=/home/max/anaconda3/envs/gptneo_finetuned/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_py_copy.o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/py_ds_aio.o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_py_aio.o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_py_aio_handle.o build/temp.linux-x86_64-3.8/csrc/aio/py_lib/deepspeed_aio_thread.o build/temp.linux-x86_64-3.8/csrc/aio/common/deepspeed_aio_utils.o build/temp.linux-x86_64-3.8/csrc/aio/common/deepspeed_aio_common.o build/temp.linux-x86_64-3.8/csrc/aio/common/deepspeed_aio_types.o -L/home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.8/deepspeed/ops/aio/async_io_op.cpython-38-x86_64-linux-gnu.so -laio
    running develop
    running egg_info
    creating deepspeed.egg-info
    writing deepspeed.egg-info/PKG-INFO
    writing dependency_links to deepspeed.egg-info/dependency_links.txt
    writing entry points to deepspeed.egg-info/entry_points.txt
    writing requirements to deepspeed.egg-info/requires.txt
    writing top-level names to deepspeed.egg-info/top_level.txt
    writing manifest file 'deepspeed.egg-info/SOURCES.txt'
    reading manifest file 'deepspeed.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.5). Most likely this shouldn't be a problem.
      warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
    warning: no files found matching '*.hip' under directory 'deepspeed'
    warning: no files found matching '*.cc' under directory 'deepspeed'
    warning: no files found matching '*.tr' under directory 'csrc'
    warning: no files found matching '*.cc' under directory 'csrc'
    adding license file 'LICENSE'
    writing manifest file 'deepspeed.egg-info/SOURCES.txt'
    running build_ext
    copying build/lib.linux-x86_64-3.8/deepspeed/ops/adam/cpu_adam_op.cpython-38-x86_64-linux-gnu.so -> deepspeed/ops/adam
    copying build/lib.linux-x86_64-3.8/deepspeed/ops/aio/async_io_op.cpython-38-x86_64-linux-gnu.so -> deepspeed/ops/aio
    copying build/lib.linux-x86_64-3.8/deepspeed/ops/utils_op.cpython-38-x86_64-linux-gnu.so -> deepspeed/ops
    Creating /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/deepspeed.egg-link (link to .)
    Adding deepspeed 0.6.0+a32e9b33 to easy-install.pth file
    Installing deepspeed script to /home/max/anaconda3/envs/gptneo_finetuned/bin
    Installing deepspeed.pt script to /home/max/anaconda3/envs/gptneo_finetuned/bin
    Installing ds script to /home/max/anaconda3/envs/gptneo_finetuned/bin
    Installing ds_ssh script to /home/max/anaconda3/envs/gptneo_finetuned/bin
    Installing ds_report script to /home/max/anaconda3/envs/gptneo_finetuned/bin
    Installing ds_elastic script to /home/max/anaconda3/envs/gptneo_finetuned/bin

    Installed /media/max/Volume/GPT/finetune/DeepSpeed
    /home/max/anaconda3/envs/gptneo_finetuned/lib/python3.8/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.5). Most likely this shouldn't be a problem.
      warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
    deepspeed build time = 90.15858387947083 secs

Successfully installed deepspeed-0.6.0+a32e9b33

**Comment by stas00** [comment]
I think you should post this to the Deepspeed Issues since this discussion is out of scope for this thread. I'm sure one of the Deepspeed devs will have a better insight into the issue.

**Comment by stas00** [comment]
This issue has been resolved by adding `-lcurand` to the linker command, so closing this.
