### ISSUE TITLE
Instance check of subclass of `IterableDataset` fails on python 3.10

### ISSUE THREAD

**Issue by kosiokarchev** [pytorch/pytorch#69911]
### 🐛 Describe the bug

In python 3.10, subclasses of `torch.utils.data.IterableDataset` cannot be checked in `isinstance` versus `IterableDataset`:

```python
>>> from torch.utils.data import IterableDataset

>>> class SubIterableDataset(IterableDataset):
...    pass

>>> isinstance(SubIterableDataset(), SubIterableDataset)
True

>>> isinstance(SubIterableDataset(), IterableDataset)
TypeError: Instance and class checks can only be used with @runtime_checkable protocols
```

This means that subclasses of `IterableDataset` cannot be used in `DataLoader`, which has an `isinstance(dataset, IterableDataset)` check (so the examples in the documentation [here](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset) don't work).

### Versions

Here's the relevant environment info:
```
PyTorch version: 1.10.0
Is debug build: False

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 11.1.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.33

Python version: 3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.15.7-1-MANJARO-x86_64-with-glibc2.33
```

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Thanks for opening the issue. The newly introduced feature from Python 3.10 leads to this Error (https://docs.python.org/3/whatsnew/3.10.html#typing).

And, we have already landed a PR and it should be fixed if you use nightly wheel of PyTorch.

**Comment by trougnouf** [comment]
I just installed python-pytorch-git 1.3.1.r42540.dd02af62835 ( dd02af628350b185202950dd665472d726992dd9 ) and I still get this error.

```
  File "/orb/benoit_phd/src/dc/../dc/train.py", line 473, in some_function
    some_variable = torch.utils.data.DataLoader(
  File "/usr/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 200, in __init__
    if isinstance(dataset, IterableDataset):
  File "/usr/lib/python3.10/typing.py", line 1473, in __instancecheck__
    raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime_checkable protocols
```

**Comment by ejguan** [comment]
Such issue should be fixed after https://github.com/pytorch/pytorch/commit/d90012689f5b99bbc289da598ad982f829687288 is landed.

Can you please check if you clean up your build?

**Comment by trougnouf** [comment]
> Such issue should be fixed after [d900126](https://github.com/pytorch/pytorch/commit/d90012689f5b99bbc289da598ad982f829687288) is landed.
> 
> Can you please check if you clean up your build?

Done, it's working, thank you!

**Comment by ejguan** [comment]
Closing this issue as the PR has landed. Feel free to open it if needed.

**Comment by hubutui** [comment]
@ejguan Hi, it seems the patch can't be cleanly cherry-picked. It's not convenient to create pkg for ArchLinux. Any plan to make a patch release in the following days? See also https://bugs.archlinux.org/task/73187.

**Comment by ejguan** [comment]
@hubutui 
Do you want to use nightly release? Besides, I believe you have to compile the source code of PyTorch to work with python 3.10. You can use the master branch to get it.
If it's not for python 3.10, I believe the Error won't show up.

**Comment by trougnouf** [comment]
> @hubutui Do you want to use nightly release? Besides, I believe you have to compile the source code of PyTorch to work with python 3.10. You can use the master branch to get it. If it's not for python 3.10, I believe the Error won't show up.

Arch Linux does use Python 3.10 (and I believe Fedora 35 does as well). I'm not a packager but I believe using the git master branch as official package would be frowned upon as inelegant. (Probably necessary if a release doesn't come out soon otherwise but best to be avoided.)

**Comment by ejguan** [comment]
Note: Python 3.10 should be officially supported by PyTorch 1.11.

**Comment by svenstaro** [comment]
I'm the maintainer of Pytorch in Arch Linux and I'd appreciate a patch release containing this fix in order for us to deliver a fixed package to our users. The patch doesn't apply cleanly so we can't just build a fixed package currently.

**Comment by jamesjohnson1025** [comment]
> Note: Python 3.10 should be officially supported by PyTorch 1.11.

I am using Arch Linux, please provide clean path. I am in the middle of pytorch course and completely stuck @ejguan .

**Comment by ejguan** [comment]
> > Note: Python 3.10 should be officially supported by PyTorch 1.11.
> 
> I am using Arch Linux, please provide clean patch. I am in the middle of pytorch course and completely stuck @ejguan .

Could you downgrade your Python to 3.9? The plan for next PyTorch release is coming but it takes some time. So, to bypass it right now, downgrading python is the easiest approach.

**Comment by trougnouf** [comment]
> > > Note: Python 3.10 should be officially supported by PyTorch 1.11.
> > 
> > 
> > I am using Arch Linux, please provide clean patch. I am in the middle of pytorch course and completely stuck @ejguan .
> 
> Could you downgrade your Python to 3.9? The plan for next PyTorch release is coming but it takes some time. So, to bypass it right now, downgrading python is the easiest approach.

I don't think downgrading python is an option nor that it's easy. Every program and library (including python ones) are neatly packaged and there are countless packages depending on python, it would be hell.

I'm also stuck out of my research without working PyTorch. I think the easiest path is to install the git version from aur. (I had it working for a while but I messed with it and I'm getting build errors now, hoping to get it back soon.)

**Comment by ejguan** [comment]
> > > > Note: Python 3.10 should be officially supported by PyTorch 1.11.
> > > 
> > > 
> > > I am using Arch Linux, please provide clean patch. I am in the middle of pytorch course and completely stuck @ejguan .
> > 
> > 
> > Could you downgrade your Python to 3.9? The plan for next PyTorch release is coming but it takes some time. So, to bypass it right now, downgrading python is the easiest approach.
> 
> I don't think downgrading python is an option nor that it's easy. Every program and library (including python ones) are neatly packaged and there are countless packages depending on python, it would be hell.
> 
> I'm also stuck out of my research without working PyTorch. I think the easiest path is to install the git version from aur. (I had it working for a while but I messed with it and I'm getting build errors now, hoping to get it back soon.)

It's gonna be a rabbit hole to debate on it. IMHO, Forward compatibility is never an easy question especially when we have zero control on how Python evolves. It does take sometime for us to make sure PyTorch is fully compatible with Python 3.10. Like I said, we are going to do another release 1.11 to support Python 3.10. It's not just the problem of a single patch, it takes a lot of hurdles to test all cases.

In above cases taking a course of PyTorch, I believe the dependency on Python version is minimum. Then, downgrading would be a better option.

**Comment by ejguan** [comment]
Note: IIRC, a RC branch should be released in the coming month.

**Comment by kosiokarchev** [comment]
FWIW, I "fixed" this by editing `utils/data/_typing.py` lines 24-28 to define simply
```
GenericMeta = type(Generic)
```
and things seem to be fine although I haven't tested systematically.

**Comment by trougnouf** [comment]
> FWIW, I "fixed" this by editing `utils/data/_typing.py` lines 24-28 to define simply
> 
> ```
> GenericMeta = type(Generic)
> ```
> 
> and things seem to be fine although I haven't tested systematically.

That does the job here :)
