### ISSUE TITLE
DISABLED test_random_seed (__main__.TestDataLoaderUtils)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70516]
This job was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_random_seed%2C%20TestDataLoaderUtils)).

cc @ezyang @gchanan @zou3519 @bdhirsh @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Closed issue as this test has been fixed (shm filepath conflict)

**Comment by janeyx99** [comment]
Re-opening as this is still a problem: https://github.com/pytorch/pytorch/runs/6787236510?check_suite_focus=true 

https://hud.pytorch.org/minihud#cf3ce329b548e1e8da65542af53b16f27d5dc72a

**Comment by janeyx99** [comment]
@ejguan could you take another look at this?

**Comment by ejguan** [comment]
Based on the log, the Error comes from:
```
OMP: Error #15: Initializing libiomp5.so, but found unknown library already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see [http://www.intel.com/software/products/support/.](http://www.intel.com/software/products/support/)
```
@janeyx99 Do you have any suggestion other than using `os.environ['KMP_DUPLICATE_LIB_OK']='True'` in the test case.

This is kind weird to me as the test code should not initialize OpenMP IMHO.

**Comment by ZainRizvi** [comment]
@ejguan wanted to bump this as it's still failing.

These log lines may help debug ([source](https://hud.pytorch.org/pytorch/pytorch/commit/afcc7c7f5c7cef740241ff0abdae8d4f2ad22a03)):

```
2022-09-13T18:46:47.0311017Z   test_random_seed (__main__.TestDataLoaderUtils) ... [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T18:46:47.0432572Z [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T18:46:47.0555636Z [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T18:46:47.0677391Z [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T18:46:47.1143134Z [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T18:46:47.1265761Z [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T18:46:47.1377961Z [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T18:46:47.1497530Z [W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
2022-09-13T21:26:24.8161444Z ##[error]The action has timed out.
```

More examples (look for "The action has timed out"):
* https://hud.pytorch.org/pytorch/pytorch/commit/dbd38f63f5731f8403edfdf9d5956ca872453dd3
* https://hud.pytorch.org/pytorch/pytorch/commit/d6733327829fa02295c239ad96a26bef8afa6da4
* https://hud.pytorch.org/pytorch/pytorch/commit/31cc03cc132020244f6985aefdcd1c05babc2e17

**Comment by ZainRizvi** [comment]
And it seems like flaky test bot isn't disabling this test :(
Can we manually disable the test for now, since it has failed multiple times this week?

**Comment by janeyx99** [comment]
The reason it's not getting properly disabled is because there's a missing super().setUp() call missing here https://github.com/pytorch/pytorch/blob/b18962552ebf59593d31110d76ae16cd7052c990/test/test_utils.py#L426
