### ISSUE TITLE
ASAN shards are very unbalanced

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#72368]
### 🐛 Describe the bug

Have a look at https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=asan:
 Typical run time for shard1 is  3h30m for shard2 is  1h30m and for shard3 is 1h20m

- Can it be because shard1 runs c++ tests?
- Or because sharding calculations are made based on runtime of optimized builds (i.e. windows and asan shards would always be scewed towards linux-cuda tests runtimes?)
- Is there a bug in sharing algorithm?
(Perhaps it ignores skipped/slow test metrics when calculating testfile runtimes?)

Tests (at the file granularity) are selected for each shards based on previous nightly runtime using following function
https://github.com/pytorch/pytorch/blob/b7307687e9cee6689c8ad513939ac406221efd9a/tools/testing/test_selections.py#L170 

### Versions

N/A it relates to CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
When we first added the third shard, testing took a lot shorter as well, with no shard going over 2 hours
https://github.com/pytorch/pytorch/pull/69843#issuecomment-994988926

**Comment by malfet** [comment]
Windows test shards are also super unbalanced, to the degree that it started to cause timeouts

**Comment by janeyx99** [comment]
> Windows test shards are also super unbalanced, to the degree that it started to cause timeouts

Windows sharding should be fixed now that stats have been uploaded since my recent changes (#73293). Looking at this commit https://hud2.pytorch.org/pytorch/pytorch/commit/b213041df304c05980b3209dddf1b595699c8b74 on trunk, the shards are much more balanced now that stats can be found.

**Comment by seemethere** [comment]
This still appears to be an issue, perhaps a higher priority issue now?

**Comment by seemethere** [comment]
@b0noI has suggested that our current primary submit a PR to disable ASAN for now until we can figure out how to re-balance (@atalman)

**Comment by suo** [comment]
@atalman any process on this? In particular the periodic change

**Comment by malfet** [comment]
> @b0noI has suggested that our current primary submit a PR to move ASAN jobs to periodic for now until we can figure out how to re-balance (@atalman)

Hmm, can we put it to triage review then? I.e. what's the motivation for moving this to periodic? And wouldn't it increase number of reverts/makes detecting regressions harder?

**Comment by atalman** [comment]
This is not unbalanced shard issue but an issue related to slow running tests.

Reference following PR introduce slow running test file:
https://github.com/pytorch/pytorch/blob/706f2b30fcfa7e7da0dbeb53269bb36683bfd166/tools/stats/export_slow_tests.py

Here are some details explaining the logic behind this:
https://github.com/pytorch/pytorch/pull/54907

Basically the following workflow seems to be happening, On March 12 the following tests where slow running:

1) Log: https://github.com/pytorch/pytorch/runs/5523825211?check_suite_focus=true
```
test_fn_gradgrad_pca_lowrank_cpu_float64 (__main__.TestGradientsCPU) ... ok (60.780s)
test_fn_gradgrad_svd_cpu_complex128 (__main__.TestGradientsCPU) ... ok (69.131s)
test_inplace_gradgrad_cumprod_cpu_complex128 (__main__.TestGradientsCPU) ... ok (211.554s)
test_variant_consistency_jit_diff_cpu_complex64 (__main__.TestJitCPU) ... ok (67.640s)
2022-03-12T21:46:25.3026906Z   test_variant_consistency_jit_linalg_solve_triangular_cpu_float32 (__main__.TestJitCPU) ... ok (125.208s)
2022-03-12T21:48:58.0469092Z   test_variant_consistency_jit_linalg_svd_cpu_complex64 (__main__.TestJitCPU) ... ok (152.744s)
2022-03-12T21:50:11.6688335Z   test_variant_consistency_jit_linalg_svd_cpu_float32 (__main__.TestJitCPU) ... ok (73.622s)
2022-03-12T21:54:44.5263321Z   test_variant_consistency_jit_lu_solve_cpu_complex64 (__main__.TestJitCPU) ... ok (102.051s)
2022-03-12T21:55:35.6167891Z   test_variant_consistency_jit_lu_solve_cpu_float32 (__main__.TestJitCPU) ... ok (51.090s)
2022-03-12T22:00:58.4220662Z   test_variant_consistency_jit_nanquantile_cpu_float32 (__main__.TestJitCPU) ... ok (47.142s)
2022-03-12T22:12:25.8979944Z   test_variant_consistency_jit_nn_functional_max_pool1d_cpu_float32 (__main__.TestJitCPU) ... ok (494.579s)
2022-03-12T22:32:45.9750642Z   test_variant_consistency_jit_nn_functional_max_pool2d_cpu_float32 (__main__.TestJitCPU) ... ok (1220.077s)
2022-03-12T22:40:31.3121960Z   test_variant_consistency_jit_nn_functional_max_pool3d_cpu_float32 (__main__.TestJitCPU) ... ok (465.337s)
2022-03-12T22:41:56.5711967Z   test_variant_consistency_jit_nn_functional_pad_circular_cpu_complex64 (__main__.TestJitCPU) ... ok (58.542s)
2022-03-12T22:45:48.7048047Z   test_variant_consistency_jit_nn_functional_pad_constant_cpu_complex64 (__main__.TestJitCPU) ... ok (232.128s)
2022-03-12T22:47:49.1422719Z   test_variant_consistency_jit_nn_functional_pad_constant_cpu_float32 (__main__.TestJitCPU) ... ok (120.437s)
2022-03-12T22:48:48.9686822Z   test_variant_consistency_jit_nn_functional_pad_reflect_cpu_complex64 (__main__.TestJitCPU) ... ok (59.826s)
2022-03-12T22:49:49.2502012Z   test_variant_consistency_jit_nn_functional_pad_replicate_cpu_complex64 (__main__.TestJitCPU) ... ok (60.272s)
2022-03-12T22:51:02.5255728Z   test_variant_consistency_jit_nn_functional_poisson_nll_loss_cpu_float32 (__main__.TestJitCPU) ... ok (73.208s)
2022-03-12T22:54:23.8291811Z   test_variant_consistency_jit_norm_cpu_complex64 (__main__.TestJitCPU) ... ok (136.107s)
2022-03-12T22:55:33.0800761Z   test_variant_consistency_jit_norm_cpu_float32 (__main__.TestJitCPU) ... ok (69.251s)
2022-03-12T22:57:50.4699741Z   test_variant_consistency_jit_ormqr_cpu_complex64 (__main__.TestJitCPU) ... ok (105.720s)
2022-03-12T22:58:46.2191192Z   test_variant_consistency_jit_ormqr_cpu_float32 (__main__.TestJitCPU) ... ok (55.749s)
2022-03-12T23:01:40.5424782Z   test_variant_consistency_jit_prod_cpu_complex64 (__main__.TestJitCPU) ... ok (89.440s)
2022-03-12T23:03:20.2300845Z   test_variant_consistency_jit_put_cpu_complex64 (__main__.TestJitCPU) ... ok (55.004s)
2022-03-12T23:05:34.2481242Z   test_variant_consistency_jit_qr_cpu_complex64 (__main__.TestJitCPU) ... ok (106.490s)
2022-03-12T23:06:26.1268335Z   test_variant_consistency_jit_qr_cpu_float32 (__main__.TestJitCPU) ... ok (51.879s)
2022-03-12T23:07:51.5261184Z   test_variant_consistency_jit_quantile_cpu_float32 (__main__.TestJitCPU) ... ok (85.399s)
test_variant_consistency_jit_sort_cpu_float32 (__main__.TestJitCPU) ... ok (84.378s)
2022-03-12T23:23:48.6314435Z   test_variant_consistency_jit_sum_cpu_complex64 (__main__.TestJitCPU) ... ok (55.706s)
2022-03-12T23:24:19.2219967Z   test_variant_consistency_jit_sum_cpu_float32 (__main__.TestJitCPU) ... ok (30.590s)
2022-03-12T23:36:45.9809917Z   test_variant_consistency_jit_svd_cpu_complex64 (__main__.TestJitCPU) ... ok (746.744s)
2022-03-12T23:42:42.7827088Z   test_variant_consistency_jit_svd_cpu_float32 (__main__.TestJitCPU) ... ok (356.802s)
2022-03-12T23:47:12.7248896Z   test_variant_consistency_jit_tile_cpu_complex64 (__main__.TestJitCPU) ... ok (85.721s)   ```

The export_slow test identified these jobs as slow and created followin commit
https://github.com/pytorch/test-infra/commit/2846e49c4849a34ec1cb30ccb3b4dbd935554cc6

2) Next workflow on following day skipped these test and finished in time https://ossci-raw-job-status.s3.amazonaws.com/log/5528677638

**Comment by atalman** [comment]
For adding asan with slow test I think we would need to add new asan periodic workflow for just slow tests while keeping the old workflow active. Similar to the following workflow: periodic-linux-xenial-cuda10.2-py3-gcc7-slow-gradcheck

**Comment by atalman** [comment]
This is not a sharding algorithm issue. To Follow up on this issue we need to make lower granularity tests on break up test suites.
Here is the content of pytorch_test_times.json (the result of calculating sharding)

```
{
    "commit": "39535fec6c3ff5bf7c2d322d096c59571c3295ed",
    "JOB_BASE_NAME": "linux-xenial-py3.7-clang7-asan",
    "job_times": {
        "test_ops": 14928.355000000636, <- This test suite is over 4hrs alone
        "test_quantization": 1635.678999999999,
        "test_nn": 369.28800000000155,
        "test_linalg": 333.88600000000065,
        "test_cpp_extensions_jit": 264.07099999999986,
        "test_foreach": 242.07600000000122,
        "test_binary_ufuncs": 154.88400000000397,
        "test_reductions": 134.60099999999795,
        "distributions/test_distributions": 69.34400000000005,
        "test_dispatch": 62.957999999999984,
        "test_sparse": 62.68500000000095,
        "test_fx_experimental": 59.15400000000006,
        "test_view_ops": 37.97500000000015,
        "test_spectral_ops": 21.590999999999987,
        "test_type_hints": 20.204,
        "test_sparse_csr": 15.15599999999997,
        "test_ao_sparsity": 8.882,
        "test_multiprocessing": 7.080000000000004,
        "test_vmap": 7.0249999999999915,
        "test_multiprocessing_spawn": 6.299000000000002,
        "test_shape_ops": 3.3529999999999993,
        "test_dataloader": 2.7889999999999886,
        "test_logging": 2.362,
        "test_package": 14.048,
        "test_expanded_weights": 1.5339999999999943,
```

----
Here is what executed on the worker 1:

```
2022-03-15T17:57:46.6183054Z Exporting S3 test stats to .pytorch-test-times.json.
2022-03-15T17:57:46.6465424Z Selected tests:
2022-03-15T17:57:46.6465709Z  test_ops
2022-03-15T17:57:46.6465911Z  test_cuda <- This is empty test
2022-03-15T17:57:46.6466087Z  test_nestedtensor <- This is empty test
```

------
Hence we either have to break down test_ops to more fine grained test or implement sharding on individual tests rather then test groups

**Comment by malfet** [comment]
Downloaded [stats](https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/1988414994/artifact/test-reports-test_default_1_3-default-1-3-linux.2xlarge.zip) for commit https://github.com/pytorch/pytorch/commit/039b62cf0324ef257c6e999a4a88fb15e43eb09c
show that `TestGradientsCPU` took 3315.3 sec to finish, and `TestJitCPU` a whooping 9547.3 sec

@mruberry any objection to splitting out above classes from `test_ops.py` into `test_ops_gradients.py` and `test_ops_jit.py`?

**Comment by suo** [comment]
Wow, guess we hit the "we have to break up test_ops" barrier in record time :P

**Comment by mruberry** [comment]
We can put TestGradients into test_ops_gradients.py (cc @albanD, @soulitzer) and TestJit into test_ops_jit.py (@suo -- would you like to propose another name?). I would also suggest we stop running TestJit under ASAN by decorating its tests with a TEST_ASAN skip decorator -or- we make running it under ASAN a periodic job. It's crazy how long it takes. @suo what are your thoughts on TestJit + ASAN?

**Comment by suo** [comment]
> @suo what are your thoughts on TestJit + ASAN?

I think it's fine to keep, and potentially split up further. ASAN jobs run on `linux.2xlarge` which are cheap as dirt, so we can shard as aggressively as we want—no need to reduce coverage.

**Comment by janeyx99** [comment]
@atalman wow what a good find, it’s funny we just talked about test_ops in OSS CI review just yesterday. +1 for removing asan tests from being considered as slow and then aggressively sharding the ASAN config (no need for periodic configs). To be able to more aggressively shard, we likely will need to split up the file even more

**Comment by janeyx99** [comment]
Reopening as it would still be nice to enable automatic sharding for asan

**Comment by atalman** [comment]
@janeyx99  Please provide some details, what makes you think automatic sharding is not enabled for asan ?

**Comment by malfet** [comment]
Agree with @janeyx99 that we should not auto-close this issue until we see tests getting balanced (and especially considering that PR on master just got reverted)

**Comment by atalman** [comment]
Created new issue to refactor test_ops_jit here #74589

**Comment by atalman** [comment]
> Reopening as it would still be nice to enable automatic sharding for asan

As per discussion, sharding is automated for asan.

**Comment by atalman** [comment]
Created issue describing improvement need to be done for sharding algorithm to improve its reliability: https://github.com/pytorch/pytorch/issues/74620

Closing this issue, with the two followups created #74620 and #4589
