### ISSUE TITLE
LTS installation instructions are outdated and index is not set up correctly

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#76829]
#74753 seemingly enabled installing the LTS wheels with the `--extra-index-url` flag for `pip install`. There are still two issues though:

1. The [official installation instructions](https://pytorch.org/get-started/locally/) have not been updated and still use the `-f` syntax.
2. Following the same scheme as the other channels, the link should be https://download.pytorch.org/whl/lts/1.8. Unfortunately, this link is broken if one omits a `/` at the end of the link. Appending that, the link works now https://download.pytorch.org/whl/lts/1.8/. For other channels it doesn't matter:
    - https://download.pytorch.org/whl/nightly
    - https://download.pytorch.org/whl/nightly/

    The behavior stays the same when appending a specific computation backend:
    - https://download.pytorch.org/whl/lts/1.8/cpu
    - https://download.pytorch.org/whl/lts/1.8/cpu/

**Comment by jambayk** [comment]
Acknowledging the assignment. 

I will look into this.

**Comment by seemethere** [comment]
Awesome! Went ahead and modified our cloudfront function to also fix this as well.
<details>
<summary> Here's the updated code: </summary>

```javascript
function handler(event) {
    var request = event.request;
    var uri = request.uri;
    var uri_parts = uri.split('/')
    var last_uri_part = uri_parts[uri_parts.length -1]
    var lts_pattern = /^[0-9]+.[0-9]+$/
    
    if (uri.startsWith('/whl')) {
        // Check whether the URI is missing a file name.
        if (uri.endsWith('/')) {
            request.uri += 'index.html';
        // Check whether the URI is folder like
        // I.e. does not have dots in path
        // For example /whl/cpu/torch
        } else if (last_uri_part.match(lts_pattern) || uri.indexOf('.') == -1) {
            request.uri += '/index.html';
        }
    } 

    return request;
}
```
</details>

**Comment by seemethere** [comment]
Going to close this, think this should now be resolved!

**Comment by pmeier** [comment]
@seemethere the behavior still persists when appending a computation backend to the link

- :heavy_multiplication_x: https://download.pytorch.org/whl/lts/1.8/cpu
- :heavy_check_mark: https://download.pytorch.org/whl/lts/1.8/cpu/
