### ISSUE TITLE
`MPSNDArray` or `MPSGraphTensorData` allocated with wrong size

### ISSUE THREAD

**Issue by philipturner** [pytorch/pytorch#77851]
### 🐛 Describe the bug

The following code:
```python
import torch
mps = torch.device("mps")

size = 16
A = torch.rand(size, device=mps)
F = torch.rand(size, size, size, device=mps)
print(A@F)
```

Produces the following error:
```
/AppleInternal/Library/BuildRoots/.../Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 1024 bytes
```

### Versions

The PyTorch Forums thread linked below should help steer discussion on this:

https://discuss.pytorch.org/t/mpsndarray-error-buffer-is-not-large-enough/152030

**Comment by philipturner** [comment]
CC: @albanD

Also, do you have Metal API validation enabled or not, and is it affecting whether errors like this occur? If it's enabled, then it takes a massive toll on CPU-side performance. In my experience, a more than two-fold increase in latency. However, Metal API validation also catches bugs like this one. I haven't checked whether that feature just covers raw Metal calls or also covers MPS calls.

**Comment by xiaoouwang** [comment]
Maybe related to #77886 as well.

**Comment by philipturner** [comment]
We have a slightly more narrowed reproducer for this crash:

https://discuss.pytorch.org/t/mpsndarray-error-buffer-is-not-large-enough/152030/6?u=philipturner

**Comment by razarmehr** [comment]
This issue is fixed in PR #78496 (nightly build 1.13.0.dev20220531).

**Comment by daniwnwd** [comment]
I still get the error "[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough." on a basic sanity test

on (1.13.0.dev20220712).

Is there any way to fix this?

**Comment by philipturner** [comment]
The crash is because the [`MPSNDArrayDescriptor`](https://developer.apple.com/documentation/metalperformanceshaders/mpsndarraydescriptor) has a size larger than the `MTLBuffer` argument. I couldn't find that specific initializer in the PyTorch repo with a GitHub search, so it's probably internal to the Metal runtime. PyTorch called some convenience function, maybe on `MPSGraphTensorData` or `MPSNDArray`, which actually delegates to `MPSNDArray.init(buffer:descriptor:)`. My best guess is that it happens somewhere in [OperationUtils.mm](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/OperationUtils.mm). If you want to fix it, try littering that section of code with assertions that check buffer size. Then, recompile PyTorch and it should crash there.

**Comment by Panter7777** [comment]
Still get the error 
MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 135266304 bytes

torch                     1.13.0.dev20220811
torchaudio            0.13.0.dev20220811
torchmetrics         0.9.3
torchvision            0.14.0.dev20220811
tokenizers             0.10.3

MacOS: 12.5
Chip: Apple M1 Max

**Comment by malfet** [comment]
@Panter7777 can you share a minimal reproducer? I've fixed the problem in few ops, but it might remain in others

**Comment by jaypinho** [comment]
I am also still getting this issue using latest nightly build (`1.13.0.dev20221002`): `PYTORCH_ENABLE_MPS_FALLBACK=1 whisper [filename goes here] --language English --model small --device mps --fp16 False`

**Comment by kapsyst** [comment]
I'm also getting the following:
```
/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 796 bytes
```
I'm not sure if it's related but I also get a warning before that:
```
venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  Referenced from: venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in: venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
```
I'll try and create a minimal reproducer. My Torch versions are the following:
```
pip freeze | grep torch
pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git@6ae863f301c66b82c8caf18e12cbae17d2620415
torch==1.13.0.dev20221002
torchgeometry==0.1.2
torchvision==0.13.1
```
Any help or pointers much appreciated!

**Comment by Sothatsit** [comment]
I also get this issue:

Error:
```
/AppleInternal/Library/BuildRoots/8d3bda53-8d9c-11ec-abd7-fa6a1964e34e/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 584530 bytes
```

Versions:
```
torch==1.14.0.dev20221014
torchaudio==0.13.0.dev20221014
torchvision==0.15.0.dev20221014
```

I'm using a large transformer issue so its hard to track down exactly what would have caused the issue.
