### ISSUE TITLE
RuntimeError while loading model with MPS device

### ISSUE THREAD

**Issue by d4rk-lucif3r** [pytorch/pytorch#77874]
### 🐛 Describe the bug

When I'm trying to load a saved model it throws a Runtime Error 

# Steps to reproduce
Steps to reproduce:
[Craft.py](https://gist.github.com/d4rk-lucif3r/3b491d74b18ad975baf187fb0ac89516)
[craft.pth](https://github.com/faustomorales/keras-ocr/releases/download/v0.8.4/craft_mlt_25k.pth)
net = CRAFT()
net.load_state_dict(torch.load(
    '/Users/arshanwar/model/craft.pth', map_location=torch.device('mps')))

# Error
---------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
test.ipynb Cell 14' in <cell line: 1>()
----> [1](vscode-notebook-cell:/Users/arshanwar/Projects/Clients/Nielsen/adscan/adscan_cv/test.ipynb#ch0000013?line=0) net.load_state_dict(torch.load(
      [2](vscode-notebook-cell:/Users/arshanwar/Projects/Clients/Nielsen/adscan/adscan_cv/test.ipynb#ch0000013?line=1)     '/Users/arshanwar/.EasyOCR//model/craft_mlt_25k.pth', map_location=torch.device('mps')))

File ~/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py:713, in load(f, map_location, pickle_module, **pickle_load_args)
    [711](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=710)             return torch.jit.load(opened_file)
    [712](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=711)         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> [713](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=712) return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)

File ~/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py:930, in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    [928](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=927) unpickler = UnpicklerWrapper(f, **pickle_load_args)
    [929](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=928) unpickler.persistent_load = persistent_load
--> [930](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=929) result = unpickler.load()
    [932](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=931) deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)
    [934](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=933) offset = f.tell() if f_should_read_directly else None

File ~/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py:876, in _legacy_load.<locals>.persistent_load(saved_id)
    [872](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=871)     obj._torch_load_uninitialized = True
    [873](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=872)     # TODO: Once we decide to break serialization FC, we can
    [874](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=873)     # stop wrapping with _TypedStorage
    [875](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=874)     deserialized_objects[root_key] = torch.storage._TypedStorage(
--> [876](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=875)         wrap_storage=restore_location(obj, location),
    [877](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=876)         dtype=dtype)
    [879](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=878) typed_storage = deserialized_objects[root_key]
    [880](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=879) if view_metadata is not None:

File ~/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py:973, in _get_restore_location.<locals>.restore_location(storage, location)
    [972](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=971) def restore_location(storage, location):
--> [973](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=972)     return default_restore_location(storage, str(map_location))

File ~/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py:179, in default_restore_location(storage, location)
    [177](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=176)     if result is not None:
    [178](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=177)         return result
--> [179](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=178) raise RuntimeError("don't know how to restore data location of "
    [180](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=179)                    + torch.typename(storage) + " (tagged with "
    [181](file:///Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py?line=180)                    + location + ")")

RuntimeError: don't know how to restore data location of torch._UntypedStorage (tagged with mps)
------

### Versions

PyTorch version: 1.12.0.dev20220519
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:27:43)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] idx2numpy==1.2.3
[pip3] numpy==1.21.6
[pip3] pytorch-tabnet==3.1.1
[pip3] torch==1.12.0.dev20220519
[pip3] torchbnn==1.2
[pip3] torchvision==0.12.0a0
[conda] idx2numpy                 1.2.3                    pypi_0    pypi
[conda] numpy                     1.21.6           py39h690d673_0    conda-forge
[conda] pytorch                   1.12.0.dev20220519         py3.9_0    pytorch-nightly
[conda] pytorch-tabnet            3.1.1                    pypi_0    pypi
[conda] torchbnn                  1.2                      pypi_0    pypi
[conda] torchvision               0.12.0          cpu_py39h384c48c_1    <unknown>

**Comment by pannous** [comment]
as a workaround you can load the model to 'cpu' first and then do model.to('mps'), but you may run into other issues such as https://github.com/pytorch/pytorch/issues/77931

**Comment by d4rk-lucif3r** [comment]
yes i tried that also..not working.

**Comment by aw632** [comment]
Able to reproduce this same RunTime Error on `'macOS-12.4-arm64-arm-64bit'` with version 1.12.0 stable.

**Comment by qqaatw** [comment]
Should be fixed already on master https://github.com/pytorch/pytorch/commit/0a651a231d81fc34d6b8858ee41cf7b9772c042a

**Comment by hombit** [comment]
I tested with current nightly, it looks like it fixed the issue for me

**Comment by xsacha** [comment]
This wasn't fixed for torchscript yet:
`torch.jit.load(..., torch::kMPS);`

> Unable to load model: supported devices include CPU and CUDA, however got MPS

**Comment by DenisVieriu97** [comment]
> Should be fixed already on master https://github.com/pytorch/pytorch/commit/0a651a231d81fc34d6b8858ee41cf7b9772c042a

@d4rk-lucif3r this is fixed in the latest PyTorch nightly. Could you please give a try and reopen this issue if you are seeing any errors? Thanks!

**Comment by d4rk-lucif3r** [comment]
@DenisVieriu97 I'm still facing the issue
checkpoint = torch.load('checkpoint.pt', map_location=torch.device('mps:0'))


Error
`    checkpoint = torch.load('checkpoint.pt', map_location=torch.device('mps:0'))
  File "/Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py", line 735, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py", line 952, in _legacy_load
    result = unpickler.load()
  File "/Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py", line 898, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "/Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py", line 995, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/Users/arshanwar/miniforge3/lucif3r-venv/lib/python3.9/site-packages/torch/serialization.py", line 198, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with mps:0)`

**Comment by DenisVieriu97** [comment]
Thanks @d4rk-lucif3r for trying this again with latest nightly - reopening this back. We'll take a look

**Comment by kulinseth** [comment]
```
import torch
import craft
net = craft.CRAFT()
state_dict = torch.load('craft.pth', map_location=torch.device('mps'))

from collections import OrderedDict
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:] # remove module.
    new_state_dict[name] = v
dict = net.load_state_dict(new_state_dict)
print (dict)
```
We tried with your provided example with latest torch nightly. and are not able to repro the issue.

Console output.
```
<All keys matched successfully>
```

Please re-open the issue if you still see the problem.

**Comment by xsacha** [comment]
Thanks @kulinseth . It must have been fixed in the past month. Very handy!

**Comment by d4rk-lucif3r** [comment]
Yes @kulinseth it is working. Thanks
