### ISSUE TITLE
Pytorch 1.12.0 AttributeError: 'Adam' object has no attribute '_warned_capturable_if_run_uncaptured'

### ISSUE THREAD

**Issue by CalciumBall** [pytorch/pytorch#80831]
### 🐛 Describe the bug

In the torch.optim.Adam:

```
@torch.no_grad()
    def step(self, closure=None):
        """Performs a single optimization step.

        Args:
            closure (callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        self._cuda_graph_capture_health_check()

        ...
```
Calls the _cuda_graph_capture_health_check()

```
 # Currently needed by Adam and AdamW
    def _cuda_graph_capture_health_check(self):
        if torch.has_cuda and torch.cuda.is_available():
            capturing = torch.cuda.is_current_stream_capturing()

            if capturing and not self.defaults['capturable']:
                raise RuntimeError("Attempting CUDA graph capture of step() for an instance of " +
                                   self.__class__.__name__ +
                                   " but this instance was constructed with capturable=False.")

            if (not self._warned_capturable_if_run_uncaptured) and self.defaults['capturable'] and (not capturing):
                print("Warning: This instance was constructed with capturable=True, but step() " +
                      "is running without CUDA graph capture. If you never intend to graph-capture this " +
                      "instance, capturable=True can impair performance, and you should set capturable=False.")
                self._warned_capturable_if_run_uncaptured = True
```

And 
```
if (not self._warned_capturable_if_run_uncaptured)
```
Raise Error:
```
AttributeError: 'Adam' object has no attribute '_warned_capturable_if_run_uncaptured'
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti
Nvidia driver version: 515.43.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-benchmark==0.3.4
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h95df7f1_0    conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] numpy                     1.22.3           py38he7a7128_0  
[conda] numpy-base                1.22.3           py38hf524024_0  
[conda] pytorch                   1.12.0          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-benchmark         0.3.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.0               py38_cu116    pytorch
[conda] torchvision               0.13.0               py38_cu116    pytorch

cc @ezyang @gchanan @zou3519 @vincentqb @jbschlosser @albanD @mcarilli

**Comment by jaried** [comment]
This is a bug, it is recommended that the issue not be closed until the official reply.

See this:
https://github.com/pytorch/pytorch/issues/80809

> Hi, I am also facing the same issue when I try to load the checkpoint and resume model training on the latest pytorch (1.12).
> 
> It seems to be related with a newly introduced parameter (capturable) for the [Adam and AdamW optimizers](https://github.com/pytorch/pytorch/blob/master/torch/optim/adamw.py). Currently two workarounds:
> 
> 1. forcing capturable = True after loading the checkpoint (as suggested above) `optim.param_groups[0]['capturable'] = True` . This seems to slow down the model training by approx. 10% (YMMV depending on the setup).
> 2. Reverting pytorch back to previous versions (I have been using 1.11.0).
> 
> I'm wondering whether enforcing `capturable = True` may incur unwanted side effects.

**Comment by CalciumBall** [comment]
I currently comment self._cuda_graph_capture_health_check() out, and it seems working.

**Comment by zou3519** [comment]
High-pri for user activity (see https://github.com/pytorch/pytorch/issues/80809, a previous thread) and because this sounds like a regression. I didn't read too much into the error message yet otherwise.

@CalciumBall do you have a script that reproduces the problem?

**Comment by albanD** [comment]
Note that this is already fixed in master via https://github.com/pytorch/pytorch/pull/80345 which already has the proper milestone.

Closing this as it is fixed.

**Comment by naveen-marthala** [comment]
I am on `1.12.0+cu113` google colab pro and I still get this error.
