### ISSUE TITLE
I have the same issue as @samgelman on my MacOS.

### ISSUE THREAD

**Issue by yuanmao** [pytorch/pytorch#83540]
I have the same issue as @samgelman on my MacOS. 

Notably 1.10.1, 1.11.0 works fine but 1.10.2 and 1.12.1 shows:
```
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6
```
One observation is that both 1.10.1 and 1.11.0 also come with `libuv` installation, which might have made the difference.

The workaround `KMP_DUPLICATE_LIB_OK=TRUE` causes a segfault.

Below is a working env:
```
python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.31.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:16:26)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.10.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py38h9ed2024_0  
[conda] mkl_fft                   1.3.1            py38h4ab4a9b_0  
[conda] mkl_random                1.2.2            py38hb2f4e1b_0  
[conda] mypy_extensions           0.4.3            py38hecd8cb5_1  
[conda] numpy                     1.21.5           py38h2e5f0a9_3  
[conda] numpy-base                1.21.5           py38h3b1a694_3  
[conda] pytorch                   1.10.1                  py3.8_0    pytorch
```

_Originally posted by @yuanmao in https://github.com/pytorch/pytorch/issues/78490#issuecomment-1217134036_

**Comment by AlexVialaBellander** [comment]
Hi, 
I am experiencing the same thing. Running macOS 12.3.

Reproducing by starting python in the environment. 

```
import numpy
import torch
```

Error:
```
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

Env:
```
# Name                    Version                   Build  Channel
absl-py                   1.2.0                    pypi_0    pypi
anyio                     3.5.0            py39hecd8cb5_0
appnope                   0.1.2           py39hecd8cb5_1001
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39hca72f7f_0
asttokens                 2.0.5              pyhd3eb1b0_0
attrs                     21.4.0             pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.11.1           py39hecd8cb5_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
bottleneck                1.3.5            py39h67323c0_0
brotli                    1.0.9                hca72f7f_7
brotli-bin                1.0.9                hca72f7f_7
brotlipy                  0.7.0           py39h9ed2024_1003
ca-certificates           2022.07.19           hecd8cb5_0
cachetools                5.2.0                    pypi_0    pypi
catalogue                 2.0.7            py39hecd8cb5_0
certifi                   2022.6.15        py39hecd8cb5_0
cffi                      1.15.1           py39hc55c11b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py39hecd8cb5_0
cloudpickle               2.2.0                    pypi_0    pypi
colorama                  0.4.5            py39hecd8cb5_0
cpuonly                   2.0                           0    pytorch-nightly
cryptography              37.0.1           py39hf6deb26_0
cycler                    0.11.0             pyhd3eb1b0_0
cymem                     2.0.6            py39he9d5cce_0
cython-blis               0.7.7            py39h67323c0_0
debugpy                   1.5.1            py39he9d5cce_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.4              py39hecd8cb5_0
executing                 0.8.3              pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.11.0               hd8bbffd_0
future                    0.18.2           py39hecd8cb5_1
gettext                   0.21.0               h7535e17_0
giflib                    5.2.1                haf1e3a3_0
glib                      2.69.1               h8346a28_1
google-auth               2.11.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.48.1                   pypi_0    pypi
gst-plugins-base          1.14.0               h4180768_2
gstreamer                 1.14.0               h0fc69c2_2
gym                       0.26.0                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
h5py                      3.7.0            py39h4a1dd59_0
hdf5                      1.10.6               hdbbcd12_0
icu                       58.2                 h0a44026_3
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          hecd8cb5_3538
ipykernel                 6.15.2           py39hecd8cb5_0
ipython                   8.4.0            py39hecd8cb5_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                8.0.2                    pypi_0    pypi
jedi                      0.18.1           py39hecd8cb5_1
jinja2                    3.0.3              pyhd3eb1b0_0
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9e                   hca72f7f_0
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.4.0            py39hecd8cb5_0
jupyter                   1.0.0            py39hecd8cb5_8
jupyter_client            7.3.5            py39hecd8cb5_0
jupyter_console           6.4.3              pyhd3eb1b0_0
jupyter_core              4.10.0           py39hecd8cb5_0
jupyter_server            1.18.1           py39hecd8cb5_0
jupyterlab                3.4.4            py39hecd8cb5_0
jupyterlab-widgets        3.0.3                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.12.0           py39hecd8cb5_0
kaggle                    1.5.12                   pypi_0    pypi
kiwisolver                1.4.2            py39he9d5cce_0
krb5                      1.19.2               hcd88c3b_0
langcodes                 3.3.0              pyhd3eb1b0_0
lcms2                     2.12                 hf1fd2bf_0
lerc                      3.0                  he9d5cce_0
libbrotlicommon           1.0.9                hca72f7f_7
libbrotlidec              1.0.9                hca72f7f_7
libbrotlienc              1.0.9                hca72f7f_7
libclang                  12.0.0          default_hbc2896b_2
libcxx                    14.0.6               h9765a3e_0
libdeflate                1.8                  h9ed2024_5
libedit                   3.1.20210910         hca72f7f_0
libffi                    3.3                  hb1e8313_2
libgfortran               3.0.1                h93005f0_2
libiconv                  1.16                 hca72f7f_2
libllvm12                 12.0.0               h9b2ccf5_3
libpng                    1.6.37               ha441bb4_0
libpq                     12.9                 h1c9f633_3
libsodium                 1.0.18               h1de35cc_0
libtiff                   4.4.0                h2ef1027_0
libwebp                   1.2.2                h56c3ce4_0
libwebp-base              1.2.2                hca72f7f_0
libxml2                   2.9.14               hbf8cd5e_0
libxslt                   1.1.35               h5b33f42_0
llvm-openmp               14.0.6               h0dcd299_0
lz4-c                     1.9.3                h23ab428_1
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1            py39hca72f7f_0
matplotlib                3.5.2            py39hecd8cb5_0
matplotlib-base           3.5.2            py39hfb0c5b7_0
matplotlib-inline         0.1.6            py39hecd8cb5_0
mistune                   0.8.4           py39h9ed2024_1000
mkl                       2021.4.0           hecd8cb5_637
mkl-service               2.4.0            py39h9ed2024_0
mkl_fft                   1.3.1            py39h4ab4a9b_0
mkl_random                1.2.2            py39hb2f4e1b_0
munkres                   1.1.4                      py_0
murmurhash                1.0.7            py39he9d5cce_0
nbclassic                 0.3.5              pyhd3eb1b0_0
nbclient                  0.5.13           py39hecd8cb5_0
nbconvert                 6.4.4            py39hecd8cb5_0
nbformat                  5.3.0            py39hecd8cb5_0
ncurses                   6.3                  hca72f7f_3
nest-asyncio              1.5.5            py39hecd8cb5_0
ninja                     1.10.2               hecd8cb5_5
ninja-base                1.10.2               haf03e11_5
nltk                      3.7                pyhd3eb1b0_0
notebook                  6.4.12           py39hecd8cb5_0
nspr                      4.33                 he9d5cce_0
nss                       3.74                 h47edf6a_0
numexpr                   2.8.3            py39h2e5f0a9_0
numpy                     1.23.1           py39h2e5f0a9_0
numpy-base                1.23.1           py39h3b1a694_0
oauthlib                  3.2.1                    pypi_0    pypi
openssl                   1.1.1q               hca72f7f_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.3            py39he9d5cce_0
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathy                     0.6.1            py39hecd8cb5_0
pcre                      8.45                 h23ab428_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.2.0            py39hde71d04_1
pip                       22.1.2           py39hecd8cb5_0
ply                       3.11             py39hecd8cb5_0
preshed                   3.0.6            py39he9d5cce_0
prometheus_client         0.14.1           py39hecd8cb5_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
prompt_toolkit            3.0.20               hd3eb1b0_0
protobuf                  3.19.5                   pypi_0    pypi
psutil                    5.9.0            py39hca72f7f_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pydantic                  1.9.0            py39hca72f7f_1
pygments                  2.11.2             pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py39hecd8cb5_0
pyqt                      5.15.7           py39he9d5cce_0
pyqt5-sip                 12.11.0          py39he9d5cce_0
pyrsistent                0.18.0           py39hca72f7f_0
pysocks                   1.7.1            py39hecd8cb5_0
python                    3.9.13               hdfd78df_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39hecd8cb5_0
python-slugify            6.1.2                    pypi_0    pypi
pytorch                   1.10.2          cpu_py39h903acac_0
pytorch-mutex             1.0                         cpu    pytorch-nightly
pytz                      2022.1           py39hecd8cb5_0
pyzmq                     23.2.0           py39he9d5cce_0
qt-main                   5.15.2               h719ae48_7
qt-webengine              5.15.9               h90a370e_4
qtconsole                 5.3.2            py39hecd8cb5_0
qtpy                      2.2.0            py39hecd8cb5_0
qtwebkit                  5.212                h24dc246_4
readline                  8.1.2                hca72f7f_1
regex                     2022.7.9         py39hca72f7f_0
requests                  2.28.1           py39hecd8cb5_0
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.1.1            py39he9d5cce_0
scipy                     1.7.1            py39h88652d9_2
seaborn                   0.11.2             pyhd3eb1b0_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                63.4.1           py39hecd8cb5_0
shellingham               1.3.1              pyhd3eb1b0_0
sip                       6.6.2            py39he9d5cce_0
six                       1.16.0             pyhd3eb1b0_1
smart_open                5.2.1            py39hecd8cb5_0
sniffio                   1.2.0            py39hecd8cb5_1
soupsieve                 2.3.1              pyhd3eb1b0_0
spacy                     3.3.1            py39hc29d2bd_0
spacy-legacy              3.0.9            py39hecd8cb5_0
spacy-loggers             1.0.1              pyhd3eb1b0_0
sqlite                    3.39.2               h707629a_0
srsly                     2.4.3            py39he9d5cce_0
stack_data                0.2.0              pyhd3eb1b0_0
tb-nightly                2.11.0a20220913          pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.13.1           py39hecd8cb5_0
testpath                  0.6.0            py39hecd8cb5_0
text-unidecode            1.3                      pypi_0    pypi
thinc                     8.0.15           py39hc29d2bd_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.12               h5d9f67b_0
toml                      0.10.2             pyhd3eb1b0_0
torchvision               0.11.3          cpu_py39h9dcb939_0
tornado                   6.2              py39hca72f7f_0
tqdm                      4.64.0           py39hecd8cb5_0
traitlets                 5.1.1              pyhd3eb1b0_0
typer                     0.4.1            py39hecd8cb5_0
typing-extensions         4.3.0            py39hecd8cb5_0
typing_extensions         4.3.0            py39hecd8cb5_0
tzdata                    2022c                h04d1e81_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.11          py39hecd8cb5_0
wasabi                    0.9.1            py39hecd8cb5_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39hecd8cb5_1
websocket-client          0.58.0           py39hecd8cb5_4
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        4.0.3                    pypi_0    pypi
xz                        5.2.5                hca72f7f_1
zeromq                    4.3.4                h23ab428_0
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h4dc903c_3
zstd                      1.5.2                hcb37349_0
```

Env config:
```name: dml-m1-p39
channels:
- defaults
- pytorch-nightly
dependencies:
- python=3.9
- pytorch=1.10.1
- torchvision
- cpuonly
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- nltk
- h5py
- spacy
- unidecode
- pip:
  - future
  - tb-nightly
  - gym
  - pillow
  - kaggle
  - ipywidgets```

**Comment by kev-zheng** [comment]
I can reproduce this when using the `pytorch` conda channel, but not `conda-forge`.

## Successful example
1. `conda install -c conda-forge python==3.8.6 numpy==1.22.4 pytorch-lightning=1.7.6`
2. `python -c "import numpy; import torch"` works :)
```
lt-repro ❯ python -m torch.utils.collect_env                                                                                                                      ✘ 130
Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:22:12)  [Clang 11.0.1 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.12.1
[pip3] torchmetrics==0.9.3
[conda] mkl                       2022.1.0           h860c996_928    conda-forge
[conda] numpy                     1.22.4           py38h3ad0702_0    conda-forge
[conda] pytorch                   1.12.1          cpu_py38h03065b0_0    conda-forge
[conda] pytorch-lightning         1.7.6              pyhd8ed1ab_0    conda-forge
[conda] torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge

```

## Failure example
1. conda install -c pytorch -c conda-forge python==3.8.6 numpy==1.22.4 pytorch-lightning=1.7.6 pytorch==1.12.1
2. Error
```
lt-repro-2 ❯ python -c "import numpy; import torch"                                                                                                               ✘ 130
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
[1]    7150 abort      python -c "import numpy; import torch"
```

```
lt-repro-2 ❯ python -m torch.utils.collect_env                                                                                                                    ✘ 130
Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:22:12)  [Clang 11.0.1 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.12.1
[pip3] torchmetrics==0.9.3
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0              16_osx64_mkl    conda-forge
[conda] libblas                   3.9.0              16_osx64_mkl    conda-forge
[conda] libcblas                  3.9.0              16_osx64_mkl    conda-forge
[conda] liblapack                 3.9.0              16_osx64_mkl    conda-forge
[conda] liblapacke                3.9.0              16_osx64_mkl    conda-forge
[conda] mkl                       2022.1.0           h860c996_928    conda-forge
[conda] mkl-devel                 2022.1.0           h694c41f_929    conda-forge
[conda] mkl-include               2022.1.0           h6bab518_928    conda-forge
[conda] numpy                     1.22.4           py38h3ad0702_0    conda-forge
[conda] pytorch                   1.12.1                  py3.8_0    pytorch
[conda] pytorch-lightning         1.7.6              pyhd8ed1ab_0    conda-forge
[conda] torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge

```

**Comment by atalman** [comment]
This issue should be fixed in pytorch-nighly by this PR: https://github.com/pytorch/builder/pull/1139
Please use following install: conda install pytorch torchvision torchaudio -c pytorch-nightly

**Comment by brownbaerchen** [comment]
I am still having the same issue. The nightly version is also not working...
