### ISSUE TITLE
Pytorch fails to compile on Intel Mac

### ISSUE THREAD

**Issue by singingwolfboy** [pytorch/pytorch#85956]
### 🐛 Describe the bug

Pytorch fails to compile on Intel Mac computers. [See this traceback in the Homebrew repo for a full traceback with error messages.](https://github.com/Homebrew/homebrew-core/pull/111718) I believe that this error started occurring with the release of LLVM 14 (macOS Command Line Tools version 2395). When running `cmake`, we get the following error messages:

```
 [ 20%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o
  cd /tmp/libtorch-20220926-10919-1nu5egq/build/confu-deps/XNNPACK && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DCPUINFO_SUPPORTED_PLATFORM=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_JIT=0 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/XNNPACK/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/XNNPACK/src -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/cpuinfo/deps/clog/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/cpuinfo/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/pthreadpool/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/FXdiv/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/FP16/include -isystem /tmp/libtorch-20220926-10919-1nu5egq/third_party/gemmlowp -isystem /tmp/libtorch-20220926-10919-1nu5egq/third_party/neon2sse -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -fPIC -std=gnu99  -fno-math-errno  -mavx  -O2  -MD -MT confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o -MF CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o.d -o CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o -c /tmp/libtorch-20220926-10919-1nu5egq/third_party/XNNPACK/src/f32-vlrelu/gen/vlrelu-avx-x16.c
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:14:7: error: unknown use of instruction mnemonic without a size suffix
        "mov r14, %[gp]\t\n"
        ^
  <inline asm>:1:2: note: instantiated into assembly here
          mov r14, -48(%rbp)      
          ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:22:8: error: brackets expression not supported on this target
        "mov r8, [r14 + 0]\t\n"
         ^
  <inline asm>:2:9: note: instantiated into assembly here
  mov r8, [r14 + 0]       
          ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:23:8: error: ambiguous instructions require an explicit suffix (could be 'decb', 'decw', 'decl', or 'decq')
        "dec r8\t\n"
         ^
  <inline asm>:3:1: note: instantiated into assembly here
  dec r8  
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:25:8: error: brackets expression not supported on this target
        "mov r9, [r14 + 8]\t\n"
         ^
  <inline asm>:4:9: note: instantiated into assembly here
  mov r9, [r14 + 8]       
          ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:27:8: error: brackets expression not supported on this target
        "mov r10, [r14 + 16]\t\n"
         ^
  <inline asm>:5:10: note: instantiated into assembly here
  mov r10, [r14 + 16]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:29:8: error: brackets expression not supported on this target
        "lea r15, [r14 + 24]\t\n"
         ^
  <inline asm>:6:10: note: instantiated into assembly here
  lea r15, [r14 + 24]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:31:8: error: brackets expression not supported on this target
        "mov r12, [r14 + 32]\t\n"
         ^
  <inline asm>:7:10: note: instantiated into assembly here
  mov r12, [r14 + 32]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:33:8: error: brackets expression not supported on this target
        "mov r13, [r14 + 40]\t\n"
         ^
  <inline asm>:8:10: note: instantiated into assembly here
  mov r13, [r14 + 40]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:35:8: error: brackets expression not supported on this target
        "mov rdi, [r14 + 48]\t\n"
         ^
  <inline asm>:9:10: note: instantiated into assembly here
  mov rdi, [r14 + 48]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:37:8: error: brackets expression not supported on this target
        "mov rsi, [r14 + 56]\t\n"
         ^
  <inline asm>:10:10: note: instantiated into assembly here
  mov rsi, [r14 + 56]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:40:8: error: unknown use of instruction mnemonic without a size suffix
        "mov rax, r9\t\n"
         ^
  <inline asm>:11:1: note: instantiated into assembly here
  mov rax, r9     
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:41:8: error: unknown use of instruction mnemonic without a size suffix
        "mov rcx, r12\t\n"
         ^
  <inline asm>:12:1: note: instantiated into assembly here
  mov rcx, r12    
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:43:8: error: unknown use of instruction mnemonic without a size suffix
        "xor ebx, ebx\t\n"
         ^
  <inline asm>:13:1: note: instantiated into assembly here
  xor ebx, ebx    
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:45:8: error: unknown use of instruction mnemonic without a size suffix
        "mov r14, r8\t\n"
         ^
  <inline asm>:15:1: note: instantiated into assembly here
  mov r14, r8     
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:46:8: error: unexpected token in argument list
        "vbroadcastss zmm31,DWORD PTR [r15]\t\n"
         ^
  <inline asm>:16:26: note: instantiated into assembly here
  vbroadcastss zmm31,DWORD PTR [r15]      
                           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:47:8: error: unexpected token in argument list
        "vcvtph2ps zmm3,YMMWORD PTR [r10 + 0]\t\n"
         ^
  <inline asm>:17:24: note: instantiated into assembly here
  vcvtph2ps zmm3,YMMWORD PTR [r10 + 0]    
                         ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:48:8: error: unexpected token in argument list
        "vcvtph2ps zmm4,YMMWORD PTR [r10 + 32]\t\n"
         ^
  <inline asm>:18:24: note: instantiated into assembly here
  vcvtph2ps zmm4,YMMWORD PTR [r10 + 32]   
                         ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:49:8: error: invalid operand for instruction
        "vxorps xmm0, xmm0, xmm0\t\n"
         ^
  <inline asm>:19:14: note: instantiated into assembly here
  vxorps xmm0, xmm0, xmm0 
               ^~~~~
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:50:8: error: invalid operand for instruction
        "vcomiss xmm31, xmm0\t\n"
         ^
  <inline asm>:20:16: note: instantiated into assembly here
  vcomiss xmm31, xmm0     
                 ^~~~
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
```

### Versions

This is when trying to compile the latest stable Pytorch: version 1.12.1, Git commit 664058fa83f1d8eede5d66418abff6e20bd76ca8.

cc @malfet @seemethere @albanD

**Comment by malfet** [comment]
I wonder fi this needs to be moved to [fbgemm](https://github.com/pytorch/FBGEMM) but let me check a bit later

**Comment by yuguo68** [comment]
facing the same issue on trunk, `clang --version Apple clang version 14.0.0 (clang-1400.0.29.102) Target: x86_64-apple-darwin21.6.0`

**Comment by malfet** [comment]
This has been fixed on fbgemm side by https://github.com/pytorch/FBGEMM/pull/1254

**Comment by malfet** [comment]
@singingwolfboy can you please confirm that issues is indeed addressed?

**Comment by singingwolfboy** [comment]
It appears that the issue still persists, unfortunately. You can see in [this pull request](https://github.com/Homebrew/homebrew-core/pull/111889) that I tried to backport this fix to the 1.12.1 release, but it still fails to build on CI. Interestingly, the error message is _almost_ identical, but not _quite_ identical; the old error message refers to the file `third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc`, while the new error message refers to the file `third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc`.

Any other ideas for why this might be happening?

**Comment by rlanday** [comment]
I think this issue should be reopened? I just tried building master on an Intel Mac (with Apple clang version 14.0.3) and got errors in these files (not necessarily an exhaustive list, since the build stopped):

- FbgemmFP16UKernelsAvx2.cc
- FbgemmFP16UKernelsAvx512.cc
- FbgemmFP16UKernelsAvx512_256.cc

Interestingly, clang seems to be getting tripped up on the “fixed” codepath from https://github.com/pytorch/FBGEMM/pull/1254:

```
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:16:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:188:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:386:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:548:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:729:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:929:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
6 errors generated.
```

**Comment by rlanday** [comment]
This appears to have been fixed in https://github.com/pytorch/FBGEMM/pull/1648

so the FBGEMM dependency needs to be updated.
