### ISSUE TITLE
linspace error with device='cuda' option

### ISSUE THREAD

**Issue by awaelchli** [pytorch/pytorch#8786]
Hello,
Using `torch.linspace` with the `device='cuda'` option gives an error.

## Code example
```
import torch
x = torch.linspace(-1, 1, 10, device='cuda')
```
Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: _linspace is not implemented for type torch.cuda.FloatTensor
```

## System Info
- PyTorch installed with pip
- PyTorch version: 0.4
- Python version: 3.6
- CUDA/cuDNN version: 8.0

**Comment by vishwakftw** [comment]
This is related to #1070 .

**Comment by GANWANSHUI** [comment]
Hi, how to Add CUDA to logspace and linspace declarations in Declarations.cwrap specifically

**Comment by SsnL** [comment]
@GANWANSHUI it has been fixed already.

**Comment by GANWANSHUI** [comment]
the problem still came out since I need to use the 0.41 version of the torch, what should I do then?

**Comment by GANWANSHUI** [comment]
@SsnL  sorry, I am really new to the problem, I don't know how to operate like ' build at a commit after that patch ', was there an example to refer? thanks for your reply!

**Comment by SsnL** [comment]
@GANWANSHUI Checkout that commit in your local copy of this repo and follow the instructions in README.md.

**Comment by GANWANSHUI** [comment]
@SsnL  Thank you, I use the replace torch.linspace by torch.arange for compromise, hope no more errors!
