### ISSUE TITLE
Fatal error: THC/THC.h: no such file or directory

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#8790]
## Issue description

I am trying to build from source with NO_DISTRIBUTED=1, and this error appears and the build is terminated. [Here](https://gist.github.com/vishwakftw/cf8d17f1e8dd50866488df9bdb4ca175) is the complete compilation log.

This occurred with a fresh clone of my fork https://github.com/vishwakftw/pytorch

## System Info
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py build develop
- OS: Ubuntu 16.04.2
- Python version: 3.6.5 (Miniconda)
- CUDA/cuDNN version: 8.0.44
- GPU models and configuration: GeForce 940M
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.11.3

**Comment by vishwakftw** [comment]
Attempting to install without NO_DISTRIBUTED=1 leads to this error 

```
CMake Error at /media/vishwak/Official/Projects/pytorch/cmake/Modules_CUDA_fix/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUDA (missing: CUDA_NVCC_EXECUTABLE)
```

Full log [here](https://gist.github.com/vishwakftw/cae09ec524caa523fdd5574d49a31914) .

**Comment by zou3519** [comment]
I think I'm seeing the same thing as you @vishwakftw, will let you know if I figure out what's up...

**Comment by zou3519** [comment]
Seems related: #8781

**Comment by vishwakftw** [comment]
Perhaps, that seems related to the comment but not the main issue.

**Comment by SsnL** [comment]
looks like that we are installing c10d when `NO_DISTRIBUTED=1`. cc @pietern  @teng-li

**Comment by zou3519** [comment]
@vishwakftw Could you try `export CUDA_NVCC_EXECUTABLE=$(which nvcc)` and then building? (It didn't work for me, but I'm wondering if it'll work for you)

**Comment by vishwakftw** [comment]
@zou3519 your solution seems to work. Also, there seems to some fix done in current master, so the export is actually not required.

Thanks @zou3519

**Comment by SsnL** [comment]
reopen as we should fix this. cause: this line sets `CUDA_NVCC_EXECUTABLE` to empty if it was previously unset:
https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.sh#L229

**Comment by vishwakftw** [comment]
`export CUDA_NVCC_EXECUTABLE=$(which nvcc)` is done earlier, why is this reset in the line you have referenced?

**Comment by vishwakftw** [comment]
@SsnL @zou3519 The build is not fixed. It was an error on my part. @zou3519 's solution only seems to work.

**Comment by vishwakftw** [comment]
@SsnL I have fixed it locally. I had to modify `build_pytorch_libs.sh` to get it working. Can I send in a PR?

**Comment by zou3519** [comment]
Please do!
