### ISSUE TITLE
CylicLR is unpickle-able due to WeakMethod defined in `_scale_fn_ref` attribute

### ISSUE THREAD

**Issue by kian-kd** [pytorch/pytorch#88684]
### 🐛 Describe the bug

We cannot pickle (or torch.save) instances of the CylicLR scheduler due to the introduction of the WeakMethod in [#85462](https://github.com/pytorch/pytorch/pull/85462).

```
import torch
import tempfile

model = torch.nn.Linear(3, 1)
optimizer = torch.optim.RMSprop(model.parameters(), lr=0.1)
lr = torch.optim.lr_scheduler.CyclicLR(optimizer, 0.1, 1.0)

tmp = tempfile.NamedTemporaryFile()
with open(tmp.name, 'wb') as f:
    torch.save(lr.state_dict(), f)
```

I get the following error with version 1.13.0 (but there is no error in version 1.12):
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [2], line 10
      8 tmp = tempfile.NamedTemporaryFile()
      9 with open(tmp.name, 'wb') as f:
---> 10     torch.save(lr.state_dict(), f)

File ~/.pyenv/versions/3.9.7/envs/rxrx/lib/python3.9/site-packages/torch/serialization.py:423, in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    421 if _use_new_zipfile_serialization:
    422     with _open_zipfile_writer(f) as opened_zipfile:
--> 423         _save(obj, opened_zipfile, pickle_module, pickle_protocol)
    424         return
    425 else:

File ~/.pyenv/versions/3.9.7/envs/rxrx/lib/python3.9/site-packages/torch/serialization.py:635, in _save(obj, zip_file, pickle_module, pickle_protocol)
    633 pickler = pickle_module.Pickler(data_buf, protocol=pickle_protocol)
    634 pickler.persistent_id = persistent_id
--> 635 pickler.dump(obj)
    636 data_value = data_buf.getvalue()
    637 zip_file.write_record('data.pkl', data_value, len(data_value))

TypeError: cannot pickle 'WeakMethod' object
```

### Versions

PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.7 (default, Jul 25 2022, 15:08:16)  [Clang 13.0.0 (clang-1300.0.27.3)] (64-bit runtime)
Python platform: macOS-12.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.7.7
[pip3] torch==1.13.0
[pip3] torchmetrics==0.10.0
[pip3] torchvision==0.13.0
[conda] Could not collect

**Comment by kian-kd** [comment]
Further evidence, same error when just trying to save the specific key:

```
import torch
import tempfile

model = torch.nn.Linear(3, 1)
optimizer = torch.optim.RMSprop(model.parameters(), lr=0.1)
lr = torch.optim.lr_scheduler.CyclicLR(optimizer, 0.1, 1.0)

tmp = tempfile.NamedTemporaryFile()
with open(tmp.name, 'wb') as f:
    state_dict = lr.state_dict()
    print(state_dict["_scale_fn_ref"])
    torch.save(state_dict["_scale_fn_ref"], f)
```

Yields:
```
<weakref at 0x127e42660; to 'CyclicLR' at 0x107c02550>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [3], line 12
     10 state_dict = lr.state_dict()
     11 print(state_dict["_scale_fn_ref"])
---> 12 torch.save(state_dict["_scale_fn_ref"], f)

File ~/.pyenv/versions/3.9.7/envs/rxrx/lib/python3.9/site-packages/torch/serialization.py:423, in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    421 if _use_new_zipfile_serialization:
    422     with _open_zipfile_writer(f) as opened_zipfile:
--> 423         _save(obj, opened_zipfile, pickle_module, pickle_protocol)
    424         return
    425 else:

File ~/.pyenv/versions/3.9.7/envs/rxrx/lib/python3.9/site-packages/torch/serialization.py:635, in _save(obj, zip_file, pickle_module, pickle_protocol)
    633 pickler = pickle_module.Pickler(data_buf, protocol=pickle_protocol)
    634 pickler.persistent_id = persistent_id
--> 635 pickler.dump(obj)
    636 data_value = data_buf.getvalue()
    637 zip_file.write_record('data.pkl', data_value, len(data_value))

TypeError: cannot pickle 'WeakMethod' object
```

**Comment by kian-kd** [comment]
Other users may find this work-around solution helpful, though it isn't ideal it does enable successful pickling. Note that you must edit the object attributes directly - just modifying the state-dict will not be enough because it will still reference the object (which contains the weak ref).

```
import torch
import tempfile

model = torch.nn.Linear(3, 1)
optimizer = torch.optim.RMSprop(model.parameters(), lr=0.1)

# no custom scale function so it'll use WeakMethod by default
lr = torch.optim.lr_scheduler.CyclicLR(optimizer, 0.1, 1.0)

# instantiate the WeakMethod in the lr scheduler object into the custom scale function attribute
lr._scale_fn_custom = lr._scale_fn_ref()

# remove the reference so there are no more WeakMethod references in the object
lr._scale_fn_ref = None

# now we can successfully pickle the lr scheduler
tmp = tempfile.NamedTemporaryFile()
with open(tmp.name, 'wb') as f:
    state_dict = lr.state_dict()
    torch.save(state_dict, f)
```

**Comment by albanD** [comment]
Hi!
Thanks for reporting this.
I am not sure why WeakMethods are used there tbh (I don't think this assignment would trigger a refcycle).

We would accept a PR that refactors this code to not need the weak method.

**Comment by Augus1999** [comment]
> Other users may find this work-around solution helpful, though it isn't ideal it does enable successful pickling. Note that you must edit the object attributes directly - just modifying the state-dict will not be enough because it will still reference the object (which contains the weak ref).
> 
> ```
> import torch
> import tempfile
> 
> model = torch.nn.Linear(3, 1)
> optimizer = torch.optim.RMSprop(model.parameters(), lr=0.1)
> 
> # no custom scale function so it'll use WeakMethod by default
> lr = torch.optim.lr_scheduler.CyclicLR(optimizer, 0.1, 1.0)
> 
> # instantiate the WeakMethod in the lr scheduler object into the custom scale function attribute
> lr._scale_fn_custom = lr._scale_fn_ref()
> 
> # remove the reference so there are no more WeakMethod references in the object
> lr._scale_fn_ref = None
> 
> # now we can successfully pickle the lr scheduler
> tmp = tempfile.NamedTemporaryFile()
> with open(tmp.name, 'wb') as f:
>     state_dict = lr.state_dict()
>     torch.save(state_dict, f)
> ```

Thank you for this solution. It really helps.

**Comment by ptrblck** [comment]
Also reported in [the discussion board](https://discuss.pytorch.org/t/torch-save-cause-typeerror-cannot-picke-weakmethod-object/166884/3?u=ptrblck).

**Comment by aheba** [comment]
Hello @ptrblck , same issue from my side when switching from 1.12.1 to 1.13.1;
Just mention the PR where it was solved:
https://github.com/pytorch/pytorch/pull/91400

**Comment by albanD** [comment]
It will be fixed in the upcoming 2.0 release!

**Comment by jkang1640** [comment]
> It will be fixed in the upcoming 2.0 release!

Is this fixed? I still have the same problem for torch 2.0.0

**Comment by albanD** [comment]
@jkang1640 this particular issue was fixed.
If you see similar problems, could you open a new issue with a repro and detailed environment info please?

**Comment by patelhrishi** [comment]
This is still not working on 1.13.x version. There are still some places where 2.0 is not supported yet ex. AWS neuron sdk. 
It would be great to get it fixed on 1.13

**Comment by hrishikeshpatel** [comment]
It is not resolved on torch 1.13.x version. There are still some places where 2.0 is not supported yet ex. AWS neuron sdk. It would be great to get it fixed on 1.13
TIA
