### ISSUE TITLE
Always get error "ConnectionResetError: [Errno 104] Connection reset by peer"

### ISSUE THREAD

**Issue by Mabinogiysk** [pytorch/pytorch#9127]
## Issue description
I found someone had reported this error and could not reproduce it. However I always get this error during my training. When I get this error, the code is still running, so I  continue  to get this problem. It seems that it has no effect on training.

## Code example
```
train_dataset = lmdbDataset(root=opt.trainroot, transform=resizeNormalize(size=(592, 32)))
train_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=opt.batchSize,
    shuffle=True, sampler=None,
    num_workers=int(opt.workers),
    collate_fn=alignCollate())
train_iter = iter(train_loader)
cpu_images, cpu_texts, cpu_lengths = next(train_iter)
```
ERROR message:
```
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fec6928a9b0>>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
                         self._shutdown_workers()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
                         self.worker_result_queue.get()
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
  turn _ForkingPickler.loads(res)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
                         fd = df.detach()
  File "/root/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
  turn reduction.recv_handle(conn)
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
  turn recvfds(s, 1)[0]
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 155, in recvfds
raise EOFError
EOFError:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get  
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 155, in recvfds
    raise EOFError
EOFError:
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fec6928a9b0>>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 155, in recvfds
    raise EOFError
EOFError:
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fec6928a9b0>>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
                         self._shutdown_workers()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
                         self.worker_result_queue.get()
  File "/root/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
  turn _ForkingPickler.loads(res)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
                         fd = df.detach()
  File "/root/anaconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
  turn reduction.recv_handle(conn)
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
  turn recvfds(s, 1)[0]
  File "/root/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 155, in recvfds
raise EOFError
EOFError:
```

## System Info
- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: centos 7
- PyTorch version: 0.4.0
- Python version: 3.6
- CUDA/cuDNN version: cuda9.0/cudnn7.0

**Comment by engharat** [comment]
I have the same issue and I do not understand what is causing it. it appears every time I run a training, but the training itself seems to go okey, the warning seems to not produce any noticeable effect.

**Comment by Mabinogiysk** [comment]
I found this error has a serious effect on my training. I got garbled in labels.
Some useful information: 
https://github.com/pytorch/pytorch/issues/1551
https://discuss.pytorch.org/t/using-torch-tensor-over-multiprocessing-queue-process-fails/2847/6

**Comment by kl2792** [comment]
+1 get this error too. Not sure if it's corrupting my training data or not.

**Comment by SsnL** [comment]
This has been fixed by #10366 . Thanks for reporting.

**Comment by udion** [comment]
@SsnL I installed pytorch in new virtual environment today using pip, I'm still getting the error (pytorch 0.4.1, followed instructions as given in pytorch landing page)

**Comment by SsnL** [comment]
@udion The fix is not in a release yet.

**Comment by udion** [comment]
@SsnL Oh!
So I need to build from source? is it going to be out soon?

**Comment by SsnL** [comment]
@udion The error doesn't mean anything and can be ignored anyways...

**Comment by udion** [comment]
@SsnL is there a way to suppress it? It's disturbing me psychologically :P

**Comment by SsnL** [comment]
:) Switch to using nightlies once #11985 is merged would be one option; and building from source would also work. But other than those, unfortunately no, unless you change the source code in your install... Sorry about it.

**Comment by EthanZhangYi** [comment]
@SsnL 
I am using pytorch 0.4.0 and I meet this error frequently. I find that there are three PRs related to this dataloader bug: #10366 #11985 #12011 .  Is there a way to easily fix it in 0.4.0? Since there is a big difference between 0.4.0 and current master branch, I do not want to build from the source of master.
If I manually merge the two changed files of #10366 into 0.4.0, is it OK?

**Comment by SsnL** [comment]
@EthanZhangYi That alone may be fine (not entirely sure if this is fixed in that PR). But you should really also merge #11985 (the cpp change can be ignored) and maybe #12700 since there are still bugs with just #10366 ).

**Comment by EthanZhangYi** [comment]
@SsnL  Got it. Thanks for your reply. I will try to merge all *.py changed in #10366 #11985 #12700

**Comment by EthanZhangYi** [comment]
@SsnL  Thanks again. After merging `torch/_six.py` and `torch/utils/data/dataloader.py` of `master-034c96` (#10366 #11985 #12700) into v0.4.0, this error is fixed.

**Comment by SsnL** [comment]
Great to hear! @EthanZhangYi

**Comment by zanghu** [comment]
> @SsnL Thanks again. After merging `torch/_six.py` and `torch/utils/data/dataloader.py` of `master-034c96` (#10366 #11985 #12700) into v0.4.0, this error is fixed.

also works in v0.4.1 , thanks a lot~

**Comment by lonce** [comment]
I still see it regularly in v0.4.1

**Comment by liluxuan1997** [comment]
> @SsnL Thanks again. After merging `torch/_six.py` and `torch/utils/data/dataloader.py` of `master-034c96` (#10366 #11985 #12700) into v0.4.0, this error is fixed.

I try to merge 'torch/_six.py' but I didn't find 'torch/_six.py' changed in pull request #10366 #11985 #12700 ?

**Comment by EthanZhangYi** [comment]
@lonce This bug is fixed in the master branch, not included in v0.4.1.
You can directly checkout this commit 034c969f3c41efef75474f08bb09d29e91a20c19, and copy `torch/_six.py` and `torch/utils/data/dataloader.py` into v0.4.1 and do a replacement.

**Comment by voletiv** [comment]
Does this bug persist in 1.0.0 and 1.0.1? Do we need to merge these files in those versions as well?

**Comment by soumith** [comment]
@voletiv the patch has been part of 1.0.0 and 1.0.1, so the bug shouldn't be present.

**Comment by Tiger1994** [comment]
for me, I found set thread number equal 0 will solve this problem, namely:
num_workers=0

**Comment by Mustenaka** [comment]
I also meet this question:
that is my code.
`from tensorflow.examples.tutorials.mnist import input_data

print("Begin of file")
mnist = input_data.read_data_sets("MNIST_data/",one_hot=True)
print(mnist.train.images.shape)
print("End of file")`


ConnectioResetError:[Errno 104] Connection reset by peer.

**Comment by anbai106** [comment]
This error still repeatedly emerge in the new version of 1.2.0. Setting num_workers=0 is not an optimal workaround... It slows down the process. Strangely, I only got this error for my test data, not training data. Is that possible the error is from my test data itself? Some image has been corrupted, for instance? 
Thanks
