### ISSUE TITLE
[Crash][MKL] `torch.linalg.eigvals` crash with NaN

### ISSUE THREAD

**Issue by ganler** [pytorch/pytorch#93124]
### 🐛 Describe the bug

Crash on latest nightly.

```python
import torch
torch.linalg.eigvals(torch.tensor([[1.1300,    torch.nan], [torch.nan,    torch.nan]]))

"""
Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.

Intel MKL ERROR: Parameter 2 was incorrect on entry to SGEHD2.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SHSEQR.
python: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[1]    1603318 abort (core dumped)  ipython
"""
```

### Versions

```
PyTorch version: 2.0.0.dev20230126+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-136-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230126+cu116
[pip3] torchaudio==2.0.0.dev20230126+cu116
[pip3] torchvision==0.15.0.dev20230126+cu116
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230126+cu116          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230126+cu116          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230126+cu116          pypi_0    pypi
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by ganler** [comment]
It seems it is a bug not thoroughly fixed by https://github.com/pytorch/pytorch/issues/61251 https://github.com/pytorch/pytorch/issues/64671

**Comment by lezcano** [comment]
This is expected. See https://pytorch.org/docs/master/notes/numerical_accuracy.html#linear-algebra-torch-linalg

**Comment by FagonViendra** [comment]
Still reproducible on my side with an all-NaN matrix.

```py
import torch
A = torch.full((4, 4), float("nan"))
torch.linalg.eigvals(A)
````

Result:

```text
Intel oneMKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
SIGSEGV / return code -11
