### ISSUE TITLE
unique() returns 0s for nan values

### ISSUE THREAD

**Issue by asmeurer** [pytorch/pytorch#94106]
### 🐛 Describe the bug

```py
>>> import torch
>>> x = torch.tensor([1, 1, torch.nan, torch.nan])
>>> torch.unique(x, return_counts=True)
(tensor([nan, nan, 1.]), tensor([0, 0, 2]))
```

The `counts` values for `nan` are set to 0, when they should be 1.

Note that this disagrees with NumPy, as well as the array API spec.

### Versions

Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.3 (x86_64)
GCC version: Could not collect
Clang version: 11.1.0
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:55:37)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-12.6.3-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] numpydoc==1.5.0
[pip3] torch==1.13.0
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] mkl                       2022.2.1         h44ed08c_16952    conda-forge
[conda] numpy                     1.23.5           py39hdfa1d0c_0    conda-forge
[conda] numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
[conda] pytorch                   1.13.0          cpu_py39h0a103a1_0    conda-forge
[conda] torch                     1.11.0a0+git5347dab           dev_0    <develop>

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @malfet @albanD

**Comment by malfet** [comment]
Please note that on GPU it works correctly. 
Tentatively grabbing for myself.

**Comment by jiayisunx** [comment]
The CPU implementation uses "std::unordered_set" to create unordered set of elements, but it doesn't treat nan values as the same values, so this issue arises, I'm still working on it, thanks.

**Comment by mingfeima** [comment]
fixed with #94886

**Comment by mingfeima** [comment]
@jiayisunx is this fixed on master ? i remember that you have a PR to fix this.

**Comment by jiayisunx** [comment]
> @jiayisunx is this fixed on master ? i remember that you have a PR to fix this.

No, my understanding was not right before, I need to prepare a new PR to fix this issue.

**Comment by jiayisunx** [comment]
Hi @malfet , I have two doubts about torch.unique:
1. At present, the default behavior of torch.unique and numpy.unique is inconsistent. By default, numpy.unique considers nan values to be equal, but torch.unique does not. Does torch.unique need to be consistent with numpy.unique?
2. What should be the behavior when the parameter ‘sorted’ of torch.unique is set to False, should it keep the original order? The ‘sorted‘ parameter is invalid on the GPU, whether "sorted" is set to true or false the output is always sorted.

**Comment by mingfeima** [comment]
@jiayisunx How about the pytorch CUDA behavior ? I think firstly we should align CPU and CUDA behavior on pytorch.

**Comment by jiayisunx** [comment]
This issue has been fixed on the latest PyTorch. Closing as completed.

**Comment by shahzad-ali** [comment]
> Hi @malfet , I have two doubts about torch.unique:
> 
> 1. At present, the default behavior of torch.unique and numpy.unique is inconsistent. By default, numpy.unique considers nan values to be equal, but torch.unique does not. Does torch.unique need to be consistent with numpy.unique?
> 2. What should be the behavior when the parameter ‘sorted’ of torch.unique is set to False, should it keep the original order? The ‘sorted‘ parameter is invalid on GPU, whether "sorted" is set to True or False the output is always sorted.

I got a chance to upgrade to PyTorch 2.0.1 Stable today and It is confirmed that the first point you highlighted is still not addressed. `torch.unique()` is still treating the duplicate `nan` values as unique which is different than `numpy.unique()`. May someone please clarify if this is a desired behaviour and the reason behind?

**Comment by malfet** [comment]
@shahzad-ali  Not sure about NumPy reasoning, but because two NaNs are not equal to each other, but two infs are,   i.e. in CPython should return evaluate following statement `x=float('nan');x==x` to False, but `x=float('inf'); x==x` is True, `torch.unique` does not group Nans.

@rgommers do you know what is the reason why NaNs are bucketed together by `np.unique`?

**Comment by rgommers** [comment]
> do you know what is the reason why NaNs are bucketed together by `np.unique`?

It's because it's the most common use case, for regular data analysis as well as for ML workflows and library code. I'll note that there's an `equal_nan=True` keyword in [np.unique](https://numpy.org/devdocs/reference/generated/numpy.unique.html#numpy.unique). If you look for `np.unique` usage in scikit-learn for example, `nan` will mean a missing value and the desired answer is for them to be considered equal.

From a C/C++ numerical computing perspective, `nan`'s have to compare as unequal, but it's less often useful. If you get an answer like in _Output_ above (`[0., 1., inf, nan, nan, nan, nan, ...]`), you'll probably see a next step eliminating all those `nan`'s.

We had long discussions about this topic in the array API standard design. Implementing the not-equal behavior is easier, and if you don't care then that's often what you want as a user for performance reasons (especially on GPU). However, if you do care about the unique values returned, you want the more useful is-equal behavior. Hence numpy has both.
