### ISSUE TITLE
[bug] Multiplication of tensor with numpy scalar does not always work

### ISSUE THREAD

**Issue by krishnap25** [pytorch/pytorch#9468]
Thanks for the amazing software. I stumbled across (what I believe is a) bug when multiplying a torch tensor with a numpy scalar. 

## Issue description

Multiplication of a torch tensor with numpy scalars exhibits unexpected behavior depending on the order of multiplication and datatypes. Specifically, multiplication of torch.FloatTensor with np.float32 does not work. Multiplication of torch.FloatTensor with np.float64 only works when written as `tensor * scalar` when tensor.requires_grad = True.

### Trial 1: right multiplication with np.float64: the only setting that works:
```python
tensor = torch.ones(2, requires_grad=True, dtype=torch.float32)
scalar = np.float64(2.0)
prod = tensor * scalar
print(prod, prod.requires_grad, prod.dtype)
```
The output is:
```
tensor([ 2.,  2.]) True torch.float32
```

### Trial 2: left multiplication with np.float64: does not work when tensor.requires_grad=True
```python
tensor = torch.ones(2, requires_grad=True, dtype=torch.float32)
scalar = np.float64(2.0)
prod = scalar * tensor
print(prod, prod.requires_grad, prod.dtype)
```
The error message is:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-58039673906b> in <module>()
      1 tensor = torch.ones(2, requires_grad=True, dtype=torch.float32)
      2 scalar = np.float64(2.0)
----> 3 prod = scalar * tensor
      4 print(prod, prod.requires_grad, prod.dtype)

~/software/anaconda3/envs/pyt4/lib/python3.6/site-packages/torch/tensor.py in __array__(self, dtype)
    374     def __array__(self, dtype=None):
    375         if dtype is None:
--> 376             return self.cpu().numpy()
    377         else:
    378             return self.cpu().numpy().astype(dtype, copy=False)

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
```
### Trial 3: right multiplication with np.float32: does not work:
```python
tensor = torch.ones(2, requires_grad=True, dtype=torch.float32)
scalar = np.float32(2.0)
prod = tensor * scalar
print(prod, prod.requires_grad, prod.dtype)
```
The error message is:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-1eb8188d0e28> in <module>()
      1 tensor = torch.ones(2, requires_grad=True, dtype=torch.float32)
      2 scalar = np.float32(2.0)
----> 3 prod = tensor * scalar
      4 print(prod, prod.requires_grad, prod.dtype)

TypeError: mul() received an invalid combination of arguments - got (numpy.float32), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (!numpy.float32!)
 * (float other)
      didn't match because some of the arguments have invalid types: (!numpy.float32!)
```

### Trial 4: left multiplication with np.float32: does not work when tensor.requires_grad=True
```python
tensor = torch.ones(2, requires_grad=True, dtype=torch.float32)
scalar = np.float32(2.0)
prod = scalar * tensor
print(prod, prod.requires_grad, prod.dtype)
```
Same error message as Trial 2.

## System Info
```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 17.10
GCC version: (Ubuntu 6.4.0-8ubuntu1) 6.4.0 20171010
CMake version: version 3.9.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp

Nvidia driver version: 390.30
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch
```

**Comment by SsnL** [comment]
reproduced the bug at trial 2 on master

**Comment by t-vi** [comment]
The problem is that the left operand is the default operand to execute the `__mul__`.
The numpy scalar's `__mul__` will then call the tensor's `__array__` and that fails (and there isn't a way out).
The solution seems to be to set a high `__array_priority__`, then the scalar (and an array) will call the Tensor's `__rmul__` instead.
Standard numpy scalars have a strongly negative priority, standard ndarrays have one of 0.
So in case 2:
```
tensor.__array_priority__ = 1000
print (scalar * tensor)
```
works!

I'm happy to send a PR.

**Comment by soumith** [comment]
seems like a good idea. please do send a PR :)

**Comment by t-vi** [comment]
I wonder whether one might allow numpy() for tensors with grad after that. The potential of accidental conversion seems to be much lower (but I won't do that now).

**Comment by t-vi** [comment]
The last two cases are strange an *not* solved by the PR. So even though they both are float32 now (one torch, one numpy), they are not compatible...

**Comment by t-vi** [comment]
To not leave it at idle talk: I tried and it seems to work relatively easily.

**Comment by weiyangfb** [comment]
This issue should be fixed by @t-vi PRs: https://github.com/pytorch/pytorch/pull/9659 and https://github.com/pytorch/pytorch/pull/9651

**Comment by weiyangfb** [comment]
closing via #9659 and #9651

**Comment by maartjeth** [comment]
This issue still seems to exist - I'm getting the same error when multiplying a numpy float64 scalar with at torch.float32 tensor. Changing the order (tensor * scalar instead of scalar * tensor) indeed solves the issue. 

Two other observations: 
1) This behaviour seems to be dependent on the type of GPU / CPU. 
2) This behaviour only shows up in some specific cases (I can't figure out what makes these examples so special).

**Comment by t-vi** [comment]
I'd be willing to reopen this bug or open a new one if you have a repro.
Two ways this could still happen is if either
- the scalar has a high `__array_priority__`, (not the default with numpy scalars and expected if you purposely mess with that),
- the scalar does is not recognized by `PyArray_IsIntegerScalar` nor by `PyArray_IsScalar` (or you compiled PyTorch without NumPy support).
If none of these conditions apply, I'd be very surprised if this still throws errors.

**Comment by maartjeth** [comment]
* `scalar. __array_priority__` = -1000000

How exactly do I check    * `PyArray_IsIntegerScalar` or     * `PyArray_IsScalar`?

**Comment by mruberry** [comment]
The snippet

```
tensor = torch.ones(2, requires_grad=True, dtype=torch.float32)
scalar = np.float64(2.0)
prod = scalar * tensor
print(prod, prod.requires_grad, prod.dtype)
```

which I think corresponds with the last issue mentioned, works as of PyTorch 1.7. Closing this issue. 

If there are other NumPy scalar interop issues with PyTorch tensors please file a new issue with a more recent version of PyTorch.
