### ISSUE TITLE
Add location information when exception are thrown in `torch.jit.annotations.try_ann_to_type`

### ISSUE THREAD

**Issue by FabianSchuetze** [pytorch/pytorch#96420]
### 🚀 The feature, motivation and pitch

The functions `is_tuple`, `is_list`, `is_dict`, `is_optional`, `is_union`, `is_future`  (all in `torch/_jit_internal`) might throw exceptions when called from `try_ann_to_type`. These exception are not very useful. For example, one says:

```
RuntimeError: Attempted to use Dict without contained types. Please add contained type, e.g. Dict[int, int]
```

This exception together with the location information would be much more useful. For example, the location says:

```
(Pdb) print(loc)
SourceRange at:
  File "/home/schuetze/Documents/work/github/prediction_net/multimodal/models/heads/retina_head.py", line 187
    def forward(self, fpn_features: t.Dict, inputs: t.Dict,
                                    ~~~~~~ <--- HERE
                gts: t.Dict = None) -> t.Dict[str, t.Any]:
        """
```

Could we maybe add `location` as an optional parameter to the `is_X` function? Would you be open for a PR in that case? 

### Alternatives

Include location information when throwing the exception. 

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by davidberard98** [comment]
fixed in https://github.com/pytorch/pytorch/pull/96423

**Comment by FabianSchuetze** [comment]
Thanks for the reply, @davidberard98 !

#96423 did not fix the problem above, only the related problem.

#96758 fixes it and I have tried to minimally adjust the `try_to_ann_type` function.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
