### ISSUE TITLE
Conv1d fails with CUDNN 6005 and dilation > 1

### ISSUE THREAD

**Issue by skaae** [pytorch/pytorch#967]
Conv1d with dilation>1 fails after upgrading from cudnn 5105 to  cudnn 6005.
Conv2d works fine. 
```
Traceback (most recent call last):
  File "conv_test.py", line 29, in <module>
    output = m(input)
  File "/home/sorson/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sorson/anaconda3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 143, in forward
    self.padding, self.dilation, self.groups)
  File "/home/sorson/anaconda3/lib/python3.5/site-packages/torch/nn/functional.py", line 61, in conv1d
    return f(input, weight, bias) if bias is not None else f(input, weight)
  File "/home/sorson/anaconda3/lib/python3.5/site-packages/torch/nn/_functions/conv.py", line 35, in forward
    output = self._update_output(input, weight, bias)
  File "/home/sorson/anaconda3/lib/python3.5/site-packages/torch/nn/_functions/conv.py", line 93, in _update_output
    self.groups, cudnn.benchmark)
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

```

```
from torch.autograd import Variable
import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn
print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1)))
cudnn_version = torch.backends.cudnn.version()
print('CUDNN  VERSION', torch.backends.cudnn.version())
for i in range(1,10):
    try:
        m = nn.Conv1d(16, 33, 3, dilation=i).cuda()
        input = Variable(torch.randn(20, 16, 50).cuda())
        output = m(input)
        print('dilation OK    ', i)
    except:
        print('dilation FAILED', i )

for i in range(1,10):
    try:
        m = nn.Conv2d(16, 33, (3, 5), dilation=i)
        input = Variable(torch.randn(20, 16, 50, 100))
        output = m(input)
        print('dilation OK    ', i)
    except:
        print('dilation FAILED', i )

# error
m = nn.Conv1d(16, 33, 3, dilation=i).cuda()
input = Variable(torch.randn(20, 16, 50).cuda())
output = m(input)
```

**Comment by ngimel** [comment]
I can't repro. What GPU are you using? (Though in truth dilated convs should work on any GPU, so the issue is likely something else).

**Comment by skaae** [comment]
Ok. I tried have tried on a Pascal and a Maxwell machine both with cuda 8. 
Both machines fails after i upgraded to cudnn 6005 but runs fine if i change back to cudnn 5105. 
The pascal machine runs ubuntu 16 and the Maxwell machine runs ubuntu 14. 

I'm not very familiar with the codebase, but it seems that cudnn 6005 will use cudnn for dilations? 
Could that be the problem?
https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/conv.py#L81

**Comment by ngimel** [comment]
Here's output and nvprof output from your snippet on GTX 1080 (I've sent 2d convolutions to the GPU, because they were not on the GPU, and changed ranges to range(2,10) to run dilated cases only. Cudnn is used for dilated convs as shown in the profiler output, and no errors are raised. Have you recompiled pytorch after updating to cudnn v6? I believe it is necessary.
``` root@e989a22080c1:/workspace/ALL/playground# nvprof python  conv1d_dilated.py 
==400== NVPROF is profiling process 400, command: python conv1d_dilated.py
True
CUDNN  VERSION 6005
dilation OK     2
dilation OK     3
dilation OK     4
dilation OK     5
dilation OK     6
dilation OK     7
dilation OK     8
dilation OK     9
dilation OK     2
dilation OK     3
dilation OK     4
dilation OK     5
dilation OK     6
dilation OK     7
dilation OK     8
dilation OK     9
==400== Profiling application: python conv1d_dilated.py
==400== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
 46.24%  5.0703ms         7  724.33us  498.86us  1.0062ms  void cudnn::detail::implicit_convolve_sgemm<float, int=1024, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=0>(int, int, int, float const *, int, cudnn::detail::implicit_convolve_sgemm<float, int=1024, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=0>*, float const *, kernel_conv_params, int, float, float, int, float const *, float const *, int, int)
 39.50%  4.3313ms        52  83.295us     640ns  537.52us  [CUDA memcpy HtoD]
  8.87%  973.05us        10  97.305us  12.161us  846.01us  void cudnn::detail::implicit_convolve_sgemm<float, int=128, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=0>(int, int, int, float const *, int, cudnn::detail::implicit_convolve_sgemm<float, int=128, int=5, int=5, int=3, int=3, int=3, int=1, bool=1, bool=0, bool=0>*, float const *, kernel_conv_params, int, float, float, int, float const *, float const *, int, int)
  5.19%  568.81us         8  71.101us  46.945us  98.082us  void add_tensor_kernel_v3<int=2, float, float, int=128, int=1, int=1, int=4, int=2>(cudnnTensorStruct, float*, cudnnTensorStruct, float const *, float, float)
  0.21%  22.657us         9  2.5170us  2.1120us  3.1370us  void add_tensor_kernel_v3<int=2, float, float, int=32, int=1, int=4, int=2, int=2>(cudnnTensorStruct, float*, cudnnTensorStruct, float const *, float, float)
```

**Comment by skaae** [comment]
Everythings works after recompiling using:
```
# build pytorch assuming cudnn 6 is extracted to ~/cuda
git clone https://github.com/pytorch/pytorch.git
cd pytorch
export  WITH_CUDNN=1 
export CUDNN_LIB_DIR=/home/USERNAME/cuda/lib64
export CUDNN_INCLUDE_DIR=/home/USERNAME/cuda/include
pip install -r requirements.txt
python setup.py install
```

Maybe documentation of the `CUDNN_LIB_DIR` and `CUDNN_INCLUDE_DIR` should be added to the readme/docs? 

Thanks for looking into this :)

**Comment by skaae** [comment]
I haven recompiled, so that i propbably the problem. I cant. Find any cudnn
info. Should i compile pytorch from source with cudnn in LD_LIBRARY_PATH?

Thanks for looking into this.

**Comment by apaszke** [comment]
When you run `python setup.py install` you should see some lines that say if numpy, CUDA and cuDNN have been found. Make sure that it's picked up.

**Comment by ngimel** [comment]
It looks like this is due to commit @34ce58c. Pytorch compiled at @c238ee3 runs the following snippet Ok, and at @34ce58c segfaults at conv1d backward (not necessarily dilated):
```.py
from torch.autograd import Variable
import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn
print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1)))
cudnn_version = torch.backends.cudnn.version()
print('CUDNN  VERSION', torch.backends.cudnn.version())
for i in range(1,10):
    try:
        m = nn.Conv1d(16, 33, 3, dilation=i).cuda()
        input = Variable(torch.randn(20, 16, 50).cuda())
        output = m(input)
        loss = output.sum()
        loss.backward()
        print('dilation OK    ', i)
    except:
        print('dilation FAILED', i )
#
for i in range(2,10):
    try:
        m = nn.Conv2d(16, 33, (3, 5), dilation=i).cuda()
        input = Variable(torch.randn(20, 16, 50, 100)).cuda()
        output = m(input)
        loss = output.sum()
        loss.backward()
        print('dilation OK    ', i)
    except:
        print('dilation FAILED', i )
```

**Comment by skaae** [comment]
@apaszke : Do you still need the `setup.py install` output?

**Comment by ngimel** [comment]
@skaae, as a workaround for now you can create your input with requires_grad=True.

**Comment by skaae** [comment]
Great Thanks! Do you know if cudnn v6.0 is faster for dilations? Otherwise i might just wait for a fix :)

**Comment by ngimel** [comment]
I'm afraid w/o the fix it will segfault in backwards regardless of whether you use cudnn - to work around that use requires_grad=True for input. Cudnn is supposed to be faster for dilated convs, but performance greatly depends on the sizes, so always benchmark.

**Comment by soumith** [comment]
the fix has been merged now.

**Comment by skaae** [comment]
I benchmarked dilations using cudnn 5.1 and 6.0. It seems that dilations != 1 are really slow for anything but batchsize 1? 

```
CUDNN  VERSION 5110
Float
batch_size: 1	dilation: 256	seqlen: 110250	 time 0.013589
batch_size: 1	dilation: 128	seqlen: 110250	 time 0.001548
batch_size: 1	dilation: 64	seqlen: 110250	 time 0.001471
batch_size: 1	dilation: 32	seqlen: 110250	 time 0.001159
batch_size: 1	dilation: 16	seqlen: 110250	 time 0.001457
batch_size: 1	dilation: 8	seqlen: 110250	 time 0.001279
batch_size: 1	dilation: 4	seqlen: 110250	 time 0.001069
batch_size: 1	dilation: 2	seqlen: 110250	 time 0.001068
batch_size: 1	dilation: 1     seqlen: 110250	 time 0.023048
batch_size: 8	dilation: 256	seqlen: 110250	 time 0.902854
batch_size: 8	dilation: 128	seqlen: 110250	 time 0.751134
batch_size: 8	dilation: 64	seqlen: 110250	 time 0.584407
batch_size: 8	dilation: 32	seqlen: 110250	 time 0.494308
batch_size: 8	dilation: 16	seqlen: 110250	 time 0.469266
batch_size: 8	dilation: 8	seqlen: 110250	 time 0.457277
batch_size: 8	dilation: 4	seqlen: 110250	 time 0.450981
batch_size: 8	dilation: 2	seqlen: 110250	 time 0.444093
batch_size: 8	dilation: 1	seqlen: 110250	 time 0.025876
batch_size: 32	dilation: 256	seqlen: 110250	 time 4.717062
batch_size: 32	dilation: 128	seqlen: 110250	 time 3.425079
batch_size: 32	dilation: 64	seqlen: 110250	 time 2.801741
batch_size: 32	dilation: 32	seqlen: 110250	 time 2.545884
batch_size: 32	dilation: 16	seqlen: 110250	 time 2.420491
batch_size: 32	dilation: 8	seqlen: 110250	 time 2.356115
batch_size: 32	dilation: 4	seqlen: 110250	 time 2.327302
batch_size: 32	dilation: 2	seqlen: 110250	 time 2.289761
batch_size: 32	dilation: 1	seqlen: 110250	 time 0.097122




True
CUDNN  VERSION 6005
Float
batch_size: 1	dilation: 256	seqlen: 110250	 time 0.013422
batch_size: 1	dilation: 128	seqlen: 110250	 time 0.001136
batch_size: 1	dilation: 64	seqlen: 110250	 time 0.001040
batch_size: 1	dilation: 32	seqlen: 110250	 time 0.001356
batch_size: 1	dilation: 16	seqlen: 110250	 time 0.001070
batch_size: 1	dilation: 8	seqlen: 110250	 time 0.000860
batch_size: 1	dilation: 4	seqlen: 110250	 time 0.000863
batch_size: 1	dilation: 2	seqlen: 110250	 time 0.000852
batch_size: 1	dilation: 1	seqlen: 110250	 time 0.023259
batch_size: 8	dilation: 256	seqlen: 110250	 time 0.820482
batch_size: 8	dilation: 128	seqlen: 110250	 time 0.638027
batch_size: 8	dilation: 64	seqlen: 110250	 time 0.543342
batch_size: 8	dilation: 32	seqlen: 110250	 time 0.493492
batch_size: 8	dilation: 16	seqlen: 110250	 time 0.469106
batch_size: 8	dilation: 8	seqlen: 110250	 time 0.457294
batch_size: 8	dilation: 4	seqlen: 110250	 time 0.451203
batch_size: 8	dilation: 2	seqlen: 110250	 time 0.450795
batch_size: 8	dilation: 1	seqlen: 110250	 time 0.027164
batch_size: 32	dilation: 256	seqlen: 110250	 time 4.883585
batch_size: 32	dilation: 128	seqlen: 110250	 time 3.500894
batch_size: 32	dilation: 64	seqlen: 110250	 time 2.873164
batch_size: 32	dilation: 32	seqlen: 110250	 time 2.561955
batch_size: 32	dilation: 16	seqlen: 110250	 time 2.420982
batch_size: 32	dilation: 8	seqlen: 110250	 time 2.356729
batch_size: 32	dilation: 4	seqlen: 110250	 time 2.327069
batch_size: 32	dilation: 2	seqlen: 110250	 time 2.289957
batch_size: 32	dilation: 1	seqlen: 110250	 time 0.096707
```



__Conv1d script__
```Python
from torch.autograd import Variable
import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn
cudnn.benchmark = True


print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1)))
cudnn_version = torch.backends.cudnn.version()
print('CUDNN  VERSION', torch.backends.cudnn.version())
import time
from torch.nn import Conv1d as Conv1d

num_runs = 10
s = 5*22050

print('Float')
for seqlen in [s]:
    for batch_size in [1, 8, 32]:
        for dilation in reversed([1, 2, 4, 8, 16, 32, 64, 128, 256]):
            m = nn.Sequential(Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation)).cuda()
            input = torch.randn(batch_size, 32, seqlen).float().cuda()

            start = time.time()
            for j in range(num_runs):
                output = m(Variable(input, requires_grad=True))
                output.backward(output.data)
            mean_time = (time.time() - start) / float(num_runs)
            print('batch_size: %i\tdilation: %i\tseqlen: %i\t time %f' %(batch_size, dilation, seqlen, mean_time))
```

**Comment by ngimel** [comment]
You need to to torch.cuda.synchronize for proper benchmarking.

**Comment by skaae** [comment]
ok. I re ran 6.0 with 

```Python
from torch.autograd import Variable
import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn
cudnn.benchmark = True


print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1)))
cudnn_version = torch.backends.cudnn.version()
print('CUDNN  VERSION', torch.backends.cudnn.version())
import time
from torch.nn import Conv1d as Conv1d

num_runs = 10
s = 5*22050

print('Float')
for seqlen in [s]:
    for batch_size in [1, 8, 32]:
        for dilation in reversed([1, 2, 4, 8, 16, 32, 64, 128, 256]):
            m = nn.Sequential(Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation),
                              Conv1d(32, 32, kernel_size=2, dilation=dilation)).cuda()
            input = torch.randn(batch_size, 32, seqlen).float().cuda()

            start = time.time()
            for j in range(num_runs):
                output = m(Variable(input, requires_grad=True))
                output.backward(output.data)
                torch.cuda.synchronize()
            mean_time = (time.time() - start) / float(num_runs)
            print('batch_size: %i\tdilation: %i\tseqlen: %i\t time %f' %(batch_size, dilation, seqlen, mean_time))
```
The timings are
```
CUDNN  VERSION 6005
Float
batch_size: 1	dilation: 256	seqlen: 110250	 time 0.162419
batch_size: 1	dilation: 128	seqlen: 110250	 time 0.112473
batch_size: 1	dilation: 64	seqlen: 110250	 time 0.095722
batch_size: 1	dilation: 32	seqlen: 110250	 time 0.086950
batch_size: 1	dilation: 16	seqlen: 110250	 time 0.082691
batch_size: 1	dilation: 8	seqlen: 110250	 time 0.080577
batch_size: 1	dilation: 4	seqlen: 110250	 time 0.079552
batch_size: 1	dilation: 2	seqlen: 110250	 time 0.078340
batch_size: 1	dilation: 1	seqlen: 110250	 time 0.028517
batch_size: 8	dilation: 256	seqlen: 110250	 time 1.174036
batch_size: 8	dilation: 128	seqlen: 110250	 time 0.910496
batch_size: 8	dilation: 64	seqlen: 110250	 time 0.775035
batch_size: 8	dilation: 32	seqlen: 110250	 time 0.704090
batch_size: 8	dilation: 16	seqlen: 110250	 time 0.669370
batch_size: 8	dilation: 8	seqlen: 110250	 time 0.652515
batch_size: 8	dilation: 4	seqlen: 110250	 time 0.643711
batch_size: 8	dilation: 2	seqlen: 110250	 time 0.634073
batch_size: 8	dilation: 1	seqlen: 110250	 time 0.073242
batch_size: 32	dilation: 256	seqlen: 110250	 time 5.434438
batch_size: 32	dilation: 128	seqlen: 110250	 time 3.855506
batch_size: 32	dilation: 64	seqlen: 110250	 time 3.158535
batch_size: 32	dilation: 32	seqlen: 110250	 time 2.816616
batch_size: 32	dilation: 16	seqlen: 110250	 time 2.678162
batch_size: 32	dilation: 8	seqlen: 110250	 time 2.607917
batch_size: 32	dilation: 4	seqlen: 110250	 time 2.575705
batch_size: 32	dilation: 2	seqlen: 110250	 time 2.534676
batch_size: 32	dilation: 1	seqlen: 110250	 time 0.284090
```

**Comment by ngimel** [comment]
Wow! 10 times slower than non-dilated. Do 2 1x1 convs, add some offsets and narrows to your result tensors, add them and you will be faster;-)

**Comment by ngimel** [comment]
I think your benchmarking is still wrong. Here's what it should be
```.py
            torch.cuda.synchronize()
            start = time.time()
            for j in range(num_runs):
                output = m(Variable(input, requires_grad=True))
                output.backward(output.data)
            torch.cuda.synchronize()
            mean_time = (time.time() - start) / float(num_runs)
            print('batch_size: %i\tdilation: %i\tseqlen: %i\t time %f' %(batch_size, dilation, seqlen, mean_time))
```
and here are my results on P100. Cudnn gives quite a speed-up and there is no drastic difference between non-dilated and dilated case. It looks like cudnn is still not used for dilated convs in your example - that would explain 10x difference. 
```
True
CUDNN  VERSION 6005
Float
batch_size: 1	dilation: 256	seqlen: 110250	 time 0.107555
batch_size: 1	dilation: 128	seqlen: 110250	 time 0.010256
batch_size: 1	dilation: 64	seqlen: 110250	 time 0.009971
batch_size: 1	dilation: 32	seqlen: 110250	 time 0.009653
batch_size: 1	dilation: 16	seqlen: 110250	 time 0.009572
batch_size: 1	dilation: 8	seqlen: 110250	 time 0.009549
batch_size: 1	dilation: 4	seqlen: 110250	 time 0.009563
batch_size: 1	dilation: 2	seqlen: 110250	 time 0.009490
batch_size: 1	dilation: 1	seqlen: 110250	 time 0.008920
batch_size: 8	dilation: 256	seqlen: 110250	 time 0.067781
batch_size: 8	dilation: 128	seqlen: 110250	 time 0.064634
batch_size: 8	dilation: 64	seqlen: 110250	 time 0.067730
batch_size: 8	dilation: 32	seqlen: 110250	 time 0.064171
batch_size: 8	dilation: 16	seqlen: 110250	 time 0.058004
batch_size: 8	dilation: 8	seqlen: 110250	 time 0.055389
batch_size: 8	dilation: 4	seqlen: 110250	 time 0.054575
batch_size: 8	dilation: 2	seqlen: 110250	 time 0.053758
batch_size: 8	dilation: 1	seqlen: 110250	 time 0.046727
batch_size: 32	dilation: 256	seqlen: 110250	 time 0.269592
batch_size: 32	dilation: 128	seqlen: 110250	 time 0.254314
batch_size: 32	dilation: 64	seqlen: 110250	 time 0.269055
batch_size: 32	dilation: 32	seqlen: 110250	 time 0.253480
batch_size: 32	dilation: 16	seqlen: 110250	 time 0.229877
batch_size: 32	dilation: 8	seqlen: 110250	 time 0.219808
batch_size: 32	dilation: 4	seqlen: 110250	 time 0.215970
batch_size: 32	dilation: 2	seqlen: 110250	 time 0.211928
batch_size: 32	dilation: 1	seqlen: 110250	 time 0.186116
```
```
True
CUDNN  VERSION 5110
Float
batch_size: 1	dilation: 256	seqlen: 110250	 time 0.185996
batch_size: 1	dilation: 128	seqlen: 110250	 time 0.098966
batch_size: 1	dilation: 64	seqlen: 110250	 time 0.087154
batch_size: 1	dilation: 32	seqlen: 110250	 time 0.081256
batch_size: 1	dilation: 16	seqlen: 110250	 time 0.078166
batch_size: 1	dilation: 8	seqlen: 110250	 time 0.076655
batch_size: 1	dilation: 4	seqlen: 110250	 time 0.075930
batch_size: 1	dilation: 2	seqlen: 110250	 time 0.075088
batch_size: 1	dilation: 1	seqlen: 110250	 time 0.082590
batch_size: 8	dilation: 256	seqlen: 110250	 time 0.972021
batch_size: 8	dilation: 128	seqlen: 110250	 time 0.786541
batch_size: 8	dilation: 64	seqlen: 110250	 time 0.693780
batch_size: 8	dilation: 32	seqlen: 110250	 time 0.646535
batch_size: 8	dilation: 16	seqlen: 110250	 time 0.622609
batch_size: 8	dilation: 8	seqlen: 110250	 time 0.610893
batch_size: 8	dilation: 4	seqlen: 110250	 time 0.604885
batch_size: 8	dilation: 2	seqlen: 110250	 time 0.597967
batch_size: 8	dilation: 1	seqlen: 110250	 time 0.046462
batch_size: 32	dilation: 256	seqlen: 110250	 time 3.904609
batch_size: 32	dilation: 128	seqlen: 110250	 time 3.162177
batch_size: 32	dilation: 64	seqlen: 110250	 time 2.789177
batch_size: 32	dilation: 32	seqlen: 110250	 time 2.597142
batch_size: 32	dilation: 16	seqlen: 110250	 time 2.501121
batch_size: 32	dilation: 8	seqlen: 110250	 time 2.453064
batch_size: 32	dilation: 4	seqlen: 110250	 time 2.429012
batch_size: 32	dilation: 2	seqlen: 110250	 time 2.401431
```

**Comment by skaae** [comment]
Thats great . Unfortunately i cannot get my GPU to run that fast :)

I reinstalled anaconda3 and have set the variables:

```
export CUDNN_LIB_DIR=/home/USERNAME/cuda60/lib64
export CUDNN_INCLUDE_DIR=/home/USERNAME/cuda60/include
export LD_LIBRARY_PATH=/home/USERNAME/cuda60/lib64:/home/USERNAME/cuda60
/include:$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=/home/USERNAME/anaconda3
```

I compile pytorch following the instructions in the readme except that i build with

```
python setup.py build_deps && python setup.py develop
```
When i build the correct cudnn is found

```
-- Building with NumPy bindings
-- Detected cuDNN at /home/sorson/cuda60/lib64, /home/sorson/cuda60/include
-- Detected CUDA at /usr/local/cuda
```

I cudnn5 is in `/usr/local/cuda/include` and `/usr/local/cuda/lib64` i dont know if that is problem?

**Comment by ngimel** [comment]
1080 is still pretty decent, with ~.32 s runtimes for batch 32. And 1080Ti is better still:-) What you are seeing is strange, may be you should rm -rf build? setup.py sometimes gets confused by old builds. To repro my numbers, try building docker image with tools/docker/Dockerfile_v6 - that will be a fresh install with no cudnn v5 hanging around, and then try figuring out what's wrong with your installs.

**Comment by skaae** [comment]
I reproduced your numbers now. I removed cudnn5 from `/usr/local/cuda/include` and `/usr/local/cuda/include/lib64` but i'm not sure if that was the problem or if i somehow messed up with the paths. The only odd thing is that fp16 seems to be slower than fp32 on a maxwell titan X. 

Your help is much appreciated! :)

**Comment by soumith** [comment]
@skaae after this PR is merged, https://github.com/pytorch/pytorch/pull/1017 your troubles should be gone. Sorry for the trouble.
@dasguptar for you as well, this PR should fix it

**Comment by soumith** [comment]
should now use the same cudnn at runtime that it linked against at compile-time.

**Comment by angusturner** [comment]
I am still encountering this issue on the latest build from source. 

I am running Ubuntu 16.04 with CUDA 8.0.61 and CUDNN 5110. 
When I run the benchmark script above, I get:

```
CUDNN  VERSION 5110
Float
batch_size: 1   dilation: 256   seqlen: 110250   time 0.322431
batch_size: 1   dilation: 128   seqlen: 110250   time 0.228681
batch_size: 1   dilation: 64    seqlen: 110250   time 0.188049
batch_size: 1   dilation: 32    seqlen: 110250   time 0.166691
batch_size: 1   dilation: 16    seqlen: 110250   time 0.155784
batch_size: 1   dilation: 8     seqlen: 110250   time 0.150233
batch_size: 1   dilation: 4     seqlen: 110250   time 0.147543
batch_size: 1   dilation: 2     seqlen: 110250   time 0.145513
batch_size: 1   dilation: 1     seqlen: 110250   time 0.057228
batch_size: 8   dilation: 256   seqlen: 110250   time 2.488083
batch_size: 8   dilation: 128   seqlen: 110250   time 1.827918
batch_size: 8   dilation: 64    seqlen: 110250   time 1.503108
batch_size: 8   dilation: 32    seqlen: 110250   time 1.333321
batch_size: 8   dilation: 16    seqlen: 110250   time 1.245614
batch_size: 8   dilation: 8     seqlen: 110250   time 1.201425
batch_size: 8   dilation: 4     seqlen: 110250   time 1.178945
batch_size: 8   dilation: 2     seqlen: 110250   time 1.163030
batch_size: 8   dilation: 1     seqlen: 110250   time 0.256762
```

**Comment by angusturner** [comment]
After upgrading to CUDNN6 and building PyTorch from source dilations are running quickly on the GPU. With CUDNN v5, dilation was extremely slow (as above) and actually slower than running code purely on the CPU. Not sure if that is still the case.

**Comment by soumith** [comment]
this should hopefully now be fixed (and with the latest binaries too). @skaae if you still have trouble, let me know

**Comment by lizhengwei1992** [comment]
I find the dilated convolution (dilation=2 ) slower much than convolution (dilation=1). my pytorch version is 0.3.0.post4, I test the dilated convolution like this:
`for batch_size in [1]:
    for dilation in reversed([1]):
        m = nn.Sequential(Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation)).cuda()
        input = torch.randn(batch_size, 128, 360, 640).cuda()

        start = time.time()
        for j in range(num_runs):
            output = m(Variable(input, requires_grad=True))
            output.backward(output.data)
            torch.cuda.synchronize()
        mean_time = (time.time() - start) / float(num_runs)
        print('batch_size: %i\tdilation: %i  time %f' %(batch_size, dilation, mean_time))

for batch_size in [1]:
    for dilation in reversed([2]):
        m = nn.Sequential(Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation),
                          Conv2d(128, 128, kernel_size=3, padding=1, dilation=dilation)).cuda()
        input = torch.randn(batch_size, 128, 360, 640).cuda()

        start = time.time()
        for j in range(num_runs):
            output = m(Variable(input, requires_grad=True))
            output.backward(output.data)
            torch.cuda.synchronize()
        mean_time = (time.time() - start) / float(num_runs)
        print('batch_size: %i\tdilation: %i  time %f' %(batch_size, dilation, mean_time))`
get that:
CUDNN  VERSION 7003
batch_size: 1   dilation: 1  time 0.198399
batch_size: 1   dilation: 2  time 0.359258
what should I do to accelerate the dilated convolution ?
