### ISSUE TITLE
 PyTorch installation does downgrade the python3.7.0 to python3.6.6

### ISSUE THREAD

**Issue by sb0709** [pytorch/pytorch#9967]
pytorch installation does downgrade the python3.7 to python3.6 when using conda installation. 

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda install pytorch torchvision cuda92 -c pytorch
- OS: ubuntu 16.04
- PyTorch version: 0.4.1
- Python version: 3.7
- CUDA/cuDNN version: 9.2
- GPU models and configuration: Titan XP

#Original env:
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

#Installation of pytorch:
conda install pytorch torchvision cuda92 -c pytorch
Solving environment: done

## Package Plan ##

  environment location: /home/sb0709/anaconda3/envs/pytorch_test

  added / updated specs: 
    - cuda92
    - pytorch
    - torchvision

The following NEW packages will be INSTALLED:

    blas:           1.0-mkl                                    
    cffi:           1.11.5-py36h9745a5d_0                      
    cuda92:         1.0-0                               pytorch
    freetype:       2.9.1-h8a8886c_0                           
    intel-openmp:   2018.0.3-0                                 
    jpeg:           9b-h024ee3a_2                              
    libgfortran-ng: 7.2.0-hdf63c60_3                           
    libpng:         1.6.34-hb9fc6fc_0                          
    libtiff:        4.0.9-he85c1e1_1                           
    mkl:            2018.0.3-1                                 
    mkl_fft:        1.0.4-py36h4414c95_1                       
    mkl_random:     1.0.1-py36h4414c95_1                       
    ninja:          1.8.2-py36h6bb024c_1                       
    numpy:          1.15.0-py36h1b885b7_0                      
    numpy-base:     1.15.0-py36h3dfced4_0                      
    olefile:        0.45.1-py36_0                              
    pillow:         5.2.0-py36heded4f4_0                       
    pycparser:      2.18-py36_1                                
    pytorch:        0.4.1-py36_cuda9.2.148_cudnn7.1.4_1 pytorch [cuda92]
    six:            1.11.0-py36_1                              
    torchvision:    0.2.1-py36_1                        pytorch

The following packages will be UPDATED:

    certifi:        2018.4.16-py37_0                            --> 2018.4.16-py36_0
    pip:            10.0.1-py37_0                               --> 10.0.1-py36_0   
    setuptools:     39.2.0-py37_0                               --> 39.2.0-py36_0   
    wheel:          0.31.1-py37_0                               --> 0.31.1-py36_0   

The following packages will be DOWNGRADED:

    python:         3.7.0-hc3d631a_0                            --> 3.6.6-hc3d631a_0

Proceed ([y]/n)? 

#output after installation:
python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by sb0709** [comment]
exact version

**Comment by zou3519** [comment]
This shouldn't be the case; we'll try to reproduce it.

**Comment by TimHsu1998** [comment]
I also have the same problem.

**Comment by soumith** [comment]
This happened because of `torchvision`. We fixed this ~1 hour ago. Thanks a lot for the report.

**Comment by y0ast** [comment]
The above is still happening with cuda 9.0 (it's indeed fine with 9.2).

**Comment by sebderhy** [comment]
I have a very similar issue with Cuda 9.2. After creating a Conda env, my python version is 3.7, but after installing Pytorch (by running 'conda install pytorch-nightly cuda92 -c pytorch'), python --version results in 'Python 3.5.6 :: Anaconda, Inc.'. 

Any idea what causes this? Thanks for the help!

**Comment by soumith** [comment]
@y0ast @sebderhy I answered here: https://github.com/pytorch/pytorch/issues/12929#issuecomment-431851959

**Comment by kleinicke** [comment]
I had the same problem typing in 
```
conda install torchvision
```
The problem didn't occur when using
```
conda install pytorch torchvision -c pytorch
```
